---
title: Specifying Your Company Name and Logo
url: https://domo-support.domo.com/s/article/360043439053
linked_kbs:  ['[https://domo-support.domo.com/s/knowledge-base/](https://domo-support.domo.com/s/knowledge-base/)', '[https://domo-support.domo.com/s/](https://domo-support.domo.com/s/)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZamlGAC](https://domo-support.domo.com/s/topic/0TO5w000000ZamlGAC)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZaoGGAS](https://domo-support.domo.com/s/topic/0TO5w000000ZaoGGAS)', '[https://domo-support.domo.com/s/article/360043438973](https://domo-support.domo.com/s/article/360043438973)', '[https://domo-support.domo.com/s/article/360043439053](https://domo-support.domo.com/s/article/360043439053)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZaoGGAS/specifying-company-settings](https://domo-support.domo.com/s/topic/0TO5w000000ZaoGGAS/specifying-company-settings)', '[https://domo-support.domo.com/s/article/360043429933](https://domo-support.domo.com/s/article/360043429933)', '[https://domo-support.domo.com/s/article/360043429953](https://domo-support.domo.com/s/article/360043429953)', '[https://domo-support.domo.com/s/article/360042925494](https://domo-support.domo.com/s/article/360042925494)', '[https://domo-support.domo.com/s/article/360043429913](https://domo-support.domo.com/s/article/360043429913)', '[https://domo-support.domo.com/s/article/4408174643607](https://domo-support.domo.com/s/article/4408174643607)', '[https://domo-support.domo.com/s/login/](https://domo-support.domo.com/s/login/)']
article_id: 000003059
views: 2,202
created_date: 2022-10-24 21:09:00
last updated: 2022-10-24 22:40:00
---



You can specify or change your company name and logo that appear in Domo. You can do this in the **Company settings** tab of the Admin Settings. You can only edit these settings if you have an "Admin" default security role or a custom role with "Manage All Company Settings" enabled. For more information about default security roles, see [Managing Custom Roles](/s/article/360043438973 "Security Role Reference").


**To specify or change your company name,**


1. Click **More** **>**  **Admin**.  
The  Admin Settings appears.
2. Click **Company settings > Company overview**.
3. Enter your company name into the **Company name** field.
4. Click **Save**.


**To specify or change your company logo,**


1. Click **More** **> Admin**.  
The Admin Settings appears.
2. Click **Company settings > Company overview**.
3. Click **Manage Logo**, click **Choose File**, browse to the desired file, then click **Open**.




 


**Note:** If the image is not square, it will need to be cropped in the modal. The image is resized to 300 x 300 pixels.
4. Click **Save**.
