---
title : Google Sheets Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:40:00
url : https://domo-support.domo.com/s/article/360043436633
linked_kbs :  ['https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360043436633', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003933
views : 4,613
created_date : 2022-10-24 21:16:00
last updated : 2022-10-24 22:40:00
---



IntroÂ
-------


Google Sheets is a spreadsheet program,Â part of a free, web-basedÂ software office suiteÂ offeredÂ by GoogleÂ within its Google DriveÂ service. The program allows users to create and edit spreadsheets online while collaborating with other users in real-time.Â To learn more about theÂ GoogleÂ API, visit their websiteÂ ([https://developers.google.com](https://developers.google.com/sheets/api/reference/rest)).Â  Â  Â  Â  Â 


The Google Sheets connector is a "Cloud App" connector, meaning it pulls data from a cloud-based application into Domo. In the Data Center, you can access the connector page for this and other Cloud App connectors by clickingÂ **Cloud App**Â in the toolbar at the top of the window.




|  |  |
| --- | --- |
| **Primary Use Cases** | This connector is appropriate for data sources in which multiple users are contributing to a single data source. |
| **Primary Metrics** | Users can create a wide variety of metrics using Google Sheet DataSets. Some frequently used metrics are...
* Tracking a list of items
* People
* Help requests
* Company assets
* Employee compliance / trainings
 |
| **Primary Company Roles** | Appropriate for all roles |
| **Average Implementation Time** | 10 minutes or less |
| **Ease of Use (on a 1-to-10 scale with 1 being easiest)** | 2 |


### 
Other panesÂ


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, seeÂ [AddingÂ a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).
Best practicesÂ
----------------


Google Forms (surveys) don't currently have a connector; however, you can convert Google Forms into Google Sheets, which can then be pulled into Domo with the Google Sheets connector.
PrerequisitesÂ Â
-----------------


To connect to your Google account and create a Google Sheets DataSet, you must have Google credentials.Â
Connecting to Your Google accountÂ Â
-------------------------------------


This section enumerates the options in theÂ **Credentials**Â andÂ **Details**Â panes in the Google Sheets Connector page.Â The components of the other panes in this page,Â **SchedulingÂ**andÂ **Name & Describe Your DataSet,**Â are universal across most connector types and are discussed in greater length inÂ [AddingÂ a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).


### 
Credentials paneÂ Â


The Domo Google Sheets connector uses OAuth to connect, so there is no need to enter credentials within Domo. ClickÂ **Connect**Â (or selectÂ **Add Account**Â ifÂ you haveÂ existing Google Sheets accounts in Domo) to open the Google OAuth screen where you can enter your Google credentials. Once you have entered valid Google credentials, you can use the same account any time you go to create a new Google SheetsÂ  DataSet. You can manage connector accounts in theÂ **Accounts**Â tab in theÂ Data Center. For more information about this tab, seeÂ [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


**Note:**Â If you are already logged into GoogleÂ when you connect in Domo, you are authenticated automatically when you clickÂ **Add account**. If you want to connect to an account that is different from the one you are logged into, you must first log out of Google.
### 
Details PaneÂ Â


In this pane, you specify the Google Drive file you want to import into Domo and set options for how you want to data to appear.




| Menu | Description |
| --- | --- |
| File Selection | Select whether you want to identify your desired Google Sheet byÂ **DiscoveryÂ**(which auto-populates a list of the files in your account),Â **Search**Â (which allows you to search for a specific filename), orÂ **Spreadsheet ID**Â (which allows you to specify a file by its ID). |
| Search | Enter the name of the file you want to search for. |
| Spreadsheet ID | Enter the ID of the Google Sheet you want to pull into Domo.Â  |
| Google Sheet | Select the Google Sheet you want to pull into Domo.Â  |
| Worksheet Name | Select the specific worksheet you want to pull into Domo.Â  |
| Spreadsheet Layout | Select whether your Google Sheet has column headers or row headers.Â  |
| Manually Enter Cell Ranges | Check this box if you want to specify a that certain range of data from the spreadsheet be pulled into Domo.Â  |
| Column Header Cell Range | Enter the range for the column headers you want to be imported into Domo. |
| Column Data Cell Range | Enter the range for the data you want to be imported into Domo.Â  |
### 
Other PanesÂ Â Â


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, seeÂ [AddingÂ a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).
FAQsÂ Â
--------


**How do I know my Google credentials are secure?Â Â**


The login process uses the OAuth process, so your Google credentials are never seen or stored by Domo. You can revoke Domo's access to your account at any time.
**How often can the data be updated?Â Â**


As often as needed.Â
**Are there any API limits I should be aware of?Â**


Google enforces total and concurrent call rate limits. To prevent rate limiting, reduce the number of DataSets scheduled to run at the same time.
**Why does the connector seem to be pulling in unwanted data?Â**


Confirm thatÂ you have selected the correct Google Sheet worksheet. If you are using advanced options, make sure you have selected the correct range of data.
TroubleshootingÂ
-----------------



* If the connection fails, confirm the Google account username and password are still accurate.
* If the connector seems to pull back the wrong data, confirm you selected the correct Google Sheet worksheet or, if using advanced options, confirm you have the correct range of data selected.