---
title : Moat Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:39:00
url : https://domo-support.domo.com/s/article/360043431593
linked_kbs :  ['https://domo-support.domo.com/s/article/360043431593', 'https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003743
views : 2,015
created_date : 2022-10-24 21:14:00
last updated : 2022-10-24 22:39:00
---



Intro
-----


Moat is a SaaS analytics company focused on transforming brand advertising online. To learn more about the Moat API, visit their page ([https://moat.com/analytics](https://moat.com/analytics "https://moat.com/analytics")).


You connect to your Moat account in the Data Center. This topic discusses the fields and menus that are specific to the Moat connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).


Prerequisites
-------------


To connect to your Moat account and create a DataSet, you must have a Moat username and password.


Connecting to Your Moat Account
-------------------------------


This section enumerates the options in the **Credentials** and **Details** panes in the Moat Connector page.Â The components of the other panes in this page, **Scheduling**Â and **Name & Describe Your DataSet**, are universal across most connector types and are discussed in greater length inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md "Adding a DataSet Using a Data Connector").


### Credentials Pane


This pane contains fields for entering credentials to connect to your Moat account. The following table describes what is needed for each field: Â 




| Field | Description |
| --- | --- |
| Username | Enter the username for your Moat account. |
| Password | Enter the password for your Moat account. |


Once you have entered valid Moat credentials, you can use the same account any time you go to create a new Moat DataSet. You can manage connector accounts in the **Accounts** tab in the Data Center. For more information about this tab, see [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


### Details Pane


This pane contains a menu from which you select a report, along with various other menus for configuring your report.




| Menu | Description |
| --- | --- |
| Report | Select the Moat report you want to run. Currently only one report is available.

|  |  |
| --- | --- |
| Stats | Retrieves statistics for selected columns in your Moat account for a specified timeframe.Â  |

 |
| Columns | Check the boxes for all fields you want to be pulled into your Moat report in Domo. |
| Level 1 ID (Optional) | Enter the Level 1 ID you want to retrieve data for. This is equivalent to an Advertiser. |
| Level 2 ID (Optional) | Enter the Level 2 ID you want to retrieve data for. This is equivalent to a Campaign. |
| Level 3 ID (Optional) | Enter the Level 3 ID you want to retrieve data for. This is equivalent to a Line Item. |
| Level 4 ID (Optional) | Enter the Level 4 ID you want to retrieve data for. This is equivalent to a Creative. |
| Slicer 1 ID (Optional) | Enter the Slicer 1 ID you want to retrieve data for. This is equivalent to a Site ID. |
| Slicer 2 ID (Optional) | Enter the Slicer 2 ID you want to retrieve data for. This is equivalent to a Placement/Position. |
| Width Height (Optional) | Enter the width height you want to retrieve data for. Example: 300\_250 |
| OS Browser (Optional) | Enter the browser you want to retrieve data for. The following browsers are available:
* Android
* BlackBerry
* iPad
* iPhone
* iPod
* Kindle
* Chrome
* Firefox
* MSIE (Microsoft Internet Explorer)
* Opera
* Safari
* Desktop
* Mobile
 |
| Report DateÂ  | Select whether the report data is for a specific date or for a relative number of days back from today.Â  |
| Select Specific DateÂ  | Select the date for the report.Â  |
| Days Back | Enter the number of past days that should appear in the report.Â Â  |
| Start Date | Specify whether theÂ first date in your date range is a specific or relative date.Â You select the last date in your range inÂ **End Date**.Â  |
| End Date | Specify whether the second date in your date range is a specific or relative date. You select the first date in your range inÂ **Start Date**.Â Â  |
| Select Specific Start Date | SelectÂ the first date in your date range.Â  |
| Select Specific End Date | Select the second date in your date range.Â  |
| Days Back to Start From | Enter the number of the farthest day back that should be represented in the report. Combine withÂ **Days Back to End At**Â to create a range of represented days.
For example, if you enteredÂ 10Â forÂ **Days Back to Start From**Â andÂ 5Â forÂ **Days Back to End At**, the report would contain data forÂ 10 days ago up untilÂ 5 days ago. |
| Days Back to End At | Enter the number of the most recent day back that should be represented in the report. Combine withÂ **Days Back to Start From**Â to create a range of represented days.
For example, if you enteredÂ 10Â forÂ **Days Back to Start From**Â andÂ 5Â forÂ **Days Back to End At**, the report would contain data forÂ 10 days ago up untilÂ 5 days ago. |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, seeÂ [AddingÂ a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).


Â