---
title : Sharing Content in Domo FAQs
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:41:00
url : https://domo-support.domo.com/s/article/360042933074
linked_kbs :  ['https://domo-support.domo.com/s/article/360043438993', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360043437933', 'https://domo-support.domo.com/s/article/360043439333', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360043437973', 'https://domo-support.domo.com/s/article/360043437813', 'https://domo-support.domo.com/s/article/360042926134', 'https://domo-support.domo.com/s/article/360042934654', 'https://domo-support.domo.com/s/article/360043428213', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/article/360043437773', 'https://domo-support.domo.com/s/article/360042933074', 'https://domo-support.domo.com/s/article/360043437953', 'https://domo-support.domo.com/s/article/360043437873', 'https://domo-support.domo.com/s/article/360043437833', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913', 'https://domo-support.domo.com/s/article/360043439353', 'https://domo-support.domo.com/s/article/360042934614', 'https://domo-support.domo.com/s/article/360042923814', 'https://domo-support.domo.com/s/article/360043438873', 'https://domo-support.domo.com/s/article/360042933054', 'https://domo-support.domo.com/s/article/360043428633']
article_id : 000004114
views : 4,317
created_date : 2022-10-24 21:22:00
last updated : 2022-10-24 22:41:00
---



This page lists a number of frequently asked questions (FAQs) involving sharing in DomoÂ and provides links to Knowledge Base topics where you can find answers to those questions.


##### How do I share cards in Domo?


See the following topics:



* [Sharing and Removing Accessible Content for a Group](..\adding_and_removing_accessible_content_for_a_group\index.md)
* [Domo using Domo Embed](/s/article/360043437973)
* [Printing a KPI Card](..\printing_a_visualization_card\index.md)
* [Exporting Sumo Data](..\exporting_sumo_data\index.md)Â
* [Emailing a KPI Card](..\emailing_a_visualization_card\index.md)
* [Exporting KPI Cards](..\exporting_visualization_cards\index.md)Â
* [Using the Domo PowerPoint PluginÂ](..\using_the_domo_powerpoint_plugin\index.md)
* [Using the Domo Excel Plugin](..\using_the_domo_excel_plugin\index.md)
* [Scheduling Reports](..\scheduling_reports\index.md)


##### How do I share pages in Domo?


See the following topics:



* [Sharing and Removing Accessible Content for a Group](..\adding_and_removing_accessible_content_for_a_group\index.md)
* [Locking or Unlocking Page Content](..\locking_or_unlocking_page_content\index.md)


##### How do I share DataSets/DataFlows in Domo?


See the following topics:Â Â Â Â Â Â 



* [Exporting DataSets](..\exporting_datasets\index.md)
* [PDP and DataFlows/DataFusions](..\pdp_and_dataflowsdatafusions\index.md)


##### What are my sharing options on Domo mobile?


See the following topics:



* [Taking Snapshots of Cards](..\taking_snapshots_of_cards\index.md)
* [Domo Mobile Quick Start Guide](..\domo_mobile_quick_start_guide\index.md)


##### How can I share Domo content outside of myÂ instance?



* [Sharing Cards Outside of Domo Using Domo Embed](/s/article/360043437973)


##### How do I keep content secure?



* [Sharing and Removing Accessible Content for a Group](..\adding_and_removing_accessible_content_for_a_group\index.md)
* [PDP vs Publication Groups](..\pdp_vs_publication_groups\index.md)
* [Setting up Publication Groups](..\setting_up_publication_groups\index.md)
* [Creating and Deleting PDP Policies](..\creating_and_deleting_pdp_policies\index.md)
* [PDP Policy Autocreation](/s/article/360043439353)