---
title : Lollipop Chart
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:41:00
url : https://domo-support.domo.com/s/article/360043429373
linked_kbs :  ['https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360043428713', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360043429153', 'https://domo-support.domo.com/s/article/360043428053', 'https://domo-support.domo.com/s/article/360043428893', 'https://domo-support.domo.com/s/article/360043429373', 'https://domo-support.domo.com/s/article/360043428693', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360042923334', 'https://domo-support.domo.com/s/article/360042924614', 'https://domo-support.domo.com/s/article/360043428673', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000004695
views : 4,066
created_date : 2022-10-24 22:23:00
last updated : 2022-10-24 22:41:00
---



Intro
-----


Lollipop charts are essentially modified bar charts in which the bars are represented as thin lines so you can fit more in a small area, with small circles to represent mouse-over points. There are eight types of lollipop charts in Domo, all of them modified versions of familiar bar and line bar charts.


For thumbnail images and descriptions of all lollipop charts, see [Available lollipop charts](..\available_lollipop_charts\index.html "Available Lollipop Graphs").


Powering lollipop charts
------------------------


All lollipop charts require three columns or rows of data from your DataSet—one for categories, one for values, and one for series data. Beyond this, the steps for configuring these charts differ depending on the specific lollipop chart type. Each chart type has an equivalent Bar- or Line Bar-type chart. You can find out more about a specific lollipop chart type by navigating to the topic for the equivalent Bar or Line Bar chart in the following table:




| Lollipop chart Type | Equivalent Bar or Line Bar chart Type |
| --- | --- |
| Vertical grouped lollipop | [Vertical grouped bar](..\grouped_bar_chart\index.html "Grouped Bar Graph") |
| Vertical stacked lollipop | [Vertical stacked bar](..\stacked_bar_chart\index.html "Stacked Bar Graph") |
| Vertical grouped lollipop with line | [Vertical grouped bar with line](..\grouped_bar_with_line_chart\index.html "Grouped Bar with Line Graph") |
| Vertical stacked lollipop with line | [Vertical stacked bar with line](..\stacked_bar_with_line_chart\index.html "Stacked Bar with Line Graph") |
| Horizontal grouped lollipop | [Horizontal grouped bar](..\grouped_bar_chart\index.html "Grouped Bar Graph") |
| Horizontal stacked lollipop | [Horizontal stacked bar](..\stacked_bar_chart\index.html "Stacked Bar Graph") |
| Horizontal grouped lollipop with line | [Horizontal grouped bar with line](..\grouped_bar_with_line_chart\index.html "Grouped Bar with Line Graph") |
| Horizontal stacked lollipop with line | [Horizontal stacked bar with line](..\stacked_bar_with_line_chart\index.html "Stacked Bar with Line Graph") |


For information about value, category, and series data, see [Understanding Chart Data](..\understanding_chart_data\index.html "Understanding Chart Data").


In the Analyzer, you choose the columns containing the data for your lollipop chart. For more information about choosing data columns, see [Applying DataSet Columns to Your Chart](..\applying_dataset_columns_to_your_chart\index.html "Applying DataSet Columns to Your Chart").


For more information about formatting charts in the Analyzer, see [KPI Card Building Part 2: The Analyzer](..\analyzer_overview\index.html "KPI Card Building Part 2: The Analyzer").