---
title : Specifying Worklog Settings
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:40:00
url : https://domo-support.domo.com/s/article/360043439113
linked_kbs :  ['https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360043439413', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360043438973', 'https://domo-support.domo.com/s/article/360043439113', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003061
views : 3,949
created_date : 2022-10-24 21:09:00
last updated : 2022-10-24 22:40:00
---



You can specify settings to prompt users to enter worklogs. You can do this in **More >** **Admin > Company settings > Worklog**. You can only do this if you have an "Admin" default security role or a custom role with "Manage All Company Settings" enabled. For more information about default security roles, see [Managing Custom Roles](..\managing_custom_roles\index.html "Security Role Reference").


When reminders are on, users are prompted to enter a worklog. Worklogs appear in the user profile.


For information about entering a worklog in your profile, see [Specifying Your Personal Profile Information](..\specifying_your_personal_profile_information\index.html "Specifying Your Personal Profile Information")


**To specify worklog settings,**


1. Click **More** **> Admin**.  
The Admin Settings appears.
2. Select **Company settings > Worklog**.
3. Click **Off** to toggle on the reminder, then specify the interval (daily, weekly, monthly, yearly) for reminding users to enter worklogs.