---
title : Pivotal Tracker Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:42:00
url : https://domo-support.domo.com/s/article/360043434613
linked_kbs :  ['https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043434613', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003446
views : 2,012
created_date : 2022-10-24 21:13:00
last updated : 2022-10-24 22:42:00
---



Intro
-----


Pivotal Tracker is an online project planning, tracking and collaboration tool designed specifically by software developers to support the software development process.Â Use Domo'sÂ Pivotal TrackerÂ connector to retrieve data about epics, notifications, projects, and stories.Â For more information about the Pivotal TrackerÂ API, visitÂ their website.Â ([https://www.pivotaltracker.com/help/api/#top](https://www.pivotaltracker.com/help/api/#top "https://www.pivotaltracker.com/help/api/#top"))


The Pivotal Tracker connector is a "Cloud App" connector, meaning it retrieves data stored in the cloud. In the Data Center, you can access the connector page for this and other Cloud App connectors by clicking **Cloud App** in the toolbar at the top of the window.


You connect to yourÂ Pivotal Tracker account in theÂ Data Center. This topic discusses the fields and menus that are specific to theÂ Pivotal TrackerÂ connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


Prerequisites
-------------


To connect to yourÂ Pivotal TrackerÂ account and create a DataSet, you must have a Pivotal TrackerÂ username and password.Â 


Connecting to YourÂ Outbrain Account
------------------------------------


This section enumerates the options in theÂ **Credentials**Â andÂ **Details**Â panes in theÂ Pivotal TrackerÂ Connector page.Â The components of the other panes in this page,Â **Scheduling**Â andÂ **Name & Describe Your DataSet**, are universal across most connector types and are discussed in greater length inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


### Credentials Pane


This pane contains fields for entering credentials to connect to yourÂ Pivotal TrackerÂ account. The following table describes what is needed for each field: Â 




| Field | Description |
| --- | --- |
| User | Enter your Pivotal Tracker username.Â  |
| PasswordÂ  | Enter your Pivotal Tracker password.Â  |


Once you have entered validÂ Pivotal Tracker credentials, you can use the same account any time you go to create a newÂ Pivotal Tracker DataSet. You can manage connector accounts in theÂ **Accounts**Â tab in theÂ Data Center. For more information about this tab, seeÂ [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


### Details Pane


This pane contains a primaryÂ **Report**Â menu in which you select a report type. Depending on the report type you select, you may also have the option to specify the number of days back for the report.




| Menu | Description |
| --- | --- |
| Report | Select a Pivotal TrackerÂ report. The following reports are available:

|  |  |
| --- | --- |
| Epics | Returns all epics for the authenticated user's projects.Â  |
| Notifications | Returns all notifications for the authenticated user. |
| Projects | Returns all of the authenticated user's active projects. |
| Stories | Returns all stories for the authenticated user's projects, filtered by theÂ **Created Date**. Append supported.Â  |

Â  |
| Created Date - Days Back | Enter the number of past days you want to retrieve data for. For example, if you enter 7, the connector pulls data for the past week. |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, seeÂ [AddingÂ a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).


Â