---
title: Magic ETL Scripting Tile Environments
url: https://domo-support.domo.com/s/article/4422644650519
linked_kbs:  ['[https://domo-support.domo.com/s/knowledge-base/](https://domo-support.domo.com/s/knowledge-base/)', '[https://domo-support.domo.com/s/](https://domo-support.domo.com/s/)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZamzGAC](https://domo-support.domo.com/s/topic/0TO5w000000ZamzGAC)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZanvGAC](https://domo-support.domo.com/s/topic/0TO5w000000ZanvGAC)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZdTHGA0](https://domo-support.domo.com/s/topic/0TO5w000000ZdTHGA0)', '[https://domo-support.domo.com/s/article/4662034775319](https://domo-support.domo.com/s/article/4662034775319)', '[https://domo-support.domo.com/s/article/4422644650519](https://domo-support.domo.com/s/article/4422644650519)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZdTHGA0/tiles](https://domo-support.domo.com/s/topic/0TO5w000000ZdTHGA0/tiles)', '[https://domo-support.domo.com/s/article/360043429933](https://domo-support.domo.com/s/article/360043429933)', '[https://domo-support.domo.com/s/article/360043429953](https://domo-support.domo.com/s/article/360043429953)', '[https://domo-support.domo.com/s/article/360042925494](https://domo-support.domo.com/s/article/360042925494)', '[https://domo-support.domo.com/s/article/360043429913](https://domo-support.domo.com/s/article/360043429913)', '[https://domo-support.domo.com/s/article/4408174643607](https://domo-support.domo.com/s/article/4408174643607)', '[https://domo-support.domo.com/s/login/](https://domo-support.domo.com/s/login/)']
article_id: 000003008
views: 2,247
created_date: 2022-10-24 20:59:00
last updated: 2022-10-24 22:42:00
---



Intro
-----


The Python and R tiles have the **Domo 1.1** environment installed by default. This environment contains a selection of Python and R libraries. The list of libraries can be found in the Default environment page list section below.


To request a custom environment, see [Requesting Custom Environments.](/s/article/4662034775319)


Default environment page list
-----------------------------


* \_r-mutex=1.0.0=anacondar\_1
* \_r-xgboost-mutex=2.0=cpu\_0
* asn1crypto=0.24.0=py37\_0
* binutils\_impl\_linux-64 2.31.1=h6176602\_1
* binutils\_linux-64 2.31.1=h6176602\_6
* blas=1.0=mkl
* blinker=1.4=py37\_0
* bwidget=1.9.11 1
* bzip2 1.0.6=h14c3975\_5
* ca-certificates=2019.1.23 0
* cairo=1.14.12=h8948797\_3
* certifi=2019.3.9=py37\_0
* cffi=1.12.2=py37h2e261b9\_1
* chardet=3.0.4=py37\_1
* convertdate=2.1.3=py37\_0
* cookies=2.2.1=py37\_1
* cryptography=2.6.1=py37h1ba5d50\_0
* cudatoolkit=10.0.130 0
* cudnn=7.3.1=cuda10.0\_0
* curl=7.64.0=hbc83047\_2
* cycler=0.10.0=py37\_0
* cython=0.29.6=py37he6710b0\_0
* dbus=1.13.6=h746ee38\_0
* decorator=4.4.0=py37\_1
* domomagic=0.2=py37\_0
* ephem=3.7.6.0=py37h14c3975\_1
* expat=2.2.6=he6710b0\_0
* fbprophet=0.4.post2=py37\_0
* fontconfig=2.13.0=h9420a91\_0
* freetype=2.9.1=h8a8886c\_1
* fribidi=1.0.5=h7b6447c\_0
* fuzzywuzzy=0.17.0=py\_0
* gcc\_impl\_linux-64 7.3.0=habb00fd\_1
* gcc\_linux-64 7.3.0=h553295d\_6
* geos=3.8.1=he6710b0\_0
* gfortran\_impl\_linux-64 7.3.0=hdf63c60\_1
* gfortran\_linux-64 7.3.0=h553295d\_6
* glib=2.56.2=hd408876\_0
* graphite2 1.3.13=h23475e2\_0
* gsl=2.4=h14c3975\_4
* gst-plugins-base=1.14.0=hbbd80ab\_1
* gstreamer=1.14.0=hb453b48\_1
* gxx\_impl\_linux-64 7.3.0=hdf63c60\_1
* gxx\_linux-64 7.3.0=h553295d\_6
* h5py=2.9.0=py37h7918eee\_0
* harfbuzz=1.8.8=hffaf4a1\_0
* hdf5 1.10.4=hb1b8bf9\_0
* holidays=0.9.10=py37\_0
* icu=58.2=h211956c\_0
* idna=2.8=py37\_0
* intel-openmp=2019.3 199
* joblib=0.13.2=py37\_0
* jpeg=9b=habf39ab\_1
* kiwisolver=1.0.1=py37hf484d3e\_0
* krb5 1.16.1=h173b8e3\_7
* libcurl=7.64.0=h20c2e04\_2
* libedit=3.1.20181209=hc058e9b\_0
* libffi=3.2.1=h4deb6c0\_3
* libgcc-ng=8.2.0=hdf63c60\_1
* libgfortran-ng=7.3.0=hdf63c60\_0
* libgpuarray=0.7.6=h14c3975\_0
* libpng=1.6.36=hbc83047\_0
* libssh2 1.8.0=h1ba5d50\_4
* libstdcxx-ng=8.2.0=hdf63c60\_1
* libtiff=4.0.10=h2733197\_2
* libuuid=1.0.3=h1bed415\_2
* libxcb=1.13=h1bed415\_1
* libxgboost=0.80=he6710b0\_0
* libxml2 2.9.9=he19cac6\_0
* lunardate=0.2.0=py37\_0
* make=4.2.1=h1bed415\_1
* mako=1.0.7=py\_1
* markupsafe=1.1.1=py37h7b6447c\_0
* matplotlib=3.0.3=py37h5429711\_0
* mkl=2019.3 199
* mkl-service=1.1.2=py37he904b0f\_5
* mkl\_fft=1.0.10=py37ha843d7b\_0
* mkl\_random=1.0.2=py37hd81dba3\_0
* ncurses=6.1=he6710b0\_1
* ninja=1.9.0=py37hfd86e86\_0
* nltk=3.4=py37\_1
* nltk\_data=2017.10.22=py\_0
* numpy=1.16.2=py37h7e9f1db\_0
* numpy-base=1.16.2=py37hde5b4d6\_0
* oauthlib=3.0.1=py\_0
* openssl=1.1.1h=h7b6447c\_0
* pandas=0.24.2=py37he6710b0\_0
* pango=1.42.4=h049681c\_0
* patsy=0.5.1=py37\_0
* pcre=8.43=he6710b0\_0
* pip=19.0.3=py37\_0
* pixman=0.38.0=h7b6447c\_0
* pycparser=2.19=py37\_0
* pygpu=0.7.6=py37h035aef0\_0
* pyjwt=1.7.1=py37\_0
* pyopenssl=19.0.0=py37\_0
* pyparsing=2.3.1=py37\_0
* pyqt=5.9.2=py37h22d08a2\_1
* pysocks=1.6.8=py37\_0
* pystan=2.18.0.0=py37h962f231\_0
* python=3.7.3=h0371630\_0
* python-dateutil=2.8.0=py37\_0
* python-levenshtein=0.12.0=py37h14c3975\_1000
* pytorch=1.0.1=cuda100py37he554f03\_0
* pytz=2018.9=py37\_0
* pyyaml=5.1=py37h7b6447c\_0
* qt=5.9.7=h5867ecd\_1
* r=3.5.1=r351\_0
* r-abind=1.4\_5=r351h6115d3f\_0
* r-acepack=1.4.1=r351ha65eedd\_0
* r-aer=1.2\_5=r351h6115d3f\_0
* r-arm=1.10\_1=r351h6115d3f\_1000
* r-arules=1.6\_2=r351h96ca727\_1000
* r-assertthat=0.2.0=r351h6115d3f\_0
* r-backports=1.1.2=r351h96ca727\_0
* r-base=3.5.1=h1e0a451\_2
* r-base64enc=0.1\_3=r351h96ca727\_4
* r-bayestree=0.3\_1.4=r351hf484d3e\_0
* r-bh=1.66.0\_1=r351h6115d3f\_0
* r-bibtex=0.4.2=r351h14c3975\_1
* r-bindr=0.1.1=r351h6115d3f\_0
* r-bindrcpp=0.2.2=r351h29659fb\_0
* r-bit=1.1\_14=r351hd10c6a6\_0
* r-bit64 0.9\_7=r351hd10c6a6\_0
* r-bitops=1.0\_6=r351h96ca727\_4
* r-blob=1.1.1=r351hf348343\_0
* r-boot=1.3\_20=r351hf348343\_0
* r-boruta=6.0.0=r351h6115d3f\_0
* r-brew=1.0\_6=r351h6115d3f\_4
* r-broom=0.5.0=r351h6115d3f\_0
* r-car=3.0\_0=r351h6115d3f\_0
* r-cardata=3.0\_1=r351h6115d3f\_0
* r-caret=6.0\_80=r351h96ca727\_0
* r-catools=1.17.1.1=r351h29659fb\_0
* r-cellranger=1.1.0=r351h6115d3f\_0
* r-ceriolioutlierdetection=1.1.9=r351\_0
* r-checkmate=1.8.5=r351h96ca727\_0
* r-chron=2.3\_52=r351h96ca727\_0
* r-class=7.3\_14=r351hd10c6a6\_4
* r-cli=1.0.0=r351h6115d3f\_1
* r-cluster=2.0.7\_1=r351hac1494b\_0
* r-coda=0.19\_1=r351h6115d3f\_0
* r-codetools=0.2\_15=r351h6115d3f\_0
* r-coin=1.2\_2=r351h96ca727\_0
* r-colorspace=1.3\_2=r351h96ca727\_0
* r-commonmark=1.5=r351h96ca727\_0
* r-corpcor=1.6.9=r351h6115d3f\_1001
* r-crayon=1.3.4=r351h6115d3f\_0
* r-cubist=0.2.2=r351h96ca727\_1000
* r-curl=3.2=r351hadc6856\_1
* r-cvst=0.2\_2=r351h6115d3f\_0
* r-cvtools=0.3.2=r351h6115d3f\_0
* r-data.table=1.11.4=r351h96ca727\_0
* r-dbi=1.0.0=r351h6115d3f\_0
* r-ddalpha=1.3.4=r351h80f5a37\_0
* r-deoptimr=1.0\_8=r351h6115d3f\_0
* r-deriv=3.8.5=r351h6115d3f\_1001
* r-desc=1.2.0=r351h6115d3f\_0
* r-dichromat=2.0\_0=r351h6115d3f\_4
* r-digest=0.6.15=r351h96ca727\_0
* r-dimred=0.1.0=r351h6115d3f\_0
* r-diptest=0.75\_7=r351h96ca727\_1001
* r-dmwr=0.4.1=r351h6115d3f\_1001
* r-domomagic=0.1=r351\_0
* r-doparallel=1.0.11=r351h6115d3f\_0
* r-dplyr=0.7.6=r351h29659fb\_0
* r-drr=0.0.3=r351h6115d3f\_0
* r-dummies=1.5.6=r351\_0
* r-e1071 1.7\_0=r351h29659fb\_0
* r-evaluate=0.11=r351h6115d3f\_0
* r-fansi=0.2.3=r351h96ca727\_0
* r-flexclust=1.3\_4=r351h14c3975\_1002
* r-flexmix=2.3\_15=r351h6115d3f\_0
* r-forcats=0.3.0=r351h6115d3f\_0
* r-foreach=1.4.4=r351h6115d3f\_0
* r-forecast=8.4=r351h29659fb\_0
* r-foreign=0.8\_71=r351h96ca727\_0
* r-formula=1.2\_3=r351h6115d3f\_0
* r-fpc=2.1\_11.1=r351h6115d3f\_1001
* r-fracdiff=1.4\_2=r351h96ca727\_4
* r-gains=1.2=r351\_0
* r-gbm=2.1.5=r351h29659fb\_0
* r-gbrd=0.4\_11=r351h6115d3f\_1000
* r-gdata=2.18.0=r351h6115d3f\_0
* r-geometry=0.3\_6=r351h96ca727\_0
* r-ggally=1.4.0=r351h6115d3f\_1000
* r-ggplot2 3.0.0=r351h6115d3f\_0
* r-git2r=0.23.0=r351h96ca727\_1
* r-glmnet=2.0\_16=r351ha65eedd\_0
* r-glue=1.3.0=r351h96ca727\_0
* r-gmedian=1.2.4=r351hf484d3e\_0
* r-gower=0.1.2=r351h96ca727\_0
* r-gplots=3.0.1=r351h6115d3f\_0
* r-gridextra=2.3=r351h6115d3f\_0
* r-gtable=0.2.0=r351h6115d3f\_0
* r-gtools=3.8.1=r351h96ca727\_0
* r-haven=1.1.2=r351h29659fb\_0
* r-highr=0.7=r351h6115d3f\_0
* r-hmisc=4.1\_1=r351ha65eedd\_0
* r-hms=0.4.2=r351h6115d3f\_0
* r-htmltable=1.12=r351h6115d3f\_0
* r-htmltools=0.3.6=r351h29659fb\_0
* r-htmlwidgets=1.2=r351h6115d3f\_0
* r-httr=1.3.1=r351h6115d3f\_1
* r-hunspell=2.9=r351h29659fb\_0
* r-ipred=0.9\_6=r351h96ca727\_0
* r-isocodes=2018.06.29=r351h6115d3f\_0
* r-iterators=1.0.10=r351h6115d3f\_0
* r-janeaustenr=0.1.5=r351h6115d3f\_0
* r-jomo=2.6\_2=r351h96ca727\_1000
* r-jsonlite=1.5=r351h96ca727\_0
* r-kernlab=0.9\_26=r351h80f5a37\_0
* r-kernsmooth=2.23\_15=r351hac1494b\_4
* r-kfksds=1.6=r351hf484d3e\_0
* r-kmsurv=0.1\_5=r351h6115d3f\_1001
* r-knitr=1.20=r351h6115d3f\_0
* r-labeling=0.3=r351h6115d3f\_4
* r-laeken=0.5.0=r351h6115d3f\_0
* r-lattice=0.20\_35=r351h96ca727\_0
* r-latticeextra=0.6\_28=r351h6115d3f\_0
* r-lava=1.6.2=r351h6115d3f\_0
* r-lazyeval=0.2.1=r351h96ca727\_0
* r-leaps=3.0=r351ha65eedd\_0
* r-littler=0.3.7=r351h14c3975\_0
* r-lme4 1.1\_17=r351h29659fb\_0
* r-lmtest=0.9\_36=r351ha65eedd\_0
* r-lubridate=1.7.4=r351h29659fb\_0
* r-magic=1.5\_8=r351h6115d3f\_0
* r-magrittr=1.5=r351h6115d3f\_4
* r-maptools=0.9\_3=r351h96ca727\_0
* r-markdown=0.8=r351h96ca727\_0
* r-mass=7.3\_50=r351h96ca727\_0
* r-matrix=1.2\_14=r351h96ca727\_0
* r-matrixcalc=1.0\_3=r351h6115d3f\_1001
* r-matrixmodels=0.4\_1=r351h6115d3f\_4
* r-maxlik=1.3\_4=r351h6115d3f\_0
* r-mclust=5.4.3=r351h9bbef5b\_0
* r-mcmc=0.9\_6=r351h14c3975\_0
* r-mcmcpack=1.4\_0=r351hf484d3e\_1002
* r-memoise=1.1.0=r351h6115d3f\_0
* r-mgcv=1.8\_24=r351h96ca727\_0
* r-mi=1.0=r351h6115d3f\_1001
* r-mice=3.4.0=r351h29659fb\_0
* r-mime=0.5=r351h96ca727\_0
* r-minqa=1.2.4=r351h80f5a37\_4
* r-misctools=0.6\_22=r351h6115d3f\_0
* r-mitml=0.3\_7=r351h6115d3f\_0
* r-mitools=2.3=r351\_1000
* r-mlbench=2.1\_1=r351h14c3975\_1002
* r-mlogit=0.4\_1=r351h6115d3f\_0
* r-mnormt=1.5\_5=r351ha65eedd\_0
* r-mnp=3.1\_0=r351h14c3975\_0
* r-modelmetrics=1.1.0=r351h29659fb\_0
* r-modeltools=0.2\_22=r351h6115d3f\_0
* r-moments=0.14=r351\_1001
* r-multcomp=1.4\_8=r351h6115d3f\_0
* r-munsell=0.5.0=r351h6115d3f\_0
* r-mvoutlier=2.0.9=r351\_1001
* r-mvtnorm=1.0\_8=r351ha65eedd\_0
* r-nada=1.6\_1=r351h6115d3f\_1000
* r-naivebayes=0.9.5=r351\_0
* r-neuralnet=1.44.2=r351h6115d3f\_0
* r-nlme=3.1\_137=r351ha65eedd\_0
* r-nloptr=1.0.4=r351h29659fb\_4
* r-nlp=0.1\_11=r351h6115d3f\_0
* r-nnet=7.3\_12=r351h96ca727\_0
* r-numderiv=2016.8\_1=r351h6115d3f\_0
* r-openssl=1.0.2=r351h96ca727\_1
* r-openxlsx=4.1.0=r351h29659fb\_0
* r-outliers=0.14=r351\_2001
* r-pan=1.6=r351ha65eedd\_0
* r-party=1.3\_3=r351h14c3975\_0
* r-pbkrtest=0.4\_7=r351h6115d3f\_0
* r-pcapp=1.9\_73=r351h29659fb\_0
* r-penalized=0.9\_51=r351h29659fb\_1002
* r-pillar=1.3.0=r351h6115d3f\_0
* r-pkgconfig=2.0.1=r351h6115d3f\_0
* r-pkgkitten=0.1.4=r351\_0
* r-plogr=0.2.0=r351h6115d3f\_0
* r-pls=2.6\_0=r351h6115d3f\_0
* r-plyr=1.8.4=r351h29659fb\_0
* r-pmml=1.5.7=r351\_0
* r-polspline=1.1.13=r351ha65eedd\_0
* r-prabclus=2.2\_7=r351h6115d3f\_0
* r-prettyunits=1.0.2=r351hf348343\_0
* r-prodlim=2018.04.18=r351h29659fb\_0
* r-progress=1.2.0=r351h6115d3f\_1002
* r-pryr=0.1.4=r351h29659fb\_0
* r-psych=1.8.4=r351h6115d3f\_0
* r-purrr=0.2.5=r351h96ca727\_0
* r-quadprog=1.5\_5=r351ha65eedd\_4
* r-quantmod=0.4\_13=r351h6115d3f\_0
* r-quantreg=5.36=r351ha65eedd\_0
* r-r6 2.2.2=r351h6115d3f\_0
* r-randomforest=4.6\_14=r351ha65eedd\_0
* r-randomforestsrc=2.8.0=r351hcdcec82\_0
* r-ranger=0.10.1=r351h29659fb\_0
* r-rcolorbrewer=1.1\_2=r351h6115d3f\_0
* r-rcpp=0.12.18=r351h29659fb\_0
* r-rcpparmadillo=0.8.600.0.0=r351h29659fb\_0
* r-rcppeigen=0.3.3.4.0=r351h29659fb\_0
* r-rcpproll=0.3.0=r351h29659fb\_0
* r-rdpack=0.10\_1=r351h6115d3f\_1000
* r-readr=1.1.1=r351h29659fb\_0
* r-readxl=1.1.0=r351h29659fb\_0
* r-recipes=0.1.3=r351h6115d3f\_0
* r-recommended=3.5.1=r351\_0
* r-reemtree=0.90.3=r351\_0
* r-relaimpo=2.2\_3=r351h6115d3f\_0
* r-rematch=1.0.1=r351h6115d3f\_0
* r-reshape=0.8.7=r351h6115d3f\_0
* r-reshape2 1.4.3=r351h29659fb\_0
* r-rgeos=0.5\_2=r35hb2de1b9\_3
* r-rio=0.5.10=r351h6115d3f\_0
* r-rjson=0.2.20=r351hebc1506\_0
* r-rlang=0.2.1=r351h96ca727\_0
* r-rms=5.1\_2=r351ha65eedd\_0
* r-robcompositions=2.0.10=r351h29659fb\_0
* r-robustbase=0.93\_2=r351ha65eedd\_0
* r-rocr=1.0\_7=r351h6115d3f\_4
* r-rose=0.0\_3=r351\_0
* r-rpart=4.1\_13=r351hd10c6a6\_0
* r-rpmm=1.25=r351h6115d3f\_1000
* r-rprojroot=1.3\_2=r351h6115d3f\_0
* r-rrcov=1.4\_4=r351ha65eedd\_1000
* r-rsnns=0.4\_11=r351h29659fb\_1000
* r-rspectra=0.13\_1=r351hf484d3e\_0
* r-rsqlite=2.1.1=r351h29659fb\_0
* r-rstudioapi=0.7=r351h6115d3f\_0
* r-sandwich=2.4\_0=r351h6115d3f\_0
* r-scales=0.5.0=r351h29659fb\_0
* r-sem=3.1\_9=r351h29659fb\_1002
* r-sfsmisc=1.1\_2=r351h6115d3f\_0
* r-sgeostat=1.0\_27=r351h9ac9557\_1002
* r-slam=0.1\_43=r351h96ca727\_0
* r-snowballc=0.5.1=r351h96ca727\_0
* r-sp=1.3\_1=r351h96ca727\_0
* r-sparsem=1.77=r351ha65eedd\_0
* r-spatial=7.3\_11=r351hd10c6a6\_4
* r-squarem=2017.10\_1=r351h6115d3f\_0
* r-sroc=0.1\_2=r351h14c3975\_1002
* r-statmod=1.4.30=r351h9ac9557\_1002
* r-sticky=0.5.2=r351\_0
* r-stopwords=0.9.0=r351h6115d3f\_0
* r-stringdist=0.9.5.1=r351h96ca727\_0
* r-stringi=1.2.4=r351h29659fb\_0
* r-stringr=1.3.1=r351h6115d3f\_0
* r-strucchange=1.5\_1=r351h6115d3f\_0
* r-stsm=1.9=r351hf484d3e\_0
* r-survey=3.35\_1=r351h6115d3f\_0
* r-survival=2.42\_6=r351h96ca727\_0
* r-th.data=1.0\_9=r351h6115d3f\_0
* r-tibble=1.4.2=r351h96ca727\_0
* r-tidyr=0.8.1=r351h29659fb\_0
* r-tidyselect=0.2.4=r351h29659fb\_0
* r-tidytext=0.1.9=r351h6115d3f\_0
* r-timedate=3043.102=r351h6115d3f\_0
* r-timeseries=3042.102=r351h6115d3f\_0
* r-tm=0.7\_5=r351h29659fb\_0
* r-tokenizers=0.2.1=r351h29659fb\_0
* r-tree=1.0\_39=r351ha65eedd\_1000
* r-trimcluster=0.1\_2.1=r351h6115d3f\_1000
* r-truncnorm=1.0\_8=r351h96ca727\_1000
* r-truncreg=0.2\_5=r351\_0
* r-tseries=0.10\_45=r351ha65eedd\_0
* r-tsoutliers=0.6\_8=r351\_0
* r-ttr=0.23\_3=r351ha65eedd\_0
* r-urca=1.3\_0=r351ha65eedd\_0
* r-uroot=2.0\_9=r351h29659fb\_0
* r-utf8 1.1.4=r351h96ca727\_0
* r-vcd=1.4\_4=r351h6115d3f\_1001
* r-vim=4.8.0=r351h29659fb\_0
* r-viridis=0.5.1=r351h6115d3f\_0
* r-viridislite=0.3.0=r351h6115d3f\_0
* r-vsurf=1.0.4=r351\_0
* r-whisker=0.3\_2=r351hf348343\_4
* r-withr=2.1.2=r351h6115d3f\_0
* r-xgboost=0.80=r351h895cf53\_0
* r-xml=3.98\_1.12=r351h96ca727\_0
* r-xml2 1.2.0=r351h29659fb\_0
* r-xts=0.11\_0=r351h96ca727\_0
* r-yaml=2.2.0=r351h96ca727\_0
* r-zcompositions=1.2.0=r351h6115d3f\_0
* r-zip=1.0.0=r351h96ca727\_0
* r-zoo=1.8\_3=r351h96ca727\_0
* readline=7.0=h7b6447c\_5
* requests=2.21.0=py37\_0
* requests-oauthlib=1.2.0=py\_0
* responses=0.10.5=py37\_0
* scikit-learn=0.20.3=py37hd81dba3\_0
* scipy=1.2.1=py37h7c811a0\_0
* scour=0.37=py\_0
* setuptools=40.8.0=py37\_0
* setuptools-git=1.2=py37h28b3542\_1
* sip=4.19.13=py37he6710b0\_0
* six=1.12.0=py37\_0
* sklearn-pandas=1.8.0=py37\_0
* sqlite=3.27.2=h7b6447c\_0
* statsmodels=0.9.0=py37h035aef0\_0
* theano=1.0.3=py37hfd86e86\_0
* tk=8.6.8=hbc83047\_0
* tktable=2.10=h14c3975\_0
* tornado=6.0.2=py37h7b6447c\_0
* twython=3.7.0=py37\_0
* urllib3 1.24.1=py37\_0
* wheel=0.33.1=py37\_0
* xz=5.2.4=h14c3975\_4
* yaml=0.1.7=h96e3832\_1
* zlib=1.2.11=h7b6447c\_3
* zstd=1.3.7=h0b5b093\_0
* pip:
* absl-py==0.7.1
* astor==0.7.1
* gast==0.2.2
* grpcio==1.19.0
* keras-applications==1.0.7
* keras-preprocessing==1.0.9
* markdown==3.1
* mock==2.0.0
* pbr==5.1.3
* pmdarima==1.1.1
* protobuf==3.7.1
* tensorboard==1.13.1
* tensorflow==1.13.1
* tensorflow-estimator==1.13.0
* termcolor==1.1.0
* werkzeug==0.15.1
