---
title : Unfollowing a Buzz Conversation
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:40:00
url : https://domo-support.domo.com/s/article/360042925794
linked_kbs :  ['https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925794', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000004313
views : 3,971
created_date : 2022-10-24 21:36:00
last updated : 2022-10-24 22:40:00
---



In Domo, when a Buzz conversation is sent to a group of which you are a member or you are manually added as a recipient of such a conversation, by default you receive notifications for ALL future posts in the conversation. You can unfollow a Buzz conversation so you do not receive further notifications for that conversation. You do this by selecting theÂ **Unfollow Conversation**Â option in the Details paneÂ for the conversation.Â 


**To unfollow a Buzz conversation,**


**Note:Â** Buzz conversations can be unfollowed, but not deleted.
1. OpenÂ the Buzz conversation you want to unfollow.
2. (Conditional) If you are not in full-screen mode, click the ellipsis icon (...)Â to open the Details pane for the conversation.
3. SelectÂ **Unfollow Conversation**.


After you have unfollowed a conversation, you can refollow so you continue to receive notifications for posts in the conversation as normal.Â 


**To refollow a Buzz conversation,**


1. Open the Buzz conversation you want to follow.
2. (Conditional) If you are not in full-screen mode, clickÂ the ellipsis icon (...)Â to open the Details pane for the conversation.
3. Select **Follow** **Conversation**.