---
title: Azure SQL Data Warehouse Connector
url: https://domo-support.domo.com/s/article/1500000281802
linked_kbs:  ['[https://domo-support.domo.com/s/knowledge-base/](https://domo-support.domo.com/s/knowledge-base/)', '[https://domo-support.domo.com/s/](https://domo-support.domo.com/s/)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZammGAC](https://domo-support.domo.com/s/topic/0TO5w000000ZammGAC)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZanLGAS](https://domo-support.domo.com/s/topic/0TO5w000000ZanLGAS)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZaojGAC](https://domo-support.domo.com/s/topic/0TO5w000000ZaojGAC)', '[https://domo-support.domo.com/s/article/360042931674](https://domo-support.domo.com/s/article/360042931674)', '[https://domo-support.domo.com/s/article/1500000281802](https://domo-support.domo.com/s/article/1500000281802)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZaojGAC/database-connectors](https://domo-support.domo.com/s/topic/0TO5w000000ZaojGAC/database-connectors)', '[https://domo-support.domo.com/s/article/360043429933](https://domo-support.domo.com/s/article/360043429933)', '[https://domo-support.domo.com/s/article/360043429953](https://domo-support.domo.com/s/article/360043429953)', '[https://domo-support.domo.com/s/article/360042925494](https://domo-support.domo.com/s/article/360042925494)', '[https://domo-support.domo.com/s/article/4408174643607](https://domo-support.domo.com/s/article/4408174643607)', '[https://domo-support.domo.com/s/article/360043429913](https://domo-support.domo.com/s/article/360043429913)', '[https://domo-support.domo.com/s/login/](https://domo-support.domo.com/s/login/)']
article_id: 000003868
views: 2,164
created_date: 2022-10-24 21:16:00
last updated: 2022-10-24 22:41:00
---



Azure SQL Datawarehouse is now Azure Synapse SQL Datawarehouse
--------------------------------------------------------------


#### *What is happening?*


Starting on Monday Nov 16th 2020, the **Azure SQL Data Warehouse** **Connector** will be known as the **Azure Synapse SQL Connector**. 


#### *How does this affect me?*


All Azure SQL Data Warehouse datasets will continue to run as normal. The functionality of the connector has not been changed.


Customers using or planning to use the connector will notice the following:


1. There is a new icon for the connector in the Appstore.  Existing datasets will now show up on the Data Center with the new icon.
2. Customers who are trying to search for an Azure Data Warehouse dataset in the Data Center using a ‘Type’ filter will now need to search for datasets of type ‘Azure Synapse SQL’ instead of ‘Azure Data Warehouse’.
3. Customers who want to create a new Azure SQL Data Warehouse will need to search the Appstore for the ‘Azure Synapse SQL Connector’ instead of the ‘Azure SQL Data Warehouse Connector.’
4. Connector Accounts for the Azure SQL Data Warehouse Connector will now be called ‘Azure Synapse SQL’ Accounts.


#### *Do I need to take any action if I have any Azure Data Warehouse datasets?*


No action is required on your part. Your existing Azure Data Warehouse/Azure Synapse SQL datasets will continue to run without interruption, and you will still be able to create new datasets with existing credentials as needed. You do not need to update any of your reports or Accounts.


Please visit [Azure Synapse SQL Connector](/s/article/360042931674 "https://knowledge.domo.com/Connect/Connecting_to_Data_with_Connectors/Configuring_Each_Connector/Database_Connectors/Azure_Synapse_SQL_Connector") documentation for any queries related to the connector functionality.

