---
title : CSV Upload Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:41:00
url : https://domo-support.domo.com/s/article/360042931934
linked_kbs :  ['https://domo-support.domo.com/s/article/360043436513', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042931914', 'https://domo-support.domo.com/s/article/360043436393', 'https://domo-support.domo.com/s/article/360043436573', 'https://domo-support.domo.com/s/article/360042931934', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003943
views : 4,138
created_date : 2022-10-24 21:17:00
last updated : 2022-10-24 22:41:00
---



This connector is now DEPRECATED.


To upload CSV files from your local machine or network to Domo, use our [File Upload connector](..\file_upload_connector\index.html "File Upload Connector").


To upload CSV files to Domo from an external SFTP server, use either our [CSV Advanced Connector](..\csv_advanced_connector\index.html "CSV-SFTP Connector").


To upload CSV files to Domo using Domo's own SFTP server, use the [CSV SFTP Push Connector](..\csv_sftp_push_connector\index.html "CSV SFTP Push Connector").


To upload CSV files to Domo from a website, use the [CSV Advanced Connector](..\csv_advanced_connector\index.html "CSV Advanced Connector").


To upload CSV files to Domo from a third-party service, use the connector corresponding to that service, such as [Amazon S3](..\amazon_s3_connector\index.html "Box Connector"), etc.