---
title: SFTP Writeback Connector
url: https://domo-support.domo.com/s/article/360042932474
linked_kbs:  ['[https://domo-support.domo.com/s/knowledge-base/](https://domo-support.domo.com/s/knowledge-base/)', '[https://domo-support.domo.com/s/](https://domo-support.domo.com/s/)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZammGAC](https://domo-support.domo.com/s/topic/0TO5w000000ZammGAC)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZanLGAS](https://domo-support.domo.com/s/topic/0TO5w000000ZanLGAS)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZapVGAS](https://domo-support.domo.com/s/topic/0TO5w000000ZapVGAS)', '[https://domo-support.domo.com/s/article/360042926274](https://domo-support.domo.com/s/article/360042926274)', '[https://domo-support.domo.com/s/article/360042926054](https://domo-support.domo.com/s/article/360042926054)', '[https://domo-support.domo.com/s/article/360042932474](https://domo-support.domo.com/s/article/360042932474)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZapVGAS/writeback-connectors](https://domo-support.domo.com/s/topic/0TO5w000000ZapVGAS/writeback-connectors)', '[https://domo-support.domo.com/s/article/360043429933](https://domo-support.domo.com/s/article/360043429933)', '[https://domo-support.domo.com/s/article/360043429953](https://domo-support.domo.com/s/article/360043429953)', '[https://domo-support.domo.com/s/article/360042925494](https://domo-support.domo.com/s/article/360042925494)', '[https://domo-support.domo.com/s/article/4408174643607](https://domo-support.domo.com/s/article/4408174643607)', '[https://domo-support.domo.com/s/article/360043429913](https://domo-support.domo.com/s/article/360043429913)', '[https://domo-support.domo.com/s/login/](https://domo-support.domo.com/s/login/)']
article_id: 000004025
views: 2,399
created_date: 2022-10-24 21:18:00
last updated: 2022-10-24 22:40:00
---



Intro
-----


Use this connector to export your data from a Domo DataSet to an SFTP server. To learn more about SFTP, visit the Wikipedia page at [https://en.wikipedia.org/wiki/SSH\_Fi...nsfer\_Protocol](https://en.wikipedia.org/wiki/SSH_File_Transfer_Protocol "https://en.wikipedia.org/wiki/SSH_File_Transfer_Protocol").


You export data to an SFTP server in the Data Center. This topic discusses the fields and menus that are specific to the SFTP Writeback connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed in [Adding a DataSet Using a Data Connector](/s/article/360042926274 "Adding a DataSet Using a Data Connector").







**Note:** The owner of a writeback dataset must also be an owner or co-owner of the input dataset.




Prerequisites
-------------


To configure this connector, you will need the following:


* A Domo Client ID and Client Secret.
* Your SFTP server hostname.




 


**Important:** The SFTP Server host name must have **sftp://** in the beginning of the URL and should not end with a **front slash (/)**.
* Your SFTP server port number.
* Your SFTP server username and password.
* Your SFTP server SSH private key.
* The passphrase for your SSH private key.







**Note:** Domo does not support the SSH keys generated using ssh-keygen. The SSH keys need to be the DES or RSA keys (in PEM format) generated by OpenSSL.



OpenSSH private key format can be converted using ssh-keygen utility to the old PEM format.





```
 ssh-keygen -p -m PEM -f ~/.ssh/id_rsa 
```



This will update the same file with the RSA key.


### To obtain your Domo Client ID and Client Secret, do the following:


1. Login to [Domo developer account.](https://developer.domo.com/login)
2. In the top right corner under **My Account,** click **New Client.**
3. Enter the application name and description.
4. Provide the application scope by selecting **Account**, **Data**, and **User**.
5. Click **Create.**
6. Once you have created a client, you can manage the client by clicking on **Manage Client.**
7. Your **Client Secret** will appear in the **Manage Client** section.


Configuring the Connection
--------------------------


This section enumerates the options in the **Credentials** and **Details** panes in the SFTP Writeback Connector page. The components of the other panes in this page, **Scheduling** and **Name & Describe Your DataSet**, are universal across most connector types and are discussed in greater length in [Adding a DataSet Using a Data Connector](/s/article/360042926274 "Adding a DataSet Using a Data Connector").


### Credentials Pane


This pane contains fields for entering credentials to connect to your Domo developer account as well as your SFTP server. Depending on the configuration of the SFTP server, you may need either a Private Key and Passphrase, username and password, or both. The following table describes what is needed for each field:


 




| Field | Description |
| --- | --- |
| Domo Client ID | Enter your Domo client ID. |
| Domo Client Secret | Enter your Domo client secret. |
| Hostname | Enter your SFTP server hostname. 


 


**Important:** The SFTP Server host name must have **sftp://** in the beginning of the URL and should not end with a **front slash (/)**.


 |
| Port | Enter your SFTP server port number. |
| Username | Enter your SFTP server username. |
| Password | Enter your SFTP server password.  |
| SSH Private Key | Enter your SFTP server SSH private key (RSA).  |
| Passphrase | Enter the passphrase for your SSH private key. |


Once you have entered valid credentials, you can use the same account any time you go to set up a new Domo-SFTP connection. You can manage connector accounts in the **Accounts** tab in the Data Center. For more information about this tab, see [Managing User Accounts for Connectors](/s/article/360042926054 "Managing User Accounts for Connectors").


 


### Details Pane


This pane contains a number of fields for specifying your data and indicating where it's going.




| Menu | Description |
| --- | --- |
| Input DataSet ID | Enter the DataSet ID (GUID) for the DataSet you want to copy to the SFTP server. You can find the ID by opening the details view for the DataSet in the Data Center and looking at the portion of the URL following datasources/. For example, in the URL <https://mycompany.domo.com/datasources/845305d8-da3d-4107-a9d6-13ef3f86d4a4/details/overview>, the DataSet ID is 845305d8-da3d-4107-a9d6-13ef3f86d4a4.





**Note:** You must either own this DataSet or have the Admin role in Domo.


 |
| Path | Enter the path in your SFTP server where you would like the data to be saved.  |
| Select Filename | Select whether you want to reference your DataSet using the **Input DataSet ID** or an output file name.  |
| Filename | Enter the output file name for your data.


 


**Note:** Your output file is stored as a CSV file. You do not need to add the extension onto your file name.


 |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, see [Adding a DataSet Using a Data Connector](/s/article/360042926274 "Adding a DataSet Using a Data Connector").

