---
title : Available Pie-Type Charts
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:39:00
url : https://domo-support.domo.com/s/article/360043428913
linked_kbs :  ['https://domo-support.domo.com/s/article/360043429113', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360043428033', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042924494', 'https://domo-support.domo.com/s/article/360042925054', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043428913', 'https://domo-support.domo.com/s/article/360042924854', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000004735
views : 4,274
created_date : 2022-10-24 22:28:00
last updated : 2022-10-24 22:39:00
---



A pie-type graph is a graph divided into sections thatÂ usually add up to 100%. Each section represents the relative size of its corresponding value. Pie-type graphs are usually accompanied by legends so you can tell what each section represents. In Domo, legends are added automatically.


When you are powering up a pie-type graph, the values in your values column do *not* need to be percentages, because Domo sums the values and converts each into the correct percentage of the total.


The following table lists the Pie-type graphsÂ available in Domo. You can click a thumbnail image to see a larger image.




| Chart Type | Description | Example |
| --- | --- | --- |
| Pie graph
 | The most common of the pie-type graphs, a basic Pie graph is a circle divided into cone-shaped "wedges," each of which represents a percentage of the overall graph.
For more information, see [Pie Graph](..\pie_chart\index.html "Pie Graph"). |  |
| Donut graph
 | Donut graphs are almost identical to Pie graphs; the only difference is that they contain a hole in the middle, like a doughnut, so the sections are arcs of a circle rather than wedges.
For more information, see [Donut Chart](..\donut_chart\index.html "Donut Graph"). |  |
| Nautilus graph
 | A Nautilus graph is the same as a standard Pie graph, except that the "wedges" are arranged in a logarithmic spiral and become smaller closer to the center of the spiral. This layout makes it easier to distinguish small differences between slices than it is with a regular Pie graph.
For more information, see [Pie Graph](..\pie_chart\index.html "Pie Graph"). |  |
| Nautilus Donut graph
 | A Nautilus Donut graph is the same as a standard Donut graph, except that the "wedges" are arranged in a logarithmic spiral and become smaller closer to the center of the spiral.
For more information, see [Pie Graph](..\pie_chart\index.html "Pie Graph"). |  |
| Nightingale Rose graph
 | As with other Pie-type graphs, Nightingale Rose graphs are divided into sections, each of which represents a percentage of the overall graph. These graphs are unique in that they are based on a polar coordinate system, i.e. each wedge originates from a common point in the center of the graph. This layout makes it easy to see smaller contributors to the overall pie.
For more information, see [Pie Graph](..\pie_chart\index.html "Pie Graph"). |  |
| Funnel graph
 | Funnel graphs are similar to basic Pie graphs, except that they use a funnel shape divided into horizontal sections.Â 
By default,Â in the legend for a Funnel graph, the percentage for each successive layer is derived from the value of the previous layer. This functionality is appropriate forÂ conversion charts, in which you want to show the degree of changeÂ from one process to the next. If you want, you can turn off this default functionality. In this case,Â percentages are derived from the chart total, as in a standard Pie chart.Â The screenshot shows aÂ typical conversion Funnel graph.
For more information, see [Funnel Chart](..\funnel_chart\index.html "Funnel Graph"). |  |
| Stream Funnel graph
 | A Stream Funnel graph is cross between a [Stacked Area graph](..\stacked_area_chart\index.html "Funnel Graph"). Unlike other pie-type graphs in Domo, Stream Funnel graphs allow you to include series data (though this is not required). Legends are not shown in a Stream Funnel graph unless series data is included. Stream Funnel graphs also do not show value data except upon mouse-over. Therefore they are best used for showing relative differences between stages rather than representing exact amounts.Â 
For more information, seeÂ [Funnel Chart](..\funnel_chart\index.html "Funnel Graph"). |  |
| Folded Funnel graph
 | A Folded Funnel graph is a Funnel graph in which the sections have been "folded." This type of Funnel graph shows the relative sizes of sections more accurately than a regular Funnel graph.
For more information, see [Funnel Chart](..\funnel_chart\index.html "Funnel Graph"). |  |
| Funnel Bars graph
 | A Funnel Bars graph is a combination of a Funnel graph and a horizontal Bar graph. This graph type shows differences between one stage in a process (such as a sales cycle) and the next. For each stage in the process, the data for the previous round drops off, so that only the relationships between the current round and all subsequent rounds is shown. In essence, this chart type shows "what's left" after each stage in a process. The example at right shows a Funnel Bars graph for a typical sales cycle. Each subsequent stage depicts the number of potential customers who have progressed to that stage.
For more information, see [Funnel Chart](..\funnel_chart\index.html "Funnel Graph"). |  |
| Tree MapÂ 
 | A Tree Map displays the names of categories within rectangles of differing sizes. The sizes of the rectangles reflect the relative values of each category.
For more information, see [Tree Map](..\tree_map\index.html "Tree Map"). |  |


Â