---
title : Available Line Charts
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:42:00
url : https://domo-support.domo.com/s/article/360042924274
linked_kbs :  ['https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360043429353', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360043429153', 'https://domo-support.domo.com/s/article/360042924754', 'https://domo-support.domo.com/s/article/360043429253', 'https://domo-support.domo.com/s/article/360043429233', 'https://domo-support.domo.com/s/article/360043428053', 'https://domo-support.domo.com/s/article/360042924594', 'https://domo-support.domo.com/s/article/360042924274', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000004740
views : 8,185
created_date : 2022-10-24 22:28:00
last updated : 2022-10-24 22:42:00
---



Line charts are most often used to represent trends over time. Data items in a line chart are represented by points, and these are connected by a line. Some types of line charts, such as grouped bar with line charts, combine lines with elements found in other types of charts.


The following tables list the types of line charts available in Domo. You can click a thumbnail image to see a larger image.


#### Horizontal line charts


Line charts are usually displayed with the line running left to right, with the value scale on the vertical axis and the category scale on the horizontal axis. There are 12 such chart types in Domo (counting 5 line-bar combination-type charts, which in the Chart Picker in Domo are found under the Bar charts section).




| Chart Type | Description | Example |
| --- | --- | --- |
| Line chart
 | Basic line charts use a single trendline to display data.
For more information, see [Line chart](..\line_chart\index.html "Line Graph"). |  |
| Symbol line chart
line-symbol-small.png | A symbol line chart is a sub-type of the basic line chart in which symbols are included at each data point.
For more information, see [Line chart](..\line_chart\index.html "Line Graph"). |  |
| Curved line chart
 | A curved line chart is a sub-type of the basic line chart in which points are connected by curved lines instead of straight lines.
For more information, see [Line chart](..\line_chart\index.html "Line Graph"). |  |
| Curved symbol line chart
 | A curved symbol line chart is the same as a curved line chart except that it includes symbols at each data point.
For more information, see [Line chart](..\line_chart\index.html "Line Graph"). |  |
| Step line
 | A step line is a sub-type of the basic line chart in which step lines are used instead of straight lines.
For more information, see [Line chart](..\line_chart\index.html "Line Graph"). |  |
| Multi-line chart
 | A multi-line chart is a basic line chart with one or more additional lines that represent comparison trends.
For more information, see [Multi-line chart](..\multiline_chart\index.html "Multi-Line Graph"). |  |
| Grouped bar with line chart
 | A grouped bar with line chart is a combination of a line chart and a grouped bar chart. It includes two y-axes, one on each side of the chart. One of these is used to measure the values along the line, and the other is used to measure the values of the bars. This type of chart is useful in situations in which you need to show a trend along with the specific quantities or amounts associated with that trend.
For more information, see [Grouped Bar with Line chart](..\grouped_bar_with_line_chart\index.html "Grouped Bar with Line Graph"). |  |
| Grouped bar with symbols chart

  | A grouped bar with symbols chart is the same as a grouped bar with line chart, except that it includes symbols instead of lines.
For more information, see [Grouped Bar with Line chart](..\grouped_bar_with_line_chart\index.html "Grouped Bar with Line Graph"). |  |
| Stacked bar with line chart
vertical-bar-stacked-plus-line-small.png | A stacked bar with line chart combines the features of a line chart and a vertical stacked bar chart. There are two y-axes, one on the left and the other on the right. The y-axis on the left measures the values along the line, and the one on the right measures the values of the bars.
For more information, see [Stacked Bar with Line chart](..\stacked_bar_with_line_chart\index.html "Stacked Bar with Line Graph"). |  |
| Stacked bar with symbols chart
 | A stacked bar with symbols chart is the same as a stacked bar with line chart, except that it includes symbols instead of lines.
For more information, see [Stacked Bar with Line chart](..\stacked_bar_with_line_chart\index.html "Stacked Bar with Line Graph"). |  |
| Grouped and stacked bar with line chart
vertical-bar-grouped-and-stacked-plus-line-small.png | A grouped and stacked bar with line chart is a combination of a vertical grouped and stacked bar chart and a stacked bar with line chart. As in a stacked bar with line chart, two value scales are present and series can appear as either lines or bars; this chart type also gives you the ability to divide series segments between bars, as in a grouped and stacked bar chart. As with standard grouped and stacked bar charts, this chart type is useful when you want to compare a primary series against several secondary series; however, because it includes a trendline, it is more compatible with time-series data than a regular grouped and stacked bar chart.
For more information, see [Grouped and Stacked Bar with Line chart](..\grouped_and_stacked_bar_with_line_chart\index.html "Grouped and Stacked Bar with Line Graph"). |  |
| Running total line chart
running-total-line-small.png | In a running total line chart, each data point shows the cumulative value of all data points up to that point. If more than one series is present, each series displays as its own individual line.
For more information, see [Running Total Line chart](..\running_total_line_chart\index.html "Running Total Line Graph"). |  |


#### Vertical line charts


Less commonly, line charts can be displayed with values on the horizontal axis and categories on the vertical axis. If the chart exceeds the vertical confines of the display area, scroll bars appear so users can scroll to see more of the chart. There are 5 types of vertical line charts in Domo.




| Chart Type | Description | Example |
| --- | --- | --- |
| Vertical line chart
vertical-line-small.png | A vertical line chart includes one or more lines that represent comparison trends. The chart in the first example includes only one trendline so the chart appears solid blue. The chart in the second example includes multiple lines.
For more information, see [Line chart](..\line_chart\index.html "Line Graph"). | 
vertical_multiline_kpi_example.png |
| Vertical curved line chart
vertical-line-curved-small.png | A vertical curved line chart is a sub-type of the basic vertical line chart in which points are connected by curved lines instead of straight lines.
For more information, see [Line chart](..\line_chart\index.html "Line Graph"). | vertical_line_curved_kpi_example.png |
| Vertical step line chart
vertical-line-step-small.png | A vertical step line chart is a sub-type of the basic line chart in which step lines are used instead of straight lines.
For more information, see [Line chart](..\line_chart\index.html "Line Graph"). | vertical_line_step_kpi_example.png |
| Vertical symbol line chart
vertical-line-symbol-small.png | A vertical symbol line chart is a sub-type of the basic vertical line chart in which symbols are included at each data point.
For more information, see [Line chart](..\line_chart\index.html "Line Graph"). | vertical_line_symbol_kpi_example.png |
| Vertical curved symbol line chart
 | A vertical curved symbol line chart is the same as a vertical curved line chart except that it includes symbols at each data point.
For more information, see [Line chart](..\line_chart\index.html "Line Graph"). | vertical_line_curved_symbol_kpi_example.png |


#### Miscellaneous line charts


Though technically a horizontal line chart, the spark line chart is included here because it is vastly different in many respects from standard line charts. This chart type is found in the **Other Charts** category in the Chart Picker.   




| Chart Type | Description | Example |
| --- | --- | --- |
| Spark line chart
spark-line-small.png | A spark line chart is essentially a line chart with no axes (providing a cleaner, uncluttered experience) and a built-in gauge that by default shows the degree of change between the first and last data points in the chart. Spark line charts are excellent for quickly showing relative rises and falls in data over time. 
For more information, see [Spark line chart](..\spark_line_chart\index.html "Spark Line Graph"). | spark_line_kpi_example.png |