---
title : Synthesio Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:40:00
url : https://domo-support.domo.com/s/article/360042927454
linked_kbs :  ['https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360042927454', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003705
views : 2,005
created_date : 2022-10-24 21:14:00
last updated : 2022-10-24 22:40:00
---



Intro
-----


Synthesio is a social intelligence tool used for social media monitoring and social analytics. Domo's Synthesio connector uses the Synthesio API to get tweet IDs from Synthesio dashboards and then rehydrates data using the Twitter API. To learn more about the Synthesio API, visit their page ([https://rest.synthesio.com/doc/#introduction](https://rest.synthesio.com/doc/#introduction "http://website.informer.com/visit?domain=api.synthesio.com")).  


You connect to your Synthesio account in the Data Center. This topic discusses the fields and menus that are specific to the Synthesio connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed in [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).


Prerequisites
-------------


To connect to your Synthesio account and create a DataSet, you must have the following:



* The username and password for your Synthesio account
* Your Synthesio client ID
* Your Synthesio client secret


For information about obtaining these credentials, reach out to your Synthesio account representative.


Connecting to Your Synthesio Account
------------------------------------


This section enumerates the options in the **Credentials** and **Details** panes in the Synthesio Connector page. The components of the other panes in this page, **Scheduling** and **Name & Describe Your DataSet**, are universal across most connector types and are discussed in greater length in [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md "Adding a DataSet Using a Data Connector").


### Credentials Pane


This pane contains fields for entering credentials to connect to your Synthesio account. 


The following table describes what is needed for each field when you are using the Domo connector:  




| Field | Description |
| --- | --- |
| Synthesio Username | Enter your Synthesio username. |
| Synthesio Password | Enter your Synthesio password. |
| Synthesio Client ID | Enter your Synthesio client ID. |
| Synthesio Client Secret | Enter your Synthesio client secret. |


Once you have entered valid Synthesio credentials, you can use the same account any time you go to create a new Synthesio DataSet. You can manage connector accounts in the **Accounts** tab in the Data Center. For more information about this tab, see [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


### Details Pane


This pane contains a primary **Reports** menu, along with various other menus which may or may not appear depending on the report type you select.




| Menu | Description |
| --- | --- |
| Report | Select the Synthesio report you want to run. 

|  |  |
| --- | --- |
| Synthesio Plus Twitter Report | Returns tweet IDs from Synthesio dashboards then rehydrates the data using the Twitter API. |

 |
| Report ID | Select the ID of the report you want to import into Domo. |
| Duration  | Select whether you want to pull data for a specific date or a date range.  |
| Report Date  | Select whether the report data is for a specific date or for a relative number of days back from today.  |
| Select Specific Date  | Select the date for the report.  |
| Days Back | Enter the number of past days that should appear in the report.   |
| Start Date | Specify whether the first date in your date range is a specific or relative date. You select the last date in your range in **End Date**.  |
| End Date | Specify whether the second date in your date range is a specific or relative date. You select the first date in your range in **Start Date**.   |
| Select Specific Start Date | Select the first date in your date range.  |
| Select Specific End Date | Select the second date in your date range.  |
| Days Back to Start From | Enter the number of the farthest day back that should be represented in the report. Combine with **Days Back to End At** to create a range of represented days.
For example, if you entered 10 for **Days Back to Start From** and 5 for **Days Back to End At**, the report would contain data for 10 days ago up until 5 days ago. |
| Days Back to End At | Enter the number of the most recent day back that should be represented in the report. Combine with **Days Back to Start From** to create a range of represented days.
For example, if you entered 10 for **Days Back to Start From** and 5 for **Days Back to End At**, the report would contain data for 10 days ago up until 5 days ago. |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, see [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).