---
title : GradLeaders Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:41:00
url : https://domo-support.domo.com/s/article/360042928154
linked_kbs :  ['https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360042928154', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003648
views : 2,025
created_date : 2022-10-24 21:13:00
last updated : 2022-10-24 22:41:00
---



Intro
-----


GradLeaders provides recruitment and career services technology, connecting employers with job-seeking students and alumni from schools around the world.Â Use Domo'sÂ GradLeadersÂ connector to retrieve lists of companies and recruiters. GradLeaders does not have online API documentation, but you can visit their website atÂ [https://www.gradleaders.com/](https://www.gradleaders.com/ "https://www.gradleaders.com/").  


You connect to your GradLeaders account in the Data Center. This topic discusses the fields and menus that are specific to the GradLeaders connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed inÂ [Â Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


Prerequisites
-------------


To connect to your GradLeaders account and create a DataSet, you must have a GradLeaders API key. Contact your support representative for more information.


Connecting to Your GradLeaders Account
--------------------------------------


This section enumerates the options in the **Credentials** and **Details** panes in the GradLeaders Connector page.Â The components of the other panes in this page, **Scheduling**Â and **Name & Describe Your DataSet**, are universal across most connector types and are discussed in greater length inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


### Credentials Pane


This pane contains fields for entering credentials to connect to your GradLeaders account. The following table describes what is needed for each field: Â 




| Field | Description |
| --- | --- |
| API Key | Enter your GradLeaders API key. |


Once you have entered valid GradLeaders credentials, you can use the same account any time you go to create a new GradLeaders DataSet. You can manage connector accounts in the **Accounts** tab in the Data Center. For more information about this tab, see [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


### Details Pane


This pane contains a primaryÂ **Reports**Â menu, along with various other menus which may or may not appear depending on the report type you select.




| Menu | Description |
| --- | --- |
| Report | Select the GradLeaders report you want to run.Â The following reports are available:

|  |  |
| --- | --- |
| Get Modified Companies | Retrieves a list of modified companies. |
| Get New Companies | Retrieves a list of newly added companies. |
| Get Modified Recruiters | Retrieves a list of modified recruiters. |
| Get New Recruiters | Retrieves a list of newly added recruiters. |

 |
| Custom Fields | Select all custom fields you want to appear in your report. |
| Include New | Select whether you want newly added records to appear in your report. |
| Date TypeÂ  | Select whether you want to pull data for a specific date or a date range.Â  |
| DateÂ  | Select whether the report data is for a specific date or for a relative number of days back from today.Â  |
| Date Picker | Select the date for the report.Â  |
| Date Offset | Enter the number of past days that should appear in the report.Â Â  |
| Date From | Specify whether theÂ first date in your date range is a specific or relative date.Â You select the last date in your range in **Date To**.Â  |
| Date To | Specify whether the second date in your date range is a specific or relative date. You select the first date in your range inÂ **Date From**.Â Â  |
| Date From Picker | SelectÂ the first date in your date range.Â  |
| Date To Picker | Select the second date in your date range.Â  |
| Date From Offset | Enter the number of the farthest day back that should be represented in the report. Combine withÂ **Date To Offset**Â to create a range of represented days.
For example, if you enteredÂ 10Â for **Date From Offset**Â andÂ 5Â forÂ **Date To Offset**, the report would contain data forÂ 10 days ago up untilÂ 5 days ago. |
| Date To Offset | Enter the number of the most recent day back that should be represented in the report. Combine withÂ **Date From Offset**Â to create a range of represented days.
For example, if you enteredÂ 10Â for **Date From Offset**Â andÂ 5Â forÂ **Date To Offset**, the report would contain data forÂ 10 days ago up untilÂ 5 days ago. |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, seeÂ [Â a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


Â