---
title : Basecamp 3 Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:41:00
url : https://domo-support.domo.com/s/article/360042930334
linked_kbs :  ['https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360042930334', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003430
views : 3,950
created_date : 2022-10-24 21:13:00
last updated : 2022-10-24 22:41:00
---



Intro
-----


Basecamp 3 is a web-based project management tool developed by Basecamp and launched in 2004. To learn more about the Basecamp 3 API, visit their page ([https://github.com/basecamp/bc3-api](https://github.com/basecamp/bc3-api "https://github.com/basecamp/bc3-api")).


You connect to your Basecamp 3 account in the Data Center. This topic discusses the fields and menus that are specific to the Basecamp 3 connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).


Prerequisites
-------------


To connect to your Basecamp 3 account and create a DataSet, you must have the following:



* The username or email address you use to log into Basecamp 3
* The password you use to log into Basecamp 3


Alternatively, if you used a Google account to set up your Basecamp 3 account, use the credentials associated with that Google account.


Connecting to Your Basecamp 3 Account
-------------------------------------


This section enumerates the options in the **Credentials** and **Details** panes in the Basecamp 3 Connector page.Â The components of the other panes in this page, **Scheduling**Â and **Name & Describe Your DataSet**, are universal across most connector types and are discussed in greater length inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md "Adding a DataSet Using a Data Connector").


### 
Credentials Pane


The DomoÂ Basecamp 3 connector uses OAuth to connect, so there is no need to enter credentials within Domo. Click **Connect** (or selectÂ **Add Account** ifÂ you haveÂ existingÂ Basecamp 3 accounts in Domo)Â to open theÂ Basecamp 3 OAuth screen where you can enter your Basecamp 3 username/email addressÂ and password. Once you have entered validÂ Basecamp 3 credentials and authorized Domo to connect to Basecamp 3, you can use the same account any time you go to create a newÂ Basecamp 3 DataSet. You can manage connector accounts in theÂ **Accounts**Â tab in theÂ Data Center. For more information about this tab, seeÂ [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


**Note:Â**If you are already logged into Basecamp 3 when you connect in Domo, you are authenticated automatically when you click **Add account**. If you want to connect to an account that is different from the one you are logged into, you must first log out of Basecamp 3.
### Details Pane


This pane contains a primaryÂ **Reports**Â menu, along with various other menus which may or may not appear depending on the report type you select.




| Menu | Description |
| --- | --- |
| Report | Select the Basecamp 3 report you want to run.Â The following reports are available:

|  |  |
| --- | --- |
| Basecamps | Returns aÂ paginated listÂ of active Basecamps visible to the current user, sorted by creation date. |
| Basecamp by Basecamp ID | Returns the Basecamp with the provided ID. |
| Campfire by Basecamp ID | Returns the Campfire with the provided Basecamp ID. |
| Campfires | Returns aÂ paginated listÂ of active Campfires visible to the current user. |
| Client Approvals | Returns a paginated list of client approvals. |
| Client Correspondence | Returns a paginated list of client correspondences in Basecamp. |
| Events | Returns a paginated list of events for the selected Recording type. |
| Forwards | Returns a paginated list of Forwards for the provided Basecamp ID. |
| People | Returns a list of all people visible to the authenticated user. |
| People by Basecamp ID | Returns a list of people for the provided Basecamp ID. |
| Pingable Persons | Returns all people in the account who can be pinged. |
| Recordings | Returns a paginated list of Recordings for the provided Recording type. |
| Templates | Returns a list of templates for the provided Basecamp ID and status. |

 |
| Status | Select the status you want to retrieve information for. |
| Basecamp ID | Select the Basecamp ID you want to retrieve information for. |
| Type | Select the Recording type you want to retrieve information for. |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, seeÂ [AddingÂ a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).