---
title: Analyzer Overview
url: https://domo-support.domo.com/s/article/360043428673
linked_kbs:  ['[https://domo-support.domo.com/s/knowledge-base/](https://domo-support.domo.com/s/knowledge-base/)', '[https://domo-support.domo.com/s/](https://domo-support.domo.com/s/)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZamoGAC](https://domo-support.domo.com/s/topic/0TO5w000000ZamoGAC)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZaoNGAS](https://domo-support.domo.com/s/topic/0TO5w000000ZaoNGAS)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZaoUGAS](https://domo-support.domo.com/s/topic/0TO5w000000ZaoUGAS)', '[https://domo-support.domo.com/s/article/360042924034](https://domo-support.domo.com/s/article/360042924034)', '[https://domo-support.domo.com/s/article/360042924174](https://domo-support.domo.com/s/article/360042924174)', '[https://domo-support.domo.com/s/article/360043428713](https://domo-support.domo.com/s/article/360043428713)', '[https://domo-support.domo.com/s/article/360042924194](https://domo-support.domo.com/s/article/360042924194)', '[https://domo-support.domo.com/s/article/360042924134](https://domo-support.domo.com/s/article/360042924134)', '[https://domo-support.domo.com/s/article/360043428773](https://domo-support.domo.com/s/article/360043428773)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZaoeGAC](https://domo-support.domo.com/s/topic/0TO5w000000ZaoeGAC)', '[https://domo-support.domo.com/s/article/360042924074](https://domo-support.domo.com/s/article/360042924074)', '[https://domo-support.domo.com/s/article/360043428733](https://domo-support.domo.com/s/article/360043428733)', '[https://domo-support.domo.com/s/article/360043428753](https://domo-support.domo.com/s/article/360043428753)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZaodGAC](https://domo-support.domo.com/s/topic/0TO5w000000ZaodGAC)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZanAGAS](https://domo-support.domo.com/s/topic/0TO5w000000ZanAGAS)', '[https://domo-support.domo.com/s/article/360043428813](https://domo-support.domo.com/s/article/360043428813)', '[https://domo-support.domo.com/s/article/360043428833](https://domo-support.domo.com/s/article/360043428833)', '[https://domo-support.domo.com/s/article/360043428853](https://domo-support.domo.com/s/article/360043428853)', '[https://domo-support.domo.com/s/article/360042923934](https://domo-support.domo.com/s/article/360042923934)', '[https://domo-support.domo.com/s/article/360043428673](https://domo-support.domo.com/s/article/360043428673)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZaoUGAS/analyzer](https://domo-support.domo.com/s/topic/0TO5w000000ZaoUGAS/analyzer)', '[https://domo-support.domo.com/s/article/360043429933](https://domo-support.domo.com/s/article/360043429933)', '[https://domo-support.domo.com/s/article/360043429953](https://domo-support.domo.com/s/article/360043429953)', '[https://domo-support.domo.com/s/article/360042925494](https://domo-support.domo.com/s/article/360042925494)', '[https://domo-support.domo.com/s/article/360043429913](https://domo-support.domo.com/s/article/360043429913)', '[https://domo-support.domo.com/s/article/4408174643607](https://domo-support.domo.com/s/article/4408174643607)', '[https://domo-support.domo.com/s/login/](https://domo-support.domo.com/s/login/)']
article_id: 000004645
views: 2,550
created_date: 2022-10-24 22:18:00
last updated: 2022-10-24 22:40:00
---



Intro
-----


In Analyzer, you build the chart or table for your Visualization card. You can also specify visual characteristics for the chart such as the chart type, filters, sorting, summary number, date grain, and advanced chart properties. You can also use Beast Mode to create calculations for use in transforming columns. 


For information about the user interface components of the Analyzer, see [Analyzer Layout](/s/article/360042924034 "Card Builder Layout").


Building your chart
-------------------


**To build and specify visual characteristics for a chart or table,**


1. In Analyzer, specify the characteristics you want.  
Use the following table to locate the desired topic.



| Topic | Link |
| --- | --- |
| Name | [Editing the Name or Description of a Visualization Card](/s/article/360042924174 "Editing the Name or Description of a KPI Card") |
| Description | [Editing the Name or Description of a Visualization Card](/s/article/360042924174 "Editing the Name or Description of a KPI Card") |
| DataSet columns | [Applying DataSet Columns to Your Chart](/s/article/360043428713 "Applying DataSet Columns to Your Chart") |
| Table labels | [Editing the Column Header Labels for Your Chart Table View](/s/article/360042924194 "Editing the Column Header Labels for Your Chart Table View") |
| Value formatting | [Formatting Values in Your Chart](/s/article/360042924134 "Formatting Values in Your Chart") |
| Goal markers | [Adding a Goal Line to Your Chart](/s/article/360043428773 "Adding a Goal Line to Your Chart") |
| Chart type | [Available Chart Types](/s/topic/0TO5w000000ZaoeGAC "Available Chart Types") |
| Filters | [Adding Filters to Your Chart](/s/article/360042924074 "Adding Filters to Your Chart") |
| Sort criteria | [Sorting the Data in Your Chart](/s/article/360043428733 "Sorting the Data in Your Chart") |
| Summary number | [Configuring Your Chart Summary Number](/s/article/360043428753 "Configuring Your Chart Summary Number") |
| Advanced chart properties | [Chart Properties](/s/topic/0TO5w000000ZaodGAC "Chart Properties") |
| Transforms and calculations | [Beast Mode](/s/topic/0TO5w000000ZanAGAS "Transforming Data Using Beast Mode") |
| Conditional colors on DataSet columns | [Setting Color Rules for a Chart](/s/article/360043428813 "Setting Color Rules for a Chart")  |
| Chart data table | [Understanding the Data Table in Analyzer](/s/article/360043428833 "Understanding the Data Table in Analyzer")  |
| DataSet lineage | [Viewing the Lineage of a DataSet in Analyzer](/s/article/360043428853 "Viewing the Lineage of a DataSet in Analyzer") |
2. Click **Save Card**.
3. (Optional) In the dialog, enter a comment about your changes.  
The comment appears with the revision in the **History** tab in the Details view for a card. For more information about the **History** tab, see History View in [Card Details View Layout](/s/article/360042923934).
4. Click **Save & Finish**.


**Video - Interface Overview - Analyzer**



 


**Video - Creating Cards in Analyzer**



 

