---
title: Sizmek SAS Connector
url: https://domo-support.domo.com/s/article/360043431913
linked_kbs:  ['[https://domo-support.domo.com/s/knowledge-base/](https://domo-support.domo.com/s/knowledge-base/)', '[https://domo-support.domo.com/s/](https://domo-support.domo.com/s/)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZammGAC](https://domo-support.domo.com/s/topic/0TO5w000000ZammGAC)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZanLGAS](https://domo-support.domo.com/s/topic/0TO5w000000ZanLGAS)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZaoQGAS](https://domo-support.domo.com/s/topic/0TO5w000000ZaoQGAS)', '[https://domo-support.domo.com/s/article/360042926274](https://domo-support.domo.com/s/article/360042926274)', '[https://domo-support.domo.com/s/article/360042926054](https://domo-support.domo.com/s/article/360042926054)', '[https://domo-support.domo.com/s/article/360043431913](https://domo-support.domo.com/s/article/360043431913)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZaoQGAS/api-connectors](https://domo-support.domo.com/s/topic/0TO5w000000ZaoQGAS/api-connectors)', '[https://domo-support.domo.com/s/article/360043429933](https://domo-support.domo.com/s/article/360043429933)', '[https://domo-support.domo.com/s/article/360043429953](https://domo-support.domo.com/s/article/360043429953)', '[https://domo-support.domo.com/s/article/360042925494](https://domo-support.domo.com/s/article/360042925494)', '[https://domo-support.domo.com/s/article/4408174643607](https://domo-support.domo.com/s/article/4408174643607)', '[https://domo-support.domo.com/s/article/360043429913](https://domo-support.domo.com/s/article/360043429913)', '[https://domo-support.domo.com/s/login/](https://domo-support.domo.com/s/login/)']
article_id: 000003715
views: 1,091
created_date: 2022-10-24 21:14:00
last updated: 2022-10-24 22:42:00
---



Intro
-----


Sizmek is an AdTech marketing platform. Sizmek works with brand marketers, agencies, publishers and trading desks, and provides tools to build, serve, analyze and target ads to global audiences across a variety of channels, including mobile and video. Combine your Sizmek data with data from sales, finance, and other departments across your organization so you can maximize your ROI. Domo's Sizmek SAS connector brings in data from the Sizmek MDX platform. Use Domo's Sizmek SAS connector to receive data from the Sizmek SAS API like ads, accounts, advertisers, brands, campaigns and more.


You connect to your Sizmek SAS account in the Data Center. This topic discusses the fields and menus that are specific to the Sizmek SAS connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed in [Adding a DataSet Using a Data Connector](/s/article/360042926274).




 


**Important:** This connector pulls data from Sizmek's MDX platform, *not* their NXT platform.



Prerequisites
-------------


To connect to your Sizmek SAS account and create a DataSet, you must have the following:


* Your Sizmek account username
* Your Sizmek account password
* A Sizmek API key (if you are using [https://adapi.sizmek.com/sas](https://adapi.sizmek.com/sas "https://adapi.sizmek.com/sas") for your **API URL**)


Connecting to Your Sizmek SAS Account
-------------------------------------


This section enumerates the options in the **Credentials** and **Details** panes in the Sizmek SAS Connector page. The components of the other panes in this page, **Scheduling** and **Name & Describe Your DataSet**, are universal across most connector types and are discussed in greater length in [Adding a DataSet Using a Data Connector](/s/article/360042926274 "Adding a DataSet Using a Data Connector").


### Credentials Pane


This pane contains fields for entering credentials to connect to your Sizmek SAS account. The following table describes what is needed for each field:  




| Field | Description |
| --- | --- |
| API URL | Select the API URL for your API user. If you are uncertain about which API URL to select, contact your Sizmek Administrator or Client Services Manager. |
| Username | Enter your Sizmek SAS Username. |
| Password | Enter your Sizmek SAS password. |
| API Key | Enter your Sizmek SAS API Key if you are using [https://adapi.sizmek.com/sas](https://adapi.sizmek.com/sas "https://adapi.sizmek.com/sas") for your API URL.   |


Once you have entered valid Sizmek SAS credentials, you can use the same account any time you go to create a new Sizmek SAS DataSet. You can manage connector accounts in the **Accounts** tab in the Data Center. For more information about this tab, see [Managing User Accounts for Connectors](/s/article/360042926054 "Managing User Accounts for Connectors").


### Details Pane


This pane contains a primary **Reports** menu, along with various other menus which may or may not appear depending on the report type you select.




| Menu | Description |
| --- | --- |
| Report | Select the Sizmek SAS report you want to run. The following reports are available:

|  |  |
| --- | --- |
| Ads | Returns information about Sizmek ads. |
| Accounts | Returns information about Sizmek accounts. |
| Advertisers | Returns information about Sizmek advertisers. |
| Brands | Returns information about Sizmek brands. |
| Campaigns | Returns information about Sizmek campaigns. |
| Delivery Groups | Returns information about Sizmek delivery groups. |
| Placements | Returns information about Sizmek ad placements. |
| Sites | Returns information about Sizmek sites. |
| Target Audience | Returns information about Sizmek target audiences. |

 |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, see [Adding a DataSet Using a Data Connector](/s/article/360042926274).

