---
title: Starting, Stopping, and Restarting the Workbench 4 Service
url: https://domo-support.domo.com/s/article/360046773094
linked_kbs:  ['[https://domo-support.domo.com/s/knowledge-base/](https://domo-support.domo.com/s/knowledge-base/)', '[https://domo-support.domo.com/s/](https://domo-support.domo.com/s/)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZammGAC](https://domo-support.domo.com/s/topic/0TO5w000000ZammGAC)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZaoPGAS](https://domo-support.domo.com/s/topic/0TO5w000000ZaoPGAS)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZapSGAS](https://domo-support.domo.com/s/topic/0TO5w000000ZapSGAS)', '[https://domo-support.domo.com/s/article/360043437153](https://domo-support.domo.com/s/article/360043437153)', '[https://domo-support.domo.com/s/article/360046772834](https://domo-support.domo.com/s/article/360046772834)', '[https://domo-support.domo.com/s/article/360047403773](https://domo-support.domo.com/s/article/360047403773)', '[https://domo-support.domo.com/s/article/360046773094](https://domo-support.domo.com/s/article/360046773094)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZapSGAS/workbench-4](https://domo-support.domo.com/s/topic/0TO5w000000ZapSGAS/workbench-4)', '[https://domo-support.domo.com/s/article/360043429933](https://domo-support.domo.com/s/article/360043429933)', '[https://domo-support.domo.com/s/article/360043429953](https://domo-support.domo.com/s/article/360043429953)', '[https://domo-support.domo.com/s/article/360042925494](https://domo-support.domo.com/s/article/360042925494)', '[https://domo-support.domo.com/s/article/4408174643607](https://domo-support.domo.com/s/article/4408174643607)', '[https://domo-support.domo.com/s/article/360043429913](https://domo-support.domo.com/s/article/360043429913)', '[https://domo-support.domo.com/s/login/](https://domo-support.domo.com/s/login/)']
article_id: 000004790
views: 2,143
created_date: 2022-10-24 22:30:00
last updated: 2022-10-24 22:41:00
---








**Important:** Support for Workbench 4 ended on **April 15, 2021**. Workbench may continue to run on installed machines, but it will no longer receive feature enhancements and security updates. When issues are encountered in Workbench 4, the recommended course of action from the Domo Support team will be to upgrade to the latest version of Workbench 5. To see this article for Workbench 5, click [**here**](/s/article/360043437153).



The Workbench service starts up automatically after the machine starts Windows.


You can stop, start, or restart the Workbench service manually using the Windows system taskbar.




 


**Tip:**If a Workbench icon does *not* appear in the Windows system taskbar, click **Start > Domo > Workbench Monitor**.



For information about running the Workbench application, see [Running Workbench 4](/s/article/360046772834 "Running Workbench 4").


**To manually start, stop, or restart the Workbench service,**


1. In the Windows system taskbar, right-click the Workbench service icon.  
A menu appears.
2. Select **Service**, then click the option you want (**Start**, **Stop**, or **Restart**).


For information about the controls and field settings in Workbench, see [Understanding the Workbench 4 User Interface](/s/article/360047403773 "Understanding the Workbench 4 User Interface").

