---
title: Workbench 4 Overview
url: https://domo-support.domo.com/s/article/360047400113
linked_kbs:  ['[https://domo-support.domo.com/s/knowledge-base/](https://domo-support.domo.com/s/knowledge-base/)', '[https://domo-support.domo.com/s/](https://domo-support.domo.com/s/)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZammGAC](https://domo-support.domo.com/s/topic/0TO5w000000ZammGAC)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZaoPGAS](https://domo-support.domo.com/s/topic/0TO5w000000ZaoPGAS)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZapSGAS](https://domo-support.domo.com/s/topic/0TO5w000000ZapSGAS)', '[https://domo-support.domo.com/s/article/360042932554](https://domo-support.domo.com/s/article/360042932554)', '[https://domo-support.domo.com/s/article/360047400113](https://domo-support.domo.com/s/article/360047400113)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZapSGAS/workbench-4](https://domo-support.domo.com/s/topic/0TO5w000000ZapSGAS/workbench-4)', '[https://domo-support.domo.com/s/article/360043429933](https://domo-support.domo.com/s/article/360043429933)', '[https://domo-support.domo.com/s/article/360043429953](https://domo-support.domo.com/s/article/360043429953)', '[https://domo-support.domo.com/s/article/360042925494](https://domo-support.domo.com/s/article/360042925494)', '[https://domo-support.domo.com/s/article/4408174643607](https://domo-support.domo.com/s/article/4408174643607)', '[https://domo-support.domo.com/s/article/360043429913](https://domo-support.domo.com/s/article/360043429913)', '[https://domo-support.domo.com/s/login/](https://domo-support.domo.com/s/login/)']
article_id: 000004800
views: 2,137
created_date: 2022-10-24 22:30:00
last updated: 2022-10-24 22:41:00
---








**Important:** Support for Workbench 4 ended on **April 15, 2021**. Workbench may continue to run on installed machines, but it will no longer receive feature enhancements and security updates. When issues are encountered in Workbench 4, the recommended course of action from the Domo Support team will be to upgrade to the latest version of Workbench 5. To see this article for Workbench 5, click [**here**](/s/article/360042932554).



What can Workbench 4 do for you?
--------------------------------


* Securely upload DataSets to Domo using wizards and other helpful interface components
* Upload data manually or on a schedule
* Create groups of DataSet jobs that run on the same schedule
* Import and export job files
* Preview and validate jobs before you run them
* Add, create, save, and delete accounts
* Add, create, save, delete, open, preview, and cancel jobs
* Revert back to a previous version of a job you saved
* Add/delete transforms to/from jobs, which includes the following:


	+ Add new columns
	+ Change date format
	+ Encrypt sensitive data in specific columns
	+ Filter columns in the DataSet
	+ Set the time zone for the DataSet job
	+ Replace column values in the DataSet
	+ Combine the DataSet with another DataSet


* Export/import Excel, CSV, QuickBooks, JSON, OLAP, ODBC, and XML file types
* View logs
* Send logs as a zip file
* Run logs from the command line
* Add and manage plugins for using Workbench
* Set up notifications for DataSet jobs that can email you if DataSets are uploaded successfully or if it experiences an error
* Enable multi-part uploading for all large DataSet Jobs


To read a white paper about making your Workbench data more secure in Domo by means of encryption, click here: [Whitepaper\_Domo+Data+Security+and+Encryption+Draft.pdf](https://domosoftware.sharepoint.com/:b:/s/CS-Edu-PublicFiles/Ec5lAMNCHyxIrujDa7ZAXFIBo5jv7_53HWgO7lQJdSsbbA?e=Xb9QgS "Whitepaper_Domo+Data+Security+and+Encryption+Draft.pdf")

