---
title : Disabling Username Autocomplete in the Login Screen
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:42:00
url : https://domo-support.domo.com/s/article/360042934514
linked_kbs :  ['https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360043438973', 'https://domo-support.domo.com/s/article/360042922874', 'https://domo-support.domo.com/s/article/360042934514', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003019
views : 3,998
created_date : 2022-10-24 21:00:00
last updated : 2022-10-24 22:42:00
---



**Note:** This feature is available *on demand.*  
Â 


To request that this feature be enabled,



* contact Technical Support.Â For information on how to contact Support, please see [Getting Help](..\getting_help\index.md).
* reach out to your Domo Customer Success Manager or Technical Consultant.


Depending on the feature, you may be required to complete training before you can use the feature.
You can disable username autocomplete in the Domo login screen by hiding the "Remember me" checkbox. When this box is disabled, users must always log in manually. You do this in **More >** **Admin****Â > Authentication > Authentication**.Â You cannot access this feature unless you haveÂ an "Admin" default security role or a custom role in which the "Manage All Company Settings" privilege has been enabled. For more information about default security roles, seeÂ [Managing Roles](..\managing_custom_roles\index.html "Security Role Reference").


**To disable username autocomplete,**


1. ClickÂ **More**Â **> Admin**Â **>Â****Authentication**.Â
2. In the **AuthenticationÂ**sub-tab, check **Disable username autocomplete**.Â