---
title: Outbrain Dashboard App
url: https://domo-support.domo.com/s/article/360043438513
linked_kbs:  ['[https://domo-support.domo.com/s/knowledge-base/](https://domo-support.domo.com/s/knowledge-base/)', '[https://domo-support.domo.com/s/](https://domo-support.domo.com/s/)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZampGAC](https://domo-support.domo.com/s/topic/0TO5w000000ZampGAC)', '[https://domo-support.domo.com/s/topic/0TO5w000000Zan9GAC](https://domo-support.domo.com/s/topic/0TO5w000000Zan9GAC)', '[https://domo-support.domo.com/s/article/360043438513](https://domo-support.domo.com/s/article/360043438513)', '[https://domo-support.domo.com/s/topic/0TO5w000000Zan9GAC/available-apps](https://domo-support.domo.com/s/topic/0TO5w000000Zan9GAC/available-apps)', '[https://domo-support.domo.com/s/article/360043429933](https://domo-support.domo.com/s/article/360043429933)', '[https://domo-support.domo.com/s/article/360043429953](https://domo-support.domo.com/s/article/360043429953)', '[https://domo-support.domo.com/s/article/360042925494](https://domo-support.domo.com/s/article/360042925494)', '[https://domo-support.domo.com/s/article/360043429913](https://domo-support.domo.com/s/article/360043429913)', '[https://domo-support.domo.com/s/article/4408174643607](https://domo-support.domo.com/s/article/4408174643607)', '[https://domo-support.domo.com/s/login/](https://domo-support.domo.com/s/login/)']
article_id: 000004187
views: 1,083
created_date: 2022-10-24 21:26:00
last updated: 2022-10-24 22:42:00
---



Intro
-----


Outbrain is a content discovery platform designed to help internet publishers increase web traffic by presenting them with relevant links.


Usage
-----


Business questions that can be answered:


* Are you leveraging your budget to capture the highest possible ROI?
* Are your ads driving sales or just generating costs?
* How are your customers reacting to your ad campaigns?


Metrics included in the App:


* Ad Spend Last 7 Days
* Bottom Campaigns
* Budget Spent
* Campaign Clicks
* Campaign Conversion Rates
* Campaign Conversions
* Conversion Rate
* CPA
* CPC
* CTR Trend
* Projected Spend
* Top Campaigns
* Top Campaigns by Clicks
* Top Campaigns by CPC
* Top Spending Campaigns


Authentication
--------------


Username and password are required.


Dashboard Reports
-----------------


For report descriptions, see Outbrain Connector.




| Report | Scheduling (Change update settings) | Parameter(s) | Selection |
| --- | --- | --- | --- |
| Budget Collection via Marketer |   | Marketer | Select the Marketer you want to report on.
  |
| Campaigns Collection via Budget |   | None |   |
| Campaign Collections via Marketer |   | Marketer | Select the Marketer you want to report on.
  |
| Marketers |   | None |   |
| Performance per Campaign per Day |   | Marketer
Duration
Start Date
Days Back to Start From
End Date
Days Back to End At | Select the Marketer you want to report on, the duration (single date or date range), and start date/end date (including any number of days to start back from/end at. |
| Performance per Campaign per Month |   | Marketer
Duration
Start Date
Days Back to Start From
End Date
Days Back to End At | Select the Marketer you want to report on, the duration (single date or date range), and start date/end date (including any number of days to start back from/end at. |
| Performance per Campaign per PromotedLink |   | Duration
Start Date
Days Back to Start From
End Date
Days Back to End At | Select the duration (single date or date range), and start date/end date (including any number of days to start back from/end at. |
| Performance for a Marketer per Campaign |   | Marketer
Duration
Start Date
Days Back to Start From
End Date
Days Back to End At | Select the Marketer you want to report on, the duration (single date or date range), and start date/end date (including any number of days to start back from/end at. |
| Performance for a Marketer per Day |   | Marketer
Duration
Start Date
Days Back to Start From
End Date
Days Back to End At | Select the Marketer you want to report on, the duration (single date or date range), and start date/end date (including any number of days to start back from/end at. |
| Performance for a Marketer per Month |   | Marketer
Duration
Start Date
Days Back to Start From
End Date
Days Back to End At | Select the Marketer you want to report on, the duration (single date or date range), and start date/end date (including any number of days to start back from/end at. |
| Performance for a Marketer per PromotedLink |   | Marketer
Duration
Start Date
Days Back to Start From
End Date
Days Back to End At | Select the Marketer you want to report on, the duration (single date or date range), and start date/end date (including any number of days to start back from/end at. |
| Performance for a PromotedLink per Day |   | Duration
Start Date
Days Back to Start From
End Date
Days Back to End At | Select the duration (single date or date range), and start date/end date (including any number of days to start back from/end at. |
| Performance for a PromotedLink per Month |   | Duration
Start Date
Days Back to Start From
End Date
Days Back to End At | Select the duration (single date or date range), and start date/end date (including any number of days to start back from/end at. |


Dashboard Data
--------------


The Outbrain Dashboard will provide the following data collections and cards:




| Collection
  | Card | Card Description | Data Name |
| --- | --- | --- | --- |
| Executive Pulse: 5 metrics you should check every day. | Ad Spend Last 7 Days | AD SPEND LAST 7 DAYSCompares the cost per acquisition/conversion (CPA) and cost per click (CPC) against the total spend over the specified period. Consider decreasing your budget allocation in order to limit expenses or increasing your budget to fuel future growth.Cost per Conversion (CPA) = Ad Spend / ConversionsCost per Click (CPC) = Ad Spend / Clicks | Campaign by Day |
| Executive Pulse: 5 metrics you should check every day. | Bottom Campaigns | BOTTOM CAMPAIGNSRanks your poorest performing campaigns by the number of conversions and displays the amount of ad spend you have put into each campaign. Justify expensive campaigns that aren't resulting in conversions. | Campaign by Day |
| Executive Pulse: 5 metrics you should check every day. | Campaign Clicks | CAMPAIGN CLICKSMeasures the number of clicks earned by each of your campaigns over the specified period. Dedicate resources to campaigns that are showing signs of growth. | Campaign by Day |
| Executive Pulse: 5 metrics you should check every day. | Top Campaigns | TOP CAMPAIGNSRanks recently run campaigns by the number of clicks they earned over the specified period. Identify which of your campaigns are driving the most clicks to your website and allocate resources accordingly. | Campaign by Day |
| Executive Pulse: 5 metrics you should check every day. | Top Spending Campaigns | TOP SPENDING CAMPAIGNSRanks your top 10 campaigns by their ad spend and plots their clicks and conversions over the specified period. Rationalize spending by determining if campaigns are generating the desired amount of clicks and conversions. | Campaign by Day |


 




| Collection
  | Card | Card Description | Data Name |
| --- | --- | --- | --- |
| Costs: Are you leveraging your budget to capture the highest possible ROI? | Budget Spent | BUDGET SPENTCompares the current amount of spend this period against the total budget for the period. Change your bid levels, ad copy and keyword choices for low-margin campaigns that are regularly maxing out your budget. | Budget
  |
| Costs: Are you leveraging your budget to capture the highest possible ROI? | CPA | COST PER ACQUISITIONCompares the cost per acquisition/conversion (CPA) against the number of conversions over the specified period. Campaigns that cost more per conversion than they generate in revenues may need to be changed or discontinued.Cost per Acquisition/Conversion (CPA) = Ad Spend / Conversions | Campaign by Day |
| Costs: Are you leveraging your budget to capture the highest possible ROI? | CPC | COST PER CLICKCompares the average cost per click (CPC) against the number of clicks over the specified period. Improving your quality score can lead to a lower CPC by decreasing the bid amount required to earn a click.Cost per Click (CPC) = Spend / Clicks | Campaign by Day |
| Costs: Are you leveraging your budget to capture the highest possible ROI? | Projected Spend | PROJECTED SPENDShows the amount of ad spend over time and forecasts spend for this period. Compare forecasts to your goals or budgets and adjust them accordingly. | Campaign by Day |


 




| Collection
  | Card | Card Description | Data Name |
| --- | --- | --- | --- |
| Conversion: Are your ads driving sales or just generating costs? | Campaign Conversion Rates | CAMPAIGN CONVERSION RATESRanks each campaign by the number of conversions it acquired and shows its conversion rate as a relative proportion of converted and unconverted clicks. Replicate the successful elements of your highest performing campaigns to increase conversions.Conversion Rate = Conversions / Clicks | Budget
  |
| Conversion: Are your ads driving sales or just generating costs? | Campaign Conversions | CAMPAIGN CONVERSIONSHighlights the campaigns that have acquired the most conversions over the specified period. Replicate the successful elements of your highest performing campaigns to increase conversions. | Campaign by Day |
| Conversion: Are your ads driving sales or just generating costs? | Conversion Rate | CONVERSION RATECompares the conversion rate to the total number of conversions over the specified period. Maximize your conversion rate by testing ad content and targeting keywords, then replicating elements of successful campaigns.Conversion Rate = Conversions / Clicks | Campaign by Day |


 




| Collection
  | Card | Card Description | Data Name |
| --- | --- | --- | --- |
| Ad Engagement: How are your customers reacting to your ad campaigns? | CTR Trend | CLICK-THROUGH RATE TRENDCompares the click-through rate (CTR) with the amount of clicks over the specified period. Increase your click-through rate by A/B testing content and modifying ad placements to better reach your target customers.Click-Through Rate (CTR) = Clicks / Impressions | Campaign by Day |
| Ad Engagement: How are your customers reacting to your ad campaigns? | Top Campaigns by Clicks | TOP CAMPAIGNS BY CLICKSRanks the top 20 campaigns by the number of clicks they acquired over the specified period. Identify which of your campaigns are driving the most clicks to your website. | Campaign by Day |
| Ad Engagement: How are your customers reacting to your ad campaigns? | Top Campaigns by CPC | TOP CAMPAIGNS BY COST PER CLICKRanks your campaigns by cost per click. Identify which campaigns are driving high amounts of clicks to your website. | Campaign by Day |


 

