---
title: Legal Notices
url: https://domo-support.domo.com/s/article/360043427413
linked_kbs:  ['[https://domo-support.domo.com/s/knowledge-base/](https://domo-support.domo.com/s/knowledge-base/)', '[https://domo-support.domo.com/s/](https://domo-support.domo.com/s/)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZamsGAC](https://domo-support.domo.com/s/topic/0TO5w000000ZamsGAC)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZanlGAC](https://domo-support.domo.com/s/topic/0TO5w000000ZanlGAC)', '[https://domo-support.domo.com/s/article/360043427413](https://domo-support.domo.com/s/article/360043427413)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZanlGAC/getting-started](https://domo-support.domo.com/s/topic/0TO5w000000ZanlGAC/getting-started)', '[https://domo-support.domo.com/s/article/360043429933](https://domo-support.domo.com/s/article/360043429933)', '[https://domo-support.domo.com/s/article/360043429953](https://domo-support.domo.com/s/article/360043429953)', '[https://domo-support.domo.com/s/article/360042925494](https://domo-support.domo.com/s/article/360042925494)', '[https://domo-support.domo.com/s/article/360043429913](https://domo-support.domo.com/s/article/360043429913)', '[https://domo-support.domo.com/s/article/4408174643607](https://domo-support.domo.com/s/article/4408174643607)', '[https://domo-support.domo.com/s/login/](https://domo-support.domo.com/s/login/)']
article_id: 000004345
views: 2,137
created_date: 2022-10-24 21:41:00
last updated: 2022-10-24 22:39:00
---



Copyright © 2012-2016 Domo, Inc. All rights reserved.


Patents
-------


﻿Domo products are protected by United States Patents #6,972,763 and #7,769,895. Additional patents pending.



﻿Domo Trademarks
-----------------


Corda and CenterView are registered trademarks and Domo, Domo Data On-ramp, Domo Apps, Domo Cards, Domo Profile, Domo Alert, Domo Workbench, the Domo logo, Domo Advanced Builder, Domo Advanced Server, Domo Mobile, Corda Builder, Corda Server, Datafunnel, OptiMap, and PopChart are trademarks of Domo, Inc., in the United States and other countries.


Third-Party Trademarks
----------------------


Adobe, Acrobat, and Acrobat Reader are registered trademarks of Adobe Systems Incorporated in the United States and other countries.


iPod touch and iTunes are registered trademarks and iPhone, iPad, Mac OS, and Macintosh are trademarks of Apple Inc., registered in the United States and other countries.


Microsoft, Active Directory, Excel, Internet Explorer, PowerPoint, and Windows are registered trademarks of Microsoft Corporation in the United States and other countries. Screenshots reprinted by permission from Microsoft Corporation.


Oracle and Java are registered trademarks of Oracle and/or its affiliates. Other names may be trademarks of their respective owners.


Sun and JavaScript are registered trademarks of Sun Microsystems, Inc., in the United States and other countries.


SVG is a trademark of the World Wide Web Consortium.


*All other third-party brand names and product names referenced in this documentation are trade names, service marks, trademarks, or registered trademarks of their respective owners.*

