---
title : Adaptive Insights Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:42:00
url : https://domo-support.domo.com/s/article/360042930154
linked_kbs :  ['https://domo-support.domo.com/s/article/360043427353', 'https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360042930154', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003438
views : 4,170
created_date : 2022-10-24 21:13:00
last updated : 2022-10-24 22:42:00
---



Intro
-----


Adaptive Insights, formerly Adaptive Planning, provides online software that allows users to replace multiple spreadsheets with an integrated system for consolidating data. To learn more about the Adaptive Insights API, log into Adaptive Insights and go toÂ **Product Documents > Integration Guide**.


You connect to your Adaptive Insights account in the Data Center. This topic discusses the fields and menus that are specific to the Adaptive Insights connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).




|  |  |
| --- | --- |
| **Primary Use Cases** | This connector helps you answer these questions:
* What are my current financial forecasts?
* How have these tracked to actuals?
 |
| **Primary Metrics** | 
* Forecasted financials
* Actual financials (budgets, income, various P&L line items)
 |
| **Primary Company Roles** | 
* FP&A analyst
* Financial analysis
* Director of finance
* CPO
* VP of finance
 |
| **Average Implementation Time** | Could be 40 hours or more, due to the complexity of Adaptive Insights' financial systemÂ  |
| **Ease of Use (on a 1-to-10 scale with 1 being easiest)** | 8 |


Best Practices
--------------


If you need to unpivot data, you can do so usingÂ Magic's "Collapse Columns" action. For more information, seeÂ [ETL Actions: Edit Columns - Collapse Columns](..\old_magic_etl_tiles_edit_columns\index.md).


Prerequisites
-------------


To connect to your Adaptive Insights account and create a DataSet, you must have the following:



* Your Adaptive Insights username and password.
* Your Adaptive Insights instance code. You can find this by logging into Adaptive Insights and navigating to **Admin > System > General Setup**. You can then find the code under **Setup Information**.


Connecting to Your Adaptive Insights Account
--------------------------------------------


This section enumerates the options in the **Credentials** and **Details** panes in the Adaptive Insights Connector page.Â The components of the other panes in this page, **Scheduling**Â and **Name & Describe Your DataSet**, are universal across most connector types and are discussed in greater length inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md "Adding a DataSet Using a Data Connector").


### Credentials Pane


This pane contains fields for entering credentials to connect to your Adaptive Insights account. The following table describes what is needed for each field: Â 




| Field | Description |
| --- | --- |
| Username | Enter your Adaptive Insights username. |
| Password | Enter your Adaptive Insights password. |
| Instance | Enter your Adaptive Insights instance code. To learn how to find your code, see "Prerequisites," above. |


Once you have entered valid Adaptive Insights credentials, you can use the same account any time you go to create a new Adaptive Insights DataSet. You can manage connector accounts in the **Accounts** tab in the Data Center. For more information about this tab, see [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


### Details Pane


This pane contains a primaryÂ **Reports**Â menu, along with various other menus which may or may not appear depending on the report type you select.




| Menu | Description |
| --- | --- |
| Report | Select the Adaptive InsightsÂ report you want to run.Â The following reports are available:

|  |  |
| --- | --- |
| Accounts | Retrieves metadata for the complete list of all accounts in the system. |
| Active Currencies | Retrieves metadata for the complete list of all currencies configured in the system. |
| Attributes | Returns the list of attributes. |
| Export Data | Retrieves a set of data from the requested version in the requested instance. |
| Export Data from Modeled and Cube Sheet | Retrieves data for the accounts, dimensions and levels that correspond to the selected sheet. |
| Customize data export | Retrieves data for the accounts, dimensions and levels specified. |
| Dimensions Structure | Retrieves metadata about custom dimensions in the system preserving their structure. |
| Dimensions with Attributes | Represents a single member value of a custom dimension being returned in the response to an exportDimensions Call with Attributes passed in the request. |
| Instances | Retrieves metadata about the instances a user has access to, if the user has access to multiple instances. |
| Levels | Retrieves metadata about organization levels in the system. |
| Roles | Retrieves metadata about roles in the system. |
| Versions | Retrieves metadata about versions in the system. |

Standard sheets are not available directly through the API. You have two options for retrieving standard sheet data:
* Export data from Custom and Assumption Groups.
* Export data from accounts that can be used to reproduce a standard sheet.

**To reproduce a standard sheet,Â**1. Log into your Adaptive Insights account.
2. Go toÂ **Model Management > Sheets**.
3. Locate the sheet you want to reproduce.Â
4. Click onÂ **Account Groups**.
5. In the connector UI in Domo, select the accounts that are showing in Adaptive Insights.
 |
| Roll Up Values? | Select whether you want to retrieve rolled up values. |
| Date Filtering | Select whether you want to filter by dates. |
| DurationÂ  | Select whether you want to pull data for a specific date or a date range.Â  |
| Report DateÂ  | Select whether the report data is for a specific date or for a relative number of days back from today.Â  |
| Select Specific DateÂ  | Select the date for the report.Â  |
| Days Back | Enter the number of past days that should appear in the report.Â Â  |
| Start Date | Specify whether theÂ first date in your date range is a specific or relative date.Â You select the last date in your range inÂ **End Date**.Â  |
| End Date | Specify whether the second date in your date range is a specific or relative date. You select the first date in your range inÂ **Start Date**.Â Â  |
| Select Specific Start Date | SelectÂ the first date in your date range.Â  |
| Select Specific End Date | Select the second date in your date range.Â  |
| Days Back to Start From | Enter the number of the farthest day back that should be represented in the report. Combine withÂ **Days Back to End At**Â to create a range of represented days.
For example, if you enteredÂ 10Â forÂ **Days Back to Start From**Â andÂ 5Â forÂ **Days Back to End At**, the report would contain data forÂ 10 days ago up untilÂ 5 days ago. |
| Days Back to End At | Enter the number of the most recent day back that should be represented in the report. Combine withÂ **Days Back to Start From**Â to create a range of represented days.
For example, if you enteredÂ 10Â forÂ **Days Back to Start From**Â andÂ 5Â forÂ **Days Back to End At**, the report would contain data forÂ 10 days ago up untilÂ 5 days ago. |
| Data Version | Select the version of the data you want to retrieve data for. |
| Currency | Select whether to retrieve data for US dollars, your local currency, or the currency used by your corporation. |
| Data Sheet | Select the sheet you want to retrieve data for. |
| Accounts | Select all of the accounts you want to retrieve data for. |
| Dimension Name | Select the dimension you want to retrieve data for. |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, seeÂ [AddingÂ a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).


FAQ
---


##### How often can the data be updated?


As often as needed,


##### Are there any API limits I should be aware of?


No.


Troubleshooting for Consulting/Support
--------------------------------------


Confirm that the customer instance is correct.