---
title : Available Period-over-Period Charts
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:39:00
url : https://domo-support.domo.com/s/article/360042924314
linked_kbs :  ['https://domo-support.domo.com/s/article/360042924834', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360043429073', 'https://domo-support.domo.com/s/article/360043428713', 'https://domo-support.domo.com/s/article/360043429493', 'https://domo-support.domo.com/s/article/360042924774', 'https://domo-support.domo.com/s/article/360043429913', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360043429253', 'https://domo-support.domo.com/s/article/360042924314', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360042924554', 'https://domo-support.domo.com/s/article/360042924714']
article_id : 000004736
views : 4,121
created_date : 2022-10-24 22:28:00
last updated : 2022-10-24 22:39:00
---



There are currently seven period-over-period chart types in Domo, all of which have a corresponding standard chart type. All period-over-period charts include only two fields, one for an x-axis column (which will always include time period data) and one for a y-axis column (which will always include value data). For information about applying columns to a chart, see [Applying DataSet Columns to Your Chart](..\applying_dataset_columns_to_your_chart\index.html "Applying DataSet Columns to Your Chart").


The following table lists and describes all of the available period-over-period charts. You can click a thumbnail image to see a full-sized version of that image. For information about building all of the charts in this table, see [Period-over-Period Charts](..\periodoverperiod_charts\index.html "Period-over-Period Charts").




| Period-over-Period Chart Type | Description | Screenshot |
| --- | --- | --- |
| Bar Line | Period being compared is shown as bars; all other periods are shown as lines.  | pop_example3.png |
| Variance Bar Line | Periods are shown as bars and variance values are shown as lines. | pop_example4.png |
| Line Bar | Period being compared is shown as a line; all other periods are shown as bars. | pop_linebar.png |
| Variance Line Bar | Periods are shown as lines and variance values are shown as bars. | pop_variancelinebar.png |
| Trendline | All periods are shown as lines. | pop_example5.png |
| Variance Trendline | All periods and variance values are shown as lines. | pop_example6.png |
| Grouped Bar | All periods are shown as bars. | pop_example7.png |
| Running Total Line | All periods are split into [running total lines](..\running_total_line_chart\index.html "Running Total Line Graph").  | pop_running_total.png |
| Multi-Value Gauge | Shows the value for the selected date range, with the percent change from the selected comparison timeframe (e.g. the quarter-to-date value with the percent change from one quarter ago for comparison). For more information about these gauges, see [Multi-Value Gauge - BETA](..\multivalue_gauge\index.html "Multi-Value Gauge - BETA"). | pop_multivalue_gauge.png |
| Shape Gauge | Shows a different shape depending on your chart properties and the percent of change from the selected comparison timeframe compared to the selected date range. For more information about these gauges, see [Shape Gauge - BETA](..\shape_gauge\index.html "Shape Gauge - BETA"). | pop_shape_gauge.png |
| Flex Table | All periods are shown as individual rows within the table, with their own spark line or spark bar chart, percent of change, etc. For more information about these tables, see [Flex Table](..\flex_table\index.html "Flex Table"). | pop_flex_table.png |
| Filled Gauge | Gauge shows the value for the selected date range, while labels indicate this value along with the value for the selected comparison timeframe. For more information about these gauges, see [Filled Gauge](..\filled_gauge\index.html "Filled Gauge"). | pop_filled_gauge.png |
| Progress Bar | Gauge shows the percent change for the selected comparison timeframe. For more information about these gauges, see [Progress Bar Gauge](..\progress_bar_gauge\index.html "Progress Bar Gauge"). | pop_progress_bar.png |