---
title : PipelineDeals Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:42:00
url : https://domo-support.domo.com/s/article/360042927854
linked_kbs :  ['https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042927854', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003676
views : 2,011
created_date : 2022-10-24 21:14:00
last updated : 2022-10-24 22:42:00
---



Intro
-----


PipelineDeals provides customer relationship management and sales CRM software to organize, track, and manage your deals, leads, and contacts. Use Domo's PipelineDeals connector to retrieve data about activities, tasks and events, companies, deals, documents and people. To learn more about the PipelineDeals API, visit their page ([https://app.pipelinedeals.com/api/docs/](https://app.pipelinedeals.com/api/docs/ "https://app.pipelinedeals.com/api/docs/")).  


You connect to your PipelineDeals account in the Data Center. This topic discusses the fields and menus that are specific to the PipelineDeals connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


Prerequisites
-------------


To connect to your PipelineDeals account and create a DataSet, you must have a PipelineDeals API key. To findÂ your API key, do the following:


1. Log into your CRM account.
2. Click **Account Settings**.
3. ClickÂ **Pipeline Deals API**Â in theÂ sidebar.Â
4. Enable API access.


Your API key should now appear on the screen.


Connecting to Your PipelineDeals Account
----------------------------------------


This section enumerates the options in the **Credentials** and **Details** panes in the PipelineDeals Connector page.Â The components of the other panes in this page, **Scheduling**Â and **Name & Describe Your DataSet**, are universal across most connector types and are discussed in greater length inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


### Credentials Pane


This pane contains fields for entering credentials to connect to your PipelineDeals account. The following table describes what is needed for each field: Â 




| Field | Description |
| --- | --- |
| API Key | Enter your PipelineDeals API key. For information about finding your API key, see "Prerequisites," above. |


Once you have entered valid PipelineDeals credentials, you can use the same account any time you go to create a new PipelineDeals DataSet. You can manage connector accounts in the **Accounts** tab in the Data Center. For more information about this tab, see [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


### Details Pane


This pane contains a single menu from which you select a report type. No other parameters are required.




| Menu | Description |
| --- | --- |
| Report | Select the PipelineDeals report you want to run.Â The following reports are available:

|  |  |
| --- | --- |
| Activities | Returns a list of all activities in your account. |
| Calendar Events and Tasks | Returns a list of all calendar events and tasks in your account. |
| Companies | Returns a list of companies in your account. |
| Deals | Returns a list of deals in your account. |
| Deals Custom Field Labels | Returns a list of deals custom field labels for your account. |
| Deals Details | Returns detailed information about deals in your account. |
| Documents | Returns a list of documents in your account. |
| People | Returns a list of people in your account. |

 |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, seeÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


Â