---
title : Cake Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:40:00
url : https://domo-support.domo.com/s/article/360043430953
linked_kbs :  ['https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360043430953', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003790
views : 2,018
created_date : 2022-10-24 21:15:00
last updated : 2022-10-24 22:40:00
---



Intro
-----


Cake is performance marketing software that provides real-time tracking, attribution, and optimization for marketing professionals. To learn more about the Cake API, visit their page ([https://support.getcake.com/support/...ons/5000109264](https://support.getcake.com/support/solutions/5000109264 "https://support.getcake.com/support/solutions/5000109264")).


You connect to your Cake account in the Data Center. This topic discusses the fields and menus that are specific to the Cake connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed in [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).


Prerequisites
-------------


To connect to your Cake account and create a DataSet, you must have the following:



* Your Cake domain name. This is the portion of your Cake URL immediately following https://. For example, if your URL was <https://mycompany.cake.com>, the domain would be mycompany.
* Your Cake API key. For information about finding your API key, visit this page: [https://support.getcake.com/support/...ersion-tracker](https://support.getcake.com/support/solutions/articles/5000576515-your-api-key-and-latest-version-tracker "https://support.getcake.com/support/solutions/articles/5000576515-your-api-key-and-latest-version-tracker")


Connecting to Your Cake Account
-------------------------------


This section enumerates the options in the **Credentials** and **Details** panes in the Cake Connector page. The components of the other panes in this page, **Scheduling** and **Name & Describe Your DataSet**, are universal across most connector types and are discussed in greater length in [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md "Adding a DataSet Using a Data Connector").


### Credentials Pane


This pane contains fields for entering credentials to connect to your Cake account. The following table describes what is needed for each field:  




| Field | Description |
| --- | --- |
| Domain Name | Enter your Cake domain name. |
| API Key | Enter your Cake API key. |


For information about obtaining these credentials, see "Prerequisites," above.


Once you have entered valid Cake credentials, you can use the same account any time you go to create a new Cake DataSet. You can manage connector accounts in the **Accounts** tab in the Data Center. For more information about this tab, see [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


### Details Pane


This pane contains a primary **Reports** menu, along with various other menus which may or may not appear depending on the report type you select.




| Menu | Description |
| --- | --- |
| Report | Select the Cake report you want to run. The following reports are available:

|  |  |
| --- | --- |
| Account Status | Returns status information for the account. |
| Advertisers | Returns information about advertisers. |
| Advertisers Export | Returns information about exported advertisers. |
| Affiliates | Returns information about affiliates. |
| Affiliate Tags | Returns a list of affiliate tags. |
| Affiliate Tiers | Returns a list of affiliate tiers. |
| Affiliate Referrals | Returns a list of affiliate referrals. |
| Affiliate Export | Returns information about exported affiliates. |
| Affiliate Summary | Returns a summary of affiliate data. |
| Accepted Dispositions | Returns a list of accepted dispositions. |
| Billing Cycles | Returns a list of billing cycles. |
| Buyers Export | Returns information about exported buyers. |
| Campaigns | Returns information about all your campaigns. |
| Campaigns Summary | Returns performance summary data by campaign. |
| Cap Intervals | Returns a list of cap intervals. |
| Cap Types | Returns a list of cap types. |
| Caps | Returns a report about click and conversion caps set on entities and the progress towards those caps within the specified timeframe. |
| Clicks | Returns information about clicks. |
| Conversion Changes | Returns a list of conversions that have changed within a specific timeframe. |
| Conversion Dispositions | Returns a list of conversion dispositions. |
| Conversions | Returns a list of conversions. |
| Currencies | Returns a list of currencies. |
| Daily Summary | Returns a list of daily summary reports. |
| Exchange Rates | Returns a list of exchange rates. |
| Languages | Returns a list of languages. |
| Leads by Affiliate | Returns a list of leads filtered by affiliate. |
| Leads by Buyer | Returns a list of leads filtered by buyer. |
| Login Export | Returns a list of logins filtered by role. |
| Offers | Returns a list of orders. |
| Offers Statuses | Returns status information for all offers. |
| Offer Types | Returns a list of offer types. |
| Payment Settings | Returns payment setting information. |
| Payment Types | Returns a list of payment types. |
| Price Formats | Returns a list of price formats. |
| Rejected Dispositions | Returns  a list of rejected dispositions. |
| Traffic Export | Returns a list of traffic reports. |
| Verticals | Returns a list of verticals. |

 |
| Past Days | Enter the number of past days you want to retrieve information for. You can enter this in any of the following formats: X, XDay, or XDays. For example: 30days |
| Affiliate Name (Optional for "Affiliates" report) | Enter the name of the affiliate name you want to retrieve data for. |
| Search (Optional) | Enter a search term you want to show data for in your report. For example: rename |
| Conversion Type | Select whether you want to pull data for conversions, events, or all (default). |
| Offer ID (Optional) | Enter the offer ID you want to retrieve data for. You can find a list of offer IDs by running the "Offers" report. |
| Advertiser ID (Optional) | Enter the advertiser ID you want to retrieve data for. You can find a list of offer IDs by running the "Advertisers" report. |
| Offer Name (Optional) | Enter the name of the offer you want to fiter by in your report. |
| Advertiser Name (Optional) | Enter the name of the advertiser you want to fiter by in your report. |
| Duration  | Select whether you want to pull data for a specific date or a date range.  |
| Report Date  | Select whether the report data is for a specific date or for a relative number of days back from today.  |
| Select Specific Date  | Select the date for the report.  |
| Days Back | Enter the number of past days that should appear in the report.   |
| Start Date | Specify whether the first date in your date range is a specific or relative date. You select the last date in your range in **End Date**.  |
| End Date | Specify whether the second date in your date range is a specific or relative date. You select the first date in your range in **Start Date**.   |
| Select Specific Start Date | Select the first date in your date range.  |
| Select Specific End Date | Select the second date in your date range.  |
| Days Back to Start From | Enter the number of the farthest day back that should be represented in the report. Combine with **Days Back to End At** to create a range of represented days.
For example, if you entered 10 for **Days Back to Start From** and 5 for **Days Back to End At**, the report would contain data for 10 days ago up until 5 days ago. |
| Days Back to End At | Enter the number of the most recent day back that should be represented in the report. Combine with **Days Back to Start From** to create a range of represented days.
For example, if you entered 10 for **Days Back to Start From** and 5 for **Days Back to End At**, the report would contain data for 10 days ago up until 5 days ago. |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, see [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).