---
title : Beast Mode Functions Reference Guide
url : https://domo-support.domo.com/s/article/360043429933
linked_kbs :  ['[https://domo-support.domo.com/s/knowledge-base/](https://domo-support.domo.com/s/knowledge-base/)', '[https://domo-support.domo.com/s/](https://domo-support.domo.com/s/)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZamoGAC](https://domo-support.domo.com/s/topic/0TO5w000000ZamoGAC)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZanAGAS](https://domo-support.domo.com/s/topic/0TO5w000000ZanAGAS)', '[https://domo-support.domo.com/s/article/360043429913](https://domo-support.domo.com/s/article/360043429913)', '[https://domo-support.domo.com/s/article/360043429953](https://domo-support.domo.com/s/article/360043429953)', '[https://domo-support.domo.com/s/article/360043429933](https://domo-support.domo.com/s/article/360043429933)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZanAGAS/beast-mode](https://domo-support.domo.com/s/topic/0TO5w000000ZanAGAS/beast-mode)', '[https://domo-support.domo.com/s/article/360042925494](https://domo-support.domo.com/s/article/360042925494)', '[https://domo-support.domo.com/s/article/4408174643607](https://domo-support.domo.com/s/article/4408174643607)', '[https://domo-support.domo.com/s/login/](https://domo-support.domo.com/s/login/)']
article_id : 000004081
html : {'Title': <div class="slds-form-element__control slds-grid itemBody" data-aura-rendered-by="16:337;a"><span class="test-id__field-value slds-form-element__static slds-grow is-read-only" data-aura-rendered-by="17:337;a"><span class="uiOutputText" data-aura-class="uiOutputText" data-aura-rendered-by="9:337;a">Beast Mode Functions Reference Guide</span></span><!--render facet: 19:337;a--><!--render facet: 20:337;a--></div>, 'Article Body': <div class="slds-form-element__control slds-grid itemBody" data-aura-rendered-by="40:337;a"><span class="test-id__field-value slds-form-element__static slds-grow is-read-only" data-aura-rendered-by="41:337;a"><div class="slds-rich-text-editor__output uiOutputRichText forceOutputRichText" data-aura-class="uiOutputRichText forceOutputRichText" data-aura-rendered-by="32:337;a" dir="ltr"><h2 data-aura-rendered-by="33:337;a">Intro</h2>
<p data-aura-rendered-by="33:337;a">You can use this reference guide to learn about supported functions in Beast Mode.</p>
<p data-aura-rendered-by="33:337;a"><span class="mt-font-size-22"><strong>Video - Intro to Beast Mode</strong></span></p>
<div class="mt-video-widget" data-aura-rendered-by="33:337;a"><iframe allowfullscreen="" frameborder="0" height="315" scrolling="auto" src="//www.youtube-nocookie.com/embed/SpVbmZPMAsM" width="560"></iframe></div>
<p data-aura-rendered-by="33:337;a"> </p>
<h2 data-aura-rendered-by="33:337;a" id="h_feb3b380-5a0c-451f-ae85-c452ff6769e7">Supported functions</h2>
<p data-aura-rendered-by="33:337;a">You can use any of the following functions in calculations. You can see examples of many of the functions in <a class="confluence-link" href="http://wiki.domo.com/confluence/display/DHCS/Sample+Beast+Mode+calculations" target="_blank" title="Sample Beast Mode Calculations">Sample Beast Mode calculations</a>.</p>
<h3 data-aura-rendered-by="33:337;a">Aggregate functions</h3>
<table border="1" cellpadding="1" cellspacing="1" data-aura-rendered-by="33:337;a" style="width: 100%;table-layout: fixed;"><thead><tr><th colspan="1" rowspan="1"><p>Function Name</p></th><th colspan="1" rowspan="1"><p>Description</p></th><th colspan="1" rowspan="1"><p>Example</p></th></tr></thead><tbody><tr><td colspan="1" rowspan="1"><p><code>APPROXIMATE COUNT (DISTINCT)</code></p></td><td colspan="1" rowspan="1"><p>Returns the approximate count of a number of unique values in a column.</p></td><td colspan="1" rowspan="1"><p><code>APPROXIMATE_COUNT_DISTINCT(`Customers`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>AVG</code></p></td><td colspan="1" rowspan="1"><p>Returns the average value for each series in a column.</p></td><td colspan="1" rowspan="1"><p><code>AVG(`Operating Budget`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>CEILING</code></p></td><td colspan="1" rowspan="1"><p>Returns the highest value for each series in a column.</p>
<p>This function differs from the <span class="mt-font-courier-new">MAX</span> function in that <span class="mt-font-courier-new">CEILING</span> is rounded whereas <span class="mt-font-courier-new">MAX</span> is not rounded.</p></td><td colspan="1" rowspan="1"><p><code>CEILING(`Operating Budget`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>COUNT</code></p></td><td colspan="1" rowspan="1"><p>Returns the number of row values in a column.</p></td><td colspan="1" rowspan="1"><p><code>COUNT(`Customers`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>COUNT (DISTINCT)</code></p></td><td colspan="1" rowspan="1"><p>Returns the count of a number of unique values in a column.</p></td><td colspan="1" rowspan="1"><p><code>COUNT(DISTINCT `Customers`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>FLOOR</code></p></td><td colspan="1" rowspan="1"><p>Returns the lowest value for each series in a numeric column.</p>
<p>This function differs from the <span class="mt-font-courier-new">MIN</span> function in that <span class="mt-font-courier-new">FLOOR</span> is rounded whereas MIN is not.</p></td><td colspan="1" rowspan="1"><p><code>FLOOR(`Operating Budget`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>MAX</code></p></td><td colspan="1" rowspan="1"><p>Returns the highest value for each series in a numeric column.</p>
<p>This function differs from the <span class="mt-font-courier-new">CEILING</span> function in that <span class="mt-font-courier-new">MAX</span> is not rounded whereas <span class="mt-font-courier-new">CEILING</span> is rounded.</p></td><td colspan="1" rowspan="1"><p><code>MAX(`Operating Budget`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>MIN</code></p></td><td colspan="1" rowspan="1"><p>Returns the lowest value for each series in a numeric column.</p>
<p>This function differs from the <span class="mt-font-courier-new">FLOOR</span> function in that <span class="mt-font-courier-new">MIN</span> is not rounded whereas <span class="mt-font-courier-new">FLOOR</span> is rounded.</p></td><td colspan="1" rowspan="1"><p><code>MIN(`Operating Budget`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>STDDEV_POP</code></p></td><td colspan="1" rowspan="1"><p>Returns the population standard deviation for each series in a numeric column.</p></td><td colspan="1" rowspan="1"><p><code>STDDEV_POP(`Values`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>SUM</code></p></td><td colspan="1" rowspan="1"><p>Returns the sum of each series in a numeric column.</p></td><td colspan="1" rowspan="1"><p><code>SUM(`Values`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>SUM (DISTINCT)</code></p></td><td colspan="1" rowspan="1"><p>Returns the sum of unique values in a numeric column.</p></td><td colspan="1" rowspan="1"><p><code>SUM(DISTINCT `Values`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>VAR_POP</code></p></td><td colspan="1" rowspan="1"><p>Returns the population standard variance for each series in a numeric column.</p></td><td colspan="1" rowspan="1"><p><code>VAR_POP(`Values`)</code></p></td></tr></tbody></table>
<p data-aura-rendered-by="33:337;a">For information about using aggregate functions in summary numbers, see <a href="/s/article/360043429913" target="_blank" title="Adding a Beast Mode Calculation to Your Chart">Applying a calculation to a summary number</a>.</p>
<h3 data-aura-rendered-by="33:337;a">Mathematical functions</h3>
<table border="1" cellpadding="1" cellspacing="1" data-aura-rendered-by="33:337;a" style="width: 100%;table-layout: fixed;"><thead><tr><th colspan="1" rowspan="1"><p>Function Name</p></th><th colspan="1" rowspan="1"><p>Description</p></th><th colspan="1" rowspan="1"><p>Example</p></th></tr></thead><tbody><tr><td colspan="1" rowspan="1"><p><code>ABS</code></p></td><td colspan="1" rowspan="1"><p>Returns the absolute value for all values in a numeric column.</p>
<p>In other words, any negative values become positive, and positive values stay the same. This is valuable when you want to see aggregation without considering positive and negative values.</p></td><td colspan="1" rowspan="1"><p><code>ABS(`Operating Budget`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>MOD</code></p></td><td colspan="1" rowspan="1"><p>Returns the remainder of each value in a numeric column divided by some specified number (dividend).</p></td><td colspan="1" rowspan="1"><p><code>MOD(`Values`,2)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>POWER</code></p></td><td colspan="1" rowspan="1"><p>Returns each value in a numeric column raised to a given power. If the column contains multiple series, the values are summed for each series.</p></td><td colspan="1" rowspan="1"><p><code>POWER(`Values`,2)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>RAND</code></p></td><td colspan="1" rowspan="1"><p>Returns random values between 0 and 1.</p></td><td colspan="1" rowspan="1"><p><code>RAND(`Values`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>ROUND</code></p></td><td colspan="1" rowspan="1"><p>Returns values in a numeric column rounded to the nearest specified decimal place.</p>
<p>If you do not include a decimal place value in the function, returned values are rounded to the nearest whole number.</p></td><td colspan="1" rowspan="1"><p><code>ROUND(`Values`,1)</code></p></td></tr></tbody></table>
<h3 data-aura-rendered-by="33:337;a">Logical functions</h3>
<table border="1" cellpadding="1" cellspacing="1" data-aura-rendered-by="33:337;a" style="width: 100%;table-layout: fixed;"><thead><tr><th colspan="1" rowspan="1"><p>Function Name</p></th><th colspan="1" rowspan="1"><p>Description</p></th><th colspan="1" rowspan="1"><p>Example</p></th></tr></thead><tbody><tr><td colspan="1" rowspan="1"><p><code>CASE</code></p></td><td colspan="1" rowspan="1"><p>Use to begin logical statements in which the value of data is replaced when certain criteria is reached (when...then or when...then, else). These statements use the following format:<br/><br/><span class="mt-font-courier-new"><code>CASE `Value` when <em>x</em> then 'resultx' else 'resulty' End</code></span></p>
<p>or<br/> </p>
<p><code>CASE when `Value`=<em>x</em> then 'resultx' else 'resulty' End</code></p>
<p>In other words, when the data in the "Value" column equals number <em>x</em>, value <em>resultx</em> is returned; otherwise value <em>resulty</em> is returned. (The value returned can be either a single-quoted string or a number.)</p>
<p>For multiple conditional statements, use the following format:<br/><br/><code>CASE when `Value`=<em>x</em> then 1 when `Value`=<em>y</em> then 2 end</code></p>
<p>Although valid, avoid using the following inefficient format:<br/><br/><code>CASE when `Value`=<em>x</em> then 1 else CASE when `Value`=<em>y</em> then 2 end end</code></p>
<p><strong>IN Operator</strong><br/><br/>In a <span class="mt-font-courier-new">CASE when</span> clause, you can use the <span class="mt-font-courier-new">IN</span> operator, which lets you specify multiple values to evaluate.<br/><br/><code>`column_name` IN (value1,value2,...)</code><br/><br/><br/><code>CASE when `State` in ('NY', 'TX') then 0 else 1 end</code></p>
<p><strong>LIKE Operator</strong><br/><br/>In a <span class="mt-font-courier-new">CASE when</span> clause, you can use the <span class="mt-font-courier-new">LIKE</span> operator, which lets you search for a specified pattern in a column.<br/><br/><code>`column_name` LIKE pattern</code></p>
<p><code>CASE when `State` like '%TX%' or `State` like '%NY' then 0 else 1 end</code><br/><br/>You can use these wildcards with the <span class="mt-font-courier-new">LIKE</span><code> </code>operator:</p><ul><li><p><code>%</code> to match any number of characters, even zero characters.<br/><code>like '%TX%'</code></p></li><li><p><code>_</code> to match exactly one character.<br/><code>like '_hn%'</code></p></li></ul><p>Values for the <span class="mt-font-courier-new">LIKE</span> operator are matched in order of the <span class="mt-font-courier-new">WHEN</span> statements. For example, if a value in the data matches the first and fourth <span class="mt-font-courier-new">LIKE</span> operators, it is applied to the first operation. </p></td><td colspan="1" rowspan="1"><p><code>CASE when `Amount`=1 then 10 else 0 End</code></p>
<p><code>CASE `Gender`<br/>            when 'M' then 'Male'<br/>            when 'F' then 'Female'<br/>            end​</code></p>
<p><code>CASE when `Pennies` &gt;= 600 then 'Large'<br/>            when `Pennies` &lt;= 300 then 'Small'<br/>            else `Pennies`<br/>            end​</code></p>
<p> </p></td></tr><tr><td colspan="1" rowspan="1"><p><code>IFNULL</code></p></td><td colspan="1" rowspan="1"><p>Used in logical statements in which you want to specify a replacement for null values.</p></td><td colspan="1" rowspan="1"><p><code>IFNULL(`Values`,0)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>NULLIF</code></p></td><td colspan="1" rowspan="1"><p>Returns null if the value in the first column equals the value in the second column; otherwise returns the value in the first column.</p></td><td colspan="1" rowspan="1"><p><code>NULLIF(`Value 1`,`Value 2`)</code></p></td></tr></tbody></table>
<p data-aura-rendered-by="33:337;a"><span class="mt-font-size-22"><strong>Video - Case Statement Overview</strong></span></p>
<div class="mt-video-widget" data-aura-rendered-by="33:337;a"><iframe allowfullscreen="" frameborder="0" height="315" scrolling="auto" src="//www.youtube-nocookie.com/embed/xFofhklohSc" width="560"></iframe></div>
<p data-aura-rendered-by="33:337;a"> </p>
<p data-aura-rendered-by="33:337;a"> </p>
<h3 data-aura-rendered-by="33:337;a">String functions</h3>
<table border="1" cellpadding="1" cellspacing="1" data-aura-rendered-by="33:337;a" style="width: 100%;table-layout: fixed;"><thead><tr><th colspan="1" rowspan="1"><p>Function</p></th><th colspan="1" rowspan="1"><p>Description</p></th><th colspan="1" rowspan="1"><p>Example</p></th></tr></thead><tbody><tr><td colspan="1" rowspan="1"><p><code>CONCAT</code></p></td><td colspan="1" rowspan="1"><p>Combines strings from two or more string columns.</p></td><td colspan="1" rowspan="1"><p><code>CONCAT(`First Name`,' ',`Last Name`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>INSTR</code></p></td><td colspan="1" rowspan="1"><p>Returns the position of the first instance of a specified string in a given column, starting from the first letter in the name.</p>
<p>In the example at right, the calculation would return the position of the first instance of the letter "e" in each string in the column.  </p></td><td colspan="1" rowspan="1"><p><code>INSTR(`Group`,'e')</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>LEFT</code></p></td><td colspan="1" rowspan="1"><p>Returns the specified number of characters in each string in the the given column, starting from the left. </p></td><td colspan="1" rowspan="1"><p><code>LEFT(`Group`,3)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>LENGTH</code></p></td><td colspan="1" rowspan="1"><p>Returns the number of characters in each string in the given column. </p></td><td colspan="1" rowspan="1"><p><code>LENGTH(`Group`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>LOWER</code></p></td><td colspan="1" rowspan="1"><p>Converts strings from one or more string columns into lower-case.</p></td><td colspan="1" rowspan="1"><p><code>LOWER(`Product Type`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>REPLACE</code></p></td><td colspan="1" rowspan="1"><p>Replaces all of the specified strings in a given column with another specified string. </p></td><td colspan="1" rowspan="1"><p><code>REPLACE(`Department`,'Human Resnources','Human Resources')</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>RIGHT</code></p></td><td colspan="1" rowspan="1"><p>Returns the specified number of characters in the given column, starting from the right. </p></td><td colspan="1" rowspan="1"><p><code>RIGHT(`Group`,3)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>SUBSTRING</code></p></td><td colspan="1" rowspan="1"><p>Extracts and returns a specified number of characters from the values in a string column.</p>
<p>You specify the characters to return by indicating the starting position and the length of characters. For example, specifying the position as 1 and the length as 3 would return the first, second, and third characters for values in the column.</p></td><td colspan="1" rowspan="1"><p><code>SUBSTRING(`Employee Name`,1,3)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>TRIM</code></p></td><td colspan="1" rowspan="1"><p>Trims leading and trailing spaces for all values in string columns.</p></td><td colspan="1" rowspan="1"><p><code>TRIM(`Employee Name`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>UPPER</code></p></td><td colspan="1" rowspan="1"><p>Converts strings from one or more string columns into upper-case.</p></td><td colspan="1" rowspan="1"><p><code>UPPER(`Customers`)</code></p></td></tr></tbody></table>
<h3 data-aura-rendered-by="33:337;a">Date and Time functions</h3>
<table border="1" cellpadding="1" cellspacing="1" data-aura-rendered-by="33:337;a" style="width: 100%;table-layout: fixed;"><thead><tr><th colspan="1" rowspan="1"><p>Function</p></th><th colspan="1" rowspan="1"><p>Description</p></th><th colspan="1" rowspan="1"><p>Example</p></th></tr></thead><tbody><tr><td colspan="1" rowspan="1"><p><code>ADDDATE</code></p></td><td colspan="1" rowspan="1"><p>Adds date or datetime values (as intervals) to date values in a date column.</p>
<p>You can specify the date or datetime values to add to date values in a date column by specifying the column, interval, expression, and unit, as in <span class="mt-font-courier-new">ADDDATE(`<em>datecolumn</em>`, interval <em>expr</em> <em>unit</em>)</span> where <em>datecolumn</em> is the column containing a date value, where <em>expr</em> is the argument containing the date or datetime value to add, and where <em>unit</em> is the string value for the corresponding date or datetime unit type.</p>
<p>You can prefix the expression with a "-" to subtract the value. Specify the unit value (such as second, minute, hour, day, week, month, quarter, year). (The "interval" keyword and unit type values are case insensitive.) For more information, see <a href="/s/article/360043429953" target="_self" title="Date Format Specifier Characters in Beast Mode">Unit type values in Beast Mode.</a></p>
<p>For example, adding 12 days to <span class="mt-font-courier-new">January 4</span> would return <span class="mt-font-courier-new">January 16</span>.</p>
<p>Same as <span class="mt-font-courier-new">DATE_ADD</span>.</p></td><td colspan="1" rowspan="1"><p><code>ADDDATE(`DateCol`, interval 12 day)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>ADDTIME</code></p></td><td colspan="1" rowspan="1"><p>Adds a specified number of seconds to all values in a time column. For example, adding 15 seconds to <span class="mt-font-courier-new">8:05</span> would return <span class="mt-font-courier-new">8:20</span>.</p></td><td colspan="1" rowspan="1"><p><code>ADDTIME(`Time`,25)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>CURDATE</code></p></td><td colspan="1" rowspan="1"><p>Returns the current date.</p>
<p>No column name is specified in this function.</p>
<p>Same as <span class="mt-font-courier-new">CURRENT_DATE</span>.</p></td><td colspan="1" rowspan="1"><p><code>CURDATE()</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>CURTIME</code></p></td><td colspan="1" rowspan="1"><p>Returns the current time.</p>
<p>No column name is specified in this function.</p>
<p>Same as <span class="mt-font-courier-new">CURRENT_TIME</span>.</p></td><td colspan="1" rowspan="1"><p><code>CURTIME()</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>CURRENT_DATE</code></p></td><td colspan="1" rowspan="1"><p>Returns the current date.</p>
<p>No column name is specified in this function.</p>
<p>Same as <span class="mt-font-courier-new">CURDATE</span>.</p></td><td colspan="1" rowspan="1"><p><code>CURRENT_DATE()</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>CURRENT_TIME</code></p></td><td colspan="1" rowspan="1"><p>Returns the current time.</p>
<p>No column name is specified in this function.</p>
<p>Same as <span class="mt-font-courier-new">CURTIME</span>.</p></td><td colspan="1" rowspan="1"><p><code>CURRENT_TIME()</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>CURRENT_TIMESTAMP</code></p></td><td colspan="1" rowspan="1"><p>Returns the value of current date and time in <span class="mt-font-courier-new">YYYY-MM-DD HH:MM:SS</span> format.</p>
<p>No column name is specified in this function.</p>
<p>Same as <span class="mt-font-courier-new">NOW</span>.</p></td><td colspan="1" rowspan="1"><p><code>CURRENT_TIMESTAMP()</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>DATE</code></p></td><td colspan="1" rowspan="1"><p>Extracts and returns the dates from datetime values.</p></td><td colspan="1" rowspan="1"><p><code>DATE(`DateCol`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>DATEDIFF</code></p></td><td colspan="1" rowspan="1"><p>Returns the number of days between two dates from datetime values.</p></td><td colspan="1" rowspan="1"><p><code>DATEDIFF(CURRENT_DATE(), `lastmoddate`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>DATE_ADD</code></p></td><td colspan="1" rowspan="1"><p>Adds date or datetime values (as intervals) to date values in a date column.</p>
<p>You can specify the date or datetime values to add to date values in a date column by specifying the column, interval, expression, and unit, as in <span class="mt-font-courier-new">DATE_ADD(`<em>datecolumn</em>`, interval <em>expr</em> <em>unit</em>)</span> where <em>datecolumn</em> is the column containing a date value, where <em>expr</em> is the argument containing the date or datetime value to add, and where <em>unit</em> is the string value for the corresponding date or datetime unit type.</p>
<p>You can prefix the expression with a "-" to subtract the value. Specify the unit value (such as second, minute, hour, day, week, month, quarter, year). (The "interval" keyword and unit type values are case insensitive.) For more information, see <a href="/s/article/360043429953" target="_self" title="Date Format Specifier Characters in Beast Mode">Unit type values in Beast Mode</a>.</p>
<p>For example, adding 12 days to <span class="mt-font-courier-new">January 4</span> would return <span class="mt-font-courier-new">January 16</span>.</p>
<p>Same as <span class="mt-font-courier-new">ADDDATE</span>.</p></td><td colspan="1" rowspan="1"><p><code>DATE_ADD(`DateCol`, interval 12 day)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>DATE_FORMAT</code></p></td><td colspan="1" rowspan="1"><p>Formats dates in a date/time column into a specific format.</p>
<div class="info-box note">
<div class="info-box-wrapper">
<div class="info-box-icon-container"><span class="info-box-icon"></span></div>
<div class="info-box-content-container">
<div class="info-box-content">
<strong>Note: </strong>Beast Mode uses SQL-like date and time formats.</div>
</div>
</div>
</div>
<p>You can specify the format to use for a date or time column by specifying the column and the date or time string, as in <span class="mt-font-courier-new">DATE_FORMAT(`<em>datecolumn</em>`,'<em>format</em>')</span> where <em>datecolumn</em> is the column containing a date value and where <em>format</em> is the string containing specifier characters to use in formatting the date value.</p>
<p>The "%" character is required before format specifier characters.</p>
<p>For example, using <span class="mt-font-courier-new">DATE_FORMAT(`MyDate`,'%Y-%m-%d %h:%i %p')</span>, the date in the <em>MyDate</em> date column uses this format: 2013-04-17 10:10 AM.</p>
<p>For information about specifier characters, see <a href="/s/article/360043429953" target="_self" title="Date Format Specifier Characters in Beast Mode">Date Format Specifier Characters in Beast Mode</a>.</p>
<p>Similar to <span class="mt-font-courier-new">TIME_FORMAT</span>.</p></td><td colspan="1" rowspan="1"><p><code>DATE_FORMAT(`DateCol`,'%y')</code><br/><code>DATE_FORMAT(`DateCol`,'%m/%d')</code><br/><code>DATE_FORMAT(NOW(),'%d %b %Y %T')</code><br/><code>DATE_FORMAT(STR_TO_DATE(`DateCol`, '%m,%d,%Y'), '%m/%d/%Y')</code><br/><code>ADDDATE(DATE_FORMAT(`DateCol`, '%Y-%m-%d'), interval 12 day)</code><br/><code>PERIOD_DIFF(DATE_FORMAT(CURDATE(), '%Y%m'), DATE_FORMAT(`DateCol`, '%Y%m'))</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>DATE_SUB</code></p></td><td colspan="1" rowspan="1"><p>Subtracts date or datetime values (as intervals) to date values in a date column.</p>
<p>You can specify the date or datetime values to subtract from date values in a date column by specifying the column, interval, expression, and unit, as in <span class="mt-font-courier-new">DATE_SUB(`<em>datecolumn</em>`, interval <em>expr</em> <em>unit</em>)</span> where <em>datecolumn</em> is the column containing a date value, where <em>expr</em> is the argument containing the date or datetime value to subtract, and where <em>unit</em> is the string value for the corresponding date or datetime unit type.</p>
<p>You can prefix the expression with a "-" to add the value. Specify the unit value (such as second, minute, hour, day, week, month, quarter, year). (The "interval" keyword and unit type values are case insensitive.) For more information, see <a href="/s/article/360043429953" target="_self" title="Date Format Specifier Characters in Beast Mode">Unit type values in Beast Mode</a>.</p>
<p>For example, subtracting 12 days from <span class="mt-font-courier-new">January 24</span> would return <span class="mt-font-courier-new">January 12</span>.</p>
<p>Same as <span class="mt-font-courier-new">SUBDATE</span>.</p></td><td colspan="1" rowspan="1"><p><code>DATE_SUB(`DateCol`, interval 12 day)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>DAY</code></p></td><td colspan="1" rowspan="1"><p>Returns the numerical day of the month for all values in a date/time column.</p>
<p>Same as <span class="mt-font-courier-new">DAYOFMONTH</span>.</p></td><td colspan="1" rowspan="1"><p><code>DAY(`DateCol`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>DAYNAME</code></p></td><td colspan="1" rowspan="1"><p>Returns the name of the day of the week for all values in a date/time column.</p></td><td colspan="1" rowspan="1"><p><code>DAYNAME(`DateCol`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>DAYOFMONTH</code></p></td><td colspan="1" rowspan="1"><p>Returns the numerical day of the month for all values in a date/time column.</p>
<p>Same as <span class="mt-font-courier-new">DAY</span>.</p></td><td colspan="1" rowspan="1"><p><code>DAYOFMONTH(`DateCol`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>DAYOFWEEK</code></p></td><td colspan="1" rowspan="1"><p>Returns the numerical day of the week for all values in a date/time column (e.g. "2" for "Monday").</p></td><td colspan="1" rowspan="1"><p><code>DAYOFWEEK(`DateCol`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>DAYOFYEAR</code></p></td><td colspan="1" rowspan="1"><p>Returns the numerical day of the year for all values in a date/time column (e.g. "226" for the 226th day of the year).</p></td><td colspan="1" rowspan="1"><p><code>DAYOFYEAR(`DateCol`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>FROM_DAYS</code></p></td><td colspan="1" rowspan="1"><p>Converts day numbers into dates.</p></td><td colspan="1" rowspan="1"><p><code>FROM_DAYS(`DateCol`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><code>FROM_UNIXTIME</code></td><td colspan="1" rowspan="1"><p>Returns a UNIX datetime value from a UNIX date/time column using the specified format.</p>
<p>For information about specifier characters, see <a href="/s/article/360043429953" target="_self" title="Date Format Specifier Characters in Beast Mode">Date Format Specifier Characters in Beast Mode</a>.</p></td><td colspan="1" rowspan="1"><p><code>FROM_UNIXTIME(`UnixDateCol`,'%Y %d %m %h:%i:%s %x')</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>HOUR</code></p></td><td colspan="1" rowspan="1"><p>Returns the hour for all values in a date/time column (e.g. the time "3:36" would return "3").</p></td><td colspan="1" rowspan="1"><p><code>HOUR(`Time`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>LAST_DAY</code></p></td><td colspan="1" rowspan="1"><p>Aggregates values for each month in a date/time column and returns each aggregation as the last day of each month.</p>
<p>For example, if a date/time column had "15," "16," and "17" as values for January, only the last given date of January would appear, with a combined value of 48.</p></td><td colspan="1" rowspan="1"><p><code>LAST_DAY(`DateCol`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>MINUTE</code></p></td><td colspan="1" rowspan="1"><p>Returns the value for each minute in a time column.</p>
<p>If there is more than one instance of a particular minute in the column, the values for those minutes are aggregated.</p></td><td colspan="1" rowspan="1"><p><code>MINUTE(`Time`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>MONTH</code></p></td><td colspan="1" rowspan="1"><p>Returns the month number (e.g. "9" for September) for all values in a date/time column.</p></td><td colspan="1" rowspan="1"><p><code>MONTH(`DateCol`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>MONTHNAME</code></p></td><td colspan="1" rowspan="1"><p>Returns the name of the month (e.g. "September" rather than "9") for all values in a date/time column.</p></td><td colspan="1" rowspan="1"><p><code>MONTHNAME(`DateCol`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>NOW</code></p></td><td colspan="1" rowspan="1"><p>Returns the value of current date and time in <span class="mt-font-courier-new">YYYY-MM-DD HH:MM:SS</span> format.</p>
<p>No column name is specified in this function.</p>
<p>Same as <span class="mt-font-courier-new">CURRENT_TIMESTAMP</span>.</p></td><td colspan="1" rowspan="1"><p><code>NOW()</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>PERIOD_ADD</code></p></td><td colspan="1" rowspan="1"><p>Adds the specified number of months to the values in a date column. For this to work, the date values must be months in the format <span class="mt-font-courier-new">YYYYMM</span>.</p></td><td colspan="1" rowspan="1"><p><code>PERIOD_ADD(`Month`,6)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>PERIOD_DIFF</code></p></td><td colspan="1" rowspan="1"><p>Returns the number of months between months in two date columns.</p>
<p>For this to work, the date values must be months in the format <span class="mt-font-courier-new">YYYYMM</span>. For example, if one column contained the date value <span class="mt-font-courier-new">200803</span> and another contained the value <span class="mt-font-courier-new">200809</span>, this function would return 6.</p></td><td colspan="1" rowspan="1"><p><code>PERIOD_DIFF(201309,201301)</code><br/><code>PERIOD_DIFF(`Month 1`, `Month 2`)</code><br/><code>PERIOD_DIFF(DATE_FORMAT(CURDATE(), '%Y%m'), DATE_FORMAT(`DateCol`, '%Y%m'))</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>QUARTER</code></p></td><td colspan="1" rowspan="1"><p>Aggregates date value data into quarters in a year.</p></td><td colspan="1" rowspan="1"><p><code>QUARTER(`DateCol`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>SECOND</code></p></td><td colspan="1" rowspan="1"><p>Returns the value for each second in a time column. If there is more than one instance of a particular second in the column, the values for those seconds are aggregated.</p></td><td colspan="1" rowspan="1"><p><code>SECOND(`Time`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>SEC_TO_TIME</code></p></td><td colspan="1" rowspan="1"><p>Converts seconds into hours, minutes, and seconds. For example, <span class="mt-font-courier-new">3489</span> would be converted into <span class="mt-font-courier-new">00:58:09</span>.</p>
<div class="info-box note">
<div class="info-box-wrapper">
<div class="info-box-icon-container"><span class="info-box-icon"></span></div>
<div class="info-box-content-container">
<div class="info-box-content">
<strong>Note:</strong> The sec_to_time function is limited to 24 hours. When a value is greater than 24 hours, it will overflow and loop back to 0 hours.</div>
</div>
</div>
</div></td><td colspan="1" rowspan="1"><p><code>SEC_TO_TIME(`Seconds`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>STR_TO_DATE</code></p></td><td colspan="1" rowspan="1"><p>Converts strings (that Domo does not recognize as dates) from one or more string columns into datetime values. You specify the column(s) and the current date format used in those columns.</p>
<p>By default, datetime values are returned in the output format <span class="mt-font-courier-new">%m-%d-%Y</span>. You can change the output format by enclosing your <span class="mt-font-courier-new">STR_TO_DATE</span> calculation in a <span class="mt-font-courier-new">DATE_FORMAT</span> calculation that specifies the date format specifier characters you want.</p>
<p>For information about specifier characters, see <a href="/s/article/360043429953" target="_self" title="Date Format Specifier Characters in Beast Mode">Date Format Specifier Characters in Beast Mode</a>.</p></td><td colspan="1" rowspan="1"><p><code>STR_TO_DATE(`DateCol`,'%m,%d,%Y')</code><br/><code>DATE_FORMAT(STR_TO_DATE(`DateCol`, '%m,%d,%Y'), '%m/%d/%Y')</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>SUBDATE</code></p></td><td colspan="1" rowspan="1"><p>Subtracts date or datetime values (as intervals) to date values in a date column.</p>
<p>You can specify the date or datetime values to subtract from date values in a date column by specifying the column, interval, expression, and unit, as in <span class="mt-font-courier-new">SUBDATE(`<em>datecolumn</em>`, interval <em>expr</em> <em>unit</em>)</span> where <em>datecolumn</em> is the column containing a date value, where <em>expr</em> is the argument containing the date or datetime value to subtract, and where <em>unit</em> is the string value for the corresponding date or datetime unit type.</p>
<p>You can prefix the expression with a "-" to add the value. Specify the unit value (such as second, minute, hour, day, week, month, quarter, year). (The "interval" keyword and unit type values are case insensitive.) For more information, see <a href="/s/article/360043429953" target="_self" title="Date Format Specifier Characters in Beast Mode">Unit type values in Beast Mode</a>.</p>
<p>For example, subtracting 12 days from <span class="mt-font-courier-new">January 24</span> would return <span class="mt-font-courier-new">January 12</span>. Same as <span class="mt-font-courier-new">DATE_SUB</span>.</p></td><td colspan="1" rowspan="1"><p><code>SUBDATE(`DateCol`, interval 12 day)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>SUBTIME</code></p></td><td colspan="1" rowspan="1"><p>Subtracts a specified number of seconds from all values in a time column.</p>
<p>For example, subtracting 30 seconds from <span class="mt-font-courier-new">8:05:45</span> would return <span class="mt-font-courier-new">8:05:15</span>.</p></td><td colspan="1" rowspan="1"><p><code>SUBTIME(`Time`,15)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>SYSDATE</code></p></td><td colspan="1" rowspan="1"><p>Returns the current date and time in YYYY-MM-DD HH:MM:SS format, as in <span class="mt-font-courier-new">2014-04-03T19:25:29</span>.</p>
<p>No column name is specified in this function.</p>
<p>Similar to <span class="mt-font-courier-new">CURRENT_DATE</span> and <span class="mt-font-courier-new">CURRENT_TIME</span>.</p></td><td colspan="1" rowspan="1"><p><code>SYSDATE()</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>TIME</code></p></td><td colspan="1" rowspan="1"><p>Extracts the times from datetime values.</p></td><td colspan="1" rowspan="1"><p><code>TIME(`DateCol`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>TIMEDIFF</code></p></td><td colspan="1" rowspan="1"><p>Returns the difference between values in two date/time columns, expressed as a time value.</p></td><td colspan="1" rowspan="1"><p><code>TIMEDIFF(`Time 1`,`Time 2`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>TIMESTAMP</code></p></td><td colspan="1" rowspan="1"><p>Returns values in a date column as datetime values.</p></td><td colspan="1" rowspan="1"><p><code>TIMESTAMP(`DateCol`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>TIME_FORMAT</code></p></td><td colspan="1" rowspan="1"><p>Formats time in a datetime column into a specific format.</p>
<div class="info-box note">
<div class="info-box-wrapper">
<div class="info-box-icon-container"><span class="info-box-icon"></span></div>
<div class="info-box-content-container">
<div class="info-box-content">
<strong>Note: </strong>Beast Mode uses SQL-like date and time formats. </div>
</div>
</div>
</div>
<p>You can specify the format to use for time values in a time column by specifying the column and the time string, as in <span class="mt-font-courier-new">TIME_FORMAT(`<em>datetimecolumn</em>`,'<em>format</em>')</span> where <em>datetimecolumn</em> is the column containing a time value and where <em>format</em> is the string containing specifier characters to use in formatting the time value.</p>
<div class="info-box note">
<div class="info-box-wrapper">
<div class="info-box-icon-container"><span class="info-box-icon"></span></div>
<div class="info-box-content-container">
<div class="info-box-content">
<strong>Note: </strong>The format specifiers used in <span class="mt-font-courier-new">DATE_FORMAT</span> may be used with <span class="mt-font-courier-new">TIME_FORMAT</span>, but specifiers other than hours, minutes, seconds and microseconds produce a NULL value or 0.<span><span> </span></span> </div>
</div>
</div>
</div>
<p>The "%" character is required before format specifier characters.</p>
<p>For example, using <span class="mt-font-courier-new">TIME_FORMAT(`Date`,'%h:%i:%s')</span>, the date in the transformed time column uses this format: 12:20:12.</p>
<p>For information about specifier characters, see <a class="confluence-link" href="/s/article/360043429953" target="_self">Date Format Specifier Characters for Beast Mode</a></p>
<p>Similar to <span class="mt-font-courier-new">DATE_FORMAT</span>.</p></td><td colspan="1" rowspan="1"><p><code>TIME_FORMAT(`Date`,'%h:%i:%s')</code><br/><code>TIME_FORMAT(NOW(),'%h:%i:%s')</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>TIME_TO_SEC</code></p></td><td colspan="1" rowspan="1"><p>Returns an elapsed number of seconds for all values in a date/time column.</p></td><td colspan="1" rowspan="1"><p><code>TIME_TO_SEC(`DateCol`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>TO_DAYS</code></p></td><td colspan="1" rowspan="1"><p>Returns the number of days since year 0 for all values in a date/time column. For example, the date "01-06-2010" would be returned as "734143," since 734,143 days have transpired between that date and January 1st of year 0.</p></td><td colspan="1" rowspan="1"><p><code>TO_DAYS(`DateCol`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><code>UNIX_TIMESTAMP</code></td><td colspan="1" rowspan="1">Returns UNIX time stamps for all values in a date/time column.</td><td colspan="1" rowspan="1"><code>UNIX_TIMESTAMP(`DateCol`)</code></td></tr><tr><td colspan="1" rowspan="1"><code>WEEK</code></td><td colspan="1" rowspan="1"><p>Returns the week number for each value of the indicated date or date-time column.</p>
<p>Syntax: <span class="mt-font-courier-new">WEEK(`dateCol`, mode)</span>.</p>
<p>For a Sunday-Saturday week frame, use mode 11: <span class="mt-font-courier-new">WEEK(`dateCol`, 11).</span></p>
<p>For a Monday-Sunday week frame, use mode 22: <span class="mt-font-courier-new">WEEK(`dateCol`, 22). </span></p></td><td colspan="1" rowspan="1"><code>WEEK(`DateCol`,22)</code></td></tr><tr><td colspan="1" rowspan="1"><p><code>YEAR</code></p></td><td colspan="1" rowspan="1"><p>Returns the year for all values in a date/time column.</p></td><td colspan="1" rowspan="1"><p><code>YEAR(`DateCol`)</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>YEARWEEK</code></p></td><td colspan="1" rowspan="1"><p>Returns the year and week number for each value of the indicated date or date-time column in "YYYYWW" format. For example, a date in the 5th week of the year 2020 will return "202005".</p>
<p>Syntax: <span class="mt-font-courier-new">YEARWEEK(`dateCol`, mode) </span></p>
<p>For a Sunday to Saturday week frame, use mode 11: <span class="mt-font-courier-new">YEARWEEK(`dateCol`, 11)</span>. </p>
<p>For a Monday to Sunday week frame, use mode 22: <span class="mt-font-courier-new">YEARWEEK(`dateCol`, 22)</span>.</p></td><td colspan="1" rowspan="1"><p><code>YEARWEEK(`DateCol`,11)</code></p></td></tr></tbody></table>
<h2 data-aura-rendered-by="33:337;a">Unsupported functions</h2>
<p data-aura-rendered-by="33:337;a">The following functions are no longer supported: <code>SQRT</code>, <code>CONVERT_TZ</code>, <code>MICROSECOND </code>,<code> WEEKDAY</code></p></div></span><!--render facet: 43:337;a--><!--render facet: 44:337;a--></div>, 'Preview Article': <div class="slds-form-element__control slds-grid itemBody" data-aura-rendered-by="74:337;a"><span class="test-id__field-value slds-form-element__static slds-grow is-read-only" data-aura-rendered-by="75:337;a"><span class="lvm-grid-no-fade-out undefined forceOutputFormulaHtml" data-aura-class="forceOutputFormulaHtml" data-aura-rendered-by="66:337;a"><a data-aura-rendered-by="67:337;a" href="https://domo-support.domo.com/s/article/360043429933" target="_blank">Click here to preview</a></span></span><!--render facet: 77:337;a--><!--render facet: 78:337;a--></div>, 'URL Name': <div class="slds-form-element__control slds-grid itemBody" data-aura-rendered-by="95:337;a"><span class="test-id__field-value slds-form-element__static slds-grow is-read-only" data-aura-rendered-by="96:337;a"><span class="uiOutputText" data-aura-class="uiOutputText" data-aura-rendered-by="88:337;a">360043429933</span></span><!--render facet: 98:337;a--><!--render facet: 99:337;a--></div>, 'Summary': <div class="slds-form-element__control slds-grid itemBody" data-aura-rendered-by="118:337;a"><span class="test-id__field-value slds-form-element__static slds-grow is-read-only" data-aura-rendered-by="119:337;a"><span class="uiOutputTextArea" data-aura-class="uiOutputTextArea" data-aura-rendered-by="109:337;a"><!--render facet: 111:337;a--></span></span><!--render facet: 121:337;a--><!--render facet: 122:337;a--></div>, 'Article Number': <div class="slds-form-element__control slds-grid itemBody" data-aura-rendered-by="150:337;a"><span class="test-id__field-value slds-form-element__static slds-grow is-read-only" data-aura-rendered-by="151:337;a"><span class="uiOutputText" data-aura-class="uiOutputText" data-aura-rendered-by="143:337;a">000004081</span></span><!--render facet: 153:337;a--><!--render facet: 154:337;a--></div>, 'Archived Date': <div class="slds-form-element__control slds-grid itemBody" data-aura-rendered-by="167:337;a"><span class="test-id__field-value slds-form-element__static slds-grow is-read-only" data-aura-rendered-by="168:337;a"><span class="uiOutputDateTime" data-aura-class="uiOutputDateTime" data-aura-rendered-by="160:337;a"></span></span><!--render facet: 170:337;a--><!--render facet: 171:337;a--></div>, 'Language': <div class="slds-form-element__control slds-grid itemBody" data-aura-rendered-by="189:337;a"><span class="test-id__field-value slds-form-element__static slds-grow is-read-only" data-aura-rendered-by="190:337;a"><span data-aura-rendered-by="181:337;a">English</span></span><!--render facet: 192:337;a--><!--render facet: 193:337;a--></div>, 'Primary Version': <div class="slds-form-element__control slds-grid itemBody" data-aura-rendered-by="222:337;a"><span class="test-id__field-value slds-form-element__static slds-grow is-read-only" data-aura-rendered-by="223:337;a"><!--render facet: 199:337;a--><!--render facet: 201:337;a--><!--render facet: 203:337;a--><a class="outputLookupLink slds-truncate outputLookupLink-ka05w00000123RzAAI-197:337;a forceOutputLookup" data-aura-class="forceOutputLookup" data-aura-rendered-by="208:337;a" data-navigable="true" data-ownerid="197:337;a" data-recordid="ka05w00000123RzAAI" data-refid="recordId" data-special-link="true" href="/s/article/360043429933" rel="noreferrer" target="_blank" title="Beast Mode Functions Reference Guide">Beast Mode Functions Reference Guide<!--render facet: 211:337;a--></a></span><!--render facet: 225:337;a--><!--render facet: 226:337;a--></div>, 'Article Total View Count': <div class="slds-form-element__control slds-grid itemBody" data-aura-rendered-by="243:337;a"><span class="test-id__field-value slds-form-element__static slds-grow is-read-only" data-aura-rendered-by="244:337;a"><span class="uiOutputNumber" data-aura-class="uiOutputNumber" data-aura-rendered-by="236:337;a" dir="auto">21,532</span></span><!--render facet: 246:337;a--><!--render facet: 247:337;a--></div>, 'Article Created Date': <div class="slds-form-element__control slds-grid itemBody" data-aura-rendered-by="278:337;a"><span class="test-id__field-value slds-form-element__static slds-grow is-read-only" data-aura-rendered-by="279:337;a"><span class="uiOutputDateTime" data-aura-class="uiOutputDateTime" data-aura-rendered-by="271:337;a">10/24/2022, 9:20 PM</span></span><!--render facet: 281:337;a--><!--render facet: 282:337;a--></div>, 'First Published Date': <div class="slds-form-element__control slds-grid itemBody" data-aura-rendered-by="313:337;a"><span class="test-id__field-value slds-form-element__static slds-grow is-read-only" data-aura-rendered-by="314:337;a"><span class="uiOutputDateTime" data-aura-class="uiOutputDateTime" data-aura-rendered-by="306:337;a">10/24/2022, 10:40 PM</span></span><!--render facet: 316:337;a--><!--render facet: 317:337;a--></div>}
views : 21,532
created_date : 2022-10-24 21:20:00
last updated : 2022-10-24 22:40:00
---



Intro
-----


You can use this reference guide to learn about supported functions in Beast Mode.


**Video - Intro to Beast Mode**



 


Supported functions
-------------------


You can use any of the following functions in calculations. You can see examples of many of the functions in [Sample Beast Mode calculations](http://wiki.domo.com/confluence/display/DHCS/Sample+Beast+Mode+calculations "Sample Beast Mode Calculations").


### Aggregate functions




| Function Name | Description | Example |
| --- | --- | --- |
| `APPROXIMATE COUNT (DISTINCT)` | Returns the approximate count of a number of unique values in a column. | `APPROXIMATE_COUNT_DISTINCT(`Customers`)` |
| `AVG` | Returns the average value for each series in a column. | `AVG(`Operating Budget`)` |
| `CEILING` | Returns the highest value for each series in a column.
This function differs from the MAX function in that CEILING is rounded whereas MAX is not rounded. | `CEILING(`Operating Budget`)` |
| `COUNT` | Returns the number of row values in a column. | `COUNT(`Customers`)` |
| `COUNT (DISTINCT)` | Returns the count of a number of unique values in a column. | `COUNT(DISTINCT `Customers`)` |
| `FLOOR` | Returns the lowest value for each series in a numeric column.
This function differs from the MIN function in that FLOOR is rounded whereas MIN is not. | `FLOOR(`Operating Budget`)` |
| `MAX` | Returns the highest value for each series in a numeric column.
This function differs from the CEILING function in that MAX is not rounded whereas CEILING is rounded. | `MAX(`Operating Budget`)` |
| `MIN` | Returns the lowest value for each series in a numeric column.
This function differs from the FLOOR function in that MIN is not rounded whereas FLOOR is rounded. | `MIN(`Operating Budget`)` |
| `STDDEV_POP` | Returns the population standard deviation for each series in a numeric column. | `STDDEV_POP(`Values`)` |
| `SUM` | Returns the sum of each series in a numeric column. | `SUM(`Values`)` |
| `SUM (DISTINCT)` | Returns the sum of unique values in a numeric column. | `SUM(DISTINCT `Values`)` |
| `VAR_POP` | Returns the population standard variance for each series in a numeric column. | `VAR_POP(`Values`)` |


For information about using aggregate functions in summary numbers, see [Applying a calculation to a summary number](/s/article/360043429913 "Adding a Beast Mode Calculation to Your Chart").


### Mathematical functions




| Function Name | Description | Example |
| --- | --- | --- |
| `ABS` | Returns the absolute value for all values in a numeric column.
In other words, any negative values become positive, and positive values stay the same. This is valuable when you want to see aggregation without considering positive and negative values. | `ABS(`Operating Budget`)` |
| `MOD` | Returns the remainder of each value in a numeric column divided by some specified number (dividend). | `MOD(`Values`,2)` |
| `POWER` | Returns each value in a numeric column raised to a given power. If the column contains multiple series, the values are summed for each series. | `POWER(`Values`,2)` |
| `RAND` | Returns random values between 0 and 1. | `RAND(`Values`)` |
| `ROUND` | Returns values in a numeric column rounded to the nearest specified decimal place.
If you do not include a decimal place value in the function, returned values are rounded to the nearest whole number. | `ROUND(`Values`,1)` |


### Logical functions




| Function Name | Description | Example |
| --- | --- | --- |
| `CASE` | Use to begin logical statements in which the value of data is replaced when certain criteria is reached (when...then or when...then, else). These statements use the following format:`CASE `Value` when *x* then 'resultx' else 'resulty' End`
or 
`CASE when `Value`=*x* then 'resultx' else 'resulty' End`
In other words, when the data in the "Value" column equals number *x*, value *resultx* is returned; otherwise value *resulty* is returned. (The value returned can be either a single-quoted string or a number.)
For multiple conditional statements, use the following format:`CASE when `Value`=*x* then 1 when `Value`=*y* then 2 end`
Although valid, avoid using the following inefficient format:`CASE when `Value`=*x* then 1 else CASE when `Value`=*y* then 2 end end`
**IN Operator**In a CASE when clause, you can use the IN operator, which lets you specify multiple values to evaluate.``column_name` IN (value1,value2,...)``CASE when `State` in ('NY', 'TX') then 0 else 1 end`
**LIKE Operator**In a CASE when clause, you can use the LIKE operator, which lets you search for a specified pattern in a column.``column_name` LIKE pattern`
`CASE when `State` like '%TX%' or `State` like '%NY' then 0 else 1 end`You can use these wildcards with the LIKEoperator:* `%` to match any number of characters, even zero characters.`like '%TX%'`
* `_` to match exactly one character.`like '_hn%'`

Values for the LIKE operator are matched in order of the WHEN statements. For example, if a value in the data matches the first and fourth LIKE operators, it is applied to the first operation.  | `CASE when `Amount`=1 then 10 else 0 End`
`CASE `Gender` when 'M' then 'Male' when 'F' then 'Female' end​`
`CASE when `Pennies` >= 600 then 'Large' when `Pennies` <= 300 then 'Small' else `Pennies` end​`
  |
| `IFNULL` | Used in logical statements in which you want to specify a replacement for null values. | `IFNULL(`Values`,0)` |
| `NULLIF` | Returns null if the value in the first column equals the value in the second column; otherwise returns the value in the first column. | `NULLIF(`Value 1`,`Value 2`)` |


**Video - Case Statement Overview**



 


 


### String functions




| Function | Description | Example |
| --- | --- | --- |
| `CONCAT` | Combines strings from two or more string columns. | `CONCAT(`First Name`,' ',`Last Name`)` |
| `INSTR` | Returns the position of the first instance of a specified string in a given column, starting from the first letter in the name.
In the example at right, the calculation would return the position of the first instance of the letter "e" in each string in the column.   | `INSTR(`Group`,'e')` |
| `LEFT` | Returns the specified number of characters in each string in the the given column, starting from the left.  | `LEFT(`Group`,3)` |
| `LENGTH` | Returns the number of characters in each string in the given column.  | `LENGTH(`Group`)` |
| `LOWER` | Converts strings from one or more string columns into lower-case. | `LOWER(`Product Type`)` |
| `REPLACE` | Replaces all of the specified strings in a given column with another specified string.  | `REPLACE(`Department`,'Human Resnources','Human Resources')` |
| `RIGHT` | Returns the specified number of characters in the given column, starting from the right.  | `RIGHT(`Group`,3)` |
| `SUBSTRING` | Extracts and returns a specified number of characters from the values in a string column.
You specify the characters to return by indicating the starting position and the length of characters. For example, specifying the position as 1 and the length as 3 would return the first, second, and third characters for values in the column. | `SUBSTRING(`Employee Name`,1,3)` |
| `TRIM` | Trims leading and trailing spaces for all values in string columns. | `TRIM(`Employee Name`)` |
| `UPPER` | Converts strings from one or more string columns into upper-case. | `UPPER(`Customers`)` |


### Date and Time functions




| Function | Description | Example |
| --- | --- | --- |
| `ADDDATE` | Adds date or datetime values (as intervals) to date values in a date column.
You can specify the date or datetime values to add to date values in a date column by specifying the column, interval, expression, and unit, as in ADDDATE(`*datecolumn*`, interval *expr* *unit*) where *datecolumn* is the column containing a date value, where *expr* is the argument containing the date or datetime value to add, and where *unit* is the string value for the corresponding date or datetime unit type.
You can prefix the expression with a "-" to subtract the value. Specify the unit value (such as second, minute, hour, day, week, month, quarter, year). (The "interval" keyword and unit type values are case insensitive.) For more information, see [Unit type values in Beast Mode.](/s/article/360043429953 "Date Format Specifier Characters in Beast Mode")
For example, adding 12 days to January 4 would return January 16.
Same as DATE\_ADD. | `ADDDATE(`DateCol`, interval 12 day)` |
| `ADDTIME` | Adds a specified number of seconds to all values in a time column. For example, adding 15 seconds to 8:05 would return 8:20. | `ADDTIME(`Time`,25)` |
| `CURDATE` | Returns the current date.
No column name is specified in this function.
Same as CURRENT\_DATE. | `CURDATE()` |
| `CURTIME` | Returns the current time.
No column name is specified in this function.
Same as CURRENT\_TIME. | `CURTIME()` |
| `CURRENT_DATE` | Returns the current date.
No column name is specified in this function.
Same as CURDATE. | `CURRENT_DATE()` |
| `CURRENT_TIME` | Returns the current time.
No column name is specified in this function.
Same as CURTIME. | `CURRENT_TIME()` |
| `CURRENT_TIMESTAMP` | Returns the value of current date and time in YYYY-MM-DD HH:MM:SS format.
No column name is specified in this function.
Same as NOW. | `CURRENT_TIMESTAMP()` |
| `DATE` | Extracts and returns the dates from datetime values. | `DATE(`DateCol`)` |
| `DATEDIFF` | Returns the number of days between two dates from datetime values. | `DATEDIFF(CURRENT_DATE(), `lastmoddate`)` |
| `DATE_ADD` | Adds date or datetime values (as intervals) to date values in a date column.
You can specify the date or datetime values to add to date values in a date column by specifying the column, interval, expression, and unit, as in DATE\_ADD(`*datecolumn*`, interval *expr* *unit*) where *datecolumn* is the column containing a date value, where *expr* is the argument containing the date or datetime value to add, and where *unit* is the string value for the corresponding date or datetime unit type.
You can prefix the expression with a "-" to subtract the value. Specify the unit value (such as second, minute, hour, day, week, month, quarter, year). (The "interval" keyword and unit type values are case insensitive.) For more information, see [Unit type values in Beast Mode](/s/article/360043429953 "Date Format Specifier Characters in Beast Mode").
For example, adding 12 days to January 4 would return January 16.
Same as ADDDATE. | `DATE_ADD(`DateCol`, interval 12 day)` |
| `DATE_FORMAT` | Formats dates in a date/time column into a specific format.





**Note:**Beast Mode uses SQL-like date and time formats.



You can specify the format to use for a date or time column by specifying the column and the date or time string, as in DATE\_FORMAT(`*datecolumn*`,'*format*') where *datecolumn* is the column containing a date value and where *format* is the string containing specifier characters to use in formatting the date value.
The "%" character is required before format specifier characters.
For example, using DATE\_FORMAT(`MyDate`,'%Y-%m-%d %h:%i %p'), the date in the *MyDate* date column uses this format: 2013-04-17 10:10 AM.
For information about specifier characters, see [Date Format Specifier Characters in Beast Mode](/s/article/360043429953 "Date Format Specifier Characters in Beast Mode").
Similar to TIME\_FORMAT. | `DATE_FORMAT(`DateCol`,'%y')``DATE_FORMAT(`DateCol`,'%m/%d')``DATE_FORMAT(NOW(),'%d %b %Y %T')``DATE_FORMAT(STR_TO_DATE(`DateCol`, '%m,%d,%Y'), '%m/%d/%Y')``ADDDATE(DATE_FORMAT(`DateCol`, '%Y-%m-%d'), interval 12 day)``PERIOD_DIFF(DATE_FORMAT(CURDATE(), '%Y%m'), DATE_FORMAT(`DateCol`, '%Y%m'))` |
| `DATE_SUB` | Subtracts date or datetime values (as intervals) to date values in a date column.
You can specify the date or datetime values to subtract from date values in a date column by specifying the column, interval, expression, and unit, as in DATE\_SUB(`*datecolumn*`, interval *expr* *unit*) where *datecolumn* is the column containing a date value, where *expr* is the argument containing the date or datetime value to subtract, and where *unit* is the string value for the corresponding date or datetime unit type.
You can prefix the expression with a "-" to add the value. Specify the unit value (such as second, minute, hour, day, week, month, quarter, year). (The "interval" keyword and unit type values are case insensitive.) For more information, see [Unit type values in Beast Mode](/s/article/360043429953 "Date Format Specifier Characters in Beast Mode").
For example, subtracting 12 days from January 24 would return January 12.
Same as SUBDATE. | `DATE_SUB(`DateCol`, interval 12 day)` |
| `DAY` | Returns the numerical day of the month for all values in a date/time column.
Same as DAYOFMONTH. | `DAY(`DateCol`)` |
| `DAYNAME` | Returns the name of the day of the week for all values in a date/time column. | `DAYNAME(`DateCol`)` |
| `DAYOFMONTH` | Returns the numerical day of the month for all values in a date/time column.
Same as DAY. | `DAYOFMONTH(`DateCol`)` |
| `DAYOFWEEK` | Returns the numerical day of the week for all values in a date/time column (e.g. "2" for "Monday"). | `DAYOFWEEK(`DateCol`)` |
| `DAYOFYEAR` | Returns the numerical day of the year for all values in a date/time column (e.g. "226" for the 226th day of the year). | `DAYOFYEAR(`DateCol`)` |
| `FROM_DAYS` | Converts day numbers into dates. | `FROM_DAYS(`DateCol`)` |
| `FROM_UNIXTIME` | Returns a UNIX datetime value from a UNIX date/time column using the specified format.
For information about specifier characters, see [Date Format Specifier Characters in Beast Mode](/s/article/360043429953 "Date Format Specifier Characters in Beast Mode"). | `FROM_UNIXTIME(`UnixDateCol`,'%Y %d %m %h:%i:%s %x')` |
| `HOUR` | Returns the hour for all values in a date/time column (e.g. the time "3:36" would return "3"). | `HOUR(`Time`)` |
| `LAST_DAY` | Aggregates values for each month in a date/time column and returns each aggregation as the last day of each month.
For example, if a date/time column had "15," "16," and "17" as values for January, only the last given date of January would appear, with a combined value of 48. | `LAST_DAY(`DateCol`)` |
| `MINUTE` | Returns the value for each minute in a time column.
If there is more than one instance of a particular minute in the column, the values for those minutes are aggregated. | `MINUTE(`Time`)` |
| `MONTH` | Returns the month number (e.g. "9" for September) for all values in a date/time column. | `MONTH(`DateCol`)` |
| `MONTHNAME` | Returns the name of the month (e.g. "September" rather than "9") for all values in a date/time column. | `MONTHNAME(`DateCol`)` |
| `NOW` | Returns the value of current date and time in YYYY-MM-DD HH:MM:SS format.
No column name is specified in this function.
Same as CURRENT\_TIMESTAMP. | `NOW()` |
| `PERIOD_ADD` | Adds the specified number of months to the values in a date column. For this to work, the date values must be months in the format YYYYMM. | `PERIOD_ADD(`Month`,6)` |
| `PERIOD_DIFF` | Returns the number of months between months in two date columns.
For this to work, the date values must be months in the format YYYYMM. For example, if one column contained the date value 200803 and another contained the value 200809, this function would return 6. | `PERIOD_DIFF(201309,201301)``PERIOD_DIFF(`Month 1`, `Month 2`)``PERIOD_DIFF(DATE_FORMAT(CURDATE(), '%Y%m'), DATE_FORMAT(`DateCol`, '%Y%m'))` |
| `QUARTER` | Aggregates date value data into quarters in a year. | `QUARTER(`DateCol`)` |
| `SECOND` | Returns the value for each second in a time column. If there is more than one instance of a particular second in the column, the values for those seconds are aggregated. | `SECOND(`Time`)` |
| `SEC_TO_TIME` | Converts seconds into hours, minutes, and seconds. For example, 3489 would be converted into 00:58:09.





**Note:** The sec\_to\_time function is limited to 24 hours. When a value is greater than 24 hours, it will overflow and loop back to 0 hours.


 | `SEC_TO_TIME(`Seconds`)` |
| `STR_TO_DATE` | Converts strings (that Domo does not recognize as dates) from one or more string columns into datetime values. You specify the column(s) and the current date format used in those columns.
By default, datetime values are returned in the output format %m-%d-%Y. You can change the output format by enclosing your STR\_TO\_DATE calculation in a DATE\_FORMAT calculation that specifies the date format specifier characters you want.
For information about specifier characters, see [Date Format Specifier Characters in Beast Mode](/s/article/360043429953 "Date Format Specifier Characters in Beast Mode"). | `STR_TO_DATE(`DateCol`,'%m,%d,%Y')``DATE_FORMAT(STR_TO_DATE(`DateCol`, '%m,%d,%Y'), '%m/%d/%Y')` |
| `SUBDATE` | Subtracts date or datetime values (as intervals) to date values in a date column.
You can specify the date or datetime values to subtract from date values in a date column by specifying the column, interval, expression, and unit, as in SUBDATE(`*datecolumn*`, interval *expr* *unit*) where *datecolumn* is the column containing a date value, where *expr* is the argument containing the date or datetime value to subtract, and where *unit* is the string value for the corresponding date or datetime unit type.
You can prefix the expression with a "-" to add the value. Specify the unit value (such as second, minute, hour, day, week, month, quarter, year). (The "interval" keyword and unit type values are case insensitive.) For more information, see [Unit type values in Beast Mode](/s/article/360043429953 "Date Format Specifier Characters in Beast Mode").
For example, subtracting 12 days from January 24 would return January 12. Same as DATE\_SUB. | `SUBDATE(`DateCol`, interval 12 day)` |
| `SUBTIME` | Subtracts a specified number of seconds from all values in a time column.
For example, subtracting 30 seconds from 8:05:45 would return 8:05:15. | `SUBTIME(`Time`,15)` |
| `SYSDATE` | Returns the current date and time in YYYY-MM-DD HH:MM:SS format, as in 2014-04-03T19:25:29.
No column name is specified in this function.
Similar to CURRENT\_DATE and CURRENT\_TIME. | `SYSDATE()` |
| `TIME` | Extracts the times from datetime values. | `TIME(`DateCol`)` |
| `TIMEDIFF` | Returns the difference between values in two date/time columns, expressed as a time value. | `TIMEDIFF(`Time 1`,`Time 2`)` |
| `TIMESTAMP` | Returns values in a date column as datetime values. | `TIMESTAMP(`DateCol`)` |
| `TIME_FORMAT` | Formats time in a datetime column into a specific format.





**Note:**Beast Mode uses SQL-like date and time formats. 



You can specify the format to use for time values in a time column by specifying the column and the time string, as in TIME\_FORMAT(`*datetimecolumn*`,'*format*') where *datetimecolumn* is the column containing a time value and where *format* is the string containing specifier characters to use in formatting the time value.





**Note:**The format specifiers used in DATE\_FORMAT may be used with TIME\_FORMAT, but specifiers other than hours, minutes, seconds and microseconds produce a NULL value or 0.  



The "%" character is required before format specifier characters.
For example, using TIME\_FORMAT(`Date`,'%h:%i:%s'), the date in the transformed time column uses this format: 12:20:12.
For information about specifier characters, see [Date Format Specifier Characters for Beast Mode](/s/article/360043429953)
Similar to DATE\_FORMAT. | `TIME_FORMAT(`Date`,'%h:%i:%s')``TIME_FORMAT(NOW(),'%h:%i:%s')` |
| `TIME_TO_SEC` | Returns an elapsed number of seconds for all values in a date/time column. | `TIME_TO_SEC(`DateCol`)` |
| `TO_DAYS` | Returns the number of days since year 0 for all values in a date/time column. For example, the date "01-06-2010" would be returned as "734143," since 734,143 days have transpired between that date and January 1st of year 0. | `TO_DAYS(`DateCol`)` |
| `UNIX_TIMESTAMP` | Returns UNIX time stamps for all values in a date/time column. | `UNIX_TIMESTAMP(`DateCol`)` |
| `WEEK` | Returns the week number for each value of the indicated date or date-time column.
Syntax: WEEK(`dateCol`, mode).
For a Sunday-Saturday week frame, use mode 11: WEEK(`dateCol`, 11).
For a Monday-Sunday week frame, use mode 22: WEEK(`dateCol`, 22).  | `WEEK(`DateCol`,22)` |
| `YEAR` | Returns the year for all values in a date/time column. | `YEAR(`DateCol`)` |
| `YEARWEEK` | Returns the year and week number for each value of the indicated date or date-time column in "YYYYWW" format. For example, a date in the 5th week of the year 2020 will return "202005".
Syntax: YEARWEEK(`dateCol`, mode) 
For a Sunday to Saturday week frame, use mode 11: YEARWEEK(`dateCol`, 11). 
For a Monday to Sunday week frame, use mode 22: YEARWEEK(`dateCol`, 22). | `YEARWEEK(`DateCol`,11)` |


Unsupported functions
---------------------


The following functions are no longer supported: `SQRT`, `CONVERT_TZ`, `MICROSECOND` , `WEEKDAY`

