---
title: Starting, Stopping, and Restarting the Workbench 5.1 Service
url: https://domo-support.domo.com/s/article/4407023720343
linked_kbs:  ['[https://domo-support.domo.com/s/knowledge-base/](https://domo-support.domo.com/s/knowledge-base/)', '[https://domo-support.domo.com/s/](https://domo-support.domo.com/s/)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZammGAC](https://domo-support.domo.com/s/topic/0TO5w000000ZammGAC)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZaoPGAS](https://domo-support.domo.com/s/topic/0TO5w000000ZaoPGAS)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZapUGAS](https://domo-support.domo.com/s/topic/0TO5w000000ZapUGAS)', '[https://domo-support.domo.com/s/article/4407022160791](https://domo-support.domo.com/s/article/4407022160791)', '[https://domo-support.domo.com/s/article/4407032210199](https://domo-support.domo.com/s/article/4407032210199)', '[https://domo-support.domo.com/s/article/4407023720343](https://domo-support.domo.com/s/article/4407023720343)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZapUGAS/workbench-51](https://domo-support.domo.com/s/topic/0TO5w000000ZapUGAS/workbench-51)', '[https://domo-support.domo.com/s/article/360043429933](https://domo-support.domo.com/s/article/360043429933)', '[https://domo-support.domo.com/s/article/360043429953](https://domo-support.domo.com/s/article/360043429953)', '[https://domo-support.domo.com/s/article/360042925494](https://domo-support.domo.com/s/article/360042925494)', '[https://domo-support.domo.com/s/article/4408174643607](https://domo-support.domo.com/s/article/4408174643607)', '[https://domo-support.domo.com/s/article/360043429913](https://domo-support.domo.com/s/article/360043429913)', '[https://domo-support.domo.com/s/login/](https://domo-support.domo.com/s/login/)']
article_id: 000004852
views: 2,160
created_date: 2022-10-24 22:32:00
last updated: 2022-10-24 22:40:00
---



The Workbench service starts up automatically after the machine starts Windows.


You can stop, start, or restart the Workbench service manually using the Windows system taskbar.




 


**Tip:**If a Workbench icon does *not* appear in the Windows system taskbar, click **Start > Domo > Workbench Monitor**.



For information about running the Workbench application, see [Running Workbench 5.1](/s/article/4407022160791).


**To manually start, stop, or restart the Workbench service,**


1. In the Windows system taskbar, right-click the Workbench service icon.  
A menu appears.
2. Select **Service**, then click the option you want (**Start**, **Stop**, or **Restart**).


For information about the controls and field settings in Workbench, see [Understanding the Workbench 5.1 User Interface](/s/article/4407032210199 "Understanding the Workbench 5 User Interface").

