---
title: Adding an Account in Workbench 4
url: https://domo-support.domo.com/s/article/360047416513
linked_kbs:  ['[https://domo-support.domo.com/s/knowledge-base/](https://domo-support.domo.com/s/knowledge-base/)', '[https://domo-support.domo.com/s/](https://domo-support.domo.com/s/)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZammGAC](https://domo-support.domo.com/s/topic/0TO5w000000ZammGAC)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZaoPGAS](https://domo-support.domo.com/s/topic/0TO5w000000ZaoPGAS)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZapSGAS](https://domo-support.domo.com/s/topic/0TO5w000000ZapSGAS)', '[https://domo-support.domo.com/s/article/360042932634](https://domo-support.domo.com/s/article/360042932634)', '[https://domo-support.domo.com/s/article/360047416513](https://domo-support.domo.com/s/article/360047416513)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZapSGAS/workbench-4](https://domo-support.domo.com/s/topic/0TO5w000000ZapSGAS/workbench-4)', '[https://domo-support.domo.com/s/article/360043429933](https://domo-support.domo.com/s/article/360043429933)', '[https://domo-support.domo.com/s/article/360043429953](https://domo-support.domo.com/s/article/360043429953)', '[https://domo-support.domo.com/s/article/360042925494](https://domo-support.domo.com/s/article/360042925494)', '[https://domo-support.domo.com/s/article/4408174643607](https://domo-support.domo.com/s/article/4408174643607)', '[https://domo-support.domo.com/s/article/360043429913](https://domo-support.domo.com/s/article/360043429913)', '[https://domo-support.domo.com/s/login/](https://domo-support.domo.com/s/login/)']
article_id: 000004789
views: 2,146
created_date: 2022-10-24 22:30:00
last updated: 2022-10-24 22:42:00
---








**Important:** Support for Workbench 4 ended on **April 15, 2021**. Workbench may continue to run on installed machines, but it will no longer receive feature enhancements and security updates. When issues are encountered in Workbench 4, the recommended course of action from the Domo Support team will be to upgrade to the latest version of Workbench 5. To see this article for Workbench 5, click [**here**](/s/article/360042932634).



When you first install Workbench 4 on your machine, you connect to a Domo server as part of the installation process. This server account becomes your primary account in Workbench 4, and any DataSet Jobs you create are included in this account. However, you can add accounts for other Domo servers to your Workbench if you want. You do this in the **Add Domo Account** wizard. 


**To add an account in Workbench 4,**


1. Click **Add New** in the **Accounts** grouping in the Buttons toolbar at the top of the Workbench window.  
This opens the **Add Domo Account** wizard.
2. In the **Domo Server** field, enter the URL for the Domo server you want to connect to, then click **Next**.
3. Enter your username and password for connecting to the Domo server, then click **Next**.
4. In the dropdown, select the agent owner for this Domo server, then click **Next**.
5. Click **Finish**.


Your new account is now active and ready for DataSet Jobs to be added.

