---
title : SAP Adaptive Server Enterprise Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:39:00
url : https://domo-support.domo.com/s/article/360043436293
linked_kbs :  ['https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043439173', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360043436293', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003882
views : 3,949
created_date : 2022-10-24 21:16:00
last updated : 2022-10-24 22:39:00
---



Intro
-----


SAP ASE (Adaptive Server Enterprise), formerly known as Sybase SQL Server, is a relational model database server product for businesses. To learn more about SAP Adaptive Server Enterprise, visit their page ([https://www.sap.com/products/sybase-ase.html#](https://www.sap.com/products/sybase-ase.html# "https://www.sap.com/products/sybase-ase.html#")).


You connect to your SAP Adaptive Server Enterprise account in the Data Center. This topic discusses the fields and menus that are specific to the SAP Adaptive Server Enterprise connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).


Prerequisites
-------------


To connect to your SAP Adaptive Server Enterprise account and create a DataSet, you must have the following:



* The username and password you use to log into your SAP Adaptive Server Enterprise account
* The host name for the database
* The port number for the database
* The database name


CA certificate text or URL path is requiredÂ *only*Â if you selectÂ **Certificate text**Â orÂ **URL path**,Â respectively, in theÂ **Certificate type**Â menu.


Before you can connect to an SAPÂ database, you must also whitelist a number of IP addresses on your database server on theÂ portÂ you want to connect to. For the full list of IP addresses, see [Whitelisting IP Addresses for Connectors](..\whitelisting_ip_addresses_in_domo\index.html "Whitelisting IP Addresses for Connectors").


Connecting to Your SAP Adaptive Server Enterprise Account
---------------------------------------------------------


This section enumerates the options in the **Credentials** and **Details** panes in the SAP Adaptive Server Enterprise Connector page.Â The components of the other panes in this page, **Scheduling**Â and **Name & Describe Your DataSet**, are universal across most connector types and are discussed in greater length inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md "Adding a DataSet Using a Data Connector").


### Credentials Pane


This pane contains fields for entering credentials to connect to your SAP Adaptive Server Enterprise account. The following table describes what is needed for each field: Â 




| Field | Description |
| --- | --- |
| Username | Enter your SAP Adaptive Server Enterprise account username. |
| Password | Enter your SAP Adaptive Server Enterprise account password. |
| Host | Enter the host name for the SAP database. For example: [db.company.com](http://db.company.com) |
| Port | Enter the port number for the database. |
| Certificate | Paste the text for your CA certificate or enter the URL where your certificate is located.Â This is optional. If you do not want to include a certificate, select **No certificate** in the **Certificate Type** menu. |
| Certificate TypeÂ  | Select a certificate type. If you do not want to include a certificate, selectÂ **No certificate**. If you selectÂ CertificateÂ text, you must paste the text for your certificate in theÂ **Certificate** field. If you selectÂ **URL path**, you must enter the URL where your certificate is located in theÂ **Certificate** field. Â Â  |
| Database | Enter the name of the database. |


Once you have entered valid SAP Adaptive Server Enterprise credentials, you can use the same account any time you go to create a new SAP Adaptive Server Enterprise DataSet. You can manage connector accounts in the **Accounts** tab in the Data Center. For more information about this tab, see [Managing User Accounts for Connectors.](..\managing_user_accounts_for_connectors\index.md)


### Details Pane


In this pane you create an SQL query to pull data from your database. TheÂ **Query**Â parameter is required. The other three parameters are here to help you construct this query if you choose.




| Menu | Description |
| --- | --- |
| Query | Enter the Structured Query Language (SQL) query to use in selecting the data you want. For example:
select \* from Employee
If you want help in constructing your query, do the following:1. Select the desiredÂ table and columns in theÂ **Database Table**Â andÂ **Table Columns**Â menus.  Your query is constructed in theÂ **Query Helper**Â field based on your selections.Â
2. Copy and paste the automatically generated query from theÂ **Query Helper**Â field into theÂ **Query**Â field.
 |
| Database Table (Optional) | Select the table containing the data you want to pull into Domo. The selected table will be added to the automatically generated query in theÂ **Query HelperÂ**field.Â  |
| Table Columns (Optional) | Select the table columns with data you want to pull into Domo.Â The selected columnsÂ will be added to the automatically generated query in theÂ **Query HelperÂ**field.Â  |
| Query Helper (Optional) | Copy and paste this query into theÂ **Query**Â field if you need help building a query. This query is automatically generated when you select a table and columns in theÂ **Database Table**Â and **Table Columns**Â fields, respectively. |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, seeÂ [AddingÂ a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).