---
title : Deprecated Chart Properties
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:40:00
url : https://domo-support.domo.com/s/article/360051709994
linked_kbs :  ['https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360051709994', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000004649
views : 2,040
created_date : 2022-10-24 22:18:00
last updated : 2022-10-24 22:40:00
---



The following chart properties have been deprecated. Note that for properties you applied by checking a box, if you applied the property before it became deprecated, the property still appears in your Chart Properties and is checked. However, if you uncheck the box and then resave the chart, the option is no longer available. 




| Property | Description |
| --- | --- |
| Legend Position | Determined whether legends appear above or below certain charts, if at all.  |
| Zero Line Width (for Bubble and Scatter Plot graphs) | Determined the width of the "zero line" on most single-axis charts, in pixels. |
| Show Data Label | Turned on data labels for most chart types. |
| Show One Label | Turned on a "total" label for vertical Stacked Bar charts. This has been replaced by the **Show Total Label** property, which is available for vertical as well as horizontal Stacked Bar charts.  |
| Disable Interactivity | Turned off interactivity in many chart types. |
| Title Position | Determined whether value scale labels in some types of Vertical Bar charts appeared to the left of the chart or above it. |
| Use Legacy Funnel  | When this box was checked, the legacy version of the Funnel graph was used. This version showed both value and percent columns in the legend, and percentages for each layer in the legend were derived from the total value of the chart, *not* from the previous layer. |
| Allow Wide Bars | Determined whether the bar in a Vertical Bar graph with a single bar used the full width of the available space. If this box was checked, the bar took up all of the space in the graph. Otherwise, a normal-sized bar appeared in the center of the chart space.  |
| Allow Tall Bars | Determined whether the bar in a Horizontal Bar graph with a single bar used the full height of the available space. If this box was checked, the bar took up all of the space in the graph. Otherwise, a normal-sized bar appeared in the center of the chart space.  |
| Series 1-16 | Let you specify custom colors for up to sixteen series in most kinds of graphs. With the Analyzer release in August 2017, these properties have been replaced by the "Color Rules" functionality. For more information, see [Setting Color Rules for a Chart](https://domohelp.domo.com/Visualize/Adding_Cards_to_Domo/KPI_Cards/KPI_Card_Building_Part_2:_The_Analyzer/Setting_Color_Rules_for_a_Chart "Setting Color Rules for a Chart") . |
| Minimum Value | Let you set the minimum value on a scale marker range. Replaced by "Lower Value."  |
| Maximum Value | Let you set the maximum value on a scale marker range. Replaced by "Upper Value."  |
| Show Lines | Determined whether red dotted lines demarcated the minimum and maximum values of your scale marker range. |
| Fill Outliers | Determined whether outliers were filled in when scale markers were set. |