---
title : Owler Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:40:00
url : https://domo-support.domo.com/s/article/360043435933
linked_kbs :  ['https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043435933', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003318
views : 2,012
created_date : 2022-10-24 21:12:00
last updated : 2022-10-24 22:40:00
---



**Important:**Â The OwlerÂ Fortune 500 public DataSet will no longer be available for use after September 2, 2019. Customers using this data will need to create their own DataSets using the Owler Connector and their personal Owler account.Â
Intro
-----


OwlerÂ crowdsourcesÂ business insightsÂ by providing news alerts, company profiles, and polls and allows members to follow, track, and research companies in real time. Use Domo'sÂ OwlerÂ connector to retrieve company and competitor data as well as feeds for selected companies. To learn more about the OwlerÂ API, visit their page ([https://developers.owler.com/](https://developers.owler.com/ "https://developers.owler.com/")).  


You connect to your Owler account in the Data Center. This topic discusses the fields and menus that are specific to the Owler connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).


Prerequisites
-------------


To connect to your Owler account and create a DataSet, you must have an Owler API key. For information about obtaining an API key, reach out to your OwlerÂ representative.


Connecting to Your Owler Account
--------------------------------


This section enumerates the options in the **Credentials** and **Details** panes in the Owler Connector page.Â The components of the other panes in this page, **Scheduling**Â and **Name & Describe Your DataSet**, are universal across most connector types and are discussed in greater length inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md "Adding a DataSet Using a Data Connector").


### Credentials Pane


This pane contains fields for entering credentials to connect to your Owler account. The following table describes what is needed for each field: Â 




| Field | Description |
| --- | --- |
| API Key | Enter your Owler API key. |


Once you have entered valid Owler credentials, you can use the same account any time you go to create a new Owler DataSet. You can manage connector accounts in the **Accounts** tab in the Data Center. For more information about this tab, see [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


### Details Pane


This pane contains a primaryÂ **Reports**Â menu, along with various other menus which may or may not appear depending on the report type you select.




| Menu | Description |
| --- | --- |
| Report | Select the Owler report you want to run.Â The following reports are available:

|  |  |
| --- | --- |
| Company Search | Returns the top 30 companies most likely to match your search criteria. |
| Company Detail | Returns detailed information for the selected companies. |
| Competitors | Returns competitor information for the selected companies. |
| Feeds | Returns the top 10 feeds for the selected companies. |

 |
| Search Filter | Select the type of filter you want to apply to your report. You then enter the actual search term in theÂ **Search**Â field. For example, if you wanted to filter on the company name "Kablinko," you would selectÂ **NameÂ**as your search filter type then enter Kablinko in theÂ **Search**Â field. |
| Search | Enter the term you want to retrieve information for in your report. Make sure you select the matching filter type in theÂ **Search FilterÂ**menu.Â For example, if you wanted to filter on the company name "Kablinko," you would selectÂ **NameÂ**in theÂ **Search Filter**Â menuÂ then enter Kablinko in theÂ **Search**Â field. |
| Input Type | Select how you would like to input company data to search for. If you selectÂ **Manual Entry**, you areÂ prompted to enter the IDs for all companies you want to retrieve information for. If you selectÂ **Search**, you are prompted to enter a search term to filter by. If you selectÂ **Fortune 500**, data is returned for Fortune 500 companies.Â Â  |
| Company IDs | Enter a comma-separated list of IDs for companies you want to retrieve information for. |
| Sub Report | Select a sub report, eitherÂ **Industries**,Â **Funding**, orÂ **Acquisition**. If you do not want a sub report, selectÂ **None**. |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, seeÂ [AddingÂ a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).