---
title : Available Filter Charts
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:42:00
url : https://domo-support.domo.com/s/article/360043428973
linked_kbs :  ['https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042923894', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042923914', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043428973', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000004729
views : 4,525
created_date : 2022-10-24 22:26:00
last updated : 2022-10-24 22:42:00
---



**Video - Filter Chart Types**



The following table lists the types of Filter charts available in Domo.




| Chart Type | Description | Example |
| --- | --- | --- |
| Slicer Card
slicer-small.png | Slicer Cards displayÂ values from a selected DataSet column. When you add themÂ to a Card Page in Domo, users visiting that Page can click on one or more values to filter the other Cards in the Page. For example, you could build a Slicer Card with names of U.S. states and add it to a Card Page. If you then clicked "Texas" and "Oklahoma," all of the Cards in the Page would be filtered to show only data for those states.
For more information about creating Slicer Cards, see [Applying Page-Level Filters](/s/article/360042923894 "Slicer Card"). | slicer_edit.gif |
| Checkbox Card
checkbox-small.png | Checkbox Cards are almost exactly the same as Slicer Cards (see above) but use checkboxes instead of buttons for filtering. As with Slicer Cards, you can filter on multiple values when you use Checkbox Cards.Â 
For more information about creating Slicer Cards, see [Applying Page-Level Filters](/s/article/360042923894 "Slicer Card").Â  Â  | checkbox.gif |
| Radio Button Card
radio-button-small.png | Radio Button Cards are similar to Slicer and Checkbox Cards (see above). The key difference is that while Slicer and Checkbox Cards allow you to set multiple filters at once, with Radio Button Cards only one filter may be set at a time.
For more information about creating Slicer Cards, see [Applying Page-Level Filters](/s/article/360042923894 "Slicer Card").Â  Â  | radio_buttons.gif |
| Range Card
range-small.png | Range Cards display a slider with a minimum and maximum value. When you add a range Card to a Card Page in Domo, users visiting that Page can use the slider buttons to narrow the range between the minimum and maximum values.Â All other Cards in the Page then filter to show the data for the newly selected range.Â 
For more information about creating Range Cards, see [Applying Page-Level Filters](/s/article/360042923894 "Range Card").Â  Â  | range.gif |
| Date Selector Card
date-selector-small.png | Date SelectorÂ Cards display a calendar-style range of dates. When you add themÂ to a Card Page in Domo, users visiting that Page can select a range of dates from the calendar as a filter. Alternatively, they can choose from a number of preset date filters such as "Last year," "Last 2 months," etc. The date filter you choose is applied to all other Cards on the Page. For example, if you selected all dates from April 1st to July 31st on the calendar, all other Cards in the Page would be filtered to show just the data for these dates.Â 
For more information about creating Date Selector Cards, see [Applying Page-Level Filters](/s/article/360042923894).Â  Â Â  | date_selector.gif |
| Dropdown Selector CardDropdown.png | Dropdown Selector Cards display values from a selected DataSet column. When you add them to a Dashboard in Domo, users visiting that Dashboard can click on values to filter the other Cards on the Dashboard. You can set up the Dropdown Selector Card to filter on a single value or multiple values at once.
For more information about creating Dropdown Selector Cards, see [Applying Page-Level Filters](..\applying_pagelevel_filters_with_filter_views\index.md). | Dropdown_Selector_Example.gif |


Â