---
title : CSV SFTP Pull Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:40:00
url : https://domo-support.domo.com/s/article/360042931894
linked_kbs :  ['https://domo-support.domo.com/s/article/360043436513', 'https://domo-support.domo.com/s/article/360042932554', 'https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042931914', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/article/360042931894', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043630093', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003946
views : 4,524
created_date : 2022-10-24 21:17:00
last updated : 2022-10-24 22:40:00
---



Intro
-----


A character-separated values (CSV) file stores tabular data in plain text form. Domo provides two connectors that allow you to access CSV files you have uploaded to an SFTPÂ (Secure File Transfer Protocol) server:



* The Domo CSV SFTPÂ Pull connector (formerly called the "CSV-SFTP" connector) allows you to access CSV files that you have uploaded to your own SFTP server.
* The Domo CSV SFTP Push connector allows you to capture and process CSV files that have been uploaded to Domo's own SFTP. With this connector, Domo gives you credentials, then you push your data to Domo.Â


This article discusses the CSV SFTPÂ Pull connector. For information about the CSV SFTP Push connector, visitÂ [CSV SFTP Push Connector](..\csv_sftp_push_connector\index.html "CSV SFTP Push Connector").Â 


If you need to access files located on a directory, use the [CSV Advanced](..\csv_advanced_connector\index.html "CSV Advanced Connector") connector.Â 


The CSV SFTPÂ Pull connector isÂ aÂ "File" connector, meaning itÂ retrieves files and outputÂ them to Domo. In the Data Center, you can access the connector page for thisÂ and other File connectors by clicking **File** in the toolbar at the top of the window.


You connect to CSV files in the Data Center. This topic discusses the fields and menus that are specific to theÂ CSV connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


Prerequisites
-------------


You must have an SFTP host name and a username and password to authenticate to the SFTPÂ server.Â You also need to whitelist the appropriate IP addresses for your region. You can access the list of IP addresses, by region, inÂ [Whitelisting IP Addresses for Connectors & Federated Adapters.](..\allowlisting_ip_addresses_for_connectors__federated_adapters\index.md)


Connecting to CSV Files
-----------------------


This section enumerates the options in theÂ **Credentials** and **Details**Â panes forÂ theÂ CSV SFTPÂ Pull connector.Â The components of the other panes in this page,Â **Scheduling**Â andÂ **Name & Describe Your DataSet**, are universal across most connector types and are discussed in greater length inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


### Credentials Pane


This pane contains fields for entering credentials to connect to your SFTP server. The following table describes what is needed for each field:




| Field | Description |
| --- | --- |
| SFTP Host Name | Enter the name of the SFTP host you want to connect to. This *must* begin with sftp://. For example: s<ftp://hostname>. |
| UsernameÂ  | Enter the username you use toÂ authenticate to the SFTP server.Â  |
| PasswordÂ  | Enter the password you use to authenticate to the SFTP server.Â  |
| Head Start Row | Signifies the row where the header should start. |
| Data Start Row | signifies the row where the data should be fetched from the CSV file. |


Looking to upload a CSV file but do not have an SFTP server? Take a look atÂ our [Workbench solution](..\workbench_5_overview\index.html "Box Connector") available forÂ download in yourÂ Domo instance.


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, seeÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).


### FAQs


Â 


#### What kind of credentials do I need to power up this connector?


You need the username, password and host name of the SFTP server.


#### How does this connector handle the data?


The CSV-SFTP connector pulls the data from customer's SFTP server into Domo.


#### How often can the data be updated?


Data will update every hour.


#### Are there any API limits that I need to be aware of?


No