---
title : Oracle Database SSH Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:39:00
url : https://domo-support.domo.com/s/article/360043436253
linked_kbs :  ['https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043436253', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043630093', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003881
views : 4,050
created_date : 2022-10-24 21:16:00
last updated : 2022-10-24 22:39:00
---



Intro
-----


Oracle Database is an object-relational database management system produced and marketed by Oracle Corporation. You can use Domo's Oracle Database SSH Connector to pull data from your Oracle database via an SSH tunnel and compile custom reports. You indicate the data you want by inputting an SQL query.


You connect to Oracle DatabaseÂ in the Data Center. This topic discusses the fields and menus that are specific to the Oracle Database SSH connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).


Prerequisites
-------------


To connect to Oracle Database with SSH and create a DataSet, you must have the following:



* The username and password you use to log into your Oracle database
* The SID of the Oracle database
* The port number for the Oracle database
* The Oracle database hostname or IP address
* The SSH hostname or URL
* The SSH username and password
* The SSH port number
* The SSH private keyÂ


Before you can connect toÂ Oracle Database, you must also whitelist a number of IP addresses on your database server on theÂ portÂ you want to connect to. For the full list of IP addresses, seeÂ [Whitelisting IP Addresses for Connectors](..\allowlisting_ip_addresses_for_connectors__federated_adapters\index.html "Whitelisting IP Addresses for Connectors").


Â
**Note: Domo does not support the SSH keys generated using ssh-keygen. The SSH keys need to be the DES or RSA keys (in PEM format) generated by OpenSSL.**
Connecting to Oracle Database
-----------------------------


This section enumerates the options in the **Credentials** and **Details** panes in the Oracle Database SSH Connector page.Â The components of the other panes in this page, **Scheduling**Â and **Name & Describe Your DataSet**, are universal across most connector types and are discussed in greater length inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md "Adding a DataSet Using a Data Connector").


### Credentials Pane


This pane contains fields for entering credentials to connect to your database and SSH server. The following table describes what is needed for each field: Â 




| Field | Description |
| --- | --- |
| SSH Server Hostname | Enter the SSH server hostname.Â  |
| SSH Username | Enter the SSH username. |
| SSH Password | Enter the SSH password. |
| SSH Port | Enter the SSH port number. |
| Database Hostname | Enter the host name for the Oracle database.Â  |
| SSH Private Key | Enter the SSH private key. |
| Database Name | Enter the Oracle database name. |
| Database Username | Enter your Oracle username. |
| Database Password | Enter your Oracle password. |
| Database Port | Enter your Oracle port number. |


Once you have entered valid Oracle Database credentials, you can use the same account any time you go to create a new Oracle Database SSH DataSet. You can manage connector accounts in the **Accounts** tab in the Data Center. For more information about this tab, see [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


### Details Pane


In this pane you create an SQL query to pull data from your database. TheÂ **Query**Â parameter is required. The other three parameters are here to help you construct this query if you choose.




| Menu | Description |
| --- | --- |
| Query | Enter the Structured Query Language (SQL) query to use in selecting the data you want. For example:
select \* from Employee
If you want help in constructing your query,Â  |
| Database Table (Optional) | Select the table containing the data you want to pull into Domo. The selected table will be added to the automatically generated query in theÂ **Query HelperÂ**field.Â  |
| Table Columns (Optional) | Select the table columns with data you want to pull into Domo.Â The selected columnsÂ will be added to the automatically generated query in theÂ **Query HelperÂ**field.Â  |
| Query Helper (Optional) | Copy and paste this query into theÂ **Query**Â field if you need help building a query. This query is automatically generated when you select a table and columns in theÂ **Database Table**Â and **Table Columns**Â fields, respectively. |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, seeÂ [AddingÂ a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).