---
title : Creating Badges for Achievements
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:40:00
url : https://domo-support.domo.com/s/article/360042934434
linked_kbs :  ['https://domo-support.domo.com/s/article/360042934434', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360043438973', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/article/360043439493', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003058
views : 3,977
created_date : 2022-10-24 21:09:00
last updated : 2022-10-24 22:40:00
---



You can create aÂ badgeÂ and designate users who can award theÂ badge to others in theirÂ ProfileÂ pages. You can do this in **More >** **Admin > Company settings > Achievements**. You can only create badges and designate users to award themÂ if you have an "Admin" default security role or a custom role with "Assign Achievements" enabled. For more information about default security roles, seeÂ [Managing Custom Roles](..\managing_custom_roles\index.html "Security Role Reference").Â 


For information about awarding a badge, seeÂ [Viewing and Awarding Badges](..\viewing_and_awarding_badges\index.html "Viewing and Awarding Badges").



**To create a badge,**


1. ClickÂ  **More**Â **> Admin**.  
TheÂ Admin SettingsÂ page appears.
2. Select **Company settings > Achievements**.
3. ClickÂ **New Achievement,** then define the badge.


	1. Enter the name of the badge.
	2. Enter the description of the badge.
	3. Enter the names of users who can award theÂ badge to others
	
	
	**Note:Â**If you have permission to award an badge, the **Give a Badge**Â button appears in theÂ **Badges** section when viewing a user profile.
	4. Upload an image of the badge.
4. ClickÂ **Add**.