---
title : Adding User Licenses in Domo
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:42:00
url : https://domo-support.domo.com/s/article/360042934454
linked_kbs :  ['https://domo-support.domo.com/s/article/360042934954', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360042934234', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042934454', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360043438953', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003020
views : 4,229
created_date : 2022-10-24 21:00:00
last updated : 2022-10-24 22:42:00
---



Â
**Note:** This feature is available *on demand.Â*To request that this feature be enabled,Â reach out to your Domo Customer Success Manager or Technical Consultant.
You can review your license seat usage and order licenses in Domo.Â TheÂ **More >** **Admin > Governance > Licenses** sub-tab shows the number of paid versus courtesy (unpaid) licenses in your Domo instance as well as the number of Social users. In this tab you can buy new licenses, pay for courtesy licenses, approve or deny upgrade requests, and upgrade Social users to paid Domo users.Â Â 


You can only view and manage user licenses if you have an "Admin" default security role or a custom role with "Manage All Company Settings" enabled. For more information about default security roles, seeÂ [Social User FAQs and Videos](..\social_user_faqs_and_video\index.html "Security Role Reference").


For information about the layout of theÂ Admin Settings, seeÂ [Admin Settings Overview](..\admin_settings_overview\index.md).


**To buy Domo licenses,**


1. ClickÂ **More**Â **> Admin**.  
 The Admin Settings appears.
2. Select the **Governance** tab.
3. Click the **Licenses** sub-tab.
4. ClickÂ **Buy Licenses**.
5. Fill out the fields in the wizard as requested.Â


Â
**Note:Â**When you confirm a license purchase order, Domo sends an email to a Domo sales representative who sends you a purchase order invoice.Â Â
**To approve or deny upgrade requests,**


1. ClickÂ **More**Â **> Admin**.  
 The Admin Settings appears.
2. Select the **Governance** tab.
3. Click the **Licenses** sub-tab.
4. In the table at the bottom of the panel, locate the user you want to approve or deny.
5. Click theÂ **Approve**Â orÂ **Deny**Â radio button in the user row.
6. (Conditional) If you have approved the user, select the desired security role in theÂ **Assign Role**Â menu.  
 For explanations of all available security roles, seeÂ [Security Role Reference](..\default_security_role_reference\index.html "Security Role Reference").


**To view the list of Social users in your Domo,**


1. ClickÂ **More**Â **> Admin**.  
 The Admin Settings appears.
2. Select the **Governance** tab.
3. Click the **Licenses** sub-tab.
4. Click theÂ **Social Users**Â tab to show the list of Social users.Â


**To assign new roles to Social users,**


1. ClickÂ **More**Â **> Admin**.  
 The Admin Settings appears.
2. Select the **Governance** tab.
3. Click the **Licenses** sub-tab.
4. Click theÂ **Social Users**Â tab to show the list of Social users.
5. In the table at the bottom of the panel, locate the user you want to reassign.
6. Select the new security role in theÂ **Assign Role**Â menu.