---
title : Allowlisting IP Addresses for Connectors & Federated Adapters
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:41:00
url : https://domo-support.domo.com/s/article/360043630093
linked_kbs :  ['https://domo-support.domo.com/s/article/360042930554', 'https://domo-support.domo.com/s/article/360042932074', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360043436193', 'https://domo-support.domo.com/s/article/360042929094', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043439173', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360043436293', 'https://domo-support.domo.com/s/article/360042932974', 'https://domo-support.domo.com/s/article/360043630093', 'https://domo-support.domo.com/s/article/360043436053', 'https://domo-support.domo.com/s/article/360043436013', 'https://domo-support.domo.com/s/article/360042931694', 'https://domo-support.domo.com/s/article/360043436253', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/article/7963308557463', 'https://domo-support.domo.com/s/article/360042931874', 'https://domo-support.domo.com/s/article/360042931734', 'https://domo-support.domo.com/s/article/360043433113', 'https://domo-support.domo.com/s/article/360043436113', 'https://domo-support.domo.com/s/article/360042930534', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360042931894', 'https://domo-support.domo.com/s/article/360043433413', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913', 'https://domo-support.domo.com/s/article/360043436513', 'https://domo-support.domo.com/s/article/360043436173', 'https://domo-support.domo.com/s/article/360043433393', 'https://domo-support.domo.com/s/article/360043436233', 'https://domo-support.domo.com/s/article/360043434973', 'https://domo-support.domo.com/s/article/360042929114', 'https://domo-support.domo.com/s/article/360043436273', 'https://domo-support.domo.com/s/article/360042932034', 'https://domo-support.domo.com/s/article/360042931614', 'https://domo-support.domo.com/s/article/360043436213', 'https://domo-support.domo.com/s/article/360042931754', 'https://domo-support.domo.com/s/article/360042931774', 'https://domo-support.domo.com/s/article/360043436033']
article_id : 000003961
views : 8,406
created_date : 2022-10-24 21:17:00
last updated : 2022-10-24 22:41:00
---



Intro
-----


Allowlisting IP addresses is usually required for database Connectors and standard (cloud-based) federated adapters. These Connectors must also have SSL enabled on their database server in order to authenticate.


**Note:** The federated agent (on-premise deployment) does not require incoming IP allowlisting. See this article for more details on the federated agent architecture: [Using the Federated Data Solution](..\using_the_federated_data_solution\index.md).
Affected Connectors
-------------------


All of the following Connectors require allowlisting:



* [Amazon QuickSight SPICE](/s/article/360043436013)
* [Amazon Redshift](..\amazon_redshift_v1_connector\index.html "Amazon Redshift Connector")
* [Amazon Redshift Advanced](..\amazon_redshift_advanced_connector\index.html "Amazon Redshift Advanced Connector")
* [Amazon Redshift SSH](..\amazon_redshift_ssh_connector\index.html "Amazon Redshift SSH Connector")
* [Apache Kafka](..\apache_kafka_connector\index.html "Apache Kafka Connector")
* [Apache Kafka REST](..\apache_kafka_rest_connector\index.html "Apache Kafka REST Connector")
* [CSV Advanced](..\csv_advanced_connector\index.html "https:\knowledge.domo.com\Connect\Connecting_to_Data_with_Connectors\Configuring_Each_Connector\Connectors_for_File_Retrieval\CSV_Advanced_Connector")
* [CSV SFTP Pull](..\csv_sftp_pull_connector\index.html "https:\knowledge.domo.com\Connect\Connecting_to_Data_with_Connectors\Configuring_Each_Connector\Connectors_for_File_Retrieval\CSV_SFTP_Pull_Connector")
* [Cvent](..\cvent_connector\index.html "https:\knowledge.domo.com\Connect\Connecting_to_Data_with_Connectors\Configuring_Each_Connector\Connectors_for_Communication\Cvent_Connector")
* [GitHub Enterprise](..\github_enterprise\index.md)
* [Hive](..\hive_connector\index.html "Hive Connector")
* [Jira](..\jira_rest_api_connector\index.md)
* [JSON Advanced](..\json_advanced_connector\index.md)
* [IBM DB2](..\ibm_db2_connector\index.html "IBM DB2 Connector")
* [IBM Informix](..\ibm_informix_connector\index.html "IBM Informix Connector")
* [IBM Informix SSH](..\ibm_informix_ssh_connector\index.html "IBM Informix SSH Connector")
* [Microsoft Excel SFTP](..\microsoft_excel_sftp_connector\index.html "https:\knowledge.domo.com\Connect\Connecting_to_Data_with_Connectors\Configuring_Each_Connector\Connectors_for_File_Retrieval\Microsoft_Excel_SFTP_Connector")
* [Microsoft SQL Server](..\microsoft_sql_server_connector\index.html "Microsoft SQL Server Connector")
* [MongoDB](..\mongodb_connector\index.html "MongoDB Connector")
* [MySQL](..\mysql_connector\index.html "MySQL Connector")
* [MySQL SSH](..\mysql_ssh_connector\index.html "MySQL SSH Connector")
* [Oracle Database](..\oracle_database_connector\index.html "Oracle Database Connector")
* [Oracle Database SSH](..\oracle_database_ssh_connector\index.html "Oracle Database SSH Connector")
* [PostgreSQL](..\postgresql_connector\index.html "PostgreSQL Connector")
* [PostgreSQL SSH](..\postgresql_ssh_connector\index.html "PostgreSQL SSH Connector")
* [SAP Adaptive Server Enterprise](..\sap_adaptive_server_enterprise_connector\index.html "SAP Adaptive Server Enterprise Connector")
* [SAP Adaptive Server Enterprise SSH](..\sap_adaptive_server_enterprise_ssh_connector\index.html "SAP Adaptive Server Enterprise SSH Connector")
* [ServiceNow](..\servicenow_connector\index.md)
* [Splunk](..\splunk_connector\index.html "https:\knowledge.domo.com\Connect\Connecting_to_Data_with_Connectors\Configuring_Each_Connector\Connectors_for_IT\Splunk_Connector")
* [Vertica](..\vertica_connector\index.html "Vertica Connector")


IP Addresses to Allowlist
-------------------------


**Important:** The IPs listed below must be allowlisted on your database server. You should *not* add these IPs to the allowlist in your Domo instance. Doing so will simply lock everyone out of the instance who is not coming from the IP addresses listed below. If you add these IPs to the allowlist in your Domo instance rather than on your server, incoming users will receive an error upon trying to log in that says "We're sorry but the system is not performing right now."


If a Domo Connector or federated adapter need access to your servers, you will need to allowlist all of the following IPs in the section below corresponding to where your Domo instance is hosted. IPs are given using CIDR notation for convenience when working with AWS Security Groups and other network security systems.


If you are unsure where your DomoÂ instance is hosted, it's most likely US East (AWS).


**Tip:Â**A /32 after an IP address is CIDR notation for a single address. Smaller numbers, such as /27,Â indicateÂ a range of IP addresses.  
Ex:Â 3.214.145.64/27 means theÂ range of IPs fromÂ 3.214.145.64Â toÂ 3.214.145.95 inclusive.
###### US East (AWS):


`3.214.145.64/27` (Includes all IPs from 3.214.145.64 through 3.214.145.95 inclusive.)


`54.208.87.122/32`


`54.208.94.194/32`


`54.208.95.167/32`


`54.208.95.237/32`


`34.198.214.100`


`34.202.52.248`


###### US East (Azure):


`13.92.125.193/32`


`40.76.8.174/32`


###### US West (AWS):


`35.82.136.240/28` (Includes all IPs from 35.82.136.240 through 35.82.136.255 inclusive.)


###### Australia (Sydney):


`52.62.103.83/32`


###### Canada:


`15.222.16.24/29` (Includes all IPs from 15.222.16.24 through 15.222.16.31 inclusive.)


###### Ireland (Dublin):


`52.18.90.222/32`


###### Japan (Tokyo):


`54.168.46.79/32`


Â 


For information about controlling access to DomoÂ based on IP address, seeÂ [Whitelisting IP Addresses in Domo](..\whitelisting_ip_addresses_in_domo\index.html "Whitelisting IP Addresses in Domo").


**Note:** For the JSON Advanced connector, you need to allowlist the IP 34.198.214.100
S3 Bucket policy for the Amazon S3 Connectors
---------------------------------------------


You only need to use these endpoints if all of the following conditions are met:



* You are using any of Domo's S3 connectors
* Your Domo instance is in the same region as your S3 bucket
* You are restricting network access via a bucket policy


If your S3 bucket is in a different region than your Domo instance, you should use the standard Connector IPs posted in the documentation.



* us-east-1 (N. Virginia) vpce-3857b651: prod1, prod2, prod3, prod4, prod5, prod6, prod7, prod9
* ap-southeast-2 (Sydney) vpce-bf4fa1d6: prod8
* eu-west-1 (Ireland) vpce-c4788cad: prod10
* ap-northeast-1 (Tokyo) vpce-0055e53d26f729c54: prod12
* ca-central-1 (Canada Central) vpce-058575bcc0a0034ae: prod14