---
title : SurveyMonkey Advanced Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:41:00
url : https://domo-support.domo.com/s/article/360042930754
linked_kbs :  ['https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429913', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360043428113', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360042930754']
article_id : 000003386
views : 3,995
created_date : 2022-10-24 21:12:00
last updated : 2022-10-24 22:41:00
---



Intro
-----


SurveyMonkey is a cloud-based company that provides free, customizable surveys, as well as a suite of paid back-end programs that include data analysis, sample selection, bias elimination, and data representation tools. To learn more about the SurveyMonkey API, visit their website. ([https://developer.surveymonkey.com/](https://developer.surveymonkey.com/ "https://developer.surveymonkey.com/"))  


You connect to your SurveyMonkey account in the Data Center. This topic discusses the fields and menus that are specific to the SurveyMonkey connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).




|  |  |
| --- | --- |
| **Primary Use Cases** | Survey and response analysis |
| **Primary Metrics** | 
* Number of people who responded to a survey
* Response counts
* Number of completed surveys
 |
| **Primary Company Roles** | 
* Marketing roles
* HR roles
 |
| **Average Implementation Time** | 1 hour |
| **Ease of Use (on a 1-to-10 scale with 1 being easiest)** | 2 |


Best Practices
--------------


Use this connector to pull historical data, then append new data via a recursive DataFlow. For more information, seeÂ [Creating a Recursive/Snapshot Magic ETL DataFlow](..\creating_a_recursivesnapshot_old_magic_etl_dataflow\index.html "Creating a Recursive\Snapshot Magic ETL DataFlow").


Prerequisites
-------------


To connect to your SurveyMonkey account and create a DataSet, you must have the username and password you use to log into your SurveyMonkey account.


Connecting to Your SurveyMonkey Account
---------------------------------------


This section enumerates the options in theÂ **Credentials**Â andÂ **Details**Â panes in the SurveyMonkey Connector page.Â The components of the other panes in this page,Â **SchedulingÂ**andÂ **Name & Describe Your DataSet,** are universal across most connector types and are discussed in greater length inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).


### Credentials Pane


The Domo SurveyMonkey connector uses OAuth to connect, so there is no need to enter credentials within Domo. ClickÂ **Connect**Â (or selectÂ **Add Account**Â ifÂ you haveÂ existing SurveyMonkey accounts in Domo) to open the SurveyMonkey OAuth screen where you can enter your SurveyMonkey credentials. Once you have entered valid SurveyMonkey credentials, you can use the same account any time you go to create a new SurveyMonkey DataSet. You can manage connector accounts in theÂ **Accounts**Â tab in theÂ Data Center. For more information about this tab, seeÂ [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


**Note:**Â If you are already logged into SurveyMonkey when you connect in Domo, you are authenticated automatically when you click **Add account**. If you want to connect to an account that is different from the one you are logged into, you must first log out of SurveyMonkey.
### Details Pane


This pane contains a primaryÂ **Reports**Â menu, along with various other menus which may or may not appear depending on the report type you select.




| Menu | Description |
| --- | --- |
| Report | Select the SurveyMonkey report you want to run.Â The following reports are available:

|  |  |
| --- | --- |
| All Surveys Details | Returns data about all or selected surveys. |
| Collector List | Returns data about collectors for a selected survey. |
| Responses | Returns data about responses for a selected survey. |
| Survey Details | Returns details for a selected survey. |
| Survey List | Returns a list of completed surveys. |
| User Details | Returns information about the current user. |

 |
| One or All Surveys | Select whether toÂ retrieve data from all surveys or a single selected survey. |
| All or New Data | Select how much data to retrieve. If you selectÂ **All data**, the reportÂ retrieves all data within theÂ givenÂ **Start Days** andÂ **End Days** range. If you selectÂ **Since last successful run**, the reportÂ retrieves all data since the last successful update. If this is a new DataSet, the runÂ retrieves dataÂ for the number of days specified inÂ **Start Days**. |
| Start Days | Enter the number of the farthest day back that should be represented in the report. Combine with **End Days** to create a range of represented days. For example, if you entered 10 for **Start Days** and 5 for **End Days**, the report would contain data forÂ 10 days ago up untilÂ 5 days ago. Use 0 for today. |
| End Days | Enter the number of the most recent day back that should be represented in the report. Combine with **Start Days** to create a range of represented days. For example, if you entered 10 for **Start Days** and 5 for **End Days**, the report would contain data forÂ 10 days ago up untilÂ 5 days ago. Use 0 for today. |
| Collector | Select the collectorÂ for whomÂ you want to retrieve data. |
| Survey | SelectÂ the survey for which you want to retrieve data. |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, seeÂ [AddingÂ a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).