---
title : Asana Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:41:00
url : https://domo-support.domo.com/s/article/360042930314
linked_kbs :  ['https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360042930314', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003431
views : 2,109
created_date : 2022-10-24 21:13:00
last updated : 2022-10-24 22:41:00
---



Intro
-----


Asana is a cloud-based project management platform that helps users track projects, tasks, stories and other project-related workflows. To learn more about the Asana API, visit their page ([https://asana.com/developers/documen...arted/overview](https://asana.com/developers/documentation/getting-started/overview "https://asana.com/developers/documentation/getting-started/overview")).


You connect to your Asana account in the Data Center. This topic discusses the fields and menus that are specific to the Asana connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).


Prerequisites
-------------


To connect to your Asana account and create a DataSet, you must have the email address you use to log into Asana, as well as your Asana password. Alternatively, you can use Google credentials to connect.


Connecting to Your Asana Account
--------------------------------


This section enumerates the options in theÂ **Credentials**Â andÂ **Details**Â panes in the Asana Connector page.Â The components of the other panes in this page,Â **SchedulingÂ**andÂ **Name & Describe Your DataSet,** are universal across most connector types and are discussed in greater length inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).


### Credentials Pane


The Domo Asana connector uses OAuth to connect, so there is no need to enter credentials within Domo. ClickÂ **Connect**Â (or selectÂ **Add Account**Â ifÂ you haveÂ existing Asana accounts in Domo) to open the Asana OAuth screen where you can enter your Asana or Google credentials. Once you have entered valid credentials, you can use the same account any time you go to create a new Asana DataSet. You can manage connector accounts in theÂ **Accounts**Â tab in theÂ Data Center. For more information about this tab, seeÂ [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


**Note:**Â If you are already logged into Asana when you connect in Domo, you are authenticated automatically when you click **Add account**. If you want to connect to an account that is different from the one you are logged into, you must first log out of Asana.
You will alsoÂ need an API Key for your Asana account. Any user can get their own API key by visiting the Account Settings dialog and clicking on the Apps tab. The API key is located at the bottom of this dialog box.


### Details Pane


This pane contains a primaryÂ **Reports**Â menu, along with various other menus which may or may not appear depending on the report type you select. If you select the "Tasks" report, a "Subreport" menu appears from which you may select a secondary report.




| Menu | Description |
| --- | --- |
| Report | Select the Asana report you want to run.Â The following reports are available:

|  |  |
| --- | --- |
| Attachments | Retrieves all attachments for a specified workspace. |
| Projects | Retrieves all projects in a specified workspace. |
| Stories | Retrieves all stories in a specified workspace. |
| Tags | Retrieves all tags made on tasks in a specified workspace. |
| Tasks | Retrieves all tasks for a specified workspace. With this report, you may also select a subreport. |
| Teams | Retrieves all teams for a specified workspace. |
| Users | Retrieves all users for a specified workspace. |
| Workspaces | Retrieves all workspaces for the authenticated user. |

 |
| Subreport | Select the desired subreport for the "Tasks" report. The following subreports are available:

|  |  |
| --- | --- |
| None | Only task data is returned. |
| Followers | Retrieves a list of tasks enhanced with followers data. |
| Hearts | Retrieves a list of tasks enhanced with hearts data. |
| Memberships | Retrieves a list of tasks enhanced with memberships data. |
| Projects | Retrieves a list of tasks enhanced with project data. |

 |
| Workspace | Select the workspace you want to retrieve data for. |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, seeÂ [AddingÂ a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md). Â 


FAQ
---


##### How often can the data be updated?


DataSets can be updated as often as once an hour.


##### Are there any API limits that I need to be aware of?


Asana does not document any limits in their API.