---
title : Marin Social Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:39:00
url : https://domo-support.domo.com/s/article/360042926994
linked_kbs :  ['https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360042926994', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003739
views : 2,002
created_date : 2022-10-24 21:14:00
last updated : 2022-10-24 22:39:00
---



Intro
-----


Marin Social is a powerful campaign management, reporting, and optimization solution that helps you scale your programs, make better decisions, and acquire high-value customers across social networks. Use Domo's Marin Social connector to retrieve data about campaigns, clients, advertisements, and so on. To learn more about the Marin Social API, you can download their API documentation here: <http://kb.socialmoov.com/wp-content/uploads/2015/09/API-Documentation_2.1.7.docx>.


You connect to your Marin Social account in the Data Center. This topic discusses the fields and menus that are specific to the Marin Social connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).


Prerequisites
-------------


To connect to your Marin Social account and create a DataSet, you must have a Marin Social API key. You should receive an API key upon creating a Marin Social account.


Connecting to Your Marin Social Account
---------------------------------------


This section enumerates the options in the **Credentials** and **Details** panes in the Marin Social Connector page.Â The components of the other panes in this page, **Scheduling**Â and **Name & Describe Your DataSet**, are universal across most connector types and are discussed in greater length inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md "Adding a DataSet Using a Data Connector").


### Credentials Pane


This pane contains fields for entering credentials to connect to your Marin Social account. The following table describes what is needed for each field: Â 




| Field | Description |
| --- | --- |
| API Key | Enter your Marin Social API key. |


Once you have entered valid Marin Social credentials, you can use the same account any time you go to create a new Marin Social DataSet. You can manage connector accounts in the **Accounts** tab in the Data Center. For more information about this tab, see [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


### Details Pane


This pane contains a primaryÂ **Reports**Â menu, along with various other menus which may or may not appear depending on the report type you select.




| Menu | Description |
| --- | --- |
| Report | Select the Marin Social report you want to run.Â The following reports are available:

|  |  |
| --- | --- |
| Accounts | Returns all accounts for your agency. |
| Account Audiences | Returns all audiences for a selected account ID. |
| Account Lead Forms | Returns all lead forms for a selected account ID. |
| Ad Statistics | Returns ad statistics for a given client ID, campaign ID, ad ID, and timeframe. |
| Advertisers | Returns all advertisers for your agency. |
| Campaigns | Returns all campaigns for your account. |
| Campaign Ads | Returns all campaign ads for a given client ID and campaign ID. |
| Campaign Statistics | Returns campaign statistics for a given client ID, campaign ID, level, and timeframe. |
| Clients | Returns all clients for your account. |
| Client Campaigns | Returns all client campaigns for a given client ID. |
| Client Users | Returns all client users for a given client ID. |
| Funding Instruments | Returns all funding instruments for a given account ID. |
| Objects | Returns all funding instruments for a given object ID. |
| Statistics | Returns statistics for a given client ID, level, and timeframe. |
| Users | Returns all users for your account. |

 |
| Account ID | Select the IDs for all accounts you want to retrieve information for. |
| Client ID | Select the IDs for all clients you want to retrieve information for. |
| Campaign ID | Select the IDs for all campaigns you want to retrieve information for. |
| Ad ID | Select the IDs for all ads you want to retrieve information for. |
| Time | Select whether you want data in your report to be broken down by day, month, or period. |
| Level | Select the reporting level for the data. |
| DurationÂ  | Select whether you want to pull data for a specific date or a date range.Â  |
| Report DateÂ  | Select whether the report data is for a specific date or for a relative number of days back from today.Â  |
| Select Specific DateÂ  | Select the date for the report.Â  |
| Days Back | Enter the number of past days that should appear in the report.Â Â  |
| Start Date | Specify whether theÂ first date in your date range is a specific or relative date.Â You select the last date in your range inÂ **End Date**.Â  |
| End Date | Specify whether the second date in your date range is a specific or relative date. You select the first date in your range inÂ **Start Date**.Â Â  |
| Select Specific Start Date | SelectÂ the first date in your date range.Â  |
| Select Specific End Date | Select the second date in your date range.Â  |
| Days Back to Start From | Enter the number of the farthest day back that should be represented in the report. Combine withÂ **Days Back to End At**Â to create a range of represented days.
For example, if you enteredÂ 10Â forÂ **Days Back to Start From**Â andÂ 5Â forÂ **Days Back to End At**, the report would contain data forÂ 10 days ago up untilÂ 5 days ago. |
| Days Back to End At | Enter the number of the most recent day back that should be represented in the report. Combine withÂ **Days Back to Start From**Â to create a range of represented days.
For example, if you enteredÂ 10Â forÂ **Days Back to Start From**Â andÂ 5Â forÂ **Days Back to End At**, the report would contain data forÂ 10 days ago up untilÂ 5 days ago. |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, seeÂ [AddingÂ a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).


Â