---
title: Qualtrics Dashboard App
url: https://domo-support.domo.com/s/article/360042934014
linked_kbs:  ['[https://domo-support.domo.com/s/knowledge-base/](https://domo-support.domo.com/s/knowledge-base/)', '[https://domo-support.domo.com/s/](https://domo-support.domo.com/s/)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZampGAC](https://domo-support.domo.com/s/topic/0TO5w000000ZampGAC)', '[https://domo-support.domo.com/s/topic/0TO5w000000Zan9GAC](https://domo-support.domo.com/s/topic/0TO5w000000Zan9GAC)', '[https://domo-support.domo.com/s/article/360042934014](https://domo-support.domo.com/s/article/360042934014)', '[https://domo-support.domo.com/s/topic/0TO5w000000Zan9GAC/available-apps](https://domo-support.domo.com/s/topic/0TO5w000000Zan9GAC/available-apps)', '[https://domo-support.domo.com/s/article/360043429933](https://domo-support.domo.com/s/article/360043429933)', '[https://domo-support.domo.com/s/article/360043429953](https://domo-support.domo.com/s/article/360043429953)', '[https://domo-support.domo.com/s/article/360042925494](https://domo-support.domo.com/s/article/360042925494)', '[https://domo-support.domo.com/s/article/360043429913](https://domo-support.domo.com/s/article/360043429913)', '[https://domo-support.domo.com/s/article/4408174643607](https://domo-support.domo.com/s/article/4408174643607)', '[https://domo-support.domo.com/s/login/](https://domo-support.domo.com/s/login/)']
article_id: 000004180
views: 1,095
created_date: 2022-10-24 21:26:00
last updated: 2022-10-24 22:42:00
---



Intro
-----


Qualtrics is a web-based survey platform that helps you gain the insights you need from your customers and prospective customers.


Usage
-----


* Business questions that can be answered:


	+ What are the responder’s levels of engagement?
	+ How did my surveys perform?
	+ What did people say and how should we react?
* Metrics included in the app:


	+ Top 10 Surveys
	+ Survey Completion Rate
	+ Questions Versus Responses
	+ Questions Answered
	+ Response Progress
	+ Survey Response Rate
	+ Response Rate
	+ Survey Status
	+ Survey List
	+ Total Questions Answered
	+ Survey Responses
	+ Responses
	+ Survey Trend
	+ Responses Per Survey


Authentication
--------------


Required information:


* Username
* API Token
* Survey Type:


	+ Standard Survey
	+ 360 Survey


Dashboard Reports
-----------------


For report descriptions, see Qualtrics Connector.


Report Configuration / Report Details
-------------------------------------


The following reports can be selected and configured using this Connector:




| Report | Scheduling (Change update settings) | Parameter(s) | Selection |
| --- | --- | --- | --- |
| Survey Responses | Append | Survey | Choose the survey to collect responses from |
| Survey Questions | Replace | Survey | Choose the survey to pull questions from |
| Surveys | Replace | None |   |


Qualtrics Dashboard Data
------------------------


The Qualtrics Dashboard will provide the following data collections and cards:




| Collection
  | Card | Card Description | Data Name |
| --- | --- | --- | --- |
| Qualtrics Pulse: 5 indicators of survey engagement. | Top 10 Surveys | Shows the survey names with the highest rate of completion. Identify the elements that contributed to the success of these surveys and replicate those elements in future surveys. | Surveys |
| Qualtrics Pulse: 5 indicators of survey engagement. | Survey Completion Rate | Measures the percentage point difference in the survey completion rate over the last 30 days versus the previous 30 days. Investigate causes in drops of completion rates. | Surveys |
| Qualtrics Pulse: 5 indicators of survey engagement. | Questions Versus Responses | Displays the total number of questions asked for each survey and how many responses have been received. Investigate possible reasons why people have left questions unanswered. | Surveys |
| Qualtrics Pulse: 5 indicators of survey engagement. | Questions Answered | Measures the total number of responses per survey in a period. Use this information to determine completion rates and completeness of responses received. | Surveys |
| Qualtrics Pulse: 5 indicators of survey engagement. | Response Progress
  | Displays the number of completed responses and remaining questions to be answered. Investigate possible reasons why people have left questions unanswered. | Surveys |


 




| Collection
  | Card | Card Description | Data Name |
| --- | --- | --- | --- |
| Results: How did my surveys perform? | Survey Response Rate | Shows the total number of questions asked for each survey and how many responses have been received. | Surveys |
| Results: How did my surveys perform? | Response Rate | Shows the total number of questions asked on each survey and the number of responses received. Identify what measures need to be taken to improve response rates.
  | Surveys |
| Results: How did my surveys perform? | Survey Status | Displays the number of completed and partially completed surveys. Find surveys close to completion and evaluate how they can be closed out. | Surveys |
| Results: How did my surveys perform? | Survey List | Shows the list of surveys and the number of questions that were asked. Find questions or surveys that were routinely skipped and modify appropriately. | Surveys |


 




| Collection
  | Card | Card Description | Data Name |
| --- | --- | --- | --- |
| Responses: What did people say and how should we react? | Total Questions Asked | Displays the total number of questions for all surveys sent during the specified period. Determine if the number of questions asked provides the right balance between maximizing insight gained without fatiguing respondents. | Surveys |
| Responses: What did people say and how should we react? | Survey Responses | Shows the total number of responses per survey. Gauge whether there are enough responses for a satisfactory sample size on a given survey. | Surveys |
| Responses: What did people say and how should we react? | Responses | Measures the number of responses received by survey. Determine if enough data has been received to take action on feedback. | Surveys |
| Responses: What did people say and how should we react? | Survey Trend | Tracks the total number of surveys started during the specified period. Determine whether the current period is above or below average. | Surveys |
| Responses: What did people say and how should we react? | Responses Per Survey | Shows the number of responses received for each survey in the period. | Surveys |


 


 

