---
title : Monitis Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:39:00
url : https://domo-support.domo.com/s/article/360042928874
linked_kbs :  ['https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360042928874', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003570
views : 2,000
created_date : 2022-10-24 21:13:00
last updated : 2022-10-24 22:39:00
---



Intro
-----


Monitis is an all-in-one application monitoring platform that monitors your websites, applications, servers and more. To learn more about the Monitis API, visit their page ([http://www.monitis.com/docs/api.html](http://www.monitis.com/docs/api.html "http://www.monitis.com/docs/api.html")).


You connect to your Monitis account in the Data Center. This topic discusses the fields and menus that are specific to the Monitis connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


Prerequisites
-------------


To connect to your Monitis account and create a DataSet, you must have the following:



* A Monitis API key
* A Monitis secret key


You can obtain both of these credentials by logging into your Monitis account then navigating to **Tools > API > API Key**.


Connecting to Your Monitis Account
----------------------------------


This section enumerates the options in the **Credentials** and **Details** panes in the Monitis Connector page.Â The components of the other panes in this page, **Scheduling**Â and **Name & Describe Your DataSet**, are universal across most connector types and are discussed in greater length inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


### Credentials Pane


This pane contains fields for entering credentials to connect to your Monitis account. The following table describes what is needed for each field: Â 




| Field | Description |
| --- | --- |
| API Key | Enter your Monitis API key. |
| Secret Key | Enter your Monitis secret key. |


For information about obtaining these credentials, see "Prerequisites," above.


Once you have entered valid Monitis credentials, you can use the same account any time you go to create a new Monitis DataSet. You can manage connector accounts in the **Accounts** tab in the Data Center. For more information about this tab, see [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


### Details Pane


This pane contains a primaryÂ **Reports**Â menu, along with various other menus which may or may not appear depending on the report type you select.




| Menu | Description |
| --- | --- |
| Report | Select the Monitis report you want to run.Â The following reports are available:

|  |  |
| --- | --- |
| Agent | Retrieves a list of agents in your account. |
| Contact Group | Retrieves a list of all groups of contacts in your account. |
| Contact List | Retrieves a list of all contacts in your account. |
| External Monitor by Tag | Retrieves a list of External monitors for the selected tag in your account. |
| External Monitor Result | Retrieves a list of results for the selected External monitor in your account. |
| External Monitor | Retrieves a list of External monitors in your account. |
| External Monitor Info | Retrieves information regarding the selected External monitor in your account. |
| External Snapshot | Retrieves a list of the last results of all users' External monitors in your account. |
| Full Page Load Info | Retrieves information about the selected Full Page Load monitor in your account. |
| Full Page Monitor Location | Retrieves a list of locations of Full Page Load monitors in your account. |
| Full Page Load Monitor | Retrieves a list of Full Page Load monitors in your account. |
| Full Page Load Monitor Result | Retrieves a list of results for the selected Full Page Load monitors in your account. |
| Full Page Load Snapshot | Retrieves a list of all users' Full Page Load monitors in your account. |
| Internal HTTP Monitor | Retrieves a list of Internal HTTP monitors for the selected agent in your account. |
| Internal HTTP Result | Retrieves results of the selected Internal HTTP monitor in your account. |
| Locations | Retrieves a list of locations in your account. |
| Notification Rules | Retrieves a list of existing notification rules for the specified monitor in your account. |
| Other Monitor | Retrieves a list of other monitors in your account. |
| Pages | Retrieves a list of pages in your account. |
| Page Modules | Retrieves a list of modules for the selected page in your account. |
| Recent Alerts | Retrieves a list of failed monitors according to sent notifications in your account. |
| Service List | Retrieves a list of available services and their possible configurations in your account. |
| Step Results | Retrieves detailed step results for certain transaction monitors in your account. |
| Step Net | Retrieves the net for the selected Transaction step in your account. |
| Tags | Retrieves a list of all tags for a user's External monitors. |
| Transaction Locations | Retrieves a list of locations of Transaction monitors in your account. |
| Transaction Monitors | Retrieves a list of Transaction monitors in your account. |
| Transaction Monitor Info | Retrieves information about specified Transactions in your account. |
| Transaction Monitor Results | Retrieves results for the selected Transaction in your account. |
| Transaction Snapshot | Retrieves the last results of all of the user's Transaction monitors. |

 |
| Tags | Select the tag you want to retrieve information for. |
| External Monitor | Select the External monitor you want to retrieve information for. |
| Transaction Monitor | Select the Transaction monitor you want to retrieve information for. |
| DurationÂ  | Select whether you want to pull data for a specific date or a date range.Â  |
| Report DateÂ  | Select whether the report data is for a specific date or for a relative number of days back from today.Â  |
| Select Specific DateÂ  | Select the date for the report.Â  |
| Days Back | Enter the number of past days that should appear in the report.Â Â  |
| Start Date | Specify whether theÂ first date in your date range is a specific or relative date.Â You select the last date in your range inÂ **End Date**.Â  |
| End Date | Specify whether the second date in your date range is a specific or relative date. You select the first date in your range inÂ **Start Date**.Â Â  |
| Select Specific Start Date | SelectÂ the first date in your date range.Â  |
| Select Specific End Date | Select the second date in your date range.Â  |
| Days Back to Start From | Enter the number of the farthest day back that should be represented in the report. Combine withÂ **Days Back to End At**Â to create a range of represented days.
For example, if you enteredÂ 10Â forÂ **Days Back to Start From**Â andÂ 5Â forÂ **Days Back to End At**, the report would contain data forÂ 10 days ago up untilÂ 5 days ago. |
| Days Back to End At | Enter the number of the most recent day back that should be represented in the report. Combine withÂ **Days Back to Start From**Â to create a range of represented days.
For example, if you enteredÂ 10Â forÂ **Days Back to Start From**Â andÂ 5Â forÂ **Days Back to End At**, the report would contain data forÂ 10 days ago up untilÂ 5 days ago. |
| Agent | Select the agent you want to retrieve information for. |
| Monitors | Select the type of monitor you want to retrieve information for. |
| Page Name | Select the page you want to retrieve information for. |
| Step Result ID | Enter the ID of the step result you want to retrieve information for. |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, seeÂ [AddingÂ a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


Â