---
title : Starting, Stopping, and Restarting the Workbench 5.1 Service
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:40:00
url : https://domo-support.domo.com/s/article/4407023720343
linked_kbs :  ['https://domo-support.domo.com/s/article/4407022160791', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/4407023720343', 'https://domo-support.domo.com/s/article/4407032210199', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000004852
views : 4,003
created_date : 2022-10-24 22:32:00
last updated : 2022-10-24 22:40:00
---



The Workbench service starts up automatically after the machine starts Windows.


You can stop,Â start, or restart the Workbench service manually usingÂ the Windows system taskbar.


**Tip:Â**IfÂ a Workbench icon does *not* appear in the Windows system taskbar, click **Start > Domo > Workbench Monitor**.
For information about running the Workbench application, seeÂ [Running Workbench 5.1](..\running_workbench_51\index.md).


**To manually start, stop, or restart the Workbench service,**


1. In the Windows system taskbar, right-click the Workbench service icon.  
A menu appears.
2. Select **Service**, thenÂ click the option you want (**Start**, **Stop**, or **Restart**).


For information about the controls and field settings in Workbench, seeÂ [Understanding the Workbench 5.1 User Interface](..\understanding_the_workbench_51_user_interface\index.html "Understanding the Workbench 5 User Interface").