---
title: Oracle Database Writeback Connector
url: https://domo-support.domo.com/s/article/360042932434
linked_kbs:  ['[https://domo-support.domo.com/s/knowledge-base/](https://domo-support.domo.com/s/knowledge-base/)', '[https://domo-support.domo.com/s/](https://domo-support.domo.com/s/)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZammGAC](https://domo-support.domo.com/s/topic/0TO5w000000ZammGAC)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZanLGAS](https://domo-support.domo.com/s/topic/0TO5w000000ZanLGAS)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZapVGAS](https://domo-support.domo.com/s/topic/0TO5w000000ZapVGAS)', '[https://domo-support.domo.com/s/article/360042926274](https://domo-support.domo.com/s/article/360042926274)', '[https://domo-support.domo.com/s/article/360042926054](https://domo-support.domo.com/s/article/360042926054)', '[https://domo-support.domo.com/s/article/360042932434](https://domo-support.domo.com/s/article/360042932434)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZapVGAS/writeback-connectors](https://domo-support.domo.com/s/topic/0TO5w000000ZapVGAS/writeback-connectors)', '[https://domo-support.domo.com/s/article/360043429933](https://domo-support.domo.com/s/article/360043429933)', '[https://domo-support.domo.com/s/article/360043429953](https://domo-support.domo.com/s/article/360043429953)', '[https://domo-support.domo.com/s/article/360042925494](https://domo-support.domo.com/s/article/360042925494)', '[https://domo-support.domo.com/s/article/4408174643607](https://domo-support.domo.com/s/article/4408174643607)', '[https://domo-support.domo.com/s/article/360043429913](https://domo-support.domo.com/s/article/360043429913)', '[https://domo-support.domo.com/s/login/](https://domo-support.domo.com/s/login/)']
article_id: 000004027
views: 2,143
created_date: 2022-10-24 21:18:00
last updated: 2022-10-24 22:40:00
---



Intro
-----


To learn more about Oracle, visit their website at [https://www.oracle.com/index.html](https://en.wikipedia.org/wiki/SSH_File_Transfer_Protocol "https://en.wikipedia.org/wiki/SSH_File_Transfer_Protocol").


You export data to an Oracle database in the Data Center. This topic discusses the fields and menus that are specific to the Oracle Database Writeback connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed in  [a DataSet Using a Data Connector](/s/article/360042926274 "Adding a DataSet Using a Data Connector").




 

**Note:** The owner of a writeback dataset must also be an owner or co-owner of the input dataset.
 



Prerequisites
-------------


To configure this connector, you will need the following:


* A Domo Client ID and Client Secret. To obtain these credentials, do the following:


	1. Log into your Domo developer account at [https://developer.domo.com/login](https://developer.domo.com/login "https://developer.domo.com/login").
	2. [Create a new client](https://developer.domo.com/new-client "Domo to S3 Writeback Connector").
	3. Select the desired data and user application scope.
	4. Click **Create**.
* Your Oracle Databaseserver hostname.
* Your Oracle Databaseserver port number.
* Your Oracle Databaseserver username and password.
* An Oracle SID. This is a unique identifier for a specific Oracle database. For more information about finding the SID for your database, see [https://asktom.oracle.com/pls/asktom...D:318216852435](https://asktom.oracle.com/pls/asktom/f?p=100:11:0::NO::P11_QUESTION_ID:318216852435 "https://asktom.oracle.com/pls/asktom/f?p=100:11:0::NO::P11_QUESTION_ID:318216852435").


Configuring the Connection
--------------------------


This section enumerates the options in the **Credentials** and **Details** panes in the Oracle Database Writeback Connector page. The components of the other panes in this page, **Scheduling** and **Name & Describe Your DataSet**, are universal across most connector types and are discussed in greater length in [Adding a DataSet Using a Data Connector](/s/article/360042926274 "Adding a DataSet Using a Data Connector").


### Credentials Pane


This pane contains fields for entering credentials to connect to your Domo developer account as well as the table in your Oracle database where you want your data to be copied to. The following table describes what is needed for each field:  




| Field | Description |
| --- | --- |
| Domo Client ID | Enter your Domo client ID. |
| Domo Client Secret | Enter your Domo client secret. |
| Host | Enter your Oracle database hostname. |
| Port | Enter your Oracle database port number. |
| Username | Enter your Oracle database username. |
| Password | Enter your Oracle database password.  |
| SID | Enter your Oracle SID. |


For more information about obtaining these credentials, see "Prerequisites," above. 


Once you have entered valid credentials, you can use the same account any time you go to set up a new Domo-Oracle connection. You can manage connector accounts in the **Accounts** tab in the Data Center. For more information about this tab, see [Managing User Accounts for Connectors](/s/article/360042926054 "Managing User Accounts for Connectors").


### Details Pane


This pane contains a number of fields for specifying your data and indicating where it's going.




| Menu | Description |
| --- | --- |
| Input DataSet ID | Enter the DataSet ID (GUID) for the DataSet you want to copy to S3. You can find the ID by opening the details view for the DataSet in the Data Center and looking at the portion of the URL following datasources/. For example, in the URL <https://mycompany.domo.com/datasources/845305d8-da3d-4107-a9d6-13ef3f86d4a4/details/overview>, the DataSet ID is 845305d8-da3d-4107-a9d6-13ef3f86d4a4.  |
| Select Table Name | Select how you want to name the table where data will be copied. * **Use Input DataSet Name as Table Name**. The table name will be the same as that of the input DataSet.
* **Enter Table Name**. You will give the table a custom name in the **Table Name** field.
 |
| Table Name | Enter the name of the table in your Oracle database where you want your DataSet data to be copied. |
| Update Type | Select how you like to update the database table. |
| Alter Schema | Select if you want to alter the database table schema.  **Note**: It may change/alter the table schema completely.  |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, see [a DataSet Using a Data Connector](/s/article/360042926274 "Adding a DataSet Using a Data Connector").

