---
title : Indeed Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:41:00
url : https://domo-support.domo.com/s/article/360043432633
linked_kbs :  ['https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360043432633', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003641
views : 2,041
created_date : 2022-10-24 21:13:00
last updated : 2022-10-24 22:41:00
---



Intro
-----


Indeed is a job search engine that offers access to millions of employment opportunities from thousands of websites. To learn more about the Indeed API, visit their page ([https://www.indeed.com/publisher](https://www.indeed.com/publisher "https://www.indeed.com/publisher")).  


You connect to your Indeed account in the Data Center. This topic discusses the fields and menus that are specific to the Indeed connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed inÂ  [a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


Prerequisites
-------------


To connect to your Indeed account and create a DataSet, you must have an Indeed publisher key. You can obtain a publisher key atÂ [https://ads.indeed.com/jobroll/xmlfeed](https://ads.indeed.com/jobroll/xmlfeed "https://ads.indeed.com/jobroll/xmlfeed").Â 


Connecting to Your Indeed Account
---------------------------------


This section enumerates the options in theÂ **Credentials**Â andÂ **Details**Â panes in the Indeed Connector page.Â The components of the other panes in this page,Â **SchedulingÂ**andÂ **Name & Describe Your DataSet,** are universal across most connector types and are discussed in greater length inÂ  [a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


### Credentials Pane


This pane contains fields for entering credentials to connect to your Indeed account. The following table describes what is needed for each field: Â 




| Field | Description |
| --- | --- |
| Publisher Key | Enter your Indeed publisher key.Â You can obtain a publisher key atÂ [https://ads.indeed.com/jobroll/xmlfeed](https://ads.indeed.com/jobroll/xmlfeed "https://ads.indeed.com/jobroll/xmlfeed").Â  |


Once you have entered valid Indeed credentials, you can use the same account any time you go to create a new Indeed DataSet. You can manage connector accounts in the **Accounts** tab in the Data Center. For more information about this tab, see [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


### Details Pane


This pane contains a primaryÂ **Reports**Â menu, along with various other menus that allow you to configure your report.




| Menu | Description |
| --- | --- |
| Report | Select the Indeed report you want to run.Â Currently only one report type is available.

|  |  |
| --- | --- |
| Search | Returns data about Indeed job searches. |

 |
| Search | Enter the keyword you want to filter by in your report. For example, if you enteredÂ Aircraft repair technician, your report would return job listingsÂ forÂ that profession.Â  |
| Job Type | Select a job type to filter your results by. |
| Country | Select the country you want to retrieve job listings for. |
| Location (Optional) | Enter the U.S. city you want to retrieve job listings for, in city, state format. For example: Seattle, Washington |
| Sort | Select whether you want to sort by date or relevance. **Date** sorts the job listings by job posting date. **Relevance** sorts by search relevance. |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, seeÂ [Â a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


Â