---
title : Amazon Redshift Advanced Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:39:00
url : https://domo-support.domo.com/s/article/360043436033
linked_kbs :  ['https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043436033', 'https://domo-support.domo.com/s/article/360043630093', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003900
views : 4,025
created_date : 2022-10-24 21:16:00
last updated : 2022-10-24 22:39:00
---



Intro
-----


Amazon Redshift is a hosted data warehouse project that is part of the larger cloud computing platform Amazon Web Services.Â Redshift handles analytics workloads on large scale DataSets stored by a column-oriented DBMS principle. You can use Domo'sÂ Amazon RedshiftÂ Connector to pull data from yourÂ RedshiftÂ database and compile custom reports. You indicate the data you want by inputting an SQL query. For more information about theÂ Redshift API, visit their website. ([http://docs.aws.amazon.com/redshift/...e/Welcome.html)](http://docs.aws.amazon.com/redshift/latest/APIReference/Welcome.html)  


You connect to your Redshift database in the Data Center. This topic discusses the fields and menus that are specific to the Redshift connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).


**Note:** Depending on your network's structure, you may need to whitelist any IP addresses necessary for the data connector to retrieve data. Contact your IT administrator for assistance.
Prerequisites
-------------


To connect to aÂ Redshift database and create a DataSet, you must have the following:



* The username and password you use to log into yourÂ Redshift database
* The host name for the database server (e.g. [db.company.com](http://db.company.com)).
* The port number for the database
* The database name


CA certificate text or URL path is required *only* if you select **CertificateÂ String** or **URL Path**, respectively, in the **CertificateÂ Format** menu.


Before you can connect to a Redshift database, you must also whitelist a number of IP addresses on your database server on theÂ portÂ you want to connect to. For the full list of IP addresses, see [Whitelisting IP Addresses for Connectors](..\allowlisting_ip_addresses_for_connectors__federated_adapters\index.html "Whitelisting IP Addresses for Connectors").


Connecting to Your Redshift Account
-----------------------------------


This section enumerates the options in the **Credentials** and **Details** panes in the Redshift Connector page.Â The components of the other panes in this page, **Scheduling**Â and **Name & Describe Your DataSet**, are universal across most connector types and are discussed in greater length inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md "Adding a DataSet Using a Data Connector").


### Credentials Pane


This pane contains fields for entering credentials to connect to your Redshift account. The following table describes what is needed for each field: Â 




| Field | Description |
| --- | --- |
| JDBC Driver | Select the JDBC driver you want to use to connect.Â  |
| Host | Enter the host name for the SQL database. For example: [db.company.com](http://db.company.com) |
| Database | Enter the name of the SQL database. |
| Username | Enter your Redshift username. |
| Password | Enter your Redshift password. |
| Database Port | Enter the port number for the database. |
| Certificate Format | SelectÂ the certificate format. If you do not want to include a certificate, selectÂ **No Certificate**. If you selectÂ **CertificateÂ String**, you must paste the text for your certificate in theÂ **Certificate** field. If you selectÂ **URL Path**, you must enter the URL where your certificate is located in theÂ **Certificate** field. |
| Certificate | Paste the text for your CA certificate or enter the URL where your certificate is located.Â This is optional. If you do not want to include a certificate, select **No Certificate** in the **CertificateÂ Format** menu. |


Once you have entered valid Redshift credentials, you can use the same account any time you go to create a new Redshift DataSet. You can manage connector accounts in the **Accounts** tab in the Data Center. For more information about this tab, see [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


### Details Pane


In this pane you create an SQL query to pull data from your database. You can also choose a specific database table and columns and specify a timeout value.




| Menu | Description |
| --- | --- |
| Query Type | Select the type of query you want to execute. |
| Query | Enter the Structured Query Language (SQL) query to use in selecting the data you want.
For example:
`select * from Employee` |
| Parameter Date Format | If you have used theÂ **Date** data type in theÂ **Query Parameters** field, enter a parameter date format here. This is optional. If you leave this blank, Domo will attempt to infer the date format. However, for the most accurate query results, you should provide the date format.
All of the following date formats are accepted:

| Format | Example |
| --- | --- |
| EEE MMM dd HH:mm:ss z yyyy | Mon Dec 02 13:23:22 MST 2013 |
| yyyy-MM-dd'T'HH:mm:ss.S+S | 2014-11-30T12:34:56.000+0000 |
| yyyy-MM-dd'T'HH:mm:ss.SÂ  | 2014-06-10T07:34:16.671 |
| yyyy-MM-dd HH:mm:ss.SÂ  | 2014-12-22 08:41:33.397 |
| yyyy-MM-dd HH:mm:ssXXXÂ  | 2014-06-10 05:34:16+00:00 |
| yyyy-MM-dd'T'HH:mm:ss'Z'Â  | 2013-03-25T08:45:00Z |
| yyyy-MM-dd'T'HH:mm:ssXXXÂ  | 2014-06-10T05:34:16+00:00 |
| yyyy-MM-dd'T'HH:mm:ss.SSS'Z'Â  | 2013-03-25T08:45:00.123Z |
| EEE,Â dd MMM yyyy HH:mm:ss zÂ  | Mon, Jan 20 2014 17:01:38 EST |
| MMM dd, yyyyÂ  | March 20, 2014 |
| yyyy MMM ddÂ  | 2014 March 20 |
| MMM dd yyyyÂ  | March 20 2014 |
| MM/dd/yyÂ  | 03/20/14 |
| dd/MM/yyÂ  | 20/03/14 |
| MM-dd-yyÂ  | 03-20-14 |
| dd-MM-yyÂ  | 20-03-14 |
| yyyy/MM/ddÂ  | 2014/03/20 |
| yyyy-MM-ddÂ  | 2014-03-20 |
| yyyy-MMM-ddÂ  | 2014-March-20 |
| MM/dd/yyyyÂ  | 03/20/2014 |
| dd/MM/yyyyÂ  | 20/03/2014 |
| MM-dd-yyyyÂ  | 03-20-2014 |
| dd-MM-yyyyÂ  | 20-03-2014 |
| dd-MMM-yyyyÂ  | 20-March-2014 |
| MMM-dd-yyyyÂ  | March-20-2014 |
| yyyy-MMÂ Â Â Â  | 2014-03 |

 |
| Database Tables | Select the database table you want to appear in your report. |
| Table Columns | Select allÂ table columns you want to appear in your report.Â  |
| Query Helper | Revise this query if desired. |
| Query Timeout | Enter the connector timeout value in minutes. |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, seeÂ [AddingÂ a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).Â