---
title : Constant Contact Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:40:00
url : https://domo-support.domo.com/s/article/360042926594
linked_kbs :  ['https://domo-support.domo.com/s/article/360042926594', 'https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003791
views : 3,966
created_date : 2022-10-24 21:15:00
last updated : 2022-10-24 22:40:00
---



Intro
-----


Constant Contact offers web-based email marketing services. Â  To learn more about the Constant Contact API, visit their page ([https://developer.constantcontact.co...ion-index.html](https://developer.constantcontact.com/docs/developer-guides/api-documentation-index.html "https://developer.constantcontact.com/docs/developer-guides/api-documentation-index.html")).


You connect to your Constant Contact account in the Data Center. This topic discusses the fields and menus that are specific to the Constant Contact connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


Prerequisites
-------------


To connect to your Constant Contact account and create a DataSet, you must have your Constant Contact username and password.


Connecting to Your Constant Contact Account
-------------------------------------------


This section enumerates the options in theÂ **Credentials**Â andÂ **DetailsÂ**panes in the Constant Contact Connector page.Â The components of the other panes in this page,Â **SchedulingÂ**andÂ **Name & Describe Your DataSet,** are universal across most connector types and are discussed in greater length inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


### Credentials Pane


The Domo Constant Contact connector uses OAuth to connect, so there is no need to enter credentials within Domo. ClickÂ **Connect**Â (or selectÂ **Add Account**Â ifÂ you haveÂ existing Constant Contact accounts in Domo) to open the Constant Contact OAuth screen where you can enter your Constant Contact username and password. Once you have entered valid Constant Contact credentials, you can use the same account any time you go to create a new Constant Contact DataSet. You can manage connector accounts in theÂ **Accounts**Â tab in theÂ Data Center. For more information about this tab, seeÂ [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


### Details Pane


This pane contains a menu from which you select your desired report type, along with various options for configuring your report.




| Menu | Description |
| --- | --- |
| Report | Select the Constant Contact report you want to run.Â The following reports are available:

|  |  |
| --- | --- |
| Contact Action Summary | Returns a list of the recent emails sent to a specific contact and a summary of the actions the contact took on that email for the most recent 200 campaigns. |
| Contact Activity Details | Returns the tracking activity data for a given account and contact. |
| Contact Lists | Returns a list of contact lists in your account. |
| Contacts | Returns all contacts in your account. |
| Email Campaigns | Returns all email campaigns in user's account. |

 |
| Contact ID | Select the contact you want to retrieve information for. |
| Contact Status | Select the status you want to filter your report data by. |
| Include Subresource? | Select whether you want to include subresources in your report. |
| Tracking Activity Types | Select the tracking activity types you want to retrieve data for. |
| Updated After Date | Select a date. The report will return all data updated after this date.Â Â  |
| Updated Days Back | Enter a relative number of days back. Every time the report runs, it will return all data updated after this relative number of days. For example, if you entered 7, each time the report ran it would pull data updated within the last 7 days.Â  |
| DurationÂ  | Select whether you want to pull data for a specific date or a date range.Â  |
| Report DateÂ  | Select whether the report data is for a specific date or for a relative number of days back from today.Â  |
| Select Specific DateÂ  | Select the date for the report.Â  |
| Days Back | Enter the number of past days that should appear in the report.Â Â  |
| Start Date | Specify whether theÂ first date in your date range is a specific or relative date.Â You select the last date in your range inÂ **End Date**.Â  |
| End Date | Specify whether the second date in your date range is a specific or relative date. You select the first date in your range inÂ **Start Date**.Â Â  |
| Select Specific Start Date | SelectÂ the first date in your date range.Â  |
| Select Specific End Date | Select the second date in your date range.Â  |
| Days Back to Start From | Enter the number of the farthest day back that should be represented in the report. Combine withÂ **Days Back to End At**Â to create a range of represented days.
For example, if you enteredÂ 10Â forÂ **Days Back to Start From**Â andÂ 5Â forÂ **Days Back to End At**, the report would contain data forÂ 10 days ago up untilÂ 5 days ago. |
| Days Back to End At | Enter the number of the most recent day back that should be represented in the report. Combine withÂ **Days Back to Start From**Â to create a range of represented days.
For example, if you enteredÂ 10Â forÂ **Days Back to Start From**Â andÂ 5Â forÂ **Days Back to End At**, the report would contain data forÂ 10 days ago up untilÂ 5 days ago. |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, seeÂ [AddingÂ a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


FAQs
----


##### What version of the Constant Contact API does this connector use?


This connector uses version 3 of the Constant Contact API (<https://api.cc.email/v3>).


##### What endpoint does each report call in this connector?




| Report Name | Endpoint URL |
| --- | --- |
| Contact Action Summary | /reports/contact\_reports/{contactId}/activity\_summary |
| Contact Activity Details | /reports/contact\_reports/{contactId}/activity\_details |
| Contact Lists | /contact\_lists |
| Contacts | /contacts |
| Email Campaigns | /emails |


##### How do I know my Constant Contact credentials are secure?


The login process uses the OAuth process, so your Constant Contact credentials are never seen or stored by Domo. This keeps your login secure. You can revoke Domo's access to your account at any time.Â Â Â Â 


##### Can I use the same account to create multiple DataSets?


Yes.


##### How often can the data be updated?


As often as needed.


##### Are there any API limits I should be aware of?


If the API reaches the daily call limit, the API key will not be able to make calls until 12:00 am the next day.Â