---
title: Amazon Redshift SSH Connector
url: https://domo-support.domo.com/s/article/360042931614
linked_kbs:  ['[https://domo-support.domo.com/s/knowledge-base/](https://domo-support.domo.com/s/knowledge-base/)', '[https://domo-support.domo.com/s/](https://domo-support.domo.com/s/)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZammGAC](https://domo-support.domo.com/s/topic/0TO5w000000ZammGAC)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZanLGAS](https://domo-support.domo.com/s/topic/0TO5w000000ZanLGAS)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZaojGAC](https://domo-support.domo.com/s/topic/0TO5w000000ZaojGAC)', '[https://domo-support.domo.com/s/article/360042926274](https://domo-support.domo.com/s/article/360042926274)', '[https://domo-support.domo.com/s/article/360043630093](https://domo-support.domo.com/s/article/360043630093)', '[https://domo-support.domo.com/s/article/360042926054](https://domo-support.domo.com/s/article/360042926054)', '[https://domo-support.domo.com/s/article/360042931614](https://domo-support.domo.com/s/article/360042931614)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZaojGAC/database-connectors](https://domo-support.domo.com/s/topic/0TO5w000000ZaojGAC/database-connectors)', '[https://domo-support.domo.com/s/article/360043429933](https://domo-support.domo.com/s/article/360043429933)', '[https://domo-support.domo.com/s/article/360043429953](https://domo-support.domo.com/s/article/360043429953)', '[https://domo-support.domo.com/s/article/360042925494](https://domo-support.domo.com/s/article/360042925494)', '[https://domo-support.domo.com/s/article/4408174643607](https://domo-support.domo.com/s/article/4408174643607)', '[https://domo-support.domo.com/s/article/360043429913](https://domo-support.domo.com/s/article/360043429913)', '[https://domo-support.domo.com/s/login/](https://domo-support.domo.com/s/login/)']
article_id: 000003899
views: 2,211
created_date: 2022-10-24 21:16:00
last updated: 2022-10-24 22:39:00
---



Intro
-----


Amazon Redshift is a hosted data warehouse project that is part of the larger cloud computing platform Amazon Web Services.  You can use Domo's Amazon Redshift SSH Connector to create a secure, encrypted connection with your Redshift database to bring your data into Domo and start making better decisions. Simply input your own SSH credentials and write a query to pull the data you need, and ready to go. For more information about the Redshift API, visit their website. ( [http://docs.aws.amazon.com/redshift/...\_commands.html](http://docs.aws.amazon.com/redshift/latest/dg/c_SQL_commands.html "http://docs.aws.amazon.com/redshift/latest/dg/c_SQL_commands.html") )


The Amazon Redshift SSH connector is a "Database" connector, meaning it retrieves data from a database based on a query. In the Data Center, you can access the connector page for this and other Database connectors by clicking **Database** in the toolbar at the top of the window.


You connect to your Redshift database in the Data Center. This topic discusses the fields and menus that are specific to the Redshift SSH connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed in [Adding a DataSet Using a Data Connector](/s/article/360042926274).




 


**Note:** Depending on your network's structure, you may need to whitelist any IP addresses necessary for the data connector to retrieve data. Contact your IT administrator for assistance.



Prerequisites
-------------


To connect to a Redshift database and create a DataSet, you must have the following:


* The hostname of the UNIX server you are SSH-tunneling through
* The SSH username and password for your UNIX account
* The SSH port number
* The SSH private key
* The Redshift database hostname or IP address
* The Redshift database name
* The username and password you use to log into your Redshift database
* The port number for the Redshift database
* The Redshift database name


CA certificate text or URL path is required *only* if you select **Certificate String** or **URL Path**, respectively, in the **Certificate Format** menu.







**Note:** Domo does not support the SSH keys generated using ssh-keygen. The SSH keys need to be the DES or RSA keys (in PEM format) generated by OpenSSL.




### Creating a Redshift account


To create a Redshift user account, contact your Redshift Database Administrator (DBA) and have them follow these directions:  
  
By default, only the master user that you created when you launched the cluster has access to the initial database in the cluster. To grant other users access, you must create one or more user accounts. Database user accounts are global across all the databases in a cluster; they do not belong to individual databases.  
  
Use the CREATE USER command to create a new database user. When you create a new user, you specify the name of the new user and a password. A password is required. It must have between 8 and 64 characters, and it must include at least one uppercase letter, one lowercase letter, and one numeral.  
  
For example, to create a user named GUEST with password ABCd4321, issue the following command:  
  
`create user guest password 'ABCd4321';` 


### Whitelisting IP addresses


Before you can connect to a Redshift database, you must also whitelist a number of IP addresses on your database server on the port you want to connect to. For the full list of IP addresses, see [Whitelisting IP Addresses for Connectors](/s/article/360043630093 "Whitelisting IP Addresses for Connectors").


Connecting to Your Redshift Database Using SSH
----------------------------------------------


This section enumerates the options in the **Credentials** and **Details** panes in the Redshift SSH Connector page. The components of the other panes in this page, **Scheduling** and **Name & Describe Your DataSet**, are universal across most connector types and are discussed in greater length in  [Adding a DataSet Using a Data Connector.](/s/article/360042926274)


### Credentials Pane


This pane contains fields for entering credentials to connect to your database. The following table describes what is needed for each field:  




| Field | Description |
| --- | --- |
| SSH Server Hostname | Enter the hostname of the UNIX server you are SSH-tunneling through. |
| SSH Username | Enter the username for your UNIX account. |
| SSH Password | Enter the password for your UNIX account. |
| SSH Port | Enter the port number used for SSH. |
| SSH Private Key | Enter the SSH private key. |
| Database Hostname | Enter the Redshift database hostname or URL. |
| Database Name | Enter the Redshift database name. |
| Database Username | Enter your username for the Redshift database. |
| Database Password | Enter your password for the Redshift database. |
| Database Port | Enter the Redshift database port number. |
| Certificate Format | Select the certificate format. If you do not want to include a certificate, select **No Certificate**. If you select **Certificate String**, you must paste the text for your certificate in the **Certificate** field. If you select **URL Path**, you must enter the URL where your certificate is located in the **Certificate** field.    |
| Certificate | Paste the text for your CA certificate or enter the URL where your certificate is located. This is optional. If you do not want to include a certificate, select **No Certificate** in the **Certificate Format** menu. |


Once you have entered valid Redshift credentials, you can use the same account any time you go to create a new Redshift SSH DataSet. You can manage connector accounts in the Accounts tab in the Data Center. For more information about this tab, see [Managing User Accounts for Connectors](/s/article/360042926054 "Managing User Accounts for Connectors").


### Details Pane


In this pane you create an SQL query to pull data from your database. You can also choose a specific database table and columns and specify which columns you want to appear in your report.




| Menu | Description |
| --- | --- |
| Query | Enter the Structured Query Language (SQL) query to use in selecting the data you want. For example:
select \* from Employee |
| Fetch Size | Enter the fetch size for memory performance. If you leave this blank, a default value of 1000 is used. If you get an "Out of Memory" error, decrease the fetch size. |
| Database Tables | Select the database table you want to appear in your report. |
| Table Columns  | Select all table columns you want to appear in your report.   |
| Query Helper | Based on the selected columns in the **Table Columns** field, the Query Helper builds a sample query for you. You can revise the query if desired. |
| Boolean Format | Select the Boolean format to be used. The following table describes the available formats:

|  |  |
| --- | --- |
| 1/0 | True values return 1, and false values return 0. |
| t/f | True values return t, and false values return f. |
| T/F | True values return t, and false values return f. |
| true/false | True values return true, and false values return false. |

 |
| Query Timeout | Enter the connector timeout value in minutes. |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, see [Adding a DataSet Using a Data Connector](/s/article/360042926274).


Troubleshooting
---------------


If you run into connection issues...


* Verify the connection works using pgAdmin.
* Confirm all of the necessary Domo IPs have been whitelisted (see [Whitelisting IP addresses,](#h_17aaa1b7-c06f-4970-ae93-758d1923ce4b) above).
* Run a profile on the SQL query.
