---
title : Neurio Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:42:00
url : https://domo-support.domo.com/s/article/360043435793
linked_kbs :  ['https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/article/360043435793', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003333
views : 2,010
created_date : 2022-10-24 21:12:00
last updated : 2022-10-24 22:42:00
---



Intro
-----


Neurio is a residential electricity usage monitoring service. Using smart devices installed in the home, Neurio can report your energy usage through a web-based dashboard. To learn more about the NeurioÂ API, visit their page ([https://api-docs.neur.io/](https://api-docs.neur.io/ "https://api-docs.neur.io/")).


You connect to your Neurio account in the Data Center. This topic discusses the fields and menus that are specific to the Neurio connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).


Prerequisites
-------------


To connect to your Neurio account and create a DataSet, you must have the email address and password you use to log into Neurio.


Connecting to Your Neurio Account
---------------------------------


This section enumerates the options in theÂ **Credentials**Â andÂ **Details**Â panes in the Neurio Connector page.Â The components of the other panes in this page,Â **SchedulingÂ**andÂ **Name & Describe Your DataSet,** are universal across most connector types and are discussed in greater length inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).


### Credentials Pane


The Domo Neurio connector uses OAuth to connect, so there is no need to enter credentials within Domo. ClickÂ **Connect**Â (or selectÂ **Add Account**Â ifÂ you haveÂ existing Neurio accounts in Domo) to open the Neurio OAuth screen where you can enter your Neurio credentials. Once you have entered valid Neurio credentials, you can use the same account any time you go to create a new Neurio DataSet. You can manage connector accounts in theÂ **Accounts**Â tab in theÂ Data Center. For more information about this tab, seeÂ [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


**Note:**Â If you are already logged into NeurioÂ when you connect in Domo, you are authenticated automatically when you click **Add account**. If you want to connect to an account that is different from the one you are logged into, you must first log out of Neurio.
### Details Pane


This pane contains a primaryÂ **Reports**Â menu, along with various other menus which may or may not appear depending on the report type you select.




| Menu | Description |
| --- | --- |
| Report | Select the Neurio report you want to run.Â The following reports are available:

|  |  |
| --- | --- |
| Appliances | Returns data about Neurio appliances for a specified location. |
| Appliance Events | Returns data about Neurio appliance events for a specified location. |
| Appliance Statistics for a Specific Appliance | Returns statistical data for a specific Neurio appliance within a given time range. |
| Appliance Statistics by Location | Returns statistical data for appliances in a specified location within a given time range. |
| Energy Statistics | Returns statistics for energy consumed within a given time interval. |
| Last Sample | Returns the last sample returned by a given sensor. |
| Recent Appliance Events | Returns data about appliance events created or updated after a specified time.Â  |
| Recent Samples | Returns recent samples, one sample per second for up to the last 2 minutes. |
| Samples | Returns a given sensor's samples for a specified time period. |
| Specific Appliance | Returns data about a specified Neurio appliance. |

 |
| Location ID | Enter the ID for the location you want to retrieve data for. |
| Sensor ID | Select the sensor you want to retrieve data for. |
| Appliance ID | Select the appliance you want to retrieve data for. |
| Granularity | Select how you want the data in your report to be broken down. For example, if you chooseÂ **Days**, the data will be broken down by day. |
| Frequency | Enter the frequencyÂ of the sampled data. ThisÂ should be a multiple of 5 when using **Minutes**Â granularity. |
| DurationÂ  | Select whether you want to pull data for a specific date or a date range.Â  |
| Report DateÂ  | Select whether the report data is for a specific date or for a relative number of days back from today.Â  |
| Select Specific DateÂ  | Select the date for the report.Â  |
| Days Back | Enter the number of past days that should appear in the report.Â Â  |
| Start Date | Specify whether theÂ first date in your date range is a specific or relative date.Â You select the last date in your range inÂ **End Date**.Â  |
| End Date | Specify whether the second date in your date range is a specific or relative date. You select the first date in your range inÂ **Start Date**.Â Â  |
| Select Specific Start Date | SelectÂ the first date in your date range.Â  |
| Select Specific End Date | Select the second date in your date range.Â  |
| Days Back to Start From | Enter the number of the farthest day back that should be represented in the report. Combine withÂ **Days Back to End At**Â to create a range of represented days.
For example, if you enteredÂ 10Â forÂ **Days Back to Start From**Â andÂ 5Â forÂ **Days Back to End At**, the report would contain data forÂ 10 days ago up untilÂ 5 days ago. |
| Days Back to End At | Enter the number of the most recent day back that should be represented in the report. Combine withÂ **Days Back to Start From**Â to create a range of represented days.
For example, if you enteredÂ 10Â forÂ **Days Back to Start From**Â andÂ 5Â forÂ **Days Back to End At**, the report would contain data forÂ 10 days ago up untilÂ 5 days ago. |


### Other PanesÂ


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, seeÂ [AddingÂ a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).