---
title : IBM Informix SSH Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:39:00
url : https://domo-support.domo.com/s/article/360043433413
linked_kbs :  ['https://domo-support.domo.com/s/article/360043433413', 'https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003578
views : 3,983
created_date : 2022-10-24 21:13:00
last updated : 2022-10-24 22:39:00
---



Intro
-----


IBM Informix is a fast and scalable database server that manages traditional relational, object-relational, and dimensional databases. Use Domo's Informix SSHÂ connector to retrieve Informix data based on an SQL query. To learn more about Informix, visit their page ([https://www.ibm.com/analytics/us/en/...logy/informix/](https://www.ibm.com/analytics/us/en/technology/informix/ "https://www.ibm.com/analytics/us/en/technology/informix/")).


You connect to Informix dataÂ in the Data Center. This topic discusses the fields and menus that are specific to the Informix connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


Prerequisites
-------------


To connect to your Informix account and create a DataSet, you must have the following:



* The username and password you use to log into your Informix database
* The port number for the Informix database
* The Informix database hostname or IP address
* The Informix server name
* The host name or URL of the UNIX server to SSH-tunnel through
* The username and password for the UNIX account
* The SSH port number
* The SSH private key (either DES or RSA)


Before you can connect to an InformixÂ database, you must also whitelist a number of IP addresses on your database server on theÂ portÂ you want to connect to. For the full list of IP addresses, see Whitelisting IP Addresses for Connectors.


**Note:** Domo does not support the SSH keys generated using ssh-keygen. The SSH keys need to be the DES or RSA keys (in PEM format) generated by OpenSSL.
Connecting to Your Informix Account
-----------------------------------


This section enumerates the options in the **Credentials** and **Details** panes in the Informix Connector page.Â The components of the other panes in this page, **Scheduling**Â and **Name & Describe Your DataSet**, are universal across most connector types and are discussed in greater length inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


### Credentials Pane


This pane contains fields for entering credentials to connect to your Informix account. The following table describes what is needed for each field: Â 




| Field | Description |
| --- | --- |
| SSHÂ Hostname | Enter the hostname or URL of the UNIX server to SSH-tunnel through. |
| SSH User | Enter the SSH username for your UNIX account. |
| SSH Password | Enter the SSH password for your UNIX account. |
| SSH Key | Enter the SSH private key. |
| SSH Port | Enter the port number for your UNIX account. |
| Database Hostname | Enter the host name for the Informix database. For example: [db.company.com](http://db.company.com) |
| Database Username | Enter your Informix username. |
| Database Password | Enter yourÂ InformixÂ password. |
| InformixÂ Server Name | Enter the name of your Informix server. |
| Database Port Number | Enter your Informix port number. |


Once you have entered valid Informix credentials, you can use the same account any time you go to create a new Informix DataSet. You can manage connector accounts in the **Accounts** tab in the Data Center. For more information about this tab, see [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


### Details Pane


This pane contains a single menu in which you enter your SQL query.




| Menu | Description |
| --- | --- |
| Query | Enter the SQL query for the Informix data you want to pull into Domo.
Â  |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, seeÂ [AddingÂ a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


Â 


Â