---
title : Workbench 5 Overview
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:41:00
url : https://domo-support.domo.com/s/article/360042932554
linked_kbs :  ['https://domo-support.domo.com/s/article/360043429913', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/article/360042932554', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/knowledge-base']
article_id : 000004809
views : 5,143
created_date : 2022-10-24 22:31:00
last updated : 2022-10-24 22:41:00
---



**What can Workbench 5 do for you?**



* Securely upload DataSets to Domo using helpful interface components
* Upload data manually or on a schedule
* Create groups of DataSet jobs that run on the same schedule
* Import and export job files
* Preview and validate jobs before you run them
* Add, create, save, and delete accounts
* Add, create, save, delete, open, preview, and cancel jobs
* Revert back to a previous version of a job you saved
* Add/delete transforms to/from jobs, which includes the following:



	+ Add new columns
	+ Change date format
	+ Encrypt sensitive data in specific columns
	+ Filter columns in the DataSet
	+ Set the time zone for the DataSet job
	+ Replace column values in the DataSet
	+ Combine the DataSet with another DataSet



* Export/import Excel, CSV, QuickBooks, OLAP, ODBC, JSON, and XML file types
* View logs
* Send logs as a zip file
* Run logs from the command line
* Add and manage plugins for using Workbench
* Set up notifications for DataSet jobs that can email you if DataSets are uploaded successfully or if it experiences an error


To read a white paper about making your Workbench data more secure in Domo by means of encryption, click here: [Whitepaper\_Domo+Data+Security+and+Encryption+Draft.pdf](https://domosoftware.sharepoint.com/:b:/s/CS-Edu-PublicFiles/Ec5lAMNCHyxIrujDa7ZAXFIBo5jv7_53HWgO7lQJdSsbbA?e=pS17jG "Whitepaper_Domo+Data+Security+and+Encryption+Draft.pdf")


**Video - Workbench 5 Overview**


{{< video www.youtube.com/embed/P0lDD4NghsQ >}}