---
title : OmegaFi Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:40:00
url : https://domo-support.domo.com/s/article/360043435913
linked_kbs :  ['https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429913', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043435913']
article_id : 000003322
views : 2,012
created_date : 2022-10-24 21:12:00
last updated : 2022-10-24 22:40:00
---



Intro
-----


OmegaFi is a management tool for fraternal organizations including billing, due collection, fund raising, and record management. To learn more about the OmegaFi API, visit their page ([https://www.omegafi.com/apps/home/ab...y/integration/](https://www.omegafi.com/apps/home/about/technology/integration/ "https://www.omegafi.com/apps/home/about/technology/integration/")).  


You connect to your OmegaFi account in the Data Center. This topic discusses the fields and menus that are specific to the OmegaFi connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed in [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).


Prerequisites
-------------


To connect to your OmegaFi account and create a DataSet, you must have an OmegaFi username and password.


Connecting to Your OmegaFi Account
----------------------------------


This section enumerates the options in the **Credentials** and **Details** panes in the OmegaFi Connector page. The components of the other panes in this page, **Scheduling** and **Name & Describe Your DataSet**, are universal across most connector types and are discussed in greater length in [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md "Adding a DataSet Using a Data Connector").


### Credentials Pane


This pane contains fields for entering credentials to connect to your OmegaFi account. The following table describes what is needed for each field:  




| Field | Description |
| --- | --- |
| Username | Enter your OmegaFi username. |
| Password | Enter your OmegaFi password. |


Once you have entered valid OmegaFi credentials, you can use the same account any time you go to create a new OmegaFi DataSet. You can manage connector accounts in the **Accounts** tab in the Data Center. For more information about this tab, see [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


### Details Pane


This pane contains a single menu from which you select an OmegaFi saved search to pull into Domo.


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, see [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).