# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/datacrew',
                'doc_host': 'https://jaewilson07.github.io',
                'git_url': 'https://github.com/jaewilson07/datacrew',
                'lib_path': 'datacrew'},
  'syms': {'datacrew.core': {'datacrew.core.foo': ('core.html#foo', 'datacrew/core.py')}}}
