---
title : AvidTrak Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:39:00
url : https://domo-support.domo.com/s/article/360043430853
linked_kbs :  ['https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043430853', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003796
views : 2,004
created_date : 2022-10-24 21:15:00
last updated : 2022-10-24 22:39:00
---



Intro
-----


AvidTrakÂ is multi-featured software for call tracking, recording, and analytics for advertising campaigns. To learn more about the AvidTrak API, visit their page ([http://avidtrak.com/Call\_Tracking\_API.php](http://avidtrak.com/Call_Tracking_API.php "http://avidtrak.com/Call_Tracking_API.php")).  


You connect to your AvidTrak account in the Data Center. This topic discusses the fields and menus that are specific to the AvidTrak connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).


Prerequisites
-------------


To connect to your AvidTrak account and create a DataSet, you must have the following:



* An AvidTrak pin code (provided by AvidTrak when you sign up)
* The base URL of your AvidTrak instanceÂ


Connecting to Your AvidTrak Account
-----------------------------------


This section enumerates the options in the **Credentials** and **Details** panes in the AvidTrak Connector page.Â The components of the other panes in this page, **Scheduling**Â and **Name & Describe Your DataSet**, are universal across most connector types and are discussed in greater length inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md "Adding a DataSet Using a Data Connector").


### Credentials Pane


This pane contains fields for entering credentials to connect to your AvidTrak account. The following table describes what is needed for each field: Â 




| Field | Description |
| --- | --- |
| Pin Code | Enter your AvidTrak pin code. |
| Base URL | Enter the URL of your AvidTrak instance. |


Once you have entered valid AvidTrak credentials, you can use the same account any time you go to create a new AvidTrak DataSet. You can manage connector accounts in the **Accounts** tab in the Data Center. For more information about this tab, see [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


### Details Pane


This pane contains a primaryÂ **Reports**Â menu, along with options for selecting the date or date range for the report.




| Menu | Description |
| --- | --- |
| Report | Select the AvidTrak report you want to run.Â The following reports are available:

|  |  |
| --- | --- |
| Geographical Data | Returns geographical data for calls for a selected date or date range. |
| Offline Portal Calls | Returns data for offline portal calls for a selected date or date range. |

 |
| DurationÂ  | Select whether you want to pull data for a specific date or a date range. If you selectÂ **Default**, yesterday's data is pulled.Â  |
| Report DateÂ  | Select whether the report data is for a specific date or for a relative number of days back from today.Â  |
| Select Specific DateÂ  | Select the date for the report.Â  |
| Date Offset | Enter the number of past days that should appear in the report.Â Â  |
| Date From | Specify whether theÂ first date in your date range is a specific or relative date.Â You select the last date in your range inÂ **End Date**.Â  |
| Date To | Specify whether the second date in your date range is a specific or relative date. You select the first date in your range inÂ **Start Date**.Â Â  |
| Select Specific Date From | SelectÂ the first date in your date range.Â  |
| Select Specific Date To | Select the second date in your date range.Â  |
| Date From Offset | Enter the number of the farthest day back that should be represented in the report. Combine withÂ **Days Back to End At**Â to create a range of represented days.
For example, if you enteredÂ 10Â forÂ **Days Back to Start From**Â andÂ 5Â forÂ **Days Back to End At**, the report would contain data forÂ 10 days ago up untilÂ 5 days ago. |
| Date To Offset | Enter the number of the most recent day back that should be represented in the report. Combine withÂ **Days Back to Start From**Â to create a range of represented days.
For example, if you enteredÂ 10Â forÂ **Days Back to Start From**Â andÂ 5Â forÂ **Days Back to End At**, the report would contain data forÂ 10 days ago up untilÂ 5 days ago. |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, seeÂ [AddingÂ a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md). Â