---
title : Clavis Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:40:00
url : https://domo-support.domo.com/s/article/360042929214
linked_kbs :  ['https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360042929214', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003529
views : 2,026
created_date : 2022-10-24 21:13:00
last updated : 2022-10-24 22:40:00
---



Intro
-----


Clavis Insight provides intelligence and analysis of how products and brands perform in online stores. Â To learn more about the ClavisÂ API, reach out to your account representative.  


You connect to your Clavis account in the Data Center. This topic discusses the fields and menus that are specific to the Clavis connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


Prerequisites
-------------


To connect to your Clavis account and create a DataSet, you must have your Clavis username and password.


Connecting to Your Clavis Account
---------------------------------


This section enumerates the options in the **Credentials** and **Details** panes in the Clavis Connector page.Â The components of the other panes in this page, **Scheduling**Â and **Name & Describe Your DataSet**, are universal across most connector types and are discussed in greater length inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


### Credentials Pane


This pane contains fields for entering credentials to connect to your Clavis account. The following table describes what is needed for each field: Â 




| Field | Description |
| --- | --- |
| Username | Enter your Clavis username. |
| Password | Enter your Clavis password. |


Once you have entered valid Clavis credentials, you can use the same account any time you go to create a new Clavis DataSet. You can manage connector accounts in the **Accounts** tab in the Data Center. For more information about this tab, see [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


### Details Pane


This pane contains a primaryÂ **Reports**Â menu, along with various other menus which may or may not appear depending on the report type you select.




| Menu | Description |
| --- | --- |
| Report | Select the Clavis report you want to run.Â The following reports are available:

|  |  |
| --- | --- |
| Content | Returns the rule failures from the Content Integrity report. |
| KPI | Returns the top level scores for each of your metrics for either a single report date or for a date range period. |
| Products | Returns data for availability, rating, number of reviews, price, promotion text and retailer product image. |
| Search Terms | Returns the search term results for a single report date. |

 |
| Classification | Select the classification you want to retrieve data for. |
| Online Store (Optional) | Enter a comma-separated list of stores you want to filter by. |
| Brand (Optional) | Enter a comma-separated list of brandsÂ you want to filter by. |
| Category (Optional)Â  | Enter a comma-separated list of categories you want to filter by. |
| DurationÂ  | Select whether you want to pull data for a specific date or a date range.Â  |
| Report DateÂ  | Select whether the report data is for a specific date or for a relative number of days back from today.Â  |
| Select Specific DateÂ  | Select the date for the report.Â  |
| Days Back | Enter the number of past days that should appear in the report.Â Â  |
| Start Date | Specify whether theÂ first date in your date range is a specific or relative date.Â You select the last date in your range inÂ **End Date**.Â  |
| End Date | Specify whether the second date in your date range is a specific or relative date. You select the first date in your range inÂ **Start Date**.Â Â  |
| Select Specific Start Date | SelectÂ the first date in your date range.Â  |
| Select Specific End Date | Select the second date in your date range.Â  |
| Days Back to Start From | Enter the number of the farthest day back that should be represented in the report. Combine withÂ **Days Back to End At**Â to create a range of represented days.
For example, if you enteredÂ 10Â forÂ **Days Back to Start From**Â andÂ 5Â forÂ **Days Back to End At**, the report would contain data forÂ 10 days ago up untilÂ 5 days ago. |
| Days Back to End At | Enter the number of the most recent day back that should be represented in the report. Combine withÂ **Days Back to Start From**Â to create a range of represented days.
For example, if you enteredÂ 10Â forÂ **Days Back to Start From**Â andÂ 5Â forÂ **Days Back to End At**, the report would contain data forÂ 10 days ago up untilÂ 5 days ago. |
| Aggregation Period | Select whether you want data to be aggregated for the entire selected date range or broken down by day. |
| Competitor Data | Select whether you want to include or exclude competitor data. |
| Manufacturer (Optional) | Enter a comma-separated list of manufacturersÂ you want to filter by. |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, seeÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector"). Â