---
title: Meetup Dashboard App
url: https://domo-support.domo.com/s/article/360043438453
linked_kbs:  ['[https://domo-support.domo.com/s/knowledge-base/](https://domo-support.domo.com/s/knowledge-base/)', '[https://domo-support.domo.com/s/](https://domo-support.domo.com/s/)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZampGAC](https://domo-support.domo.com/s/topic/0TO5w000000ZampGAC)', '[https://domo-support.domo.com/s/topic/0TO5w000000Zan9GAC](https://domo-support.domo.com/s/topic/0TO5w000000Zan9GAC)', '[https://domo-support.domo.com/s/article/360043438453](https://domo-support.domo.com/s/article/360043438453)', '[https://domo-support.domo.com/s/topic/0TO5w000000Zan9GAC/available-apps](https://domo-support.domo.com/s/topic/0TO5w000000Zan9GAC/available-apps)', '[https://domo-support.domo.com/s/article/360043429933](https://domo-support.domo.com/s/article/360043429933)', '[https://domo-support.domo.com/s/article/360043429953](https://domo-support.domo.com/s/article/360043429953)', '[https://domo-support.domo.com/s/article/360042925494](https://domo-support.domo.com/s/article/360042925494)', '[https://domo-support.domo.com/s/article/360043429913](https://domo-support.domo.com/s/article/360043429913)', '[https://domo-support.domo.com/s/article/4408174643607](https://domo-support.domo.com/s/article/4408174643607)', '[https://domo-support.domo.com/s/login/](https://domo-support.domo.com/s/login/)']
article_id: 000004191
views: 1,084
created_date: 2022-10-24 21:26:00
last updated: 2022-10-24 22:42:00
---



Intro
-----


Meetup is a social networking site that helps members anywhere in the world find or start offline meetings with people of similar interests.


Requirements and Notes
----------------------


Login credentials required  
Default Date Range: pulls all available data


Usage
-----


* Meetup Pulse: Your different group activities at a glance


	+ Recent RSVPs
	+ Activity for All Your Groups
	+ New Members
	+ Confirmed RSVPs
* Specific Group Activity: Quick insight into upcoming events and activity


	+ Comments Trend
	+ New Members Trend
	+ Group Photos
	+ Scheduled Events
	+ People Commenting
* Specific Group Demographics: Where do group members live and what are their interests?


	+ Members
	+ Members' Hometown
	+ Member Bios / Interests
	+ Member List


Authentication
--------------




| Credential | Description |
| --- | --- |
| Email | This is your email address with access to Meetup |
| Password | This is your password for the email with access to Meetup |


Dashboard Reports
-----------------


For report descriptions, see Meetup Connector.




| Report | Schedule Update Setting | Parameters | Selection |
| --- | --- | --- | --- |
| Activity Feed | Replace | Report | Activity Feed |
| Events | Replace | Report | Events |
| Group URL Name | Your entered group URL |
| Limited Events | False |
| Status |   |
| Text Format | Plain |
| Event ID |   |
| Member ID |   |
| Group ID |   |
| RSVP |   |
| Venue ID |   |
| Members | Replace | Report | Members |
| Group URL Name | Your entered group URL |
| Member ID |   |
| Group ID |   |
| Service |   |
| Comments | Replace | Report | Comments |
| Group URL Name | Your entered group URL |
| Group ID |   |
| Photos | Replace | Report | Photos |
| Group URL Name | Your entered group URL |
| Event ID |   |
| Member ID |   |
| Group ID |   |
| Photo Album ID |   |
| Photo ID |   |
| Tagged |   |
| Profiles | Replace | Report | Profiles |
| Group URL Name | Your entered group URL |
| Status | Active |
|   |   | Member ID |   |
| Group ID |   |
| Role |   |


