---
title: Setting Up Direct Upload in Workbench 5
url: https://domo-support.domo.com/s/article/360043437493
linked_kbs:  ['[https://domo-support.domo.com/s/knowledge-base/](https://domo-support.domo.com/s/knowledge-base/)', '[https://domo-support.domo.com/s/](https://domo-support.domo.com/s/)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZammGAC](https://domo-support.domo.com/s/topic/0TO5w000000ZammGAC)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZaoPGAS](https://domo-support.domo.com/s/topic/0TO5w000000ZaoPGAS)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZapTGAS](https://domo-support.domo.com/s/topic/0TO5w000000ZapTGAS)', '[https://domo-support.domo.com/s/article/360043437233](https://domo-support.domo.com/s/article/360043437233)', '[https://domo-support.domo.com/s/article/360043437493](https://domo-support.domo.com/s/article/360043437493)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZapTGAS/workbench-5](https://domo-support.domo.com/s/topic/0TO5w000000ZapTGAS/workbench-5)', '[https://domo-support.domo.com/s/article/360043429933](https://domo-support.domo.com/s/article/360043429933)', '[https://domo-support.domo.com/s/article/360043429953](https://domo-support.domo.com/s/article/360043429953)', '[https://domo-support.domo.com/s/article/360042925494](https://domo-support.domo.com/s/article/360042925494)', '[https://domo-support.domo.com/s/article/4408174643607](https://domo-support.domo.com/s/article/4408174643607)', '[https://domo-support.domo.com/s/article/360043429913](https://domo-support.domo.com/s/article/360043429913)', '[https://domo-support.domo.com/s/login/](https://domo-support.domo.com/s/login/)']
article_id: 000004829
views: 2,176
created_date: 2022-10-24 22:31:00
last updated: 2022-10-24 22:41:00
---



Direct upload is designed to limit load and increase upload speeds for Workbench users. It is available only when using the "External Process File Provider" transport method for CSV data. Follow the steps in this section to set up direct upload of data in Workbench. Remember to save the job and validate the data types throughout the process to not lose your work.


The CSV file must be in the correct format and the steps outlined below must be followed in the correct order for direct upload to work.




 

**Important:**Following the direct upload setup process as shown below. is essential for successful uploads. Be sure not to turn on direct upload until the end of the process.



**To set up direct upload in Workbench,**


1. Add a new CSV DataSet job to Workbench, making sure to do the following:


	1. Set the **Transport Type** to **External process provider**.
	2. In the **Reader Type** menu, select CSV.  
	 For more information about configuring CSV jobs in Workbench, see [Connecting to CSV Data in Workbench 5](/s/article/360043437233 "Connecting to CSV Data in Workbench 5").
2. In the **Configure** tab, under **Data**, click the **Edit**button under "Source" then do the following:


	1. Configure the **Program executable** field with the connection needed.
	2. In the **Arguments** field, set arguments as needed.
	3. In **Output File Path**, select the file path for the CSV file.  
	 The file type can be CSV or GZIP. GZIP files will have the fastest upload times.
	4. Check the **Direct Upload** box.
	5. Click **Apply**.   
	   
	 *Do not enable Direct Upload yet!*
3. Click the **Edit** button under "Processing," deselect the box for **First row contains column headers**, then click **Apply**.
4. Click the **Schema** tab.
5. Set/rename **Destination** **C****olumn** names (as column names do not appear for CSV files by default) and validate the data types for the columns.
6. Run the job.
