---
title: Digital Traffic App
url: https://domo-support.domo.com/s/article/360042933474
linked_kbs:  ['[https://domo-support.domo.com/s/knowledge-base/](https://domo-support.domo.com/s/knowledge-base/)', '[https://domo-support.domo.com/s/](https://domo-support.domo.com/s/)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZampGAC](https://domo-support.domo.com/s/topic/0TO5w000000ZampGAC)', '[https://domo-support.domo.com/s/topic/0TO5w000000Zan9GAC](https://domo-support.domo.com/s/topic/0TO5w000000Zan9GAC)', '[https://domo-support.domo.com/s/article/360042933474](https://domo-support.domo.com/s/article/360042933474)', '[https://domo-support.domo.com/s/topic/0TO5w000000Zan9GAC/available-apps](https://domo-support.domo.com/s/topic/0TO5w000000Zan9GAC/available-apps)', '[https://domo-support.domo.com/s/article/360043429933](https://domo-support.domo.com/s/article/360043429933)', '[https://domo-support.domo.com/s/article/360043429953](https://domo-support.domo.com/s/article/360043429953)', '[https://domo-support.domo.com/s/article/360042925494](https://domo-support.domo.com/s/article/360042925494)', '[https://domo-support.domo.com/s/article/360043429913](https://domo-support.domo.com/s/article/360043429913)', '[https://domo-support.domo.com/s/article/4408174643607](https://domo-support.domo.com/s/article/4408174643607)', '[https://domo-support.domo.com/s/login/](https://domo-support.domo.com/s/login/)']
article_id: 000005043
views: 1,090
created_date: 2022-11-03 20:29:00
last updated: 2022-11-03 20:37:00
---



#### Publisher


Domo


#### Description


Measuring traffic in the digital world can be extremely challenging, especially when the data is scattered across several sources. This app is designed to measure digital traffic across your websites, social networks, geographical locations, and devices so you can analyze all of your traffic in one place. Monitor trending in total conversions, conversion rates, and page views. Gain insights into your top and bottom performing segments. Use this information to analyze traffic irregularities and respond to segments that have impacted your traffic variance.


#### Business Questions


* How can I analyze all of my digital traffic trends more effectively?
* What are my daily top and bottom performing traffic segments?
* What is causing traffic irregularities and how can I improve my response?


#### Screenshot


clipboard_e8619f6f35c718dfbb6759e3c09a93fbe.png
-----------------------------------------------


#### 


 
 

