---
title: VerticalResponse Connector
url: https://domo-support.domo.com/s/article/360042927574
linked_kbs:  ['[https://domo-support.domo.com/s/knowledge-base/](https://domo-support.domo.com/s/knowledge-base/)', '[https://domo-support.domo.com/s/](https://domo-support.domo.com/s/)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZammGAC](https://domo-support.domo.com/s/topic/0TO5w000000ZammGAC)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZanLGAS](https://domo-support.domo.com/s/topic/0TO5w000000ZanLGAS)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZaoQGAS](https://domo-support.domo.com/s/topic/0TO5w000000ZaoQGAS)', '[https://domo-support.domo.com/s/article/360042926274](https://domo-support.domo.com/s/article/360042926274)', '[https://domo-support.domo.com/s/article/360042926054](https://domo-support.domo.com/s/article/360042926054)', '[https://domo-support.domo.com/s/article/360042927574](https://domo-support.domo.com/s/article/360042927574)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZaoQGAS/api-connectors](https://domo-support.domo.com/s/topic/0TO5w000000ZaoQGAS/api-connectors)', '[https://domo-support.domo.com/s/article/360043429933](https://domo-support.domo.com/s/article/360043429933)', '[https://domo-support.domo.com/s/article/360043429953](https://domo-support.domo.com/s/article/360043429953)', '[https://domo-support.domo.com/s/article/360042925494](https://domo-support.domo.com/s/article/360042925494)', '[https://domo-support.domo.com/s/article/4408174643607](https://domo-support.domo.com/s/article/4408174643607)', '[https://domo-support.domo.com/s/article/360043429913](https://domo-support.domo.com/s/article/360043429913)', '[https://domo-support.domo.com/s/login/](https://domo-support.domo.com/s/login/)']
article_id: 000003691
views: 1,075
created_date: 2022-10-24 21:14:00
last updated: 2022-10-24 22:40:00
---



Intro
-----


VerticalResponse  provides software for sending email marketing, online surveys and direct mail for direct marketing campaigns. To learn more about the VerticalResponse API, visit their page ([http://developers.verticalresponse.com/](http://developers.verticalresponse.com/ "http://developers.verticalresponse.com/")).


You connect to your VerticalResponse account in the Data Center. This topic discusses the fields and menus that are specific to the VerticalResponse connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed in [Adding a DataSet Using a Data Connector](/s/article/360042926274 "Adding a DataSet Using a Data Connector").


Prerequisites
-------------


To connect to your VerticalResponse account and create a DataSet, you must have a VerticalResponse username and password.


Connecting to Your VerticalResponse Account
-------------------------------------------


This section enumerates the options in the **Credentials** and **Details** panes in the VerticalResponse Connector page. The components of the other panes in this page, **Scheduling** and **Name & Describe Your DataSet**, are universal across most connector types and are discussed in greater length in [Adding a DataSet Using a Data Connector](/s/article/360042926274 "Adding a DataSet Using a Data Connector").


### Credentials Pane


This pane contains fields for entering credentials to connect to your VerticalResponse account. The following table describes what is needed for each field:  




| Field | Description |
| --- | --- |
| Username | Enter your VerticalResponse username. |
| Password | Enter your VerticalResponse password. |


Once you have entered valid VerticalResponse credentials, you can use the same account any time you go to create a new VerticalResponse DataSet. You can manage connector accounts in the **Accounts** tab in the Data Center. For more information about this tab, see [Managing User Accounts for Connectors](/s/article/360042926054 "Managing User Accounts for Connectors").


### Details Pane


This pane contains a single menu from which you can select a VerticalResponse report.




| Menu | Description |
| --- | --- |
| Report | Select the VerticalResponse report you want to run. The following reports are available:

|  |  |
| --- | --- |
| Campaigns | Returns data about your email campaigns. |
| Lists | Returns data about members of your lists. |
| Campaign Response Summary | Returns a summary of your campaign responses. |

 |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, see [Adding a DataSet Using a Data Connector](/s/article/360042926274 "Adding a DataSet Using a Data Connector").

