---
title : Available Table-Type Charts
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:42:00
url : https://domo-support.domo.com/s/article/360042924354
linked_kbs :  ['https://domo-support.domo.com/s/article/360043429333', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360043429073', 'https://domo-support.domo.com/s/article/360043429913', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360043429573', 'https://domo-support.domo.com/s/article/360043429593', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/article/360043429473', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360042924354']
article_id : 000004733
views : 4,395
created_date : 2022-10-24 22:27:00
last updated : 2022-10-24 22:42:00
---



The following table lists the types of tables available in Domo. You can click a thumbnail image to see a larger image.




| Table Type | Description | Example |
| --- | --- | --- |
| HTML table
table-small.png
Â  | In a table, items in each column are grouped with the other items in the same row.
In the sample image, employees (in the "Employee" column) are grouped with their email addresses and telephone extensions.
For more information, see [Table](..\table_chart\index.html "Table"). | table_kpi_example.png |
| Heat Map Table
heatmap-table-small.png | A heat map table is the same as a regular table except that values in value columns are highlighted in different shades depending on where they fall in the given range. For example, if the values in a column ranged from 10 to 1000, the values around "10" would appear light-colored, the values around "1000" would appear dark-colored, and all other values would fall somewhere in between.
For more information, see [Table](..\table_chart\index.html "Table"). | heatmap_table_kpi_example.png |
| Textbox
textbox-small.png | A textbox is used to represent a piece of text. The text can be as long as you want as long as it fits in a single cell in a DataSet, and can contain any character. You can format text to be centered, left-aligned, or right-aligned, and can set the space of the margins. You can also specify text to override the text from your DataSet, as well as reference a value column instead using a macro.
For more information, see [Textbox](..\textbox\index.html "Textbox"). | textbox_kpi_example.png |
| Flex Table
flex-table-small.png | A flex table displays different rows for each series of a graph, with all series depicted as individualÂ [spark bar](..\spark_bar_chart\index.html "Spark Line Graph")Â graphs. For each individual series, information about that series is provided in the other columns in the table. By default, this information includes the name of the series, an indicator showing whether the percent change for the series is positive or negative, and the degree of change. However, in the Chart Properties for the table, you can change columns to reflect any of a variety of other aspects of the series, such as the minimum or maximum value in the chart, the second-to-last value, a change value (as opposed to a percentage), etc. You can also add additional columns to the table (up to 10) with this information.
For more information, seeÂ [Flex Table](..\flex_table\index.html "Flex Table"). | flex_table_after.jpg |
| Pivot Table
Pivot_Table.png | Pivot tables provide a more powerful alternative toÂ [HTML tables](..\table_chart\index.html "Table Chart")Â in Domo.Â They allow you to quickly and easily summarize large quantities of data from a DataSet as well as explore data by different dimensions and measures.Â 
With pivot tables, you can display data using both rows and columns. Each cell in the tableÂ contains data for the intersecting column and row. You can even have multiple columns and/or rows. Each subsequent column or row you add appears as a new grouping within the previously added grouping.
For more information, seeÂ [Pivot Table](..\pivot_table\index.html "Pivot Table - BETA"). | pivot_table_example1.png |
| Mega Table
mega-table-small.png | Mega tables have all of the same functionality as HTML tables and heat map tables; in addition, they can have up to 25,000 rows (HTML tables are limited to 10,000 cells), have expand/collapse and column sorting functionality, and can include functional URLs and images.Â 
For more information, seeÂ [Table](..\table_chart\index.html "Table"). | megatable_images_and_links.png |


Â