---
title : Pocket Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:41:00
url : https://domo-support.domo.com/s/article/360043435513
linked_kbs :  ['https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043435513', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003374
views : 2,003
created_date : 2022-10-24 21:12:00
last updated : 2022-10-24 22:41:00
---



Intro
-----


Pocket, previously known as Read It Later, is an application and service for managing a reading list of articles from the Internet. To learn more about the Pocket API, visit their page ([https://getpocket.com/developer/](https://getpocket.com/developer/ "https://getpocket.com/developer/")).
You connect to your Pocket account in the Data Center. This topic discusses the fields and menus that are specific to the Pocket connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed inÂ  [a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


Prerequisites
-------------


To connect to your Pocket account and create a DataSet, you must have credentials for a Pocket account. Any of the following types of credentials will work:



* A Pocket username and password
* Google or Firefox credentials you have used to sign into Pocket


Connecting to Your Pocket Account
---------------------------------


This section enumerates the options in theÂ **Credentials**Â andÂ **Details**Â panes in the Pocket Connector page.Â The components of the other panes in this page,Â **SchedulingÂ**andÂ **Name & Describe Your DataSet,** are universal across most connector types and are discussed in greater length inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


### Credentials Pane


The Domo Pocket connector uses OAuth to connect, so there is no need to enter credentials within Domo. ClickÂ **Connect**Â (or selectÂ **Add Account**Â ifÂ you haveÂ existing Pocket accounts in Domo) to open the Pocket OAuth screen where you can enter your Pocket credentials. You can enter a Pocket username and password, or, if you signed up for Pocket through Google or Firefox, you can use those to log in. Once you have entered valid credentials, you can use the same account any time you go to create a new Pocket DataSet. You can manage connector accounts in theÂ **Accounts**Â tab in theÂ Data Center. For more information about this tab, seeÂ [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


**Note:**Â If you are already logged into Pocket when you connect in Domo, you are authenticated automatically when you click **Add account**. If you want to connect to an account that is different from the one you are logged into, you must first log out of Pocket.
### Details Pane


This pane contains a primaryÂ **Reports**Â menu, along with various other menus which may or may not appear depending on the report type you select.




| Menu | Description |
| --- | --- |
| Report | Select the Pocket report you want to run.Â The following reports are available:

|  |  |
| --- | --- |
| Get Article Data | Returns a list of articles in your Pocket account. |
| Get Image Data | Returns a list of images associated with articles in your Pocket account. |
| Get Video Data | Returns a list of videos associated with articles in your Pocket account. |

 |
| State | Lets you select whether to retrieve data for all articles or only those that are archived or unread. |
| Detail Type | Select the level of detail you want your report to contain. If you select **Simple**, basic information such as title, URL, and status is returned. If you select **Detailed**, all data is returned, including tags, images, authors, videos, etc. |
| Tag (Optional) | Enter a search tag to retrieve data for. |
| Date Since | Select whether you want to retrieve data for a specific date or for a relative number of days back. |
| Specific Date | Select the date you want to retrieve data for. |
| Days Back | Enter the number of days back you want to retrieve data for. |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, seeÂ [AddingÂ a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


Â