---
title : Bitly Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:39:00
url : https://domo-support.domo.com/s/article/360042926454
linked_kbs :  ['https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042926454', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003797
views : 3,952
created_date : 2022-10-24 21:15:00
last updated : 2022-10-24 22:39:00
---



Intro
------


Bitly is a URL-shortening, bookmarking serviceÂ and link-sharing platform. Â To learn more about the BitlyÂ API, visit theirÂ website (<https://dev.bitly.com/v4_documentation.html>).


The Bitly connector is a "Cloud App" connector, meaning it retrieves data stored in the cloud. In the Data Center, you can access the connector page for this and other Cloud App connectors by clicking **Cloud App** in the toolbar at the top of the window. Â 


You connect to yourÂ Bitly account in theÂ Data Center. This topic discusses the fields and menus that are specific to theÂ Bitly connector user interface. General information for adding DataSets, setting update schedules, and editingÂ DataSet information is discussed inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").




|  |  |
| --- | --- |
| **Primary Use Cases** | Retrieving data about link statistics (such as number of clicks, countries providing click traffic, etc.) |
| **Primary Metrics** | 
* Number of clicks
* Number of encoders
* Countries providing the most traffic
 |
| **Primary Company Roles** | Marketing analysts |
| **Average Implementation Time** | Less than 1 hour |
| **Ease of Use (on a 1-to-10 scale with 1 being easiest)** | 2 |


Â 


Prerequisites
-------------


To connect to yourÂ Bitly account and create a DataSet, you must provide credentials for Bitly, Facebook, or Twitter.Â 


Connecting to YourÂ Bitly Account
---------------------------------


This section enumerates the options in theÂ **Credentials**Â andÂ **Details**Â panes in theÂ Bitly Connector page.Â The components of the other panes in this page,Â **Scheduling**Â andÂ **Name & Describe Your DataSet**, are universal across most connector types and are discussed in greater length inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


### Credentials Pane


The DomoÂ Bitly connector uses OAuth to connect, so there is no need to enter credentials within Domo. ClickÂ **ConnectÂ**(or selectÂ **Add Account**Â ifÂ you haveÂ existingÂ Bitly accounts in Domo)Â to open theÂ BitlyÂ OAuth screen where you can sign in to Bitly using Bitly, Facebook, or TwitterÂ credentials.Â 


Once you have entered valid BitlyÂ credentials, you can use the same account any time you go to create a newÂ Bitly DataSet. You can manage connector accounts in theÂ **Accounts**Â tab in theÂ Data Center. For more information about this tab, seeÂ [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


### Details Pane


This pane contains a primaryÂ **Report**Â menu, along with various other menus and fields which may or may not appear depending on the report type you select.




| Menu | Description |
| --- | --- |
| Report | Select theÂ Bitly report you want to run. The following reports are available:

|  |  |
| --- | --- |
| Link Clicks | Returns the number of clicks for a given Bitlink. |
| Link Countries | Returns metrics about the countries referring click traffic to a givenÂ Bitlink. |
| Link Encoders | Returns users who have encoded a given Bitlink. |
| Link Encoders by Count | Returns users who have encoded this Bitlink, sorted by the number of clicks on each encoding user's link. |
| Link Encoders Count | Returns the number of users who have shortened (encoded) a givenÂ Bitlink. |
| Link Information | Returns metadataÂ for a given Bitlink. |
| Link Referrers | Returns metrics about the pages referring click traffic to a given Bitlink. |
| Link Referrers by Domain | Returns metrics about the pages referring click traffic to a given Bitlink, grouped by referring domain. |
| Link Referring Domain | Returns metrics about the domains referring click traffic to a givenÂ Bitlink. |
| Popular Links | Returns the authenticated user's most-clicked Bitlinks (ordered by number of clicks) in a given time period. |
| Popular Owned by Clicks | Returns the top links to your tracking domain (or domains) created by users not associated with your account, ordered by clicks. |
| Popular Owned by Shortens | Returns the top links to your tracking domain (or domains) created by users not associated with your account, ordered by shortens. |
| Referrers | Returns aggregate metrics about the pages referring click traffic to all of the authenticated user's Bitlinks. |
| Referring Domains | Returns aggregate metrics about the domains referring click traffic to all of the authenticated user's Bitlinks.Â  |
| Shorten Counts | Returns the number of Bitlinks created in a given time period by the authenticated user. |
| User Clicks | Returns the aggregate number of clicks on all of the authenticated user's Bitlinks. |
| User Countries | Returns aggregate metrics about the countries referring click traffic to all of the authenticated user's Bitlinks. |

Â  |
| Bitly Link | Enter the BitlinkÂ you want to retrieve information for.Â  |
| Unit | Select whether data should be broken down by day, by hour, by week, etc.Â  |
| Number of Units | Enter the number of units of the selected time unit that should be returned. For example, if you selectedÂ **Month**Â as the **Unit** and enteredÂ 3Â for **Number of Units**, data would be returned for the last 3 months. If you enterÂ -1,Â all units of time are returned.Â  |
| Time Zone | Enter the desired time zone. You can enter this as an integer hour offset from UTC (fromÂ -14Â toÂ 14) or as anÂ actual time zone name. This defaults to Eastern Standard Time.Â Â  |
| Roll UpÂ  | Choose whether to return data for multiple units rolled up to a single result instead of a separate value for each period of time. |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, seeÂ [AddingÂ a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md). Â Â