---
title : SmartRecruiters Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:42:00
url : https://domo-support.domo.com/s/article/360042928274
linked_kbs :  ['https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042928274', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003633
views : 2,021
created_date : 2022-10-24 21:13:00
last updated : 2022-10-24 22:42:00
---



Intro
-----


SmartRecruiters Talent Acquisition Platform is recruiting software that puts all your recruiting solutions, people, and vendors at your fingertips. To learn more about the SmartRecruiters API, visit their page ([https://dev.smartrecruiters.com/customer-api/live-docs/customer-api-2/](https://dev.smartrecruiters.com/customer-api/live-docs/customer-api-2/ "Follow link")).  


You connect to your SmartRecruiters account in the Data Center. This topic discusses the fields and menus that are specific to the SmartRecruiters connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed inÂ  [a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


Prerequisites
-------------


To connect to your SmartRecruiters account and create a DataSet, you must have a SmartRecruiters API key. For information about obtaining an API key, see the following page: [https://dev.smartrecruiters.com/cust...ation/api-key/](https://dev.smartrecruiters.com/customer-api/authentication/api-key/ "https://dev.smartrecruiters.com/customer-api/authentication/api-key/")


Connecting to Your SmartRecruiters Account
------------------------------------------


This section enumerates the options in the **Credentials** and **Details** panes in the SmartRecruiters Connector page.Â The components of the other panes in this page, **Scheduling**Â and **Name & Describe Your DataSet**, are universal across most connector types and are discussed in greater length inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


### Credentials Pane


This pane contains fields for entering credentials to connect to your SmartRecruiters account. The following table describes what is needed for each field: Â 




| Field | Description |
| --- | --- |
| API Key | Enter your SmartRecruiters API key. |


Once you have entered valid SmartRecruiters credentials, you can use the same account any time you go to create a new SmartRecruiters DataSet. You can manage connector accounts in the **Accounts** tab in the Data Center. For more information about this tab, see [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


### Details Pane


This pane contains a primaryÂ **Reports**Â menu, along with various other menus which may or may not appear depending on the report type you select.




| Menu | Description |
| --- | --- |
| Report | Select the SmartRecruiters report you want to run.Â The following reports are available:

|  |  |
| --- | --- |
| Company Details | Returns information about your company. |
| List Applications | Returns a list of applications. |
| List Candidate Properties | Returns candidate properties and their configuration. |
| List Candidate Source-Types | Returns a list of candidate source-types with subtypes. |
| List Departments | Returns a list of departments. |
| List Hiring Process | Returns hiring process information. |
| List Hiring Team | Lists the members of your hiring team. |
| List Interviews | Returns a list of interviews. |
| List Job Fields | Returns a list of job fields. |
| List Job Positions | Returns a list of job positions. |
| List Job Properties | Returns a list of job properties. |
| List Jobs | Returns a list of jobs. |
| List Offer Properties | Returns a list of available offer properties. |
| List Rejection Reasons | Returns a list of rejection reasons. |
| List Users | Returns a list of users in your company. |
| List Withdrawal Reasons | Returns a list of withdrawal reasons. |
| My User Details | Returns details for your user. |
| Search Candidates | Returns candidates for a specific date or number of days back. |
| Search Jobs | Returns jobs with a particular status for a specific date or number of days back. |
| Search Offers | Returns offers with a particular status for a given timeframe. |

 |
| Posting Status | Select the posting status you want to pull data for. |
| Status | Select the status you want to pull data for. |
| DurationÂ  | Select whether you want to pull data for a specific date or a date range.Â  |
| Report DateÂ  | Select whether the report data is for a specific date or for a relative number of days back from today.Â  |
| Select Specific DateÂ  | Select the date for the report.Â  |
| Days Back | Enter the number of past days that should appear in the report.Â Â  |
| Start Date | Specify whether theÂ first date in your date range is a specific or relative date.Â You select the last date in your range inÂ **End Date**.Â  |
| End Date | Specify whether the second date in your date range is a specific or relative date. You select the first date in your range inÂ **Start Date**.Â Â  |
| Select Specific Start Date | SelectÂ the first date in your date range.Â  |
| Select Specific End Date | Select the second date in your date range.Â  |
| Days Back to Start From | Enter the number of the farthest day back that should be represented in the report. Combine withÂ **Days Back to End At**Â to create a range of represented days.
For example, if you enteredÂ 10Â forÂ **Days Back to Start From**Â andÂ 5Â forÂ **Days Back to End At**, the report would contain data forÂ 10 days ago up untilÂ 5 days ago. |
| Days Back to End At | Enter the number of the most recent day back that should be represented in the report. Combine withÂ **Days Back to Start From**Â to create a range of represented days.
For example, if you enteredÂ 10Â forÂ **Days Back to Start From**Â andÂ 5Â forÂ **Days Back to End At**, the report would contain data forÂ 10 days ago up untilÂ 5 days ago. |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, seeÂ [Â a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


Â