---
title : Understanding the Customer Support Portal
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:42:00
url : https://domo-support.domo.com/s/article/360043427573
linked_kbs :  ['https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043427573', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360043427533', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000004370
views : 2,082
created_date : 2022-10-24 21:45:00
last updated : 2022-10-24 22:42:00
---



You can use the Customer Support Portal to manage your customer support tickets. You can create new cases, update existing ones, and if you are an Admin, manage the support tickets for your organization. Access the Customer Support Portal by navigating to [support.domo.com](http://support.domo.com) and logging in with your Domo account credentials. The Customer Support Portal is available for all users with Professional or Enterprise versions of Domo.


To learn how toÂ create lists of cases based on different criteria in the Support Portal, seeÂ [Creating a New List in the Customer Portal](..\creating_a_new_list_in_the_customer_portal\index.html "Creating a New List in the Customer Portal").


For a walkthrough of the features of the Customer Support Portal, watch the following video:


**Video - Support Portal Overview**



Â