---
title : Celtra Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:40:00
url : https://domo-support.domo.com/s/article/360043430973
linked_kbs :  ['https://domo-support.domo.com/s/article/360043430973', 'https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003788
views : 2,017
created_date : 2022-10-24 21:15:00
last updated : 2022-10-24 22:40:00
---



Intro
-----


Celtra empowers agencies, media suppliers and brand leaders with the leading creative technology for data-driven brand display advertising across all screens. To learn more about the Celtra API, refer to their blog ([http://www.celtra.com/insights/blog/...ed-adcreator-3](http://www.celtra.com/insights/blog/creative-javascript-api-introduced-adcreator-3 "http://www.celtra.com/insights/blog/creative-javascript-api-introduced-adcreator-3")).


You connect to your Celtra account in the Data Center. This topic discusses the fields and menus that are specific to the Celtra connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).


Best Practices
--------------


The dimensions and metrics available when using the Celtra connector are almost identical to those in the Celtra Report Builder (which you can find in Celtra by going to **Reporting Center > Report Builder**). It is recommended you use the Report Builder to build the report you want in Domo, noting the dimensions and metrics, then select those same fields in the Domo connector. This lets you quickly find the right data, speed up your connector configuration time, and schedule your reporting.


Prerequisites
-------------


To connect to your Celtra account and create a DataSet, you must have the following:



* A Celtra App ID
* A Celtra secret key
* Your Celtra subdomain


You can obtain your App ID and secret key by navigating to **User Name > Settings** in Celtra. After you create the API application, you will receive these credentials.


You can find your Celtra subdomain by looking at the portion of your Celtra instance URL right after https://. For example, if your Celtra instance was [customerxyz.celtra.com](http://customerxyz.celtra.com), your subdomain would be customerxyz.Â 


Connecting to Your Celtra Account
---------------------------------


This section enumerates the options in the **Credentials** and **Details** panes in the Celtra Connector page.Â The components of the other panes in this page, **Scheduling**Â and **Name & Describe Your DataSet**, are universal across most connector types and are discussed in greater length inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md "Adding a DataSet Using a Data Connector").


### Credentials Pane


This pane contains fields for entering credentials to connect to your Celtra account. The following table describes what is needed for each field: Â 




| Field | Description |
| --- | --- |
| App ID | Enter your Celtra app ID. |
| Secret Key | Enter your Celtra secret key. |
| Subdomain | Enter your Celtra subdomain. |


For information about obtaining these credentials, see "Prerequisites," above.


Once you have entered valid Celtra credentials, you can use the same account any time you go to create a new Celtra DataSet. You can manage connector accounts in the **Accounts** tab in the Data Center. For more information about this tab, see [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


### Details Pane


This pane contains a primaryÂ **Reports**Â menu, along with various other menus which may or may not appear depending on options you select.




| Menu | Description |
| --- | --- |
| Report | Select the Celtra report you want to run. Currently only one report type is available.

|  |  |
| --- | --- |
| Analytics | Returns analytics data for the authenticated user. |

 |
| Filter Type | Select whether you want the data in your report to be filtered by an account, campaign, creative, or placement. |
| Account ID | Enter the ID of the account you want to retrieve data for. The ID is presented as an 8 character alpha-numeric value.
**To find an account ID in Celtra, do the following:**1. Log into Celtra.
2. Navigate to the Report Builder (**Reporting Center > Report Builder**).
3. Locate the "Account ID" dimension and include it in the report.

The spreadsheet sample panel then populates with the "Account ID" column.
If you only have one account in Celtra, the ID that appears as the data for the "Account ID" column is your Account ID to use for the connector configuration. If you have many accounts, it is recommended that you download the report from Celtra as an Excel file to see all the Account IDs that exist for your organization. You may then pick and choose the Accounts IDs you want to use for the connector.
The Domo connector currently only supports 1 Account ID per DataSet, so if you have 4 Accounts IDs you want to use in Domo, at a minimum you must set up 4 DataSets, 1 DataSet per Account ID. |
| Campaign ID | Enter the ID of the campaign you want to retrieve data for. You can find the campaign ID under the campaign name in the **My Campaign** tab. |
| Creative ID | Enter the ID of the creative you want to retrieve data for. |
| Placement ID | Enter the ID of the placement in which the creative was trafficked. |
| Dimension | Select all of the dimensions you want your data to be broken down by. |
| Metrics | Select all of the metrics you want to appear in your report. |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, seeÂ [AddingÂ a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md). Â