project:
  type: website
  preview:
    port: 3000

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  sidebar:
    style: floating
    contents:
      - auto: "/*.ipynb"
      - section: Crawler
        contents: crawler/*

  navbar:
    background: primary
    search: true

    right:
      - icon: github
        href: "https://github.com/jaewilson07/datacrew"
      - icon: twitter
        href: https://twitter.com/onyxreporting
        aria-label: OnyxReporting Twitter

metadata-files: [nbdev.yml]
