project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true

    left:
      - text: "Knowledge Base"
        href: projects/kb_md/index.qmd
    right:
      - icon: github
        href: "https://github.com/jaewilson07/domo_library"
      - icon: twitter
        href: https://twitter.com/onyxreporting
        aria-label: OnyxReporting Twitter

  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]
