---
title : Simpli.fi Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:42:00
url : https://domo-support.domo.com/s/article/360042927294
linked_kbs :  ['https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360042927294', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003713
views : 3,975
created_date : 2022-10-24 21:14:00
last updated : 2022-10-24 22:42:00
---



Intro
-----


Â 


Â
**Important:** [Simpli.fi](http://Simpli.fi) is deprecating certain endpoints on **January 31, 2022**. Domo has created new reports to replace the deprecated endpoints.  
**What does this mean for you?**



* You will need to create a new DataSet with the updated report.
* You will then need to reach out to Domo Support and ask them to migrate your current DataSet to your new DataSet.
[Simpli.fi](http://Simpli.fi) is a comprehensive RTB platform built for localized campaigns. To learn more about the [Simpli.fi](http://Simpli.fi) API, visit their page ([https://www.simpli.fi/platform/custom-api/](https://www.simpli.fi/platform/custom-api/ "https://www.simpli.fi/platform/custom-api/")).


You connect to your [Simpli.fi](http://Simpli.fi) account in the Data Center. This topic discusses the fields and menus that are specific to the [Simpli.fi](http://Simpli.fi) connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).


Prerequisites
-------------


To connect to your [Simpli.fi](http://Simpli.fi) account and create a DataSet, you must have the following:



* A [Simpli.fi](http://Simpli.fi) user key


These credentials are provided on account creation. For more information, contact your [Simpli.fi](http://Simpli.fi) account representative.


Connecting to Your [Simpli.fi](http://Simpli.fi) Account
--------------------------------------------------------


This section enumerates the options in the **Credentials** and **Details** panes in the [Simpli.fi](http://Simpli.fi) Connector page.Â The components of the other panes in this page, **Scheduling**Â and **Name & Describe Your DataSet**, are universal across most connector types and are discussed in greater length inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md "Adding a DataSet Using a Data Connector").


### Credentials Pane


This pane contains fields for entering credentials to connect to your [Simpli.fi](http://Simpli.fi) account. The following table describes what is needed for each field: Â 




| Field | Description |
| --- | --- |
| User Key | Enter your [Simpli.fi](http://Simpli.fi) user key. |


Once you have entered valid [Simpli.fi](http://Simpli.fi) credentials, you can use the same account any time you go to create a new [Simpli.fi](http://Simpli.fi) DataSet. You can manage connector accounts in the **Accounts** tab in the Data Center. For more information about this tab, see [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


### Details Pane


This pane contains a primaryÂ **Reports**Â menu, along with various other menus which may or may not appear depending on the report type you select.




| Menu | Description |
| --- | --- |
| Report | Select the [Simpli.fi](http://Simpli.fi) report you want to run.Â The following reports are available:

|  |  |
| --- | --- |
| All Campaign Ads | This report returns the data for all Campaign Ads. |
| All Campaigns | This report returns the data for all Campaigns. |
| All Campaign Stats | This report returns the status of all Campaigns. |
| Campaign Ads By Organization | This report returns the data for all Campaign Ads for the selected organization. |
| Campaign Ads | This report returns the list of Campaign Ads. |
| Campaigns List | This report returns a list of all Campaigns. |
| Campaign Stats | This report returns the status of the Campaign. |
| Organizations | This report returns the list of all the Organizations. |
| Report-Center | This report helps to retrieve existing report models, create new report models, and update the report models. |

 |
| Select the Company | Select the company you want to retrieve data for. |
| Organization Selection Criteria | Specify whether you want to retrieve report for all organizations or a specific organization. |
| Organization | Select the organization. |
| Client Selection Criteria | Specify whether you want to retrieve report for all clients or a specific client. |
| Report Model Selection Criteria | Specify whether you want to retrieve the existing report model or create the new model. |
| Campaign Selection Criteria | Specify whether you want to retrieve the campaigns only for the selected organization or include its descendants. |
| Campaigns Fetch Criteria | Specify whether you want to bring the data for selected campaign Ids or for all the available campaign Ids. |
| Report Model | Select the report model. |
| Select the Client | Select the client you want to retrieve data for. |
| Template | Select the template. |
| Model Name | Enter the Report Model name. 'Domo\_' will be prepended to the model name that you have provided. |
| Current Fields To Exclude | This is a list of fields automatically included in the report. Select fields that you wish to exclude. |
| Additional Fields | Select additional fields to retrieve. |
| Date Filters | Select the field for which you wish to apply a date selector. |
| Client | Select the client. |
| Campaigns | Select the campaign. |
| Granularity By Day | Select 'True' to breakdown the data by day. |
| Report DurationÂ  | Select the duration for the report (a Single Date, or a Date Range). For the Report Center report, dates will only be used for the first run, subsequent run will retrieve only new data unless selections are modified. |
| Report DateÂ  | Select whether the report data is for a specific date or for a relative number of days back from today.Â  |
| Select Specific DateÂ  | Select the date for the report.Â  |
| Days Back | Enter the number of past days that should appear in the report.Â Â  |
| Start Date | Specify whether theÂ first date in your date range is a specific or relative date.Â You select the last date in your range inÂ **End Date**.Â  |
| End Date | Specify whether the second date in your date range is a specific or relative date. You select the first date in your range inÂ **Start Date**.Â Â  |
| Select Specific Start Date | SelectÂ the first date in your date range.Â  |
| Select Specific End Date | Select the second date in your date range.Â  |
| Days Back to Start From | Enter the number of the farthest day back that should be represented in the report. Combine withÂ **Days Back to End At**Â to create a range of represented days.
For example, if you enteredÂ 10Â forÂ **Days Back to Start From**Â andÂ 5Â forÂ **Days Back to End At**, the report would contain data forÂ 10 days ago up untilÂ 5 days ago. |
| Days Back to End At | Enter the number of the most recent day back that should be represented in the report. Combine withÂ **Days Back to Start From**Â to create a range of represented days.
For example, if you enteredÂ 10Â forÂ **Days Back to Start From**Â andÂ 5Â forÂ **Days Back to End At**, the report would contain data forÂ 10 days ago up untilÂ 5 days ago. |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, seeÂ [AddingÂ a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).