---
title : Vertica Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:41:00
url : https://domo-support.domo.com/s/article/360042931874
linked_kbs :  ['https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429913', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043630093', 'https://domo-support.domo.com/s/article/360042931874']
article_id : 000003875
views : 2,032
created_date : 2022-10-24 21:16:00
last updated : 2022-10-24 22:41:00
---



Intro
-----


The cluster-based, column-oriented, Vertica Analytics Platform is designed to manage large, fast-growing volumes of data and provide fast query performance. Use Domo's Vertica connector to retrieve data from Vertica tables usingÂ SQL queries. To learn more about Vertica, visit their documentation home page ([https://www.vertica.com/documentation/vertica/9-3-x-documentation/](https://my.vertica.com/documentation/vertica/ "https://my.vertica.com/documentation/vertica/")).  


You connect to your Vertica account in the Data Center. This topic discusses the fields and menus that are specific to the Vertica connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).


Prerequisites
-------------


To connect to your Vertica account and create a DataSet, you must have the following:



* The name of the server where the VerticaÂ database is hosted
* The username and password you use to connect to the Vertica database
* The Vertica database port number
* The name of the VerticaÂ databaseÂ Â


Connecting to Your Vertica Account
----------------------------------


This section enumerates the options in the **Credentials** and **Details** panes in the Vertica Connector page.Â The components of the other panes in this page, **Scheduling**Â and **Name & Describe Your DataSet**, are universal across most connector types and are discussed in greater length inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md "Adding a DataSet Using a Data Connector").


### Credentials Pane


This pane contains fields for entering credentials to connect to your Vertica account. The following table describes what is needed for each field: Â 




| Field | Description |
| --- | --- |
| JDBC Driver | Select the appropriate JDBC driver to use. |
| Host | Enter the name of the server where the VerticaÂ database is hosted. |
| Username | Enter the username you use to connect to the Vertica database. |
| Password | Enter the password you use to connect to the Vertica database. |
| Port Number | Enter the port number of the Vertica database.Â  |
| Database Name | Enter the name of the Vertica database. |


Once you have entered valid Vertica credentials, you can use the same account any time you go to create a new Vertica DataSet. You can manage connector accounts in the **Accounts** tab in the Data Center. For more information about this tab, see [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


### Whitelisting


Before you can connect to aÂ Vertica database, you must also whitelist a number of IP addresses on your database server on theÂ portÂ you want to connect to. For the full list of IP addresses, seeÂ [Whitelisting IP Addresses for Connectors](..\allowlisting_ip_addresses_for_connectors__federated_adapters\index.html "Whitelisting IP Addresses for Connectors").


### Details Pane


In this pane you input the SQL query you want to use to pull data from your Vertica database. Optionally, you can also indicate the specific table and columns from that table to bring into Domo.




| Menu | Description |
| --- | --- |
| Query | Enter the SQL query to use to retrieve your data. You can use theÂ **Query HelperÂ**parameter to help you write a usable SQL query. To use theÂ **Query Helper**, do the following:1. Select your database tableÂ and table columns in the appropriate menus.
2. Copy the SQL statement that appears in theÂ **Query HelperÂ**field.
3. Paste the copied SQL statement into theÂ **Query**Â field.

Â  |
| Database Tables (Optional) | Select the database tables you want to pull into Domo, if desired. |
| Table Columns (Optional) | Select the table columns you want to pull into Domo. |
| Query Helper (Optional) | (Optional) Copy and paste the SQL statement in this field into theÂ **QueryÂ**field. For more information, seeÂ **Query**, above. |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, seeÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).