---
title : Infusionsoft REST Hook Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:40:00
url : https://domo-support.domo.com/s/article/360042926834
linked_kbs :  ['https://domo-support.domo.com/s/article/360042926834', 'https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003757
views : 2,014
created_date : 2022-10-24 21:14:00
last updated : 2022-10-24 22:40:00
---



Intro
-----


Infusionsoft automates your small business sales and marketing, while combining your CRM, email marketing, lead capture and e-commerce in one place. You can use this connector to automatically pull data from your Infusionsoft account anytime changes are made within your subscribed columns.Â 


Because this connector is webhook-based, DataSets created using this connector update automatically when new data is sent to your Infusionsoft account. You doÂ *not*Â need to worry about scheduling updates when using this connector.


You connect to your InfusionsoftÂ account in the Data Center. This topic discusses the fields and menus that are specific to the InfusionsoftÂ REST Hook connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).


For more information about webhooks in Infusionsoft, seeÂ [https://developer.infusionsoft.com/r...documentation/](https://developer.infusionsoft.com/rest-hook-documentation/ "https://developer.infusionsoft.com/rest-hook-documentation/").Â 


Â 


Prerequisites
-------------


To connect to your Infusionsoft account and create a DataSet, you must have the following:



* The email address associated with your Infusionsoft account
* Your Infusionsoft password


Â
-


Connecting to Your Infusionsoft Account
---------------------------------------


This section enumerates the options in the **Credentials** and **Details** panes in the InfusionsoftÂ REST Hook Connector page.Â The components of the other panes in this page, **Scheduling**Â and **Name & Describe Your DataSet**, are universal across most connector types and are discussed in greater length inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md "Adding a DataSet Using a Data Connector").


Â 


### Credentials Pane


When you clickÂ **Add account**Â in this pane,Â you are taken to the InfusionsoftÂ login screen, where you can log into your Infusionsoft account using your Infusionsoft credentials (the email address associated with your Infusionsoft account as well as your Infusionsoft password).Â 


Once you have entered valid credentials for your Infusionsoft app and account, you can use the same account any time you go to create a new InfusionsoftÂ Webhook DataSet. You can manage connector accounts in the **Accounts** tab in the Data Center. For more information about this tab, see [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


Â 


### Details Pane


In this pane, you configure webhook subscriptions for your Infusionsoft app by selecting the columns you want to subscribe to then clicking a button to register the subscriptions.Â 


**To configure webhook subscriptions for your app,**


1. In the Details pane in Domo, check the boxes for all of the columns you want to subscribe to.  
 When changes are made to any of your subscribed columns in Infusionsoft, your DataSet will automatically update.


**Note:Â**Ignore theÂ **Webhook URL**Â field. You doÂ *not*Â need to paste this URL in Infusionsoft for the connector to work.
2. Click the green button under "Register Subscriptions."
3. (Conditional) If you want new data in your DataSet to be replaced instead of simply added onto, click **Change update settings**Â then chooseÂ **Replace.**
4. ClickÂ **Save**.Â Â


FAQs
----


##### How often can the data be updated?


The Infusionsoft Webhook connector updates automatically as Infusionsoft receives data. Â 


##### Are there any API limits I should be aware of?


No.


##### What's the difference between this connector and the Infusionsoft connector?


The Infusionsoft Webhook connector automatically updates as Infusionsoft receives more dataÂ and does not update on a set schedule. The Infusionsoft connector, on the other hand, is an API-based connectorÂ in which you choose a report and set an update schedule.


##### How do I know my Infusionsoft credentials are secure?


The login process uses the OAuth process, so your Infusionsoft credentials are never seen or stored by Domo. You can revoke Domo's access to your account at any time.


##### Can I use the same account to create multiple DataSets?


Yes.


##### When I click **Connect**, why am I getting automatically validated without needing to enter credentials?


If you are already logged into Infusionsoft when you connect to Domo, you are authenticated automatically as you click **Connect**. If you want to connect to an account that is different from the one you are logged into, you must first log out of Infusionsoft.