---
title : Kounta Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:41:00
url : https://domo-support.domo.com/s/article/360043432833
linked_kbs :  ['https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360043432833', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003628
views : 2,020
created_date : 2022-10-24 21:13:00
last updated : 2022-10-24 22:41:00
---



Intro
-----


Kounta produces a cloud-based point of sale (POS) mobile app. To learn more about the Kounta API, visit their page ([https://www.kounta.com/documentation/](https://www.kounta.com/documentation/ "https://www.kounta.com/documentation/")).


You connect to your Kounta account in the Data Center. This topic discusses the fields and menus that are specific to the Kounta connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed inÂ  [a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


Prerequisites
-------------


To connect to your Kounta account and create a DataSet, you must have the email address and password you use to log into Kounta.


Connecting to Your Kounta Account
---------------------------------


This section enumerates the options in theÂ **Credentials**Â andÂ **Details**Â panes in the Kounta Connector page.Â The components of the other panes in this page,Â **SchedulingÂ**andÂ **Name & Describe Your DataSet,** are universal across most connector types and are discussed in greater length inÂ  [a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


### Credentials Pane


The Domo Kounta connector uses OAuth to connect, so there is no need to enter credentials within Domo. ClickÂ **Connect**Â (or selectÂ **Add Account**Â ifÂ you haveÂ existing Kounta accounts in Domo) to open the Kounta OAuth screen where you can enter your KountaÂ email address and password. Once you have entered valid Kounta credentials, you can use the same account any time you go to create a new Kounta DataSet. You can manage connector accounts in theÂ **Accounts**Â tab in theÂ Data Center. For more information about this tab, seeÂ [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


Â
**Note:**Â If you are already logged into Kounta when you connect in Domo, you are authenticated automatically when you click **Add account**. If you want to connect to an account that is different from the one you are logged into, you must first log out of Kounta.
### Details Pane


This pane contains a primaryÂ **Reports**Â menu, along with various other menus which may or may not appear depending on the report type you select.




| Menu | Description |
| --- | --- |
| Report | Select the Kounta report you want to run.Â The following reports are available:

|  |  |
| --- | --- |
| Categories | Returns a list of Kounta categories. |
| Check-Ins | Returns a list of check-ins. |
| Customers | Returns a list of customers in your account. |
| Inventory | Returns a list of inventory in your account. |
| Option Sets | Returns a list of option sets. |
| Order Lines | Returns a list of order lines. |
| Order Payments | Returns a list of order payments. |
| Orders | Returns a list of orders in your account. |
| Payment Methods | Returns a list of payment methods. |
| Price Lists | Returns information about price lists. |
| Products | Returns a list of products in your account. |
| Products Detail | Returns a detailed list of products in your account. |
| Registers | Returns a list of registers in your account. |
| Shifts | Returns a list of shifts. |
| Site Details | Returns a detailed list of sites in your account. |
| Site Status | Returns status information about the sites in your account. |
| Sites | Returns a list of sites in your account. |
| Staff | Returns a list of the staff in your account. |
| Taxes | Returns tax information. |
| Unprocessed Cashups | Returns a list of unprocessed cashups. |

 |
| Date | Select whether you want a specific date for the report or a relative number of days back as the start date.Â  |
| Relative Start Date | Enter the number of days back you want to begin pulling data for. For example, if you entered 10, every time the report ran it would pull data for the last 10 days. |
| Fixed Start Date | Select the start date for the report. The report will pull all data from this date up to today.Â Â  |


### Other PanesÂ


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, seeÂ [Â a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").