---
title: Writeback Connectors List
url: https://domo-support.domo.com/s/article/000005122
linked_kbs:  ['[https://domo-support.domo.com/s/knowledge-base/](https://domo-support.domo.com/s/knowledge-base/)', '[https://domo-support.domo.com/s/](https://domo-support.domo.com/s/)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZammGAC](https://domo-support.domo.com/s/topic/0TO5w000000ZammGAC)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZanLGAS](https://domo-support.domo.com/s/topic/0TO5w000000ZanLGAS)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZapVGAS](https://domo-support.domo.com/s/topic/0TO5w000000ZapVGAS)', '[https://domo-support.domo.com/s/article/000005122](https://domo-support.domo.com/s/article/000005122)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZapVGAS/writeback-connectors](https://domo-support.domo.com/s/topic/0TO5w000000ZapVGAS/writeback-connectors)', '[https://domo-support.domo.com/s/article/360043429933](https://domo-support.domo.com/s/article/360043429933)', '[https://domo-support.domo.com/s/article/360043429953](https://domo-support.domo.com/s/article/360043429953)', '[https://domo-support.domo.com/s/article/360042925494](https://domo-support.domo.com/s/article/360042925494)', '[https://domo-support.domo.com/s/article/4408174643607](https://domo-support.domo.com/s/article/4408174643607)', '[https://domo-support.domo.com/s/article/360043429913](https://domo-support.domo.com/s/article/360043429913)', '[https://domo-support.domo.com/s/login/](https://domo-support.domo.com/s/login/)']
article_id: 000005122
views: 348
created_date: 2023-02-10 07:38:00
last updated: 2023-02-10 07:39:00
---



Intro
-----


This KB article describes the list of Writeback connectors that Domo has already released.


Writeback Connector List
------------------------


The following table describes the current list of Writeback connectors that are released.




 

**Important:** This table will keep getting updated based on the Writeback connectors that will be released.




 



| Connector ID |
| --- |
| com.domo.connector.snowflake writeback |
| com.domo.connector.googlesheetswriteback |
| com.domo.connector.domoS3writeback |
| com.domo.connector.domosftpwriteback |
| com.domo.connector.salesforcewriteback |
| com.domo.connector.adlsgen2writeback |
| com.domo.connector.googlebigquerywriteback |
| com.domo.connector.googlesheets.enterprise.writeback |
| com.domo.connector.mssqlwriteback |
| com.domo.connector.domomysqlwritebackconnector |
| com.domo.connector.domoboxwriteback |
| com.domo.connector.sharepointonlinewriteback |
| com.domo.connector.microsoftsqlserverwriteback |
| com.domo.connector.postgresqlwriteback |
| com.domo.connector.onedrivewriteback |
| com.domo.connector.azureblobstoragewriteback |
| com.domo.connector.redshiftwriteback |
| com.domo.connector.snowflakekeypairwriteback |
| com.domo.connector.eloquawriteback |
| com.domo.connector.smartsheetwriteback |
| com.domo.connector.sharepointonlinesdkwriteback |
| com.domo.connector.hubspot.writeback |
| com.domo.connector.s3writeback.assumeRole |
| com.domo.connector.azureblobstorage.sastoken.writeback |
| com.domo.connector.azuredatalakegen2.writeback |
| com.domo.connector.googledrivewriteback |
| com.domo.connector.netsuitewriteback |
| com.domo.connector.dropboxwriteback |
| com.domo.connector.googlecloudstoragewriteback |
| com.domo.connector.powerbi.writeback |
| com.domo.connector.jsonpostwriteback |
| com.domo.connector.mysqladvanced.writeback |
| com.domo.connector.azuredatalake.sastoken.writeback |
| com.domo.connector.datalakewriteback |
| com.domo.connector.mariadbwriteback |
| com.domo.connector.s3unloadwriteback |
| com.domo.connector.mysql.ssh.writeback |
| com.domo.connector.hl7.writeback |
| com.domo.connector.oracledatabasewriteback |
| com.domo.connector.marketowriteback |
| com.domo.connector.aurorawriteback |
| com.domo.connector.adaptiveplanningwriteback |
| com.domo.connector.snowflake.oauth.writeback |
| com.domo.connector.workivawriteback |
| com.domo.connector.workfrontwriteback |
| com.domo.connector.fedex.writeback |
| com.domo.connector.labeltraxx.writeback |
| com.domo.connector.amazonkendrawriteback |
| com.domo.connector.emarsyscontacts.writeback |
| com.domo.connector.googledriveenterprisewriteback |
| com.domo.connector.firebasewriteback |
| com.domo.connector.splunk.writeback |
| com.domo.connector.amazonkendra.sharepointonline.writeback |
| com.domo.connector.cventwriteback |
| com.domo.connector.databricks.writeback |
| com.domo.connector.emarsys.sales.writeback |
| com.domo.connector.anonomatic.augmented.writeback |
| com.domo.connector.mongodbwriteback |
| com.domo.connector.redshiftsshwriteback |

