---
title : Sample Beast Mode Calculations
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC/release-notes', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamoGAC', 'https://domo-support.domo.com/s/topic/0TO5w000000ZanAGAS', 'https://domo-support.domo.com/s/topic/0TO5w000000ZanAGAS/beast-mode']
date: 2022-10-24 22:42:00

url : https://domo-support.domo.com/s/article/360043429993
linked_kbs :  ['[https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC/release-notes](https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC/release-notes)', '[https://domo-support.domo.com/s/article/360043429693](https://domo-support.domo.com/s/article/360043429693)', '[https://domo-support.domo.com/s/article/360043430113](https://domo-support.domo.com/s/article/360043430113)', '[https://domo-support.domo.com/s/article/360043430133](https://domo-support.domo.com/s/article/360043430133)', '[https://domo-support.domo.com/s/article/360043430093](https://domo-support.domo.com/s/article/360043430093)', '[https://domo-support.domo.com/s/article/360043429993](https://domo-support.domo.com/s/article/360043429993)', '[https://domo-support.domo.com/s/article/360043429933](https://domo-support.domo.com/s/article/360043429933)', '[https://domo-support.domo.com/s/knowledge-base/](https://domo-support.domo.com/s/knowledge-base/)', '[https://domo-support.domo.com/s/knowledge-base](https://domo-support.domo.com/s/knowledge-base)', '[https://domo-support.domo.com/s/article/360043931814](https://domo-support.domo.com/s/article/360043931814)', '[https://domo-support.domo.com/s/article/360042925514](https://domo-support.domo.com/s/article/360042925514)', '[https://domo-support.domo.com/s/article/360043429953](https://domo-support.domo.com/s/article/360043429953)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZamoGAC](https://domo-support.domo.com/s/topic/0TO5w000000ZamoGAC)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZanAGAS](https://domo-support.domo.com/s/topic/0TO5w000000ZanAGAS)', '[https://domo-support.domo.com/s/article/360042925494](https://domo-support.domo.com/s/article/360042925494)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZanAGAS/beast-mode](https://domo-support.domo.com/s/topic/0TO5w000000ZanAGAS/beast-mode)', '[https://domo-support.domo.com/s/article/360043430073](https://domo-support.domo.com/s/article/360043430073)']
article_id : 000004087
views : 11,891
created_date : 2022-10-24 21:20:00
last updated : 2022-10-24 22:42:00
---



Hello! To better help our users to find what they're looking for, we have divided this topic into a number of much more navigable smaller topics. Click on the link in the following table that corresponds to the calculation you're looking for. 




| Topic | Description | Link |
| --- | --- | --- |
| Sample Beast Mode Calculations: Basic Transforms | Refer to this article for help in writing Beast Mode calculations for basic transforms such as renaming a column, creating a custom sort order, filtering values, and so on. | [Sample Beast Mode Calculations: Basic Transforms](/s/article/360043430073 "Sample Beast Mode Calculations: Basic Transforms") |
| Sample Beast Mode Calculations: Date Transforms | Learn how to transform date columns by creating calculations for transforming time zones, converting week numbers to dates, and more. | [Sample Beast Mode Calculations: Date Transforms](/s/article/360042925494 "Sample Beast Mode Calculations: Date Transforms") |
| Sample Beast Mode Calculations: Period-over-Period Transforms | Learn how to create dozens of different period-over-period Beast Mode transforms. | [Sample Beast Mode Calculations: Period-over-Period Transforms](/s/article/360043430133 "Sample Beast Mode Calculations: Period-over-Period Transforms") |
| Sample Beast Mode Calculations: Card Element Transforms | Learn how to transform card elements such as summary numbers, table values, and URLs. | [Sample Beast Mode Calculations: Card Element Transforms](/s/article/360043430093 "Sample Beast Mode Calculations: Card Element Transforms") |
| Sample Beast Mode Calculations: Mathematical Transforms | Refer to this article when you need to perform mathematical transforms using Beast Mode, such as finding the X-bar value, computing averages of data points, converting hexadecimal to decimal, etc. | [Sample Beast Mode Calculations: Mathematical Transforms](/s/article/360042925514 "Sample Beast Mode Calculations: Mathematical Transforms") |
| Sample Beast Mode Calculations: Miscellaneous Transforms | Refer to this article to learn how to write a variety of miscellaneous Beast Mode calculations, such as calculating average time in seconds, removing NULL values, creating page Analyzer links, and so on. | [Sample Beast Mode Calculations: Miscellaneous Transforms](/s/article/360043430113 "Sample Beast Mode Calculations: Miscellaneous Transforms") |


 

