---
title : Best Practices for Managing DataSets
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:42:00
url : https://domo-support.domo.com/s/article/360042926154
linked_kbs :  ['https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360042935334', 'https://domo-support.domo.com/s/article/360043429913', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360043439953', 'https://domo-support.domo.com/s/article/360042935294', 'https://domo-support.domo.com/s/article/360043440173', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360042926154', 'https://domo-support.domo.com/s/article/360043439993', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360043430493', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
article_id : 000004900
views : 8,634
created_date : 2022-10-24 22:34:00
last updated : 2022-10-24 22:42:00
---



General Best Practices
----------------------



* Make sure that every DataSet you create or import has a name and a description with specific details about what that DataSet contains.
* Refrain from including the name of the connector you’re using in the DataSet title name to avoid redundancy.
* Don’t add date ranges in the DataSet name (for example, “Google Analytics 2016”). Most DataSets are set up on automated schedule, and the name may become out of date soon. This practice will also help you avoid having to rename the DataSet and all other DataSets with dates in their names.
* For DataSet descriptions, write a basic description of what data is being pulled, such as spends, impressions, etc. You can put the update frequency in the description, but it will often depend on whether or not that element is important to typical users.
* Always designate an owner of the DataSet. This person should be responsible for that data. If a person sets up a DataSet and then does not transfer it to the owner of the data who should responsible for updating it, then the person who created the dataset (not the presumed owner) would receive the alert if that dataset breaks instead of the presumed owner, who is tasked with fixing it.
* Add the data input and outsets for that DataFlow so future users can track down information relevant to the DataSet or DataFlow. In addition, include the frequency of the DataFlow and if it is automated or on a schedule.



	+ **Suggested DataFlow DataSet Descriptions:** 
	
	
	
		- Input DataSets:
		- Output DataSets:
		- Run Frequency:
* When creating DataFlows that contain a calculated field, you want to add a prefix or a suffix such as ”CALC” so future users know there a calculated field in the DataFlow. When you troubleshoot the DataFlow later, it is much easier to determine if you are aware of the calculations.
* DataSets should be named using the following template: TYPE\_ClientInfo\_Source\_ReportName (for example, RAW\_Kablinko\_Sizmek\_Performance\_Analytics)
* **Recommended Naming Prefixes and What Each Means**



	+ RAW\_: Raw data file that is pulled directly from a source. Transformations will be done on this data with Magic ETL or MySQL.
	+ INT\_: Intermediary DataSet for DataFlow.  Usually the output of a dataflow that prepares the data to be merged with another source. Add PROD DataSet to description.
	+ DEV\_: Data is being audited. Change to PROD when audited.
	+ PROD\_: Production. Used for final DataSets. These are DataSets you can build cards on.
	+ TEMP\_: Used for test, development, and ad-hoc DataSets. These should be periodically audited to determine necessity.
* **Recommended Naming Suffix**



	+ CALC: Calculated fields that have been added through the ETL process.
* All DataSets must follow certain column naming conventions that ensure your column names are correctly interpreted. This applies to all DataSets (Connectors, imports, DataFlow output, etc.)
* **Column Naming Conventions**

	+ Column names cannot begin with a single quote, double quote, or a backtick.
	+ Column names cannot contain surrogate characters (special characters that use two code points to represent a single character.)
	+ Column names must be unique, regardless of case. In other words, columns that differ in name by case only are not allowed.
	+ All other column names are valid.
* Before you select the Share Calculation option when creating a Beast Mode, determine when it is effective to select this option. If the calculation is a common field many people will be using, it’s a good idea to share the calculation. If it’s a one time, ad hoc function, it is better to not share it, because it may end up causing problems for other users who don’t understand how it is supposed to be used in context.


Data Governance
---------------



* If your company wants to create an extensive governance model, you have the option of adding comments to a Beast Mode calculation for a DataSet. These comments, which are essentially metadata within the Beast Mode calculation itself, can identify the author of the Beast Mode calculation and create a date and description of the Beast Mode and what it does. This way other people can access this useful information when they are determining whether to use it in their cards or who they need to talk to if they have questions about it.



	+ **Example Metadata for Beast Mode Identifying Author, Created Date, Brief Description**


/\* Author: 


Created Date:


Description:


  \*/  
 



* If you are doing a test connection on a new DataSet, always set it to update manually instead of trying to set up an automatic feed. You don’t want a test or a problem dataset uploaded regularly.
* Have the MajorDomo or another key stakeholder audit DataSets on a regular basis to make sure that there aren’t redundant DataSets, DataSets that have zero cards, and DataSets with zero DataFlows connected to them.
* The MajorDomo can audit cards in the Data Center by sorting by number of cards. If you find a number of cards with zero DataSets connected to them, you can either delete each or reach out to the owner of the DataSets to determine why the cards are inside of Domo and, if necessary, ask that the owner delete the DataSet(s).
* When auditing unused DataFlows it is a bit trickier to distinguish, but if you see it hasn’t run in 1-2 months, that’s an indication that there is no schedule on it and you may be able to delete it out, or investigate with the owner what’s going on with it.
* When setting up data governance, make individual assignments for each tools. For example, you could assign one person to audit Workbench, one to audit all of the social data, one to audit Magic ETL data, and so on. Having an owner for each data type ensures those resources are always being audited. This can help facilitate your DataSet requirements and decrease the number of issues that are brought to the Center of Excellence.
* Have a process in place for the user to 



	+ Upload the data.
	+ Validate that the data is correct, either in Workbench or another tool.
	+ Validate the data again in Domo to make sure your numbers are projecting as expected.
	+ Go through every step of the process to ensure your data is correct and you can build cards from it.
	+ After you have validated the data, make sure that Analyzer understands the DataSet.
	+ After the card is built, have your data owner validate the card, as there may be a dimension that the person who built the card missed in regards to filtering.


By having validation steps throughout the entire process, you make sure that the numbers are appearing as expected and aren’t missing any details in a complex data structure or have calculations that don’t make sense.



* Have those who audit data always check errors and check run failures. Make sure these persons have credentials and access to accounts if they are not the credential owner.
* It is good practice to audit the Data Center once a quarter and make sure all the important DataFlows and DataSets are running. Also, confirm that all credentials are working or re-authenticate any of the ones that are out of date.


Other Best Practices Topics
---------------------------


For more Domo best practices, visit the following topics:



* [Projects and Tasks Best Practices](..\projects_and_tasks_best_practices\index.qmd "Projects and Tasks Best Practices")
* [Best Practices for Creating Visualization Cards](..\best_practices_for_creating_visualization_cards\index.qmd "Best Practices for Creating KPI Cards")
* [Best Practices for Choosing Chart Types](..\best_practices_for_choosing_chart_types\index.qmd "Best Practices for Choosing Chart Types")
* [Top 10 Dashboard Design Best Practices](..\top_10_dashboard_design_best_practices\index.qmd "Top 10 Dashboard Design Best Practices")
* [Best Practices for Standardizing KPIs](..\best_practices_for_standardizing_visualization_cards\index.qmd "Best Practices for Standardizing KPIs")
* [Best Practices for Designing KPIs](/s/article/360042935334 "Best Practices for Designing KPIs")