---
title : Date Format Specifier Characters for Beast Mode
url : https://domo-support.domo.com/s/article/360043429953
linked_kbs :  ['[https://domo-support.domo.com/s/knowledge-base/](https://domo-support.domo.com/s/knowledge-base/)', '[https://domo-support.domo.com/s/](https://domo-support.domo.com/s/)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZamoGAC](https://domo-support.domo.com/s/topic/0TO5w000000ZamoGAC)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZanAGAS](https://domo-support.domo.com/s/topic/0TO5w000000ZanAGAS)', '[https://domo-support.domo.com/s/article/360043429913](https://domo-support.domo.com/s/article/360043429913)', '[https://domo-support.domo.com/s/article/360043429953](https://domo-support.domo.com/s/article/360043429953)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZanAGAS/beast-mode](https://domo-support.domo.com/s/topic/0TO5w000000ZanAGAS/beast-mode)', '[https://domo-support.domo.com/s/article/360043429933](https://domo-support.domo.com/s/article/360043429933)', '[https://domo-support.domo.com/s/article/360042925494](https://domo-support.domo.com/s/article/360042925494)', '[https://domo-support.domo.com/s/article/4408174643607](https://domo-support.domo.com/s/article/4408174643607)', '[https://domo-support.domo.com/s/login/](https://domo-support.domo.com/s/login/)']
article_id : 000004088
html : {'Title': <div class="slds-form-element__control slds-grid itemBody" data-aura-rendered-by="16:337;a"><span class="test-id__field-value slds-form-element__static slds-grow is-read-only" data-aura-rendered-by="17:337;a"><span class="uiOutputText" data-aura-class="uiOutputText" data-aura-rendered-by="9:337;a">Date Format Specifier Characters for Beast Mode</span></span><!--render facet: 19:337;a--><!--render facet: 20:337;a--></div>, 'Article Body': <div class="slds-form-element__control slds-grid itemBody" data-aura-rendered-by="40:337;a"><span class="test-id__field-value slds-form-element__static slds-grow is-read-only" data-aura-rendered-by="41:337;a"><div class="slds-rich-text-editor__output uiOutputRichText forceOutputRichText" data-aura-class="uiOutputRichText forceOutputRichText" data-aura-rendered-by="32:337;a" dir="ltr"><h2 data-aura-rendered-by="33:337;a">Intro</h2>
<p data-aura-rendered-by="33:337;a">In a Beast Mode calculation using a <span class="mt-font-courier-new">DATE_FORMAT</span> function, you can specify the format to use for a date or time column by specifying the column and the date or time string, as in <span class="mt-font-courier-new">DATE_FORMAT(`<em>datecolumn</em>`,'<em>format</em>')</span> where <em>datecolumn</em> is the column containing a date value and where <em>format</em> is the string containing specifier characters to use in formatting the date value.</p>
<p data-aura-rendered-by="33:337;a">For example, using <span class="mt-font-courier-new">DATE_FORMAT(`MyDate`,'%Y-%m-%d %h:%i %p')</span>, the date in the <em>MyDate</em> date column uses this format: 2013-04-17 10:10 AM.</p>
<p data-aura-rendered-by="33:337;a">The "%" character is required before format specifier characters.</p>
<p data-aura-rendered-by="33:337;a">If necessary, you can convert date string values in columns to datetime values using the <span class="mt-font-courier-new">STR_TO_DATE</span> function.</p>
<div class="info-box note" data-aura-rendered-by="33:337;a">
<div class="info-box-wrapper">
<div class="info-box-icon-container"><span class="info-box-icon"> </span></div>
<div class="info-box-content-container">
<div class="info-box-content">
<strong>Note: </strong>In a Beast Mode calculation using a <span class="mt-font-courier-new">TIME_FORMAT</span> function, you can specify the format to use for time values in a time column by specifying the column and the time string, as in <span class="mt-font-courier-new">TIME_FORMAT(`<em>datetimecolumn</em>`,'<em>format</em>')</span> where <em>datetimecolumn</em> is the column containing a time value and where <em>format</em> is the string containing specifier characters to use in formatting the time value.<br/><br/>The format specifiers used in <span class="mt-font-courier-new">DATE_FORMAT</span> may be used with <span class="mt-font-courier-new">TIME_FORMAT</span>, but specifiers other than hours, minutes, seconds and microseconds produce a NULL value or 0.</div>
</div>
</div>
</div>
<p data-aura-rendered-by="33:337;a"><strong>Sample Formats</strong></p>
<table border="1" cellpadding="1" cellspacing="1" data-aura-rendered-by="33:337;a" style="width: 100%;table-layout: fixed;"><thead><tr><th colspan="1" rowspan="1"><p>Format</p></th><th colspan="1" rowspan="1"><p>Result</p></th></tr></thead><tbody><tr><td colspan="1" rowspan="1"><p><code>DATE_FORMAT(`MyDateColumn`,'%m-%d-%Y')</code></p></td><td colspan="1" rowspan="1"><p><code>11-04-2008</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>DATE_FORMAT(`MyDateColumn`,'%d %b %y')</code></p></td><td colspan="1" rowspan="1"><p><code>04 Nov 08</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>DATE_FORMAT(`MyDateColumn`,'%d %b %Y %T')</code></p></td><td colspan="1" rowspan="1"><p><code>04 Nov 2008 11:45:34</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>DATE_FORMAT(`MyDateColumn`, '%m/%d/%Y')</code></p></td><td colspan="1" rowspan="1"><p><code>01/13/2013</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>DATE_FORMAT(`MyDateColumn`, '%M %d, %Y')</code></p></td><td colspan="1" rowspan="1"><p><code>August 1, 2013</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>DATE_FORMAT(`MyDateColumn`, '%b %d, %Y')</code></p></td><td colspan="1" rowspan="1"><p><code>Aug 1, 2013</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>DATE_FORMAT(`MyDateColumn`,'%b %d %Y %h:%i %p')</code></p></td><td colspan="1" rowspan="1"><p><code>Nov 04 2008 11:45 PM</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>DATE_FORMAT(`MyDateColumn`,'%Y-%m-%d %h:%i:%s')</code></p></td><td colspan="1" rowspan="1"><p><code>2013-11-06 09:38:10</code></p></td></tr><tr><td colspan="1" rowspan="1"><p><code>DATE_FORMAT(STR_TO_DATE(`MyDateColumn`,'%m,%d,%Y'),'%m/%d/%Y')</code></p></td><td colspan="1" rowspan="1"><p><code>11/04/2008</code></p></td></tr></tbody></table>
<p data-aura-rendered-by="33:337;a">For more information about adding Beast Mode calculations, see <a href="/s/article/360043429913" target="_blank" title="Adding a Beast Mode Calculation to Your Chart">Adding a Beast Mode Calculation to Your Chart</a>.</p>
<h2 data-aura-rendered-by="33:337;a">Date format specifiers</h2>
<p data-aura-rendered-by="33:337;a">All examples assume a date and time of April 15th, 2013, at 11:44:15 PM.</p>
<table border="1" cellpadding="1" cellspacing="1" data-aura-rendered-by="33:337;a" style="width: 100%;table-layout: fixed;"><thead><tr><th colspan="1" rowspan="1"><p>Specifier</p></th><th colspan="1" rowspan="1"><p>Description</p></th><th colspan="1" rowspan="1"><p>Sample</p></th><th colspan="1" rowspan="1"><p>Result</p></th></tr></thead><tbody><tr><td colspan="1" rowspan="1"><p><code>%a</code></p></td><td colspan="1" rowspan="1"><p>Abbreviated weekday name (Sun..Sat)</p></td><td colspan="1" rowspan="1"><p><code>DATE_FORMAT(`MyDate`,'%a')</code></p></td><td colspan="1" rowspan="1"><p>Mon </p></td></tr><tr><td colspan="1" rowspan="1"><p><code>%b</code></p></td><td colspan="1" rowspan="1"><p>Abbreviated month name (Jan..Dec)</p></td><td colspan="1" rowspan="1"><p><code>DATE_FORMAT(`MyDate`,'%b')</code></p></td><td colspan="1" rowspan="1"><p>Apr</p></td></tr><tr><td colspan="1" rowspan="1"><p><code>%d</code></p></td><td colspan="1" rowspan="1"><p>Day of month, numeric (00-31)</p></td><td colspan="1" rowspan="1"><p><code>DATE_FORMAT(`MyDate`,'%d')</code></p></td><td colspan="1" rowspan="1"><p>13</p></td></tr><tr><td colspan="1" rowspan="1"><p><code>%f</code></p></td><td colspan="1" rowspan="1"><p>Microseconds (000000..999999)</p></td><td colspan="1" rowspan="1"><p><code>DATE_FORMAT(`MyDate`,'%f')</code></p></td><td colspan="1" rowspan="1"><p>300000</p></td></tr><tr><td colspan="1" rowspan="1"><p><code>%H</code></p></td><td colspan="1" rowspan="1"><p>Hour (00-23)</p></td><td colspan="1" rowspan="1"><p><code>DATE_FORMAT(`MyDate`,'%H')</code></p></td><td colspan="1" rowspan="1"><p>23</p></td></tr><tr><td colspan="1" rowspan="1"><p><code>%h</code></p></td><td colspan="1" rowspan="1"><p>Hour (01-12)</p></td><td colspan="1" rowspan="1"><p><code>DATE_FORMAT(`MyDate`,'%h')</code></p></td><td colspan="1" rowspan="1"><p>11</p></td></tr><tr><td colspan="1" rowspan="1"><p><code>%i</code></p></td><td colspan="1" rowspan="1"><p>Minutes, numeric (00-59)</p></td><td colspan="1" rowspan="1"><p><code>DATE_FORMAT(`MyDate`,'%i')</code></p></td><td colspan="1" rowspan="1"><p>44</p></td></tr><tr><td colspan="1" rowspan="1"><p><code>%j</code></p></td><td colspan="1" rowspan="1"><p>Day of year (001-366)</p></td><td colspan="1" rowspan="1"><p><code>DATE_FORMAT(`MyDate`, '%j')</code></p></td><td colspan="1" rowspan="1"><p>105</p></td></tr><tr><td colspan="1" rowspan="1"><p><code>%M</code></p></td><td colspan="1" rowspan="1"><p>Month name (January..December)</p>
<div class="info-box note">
<div class="info-box-wrapper">
<div class="info-box-icon-container"><span class="info-box-icon"></span></div>
<div class="info-box-content-container">
<div class="info-box-content">
<strong>Note:</strong> This option is padded with trailing whitespace to 9 characters.</div>
</div>
</div>
</div></td><td colspan="1" rowspan="1"><p><code>DATE_FORMAT(`MyDate`,'%M')</code></p></td><td colspan="1" rowspan="1"><p>April</p></td></tr><tr><td colspan="1" rowspan="1"><p><code>%m</code></p></td><td colspan="1" rowspan="1"><p>Month, numeric (00-12)</p></td><td colspan="1" rowspan="1"><p><code>DATE_FORMAT(`MyDate`,'%m')</code></p></td><td colspan="1" rowspan="1"><p>04</p></td></tr><tr><td colspan="1" rowspan="1"><p><code>%p</code></p></td><td colspan="1" rowspan="1"><p>AM or PM</p></td><td colspan="1" rowspan="1"><p><code>DATE_FORMAT(`MyDate`,'%p')</code></p></td><td colspan="1" rowspan="1"><p>PM</p></td></tr><tr><td colspan="1" rowspan="1"><p><code>%r</code></p></td><td colspan="1" rowspan="1"><p>Time, 12-hour (hh:mm:ss followed by AM or PM)</p></td><td colspan="1" rowspan="1"><p><code>DATE_FORMAT(`MyDate`,'%r')</code></p></td><td colspan="1" rowspan="1"><p>11:44:15 PM</p></td></tr><tr><td colspan="1" rowspan="1"><p><code>%s</code></p></td><td colspan="1" rowspan="1"><p>Seconds (00-59)</p></td><td colspan="1" rowspan="1"><p><code>DATE_FORMAT(`MyDate`,'%s')</code></p></td><td colspan="1" rowspan="1"><p>15</p></td></tr><tr><td colspan="1" rowspan="1"><p><code>%T</code></p></td><td colspan="1" rowspan="1"><p>Time, 24-hour (hh:mm:ss)</p></td><td colspan="1" rowspan="1"><p><code>DATE_FORMAT(`MyDate`,'%T')</code></p></td><td colspan="1" rowspan="1"><p>23:44:15</p></td></tr><tr><td colspan="1" rowspan="1"><p><code>%v</code></p></td><td colspan="1" rowspan="1"><p>ISO week number of the year (the first Thursday of the new year is in week 1)</p></td><td colspan="1" rowspan="1"><p><code>DATE_FORMAT(`MyDate`,'v')</code></p></td><td colspan="1" rowspan="1"><p>16</p></td></tr><tr><td colspan="1" rowspan="1"><p><code>%W</code></p></td><td colspan="1" rowspan="1"><p>Weekday name (Sunday..Saturday)</p></td><td colspan="1" rowspan="1"><p><code>DATE_FORMAT(`MyDate`,'%W')</code></p></td><td colspan="1" rowspan="1"><p>Monday</p></td></tr><tr><td colspan="1" rowspan="1"><p><code>%w</code></p></td><td colspan="1" rowspan="1"><p>Day of the week (1-7; Sunday is 1)</p></td><td colspan="1" rowspan="1"><p><code>DATE_FORMAT(`MyDate`,'w')</code></p></td><td colspan="1" rowspan="1"><p>2</p></td></tr><tr><td colspan="1" rowspan="1"><p><code>%x</code></p></td><td colspan="1" rowspan="1"><p>ISO year (4 or more digits)</p></td><td colspan="1" rowspan="1"><p><code>DATE_FORMAT(`MyDate`,'x')</code></p></td><td colspan="1" rowspan="1"><p>2013</p></td></tr><tr><td colspan="1" rowspan="1"><p><code>%Y</code></p></td><td colspan="1" rowspan="1"><p>Year (4 or more digits)</p></td><td colspan="1" rowspan="1"><p><code>DATE_FORMAT(`MyDate`,'%Y')</code></p></td><td colspan="1" rowspan="1"><p>2013</p></td></tr><tr><td colspan="1" rowspan="1"><p><code>%y</code></p></td><td colspan="1" rowspan="1"><p>Last two digits of year</p></td><td colspan="1" rowspan="1"><p><code>DATE_FORMAT(`MyDate`,'%y')</code></p></td><td colspan="1" rowspan="1"><p>13</p></td></tr></tbody></table>
<h2 data-aura-rendered-by="33:337;a" id="h_6b077e3a-2345-41a0-ac1d-21e61753d0a8">Unit type values</h2>
<p data-aura-rendered-by="33:337;a">You can specify unit type values for date or datetime expressions in <span class="mt-font-courier-new">ADDDATE</span>, <span class="mt-font-courier-new">DATE_ADD</span>, <span class="mt-font-courier-new">DATE_SUB</span>, and <span class="mt-font-courier-new">SUBDATE</span> functions, including those listed in the following table.</p>
<div class="info-box note" data-aura-rendered-by="33:337;a">
<div class="info-box-wrapper">
<div class="info-box-icon-container"><span class="info-box-icon"> </span></div>
<div class="info-box-content-container">
<div class="info-box-content">
<strong>Note: </strong>In Beast Mode calculations, the unit type value is case insensitive.</div>
</div>
</div>
</div>
<table border="1" cellpadding="1" cellspacing="1" data-aura-rendered-by="33:337;a" style="width: 100%;table-layout: fixed;"><thead><tr><th colspan="1" rowspan="1"><p>Unit Type Value</p></th><th colspan="1" rowspan="1"><p>Expected Expression Format</p></th></tr></thead><tbody><tr><td colspan="1" rowspan="1"><p>MICROSECOND</p></td><td colspan="1" rowspan="1"><p>MICROSECONDS</p></td></tr><tr><td colspan="1" rowspan="1"><p>SECOND</p></td><td colspan="1" rowspan="1"><p>SECONDS</p></td></tr><tr><td colspan="1" rowspan="1"><p>MINUTE</p></td><td colspan="1" rowspan="1"><p>MINUTES</p></td></tr><tr><td colspan="1" rowspan="1"><p>HOUR</p></td><td colspan="1" rowspan="1"><p>HOURS</p></td></tr><tr><td colspan="1" rowspan="1"><p>DAY</p></td><td colspan="1" rowspan="1"><p>DAYS</p></td></tr><tr><td colspan="1" rowspan="1"><p>WEEK</p></td><td colspan="1" rowspan="1"><p>WEEKS</p></td></tr><tr><td colspan="1" rowspan="1"><p>MONTH</p></td><td colspan="1" rowspan="1"><p>MONTHS</p></td></tr><tr><td colspan="1" rowspan="1"><p>QUARTER</p></td><td colspan="1" rowspan="1"><p>QUARTERS</p></td></tr><tr><td colspan="1" rowspan="1"><p>YEAR</p></td><td colspan="1" rowspan="1"><p>YEARS</p></td></tr><tr><td colspan="1" rowspan="1"><p>SECOND_MICROSECOND</p></td><td colspan="1" rowspan="1"><p>'SECONDS.MICROSECONDS'</p></td></tr><tr><td colspan="1" rowspan="1"><p>MINUTE_MICROSECOND</p></td><td colspan="1" rowspan="1"><p>'MINUTES:SECONDS.MICROSECONDS'</p></td></tr><tr><td colspan="1" rowspan="1"><p>MINUTE_SECOND</p></td><td colspan="1" rowspan="1"><p>'MINUTES:SECONDS'</p></td></tr><tr><td colspan="1" rowspan="1"><p>HOUR_MICROSECOND</p></td><td colspan="1" rowspan="1"><p>'HOURS:MINUTES:SECONDS.MICROSECONDS'</p></td></tr><tr><td colspan="1" rowspan="1"><p>HOUR_SECOND</p></td><td colspan="1" rowspan="1"><p>'HOURS:MINUTES:SECONDS'</p></td></tr><tr><td colspan="1" rowspan="1"><p>HOUR_MINUTE</p></td><td colspan="1" rowspan="1"><p>'HOURS:MINUTES'</p></td></tr><tr><td colspan="1" rowspan="1"><p>DAY_MICROSECOND</p></td><td colspan="1" rowspan="1"><p>'DAYS HOURS:MINUTES:SECONDS.MICROSECONDS'</p></td></tr><tr><td colspan="1" rowspan="1"><p>DAY_SECOND</p></td><td colspan="1" rowspan="1"><p>'DAYS HOURS:MINUTES:SECONDS'</p></td></tr><tr><td colspan="1" rowspan="1"><p>DAY_MINUTE</p></td><td colspan="1" rowspan="1"><p>'DAYS HOURS:MINUTES'</p></td></tr><tr><td colspan="1" rowspan="1"><p>DAY_HOUR</p></td><td colspan="1" rowspan="1"><p>'DAYS HOURS'</p></td></tr><tr><td colspan="1" rowspan="1"><p>YEAR_MONTH</p></td><td colspan="1" rowspan="1"><p>'YEARS-MONTHS'</p></td></tr></tbody></table></div></span><!--render facet: 43:337;a--><!--render facet: 44:337;a--></div>, 'Preview Article': <div class="slds-form-element__control slds-grid itemBody" data-aura-rendered-by="74:337;a"><span class="test-id__field-value slds-form-element__static slds-grow is-read-only" data-aura-rendered-by="75:337;a"><span class="lvm-grid-no-fade-out undefined forceOutputFormulaHtml" data-aura-class="forceOutputFormulaHtml" data-aura-rendered-by="66:337;a"><a data-aura-rendered-by="67:337;a" href="https://domo-support.domo.com/s/article/360043429953" target="_blank">Click here to preview</a></span></span><!--render facet: 77:337;a--><!--render facet: 78:337;a--></div>, 'URL Name': <div class="slds-form-element__control slds-grid itemBody" data-aura-rendered-by="95:337;a"><span class="test-id__field-value slds-form-element__static slds-grow is-read-only" data-aura-rendered-by="96:337;a"><span class="uiOutputText" data-aura-class="uiOutputText" data-aura-rendered-by="88:337;a">360043429953</span></span><!--render facet: 98:337;a--><!--render facet: 99:337;a--></div>, 'Summary': <div class="slds-form-element__control slds-grid itemBody" data-aura-rendered-by="118:337;a"><span class="test-id__field-value slds-form-element__static slds-grow is-read-only" data-aura-rendered-by="119:337;a"><span class="uiOutputTextArea" data-aura-class="uiOutputTextArea" data-aura-rendered-by="109:337;a"><!--render facet: 111:337;a--></span></span><!--render facet: 121:337;a--><!--render facet: 122:337;a--></div>, 'Article Number': <div class="slds-form-element__control slds-grid itemBody" data-aura-rendered-by="150:337;a"><span class="test-id__field-value slds-form-element__static slds-grow is-read-only" data-aura-rendered-by="151:337;a"><span class="uiOutputText" data-aura-class="uiOutputText" data-aura-rendered-by="143:337;a">000004088</span></span><!--render facet: 153:337;a--><!--render facet: 154:337;a--></div>, 'Archived Date': <div class="slds-form-element__control slds-grid itemBody" data-aura-rendered-by="167:337;a"><span class="test-id__field-value slds-form-element__static slds-grow is-read-only" data-aura-rendered-by="168:337;a"><span class="uiOutputDateTime" data-aura-class="uiOutputDateTime" data-aura-rendered-by="160:337;a"></span></span><!--render facet: 170:337;a--><!--render facet: 171:337;a--></div>, 'Language': <div class="slds-form-element__control slds-grid itemBody" data-aura-rendered-by="189:337;a"><span class="test-id__field-value slds-form-element__static slds-grow is-read-only" data-aura-rendered-by="190:337;a"><span data-aura-rendered-by="181:337;a">English</span></span><!--render facet: 192:337;a--><!--render facet: 193:337;a--></div>, 'Primary Version': <div class="slds-form-element__control slds-grid itemBody" data-aura-rendered-by="222:337;a"><span class="test-id__field-value slds-form-element__static slds-grow is-read-only" data-aura-rendered-by="223:337;a"><!--render facet: 199:337;a--><!--render facet: 201:337;a--><!--render facet: 203:337;a--><a class="outputLookupLink slds-truncate outputLookupLink-ka05w00000123SZAAY-197:337;a forceOutputLookup" data-aura-class="forceOutputLookup" data-aura-rendered-by="208:337;a" data-navigable="true" data-ownerid="197:337;a" data-recordid="ka05w00000123SZAAY" data-refid="recordId" data-special-link="true" href="/s/article/360043429953" rel="noreferrer" target="_blank" title="Date Format Specifier Characters for Beast Mode">Date Format Specifier Characters for Beast Mode<!--render facet: 211:337;a--></a></span><!--render facet: 225:337;a--><!--render facet: 226:337;a--></div>, 'Article Total View Count': <div class="slds-form-element__control slds-grid itemBody" data-aura-rendered-by="243:337;a"><span class="test-id__field-value slds-form-element__static slds-grow is-read-only" data-aura-rendered-by="244:337;a"><span class="uiOutputNumber" data-aura-class="uiOutputNumber" data-aura-rendered-by="236:337;a" dir="auto">7,034</span></span><!--render facet: 246:337;a--><!--render facet: 247:337;a--></div>, 'Article Created Date': <div class="slds-form-element__control slds-grid itemBody" data-aura-rendered-by="278:337;a"><span class="test-id__field-value slds-form-element__static slds-grow is-read-only" data-aura-rendered-by="279:337;a"><span class="uiOutputDateTime" data-aura-class="uiOutputDateTime" data-aura-rendered-by="271:337;a">10/24/2022, 9:20 PM</span></span><!--render facet: 281:337;a--><!--render facet: 282:337;a--></div>, 'First Published Date': <div class="slds-form-element__control slds-grid itemBody" data-aura-rendered-by="313:337;a"><span class="test-id__field-value slds-form-element__static slds-grow is-read-only" data-aura-rendered-by="314:337;a"><span class="uiOutputDateTime" data-aura-class="uiOutputDateTime" data-aura-rendered-by="306:337;a">10/24/2022, 10:42 PM</span></span><!--render facet: 316:337;a--><!--render facet: 317:337;a--></div>}
views : 7,034
created_date : 2022-10-24 21:20:00
last updated : 2022-10-24 22:42:00
---



Intro
-----


In a Beast Mode calculation using a DATE\_FORMAT function, you can specify the format to use for a date or time column by specifying the column and the date or time string, as in DATE\_FORMAT(`*datecolumn*`,'*format*') where *datecolumn* is the column containing a date value and where *format* is the string containing specifier characters to use in formatting the date value.


For example, using DATE\_FORMAT(`MyDate`,'%Y-%m-%d %h:%i %p'), the date in the *MyDate* date column uses this format: 2013-04-17 10:10 AM.


The "%" character is required before format specifier characters.


If necessary, you can convert date string values in columns to datetime values using the STR\_TO\_DATE function.




 


**Note:**In a Beast Mode calculation using a TIME\_FORMAT function, you can specify the format to use for time values in a time column by specifying the column and the time string, as in TIME\_FORMAT(`*datetimecolumn*`,'*format*') where *datetimecolumn* is the column containing a time value and where *format* is the string containing specifier characters to use in formatting the time value.  
  
The format specifiers used in DATE\_FORMAT may be used with TIME\_FORMAT, but specifiers other than hours, minutes, seconds and microseconds produce a NULL value or 0.



**Sample Formats**




| Format | Result |
| --- | --- |
| `DATE_FORMAT(`MyDateColumn`,'%m-%d-%Y')` | `11-04-2008` |
| `DATE_FORMAT(`MyDateColumn`,'%d %b %y')` | `04 Nov 08` |
| `DATE_FORMAT(`MyDateColumn`,'%d %b %Y %T')` | `04 Nov 2008 11:45:34` |
| `DATE_FORMAT(`MyDateColumn`, '%m/%d/%Y')` | `01/13/2013` |
| `DATE_FORMAT(`MyDateColumn`, '%M %d, %Y')` | `August 1, 2013` |
| `DATE_FORMAT(`MyDateColumn`, '%b %d, %Y')` | `Aug 1, 2013` |
| `DATE_FORMAT(`MyDateColumn`,'%b %d %Y %h:%i %p')` | `Nov 04 2008 11:45 PM` |
| `DATE_FORMAT(`MyDateColumn`,'%Y-%m-%d %h:%i:%s')` | `2013-11-06 09:38:10` |
| `DATE_FORMAT(STR_TO_DATE(`MyDateColumn`,'%m,%d,%Y'),'%m/%d/%Y')` | `11/04/2008` |


For more information about adding Beast Mode calculations, see [Adding a Beast Mode Calculation to Your Chart](/s/article/360043429913 "Adding a Beast Mode Calculation to Your Chart").


Date format specifiers
----------------------


All examples assume a date and time of April 15th, 2013, at 11:44:15 PM.




| Specifier | Description | Sample | Result |
| --- | --- | --- | --- |
| `%a` | Abbreviated weekday name (Sun..Sat) | `DATE_FORMAT(`MyDate`,'%a')` | Mon  |
| `%b` | Abbreviated month name (Jan..Dec) | `DATE_FORMAT(`MyDate`,'%b')` | Apr |
| `%d` | Day of month, numeric (00-31) | `DATE_FORMAT(`MyDate`,'%d')` | 13 |
| `%f` | Microseconds (000000..999999) | `DATE_FORMAT(`MyDate`,'%f')` | 300000 |
| `%H` | Hour (00-23) | `DATE_FORMAT(`MyDate`,'%H')` | 23 |
| `%h` | Hour (01-12) | `DATE_FORMAT(`MyDate`,'%h')` | 11 |
| `%i` | Minutes, numeric (00-59) | `DATE_FORMAT(`MyDate`,'%i')` | 44 |
| `%j` | Day of year (001-366) | `DATE_FORMAT(`MyDate`, '%j')` | 105 |
| `%M` | Month name (January..December)





**Note:** This option is padded with trailing whitespace to 9 characters.


 | `DATE_FORMAT(`MyDate`,'%M')` | April |
| `%m` | Month, numeric (00-12) | `DATE_FORMAT(`MyDate`,'%m')` | 04 |
| `%p` | AM or PM | `DATE_FORMAT(`MyDate`,'%p')` | PM |
| `%r` | Time, 12-hour (hh:mm:ss followed by AM or PM) | `DATE_FORMAT(`MyDate`,'%r')` | 11:44:15 PM |
| `%s` | Seconds (00-59) | `DATE_FORMAT(`MyDate`,'%s')` | 15 |
| `%T` | Time, 24-hour (hh:mm:ss) | `DATE_FORMAT(`MyDate`,'%T')` | 23:44:15 |
| `%v` | ISO week number of the year (the first Thursday of the new year is in week 1) | `DATE_FORMAT(`MyDate`,'v')` | 16 |
| `%W` | Weekday name (Sunday..Saturday) | `DATE_FORMAT(`MyDate`,'%W')` | Monday |
| `%w` | Day of the week (1-7; Sunday is 1) | `DATE_FORMAT(`MyDate`,'w')` | 2 |
| `%x` | ISO year (4 or more digits) | `DATE_FORMAT(`MyDate`,'x')` | 2013 |
| `%Y` | Year (4 or more digits) | `DATE_FORMAT(`MyDate`,'%Y')` | 2013 |
| `%y` | Last two digits of year | `DATE_FORMAT(`MyDate`,'%y')` | 13 |


Unit type values
----------------


You can specify unit type values for date or datetime expressions in ADDDATE, DATE\_ADD, DATE\_SUB, and SUBDATE functions, including those listed in the following table.




 


**Note:**In Beast Mode calculations, the unit type value is case insensitive.





| Unit Type Value | Expected Expression Format |
| --- | --- |
| MICROSECOND | MICROSECONDS |
| SECOND | SECONDS |
| MINUTE | MINUTES |
| HOUR | HOURS |
| DAY | DAYS |
| WEEK | WEEKS |
| MONTH | MONTHS |
| QUARTER | QUARTERS |
| YEAR | YEARS |
| SECOND\_MICROSECOND | 'SECONDS.MICROSECONDS' |
| MINUTE\_MICROSECOND | 'MINUTES:SECONDS.MICROSECONDS' |
| MINUTE\_SECOND | 'MINUTES:SECONDS' |
| HOUR\_MICROSECOND | 'HOURS:MINUTES:SECONDS.MICROSECONDS' |
| HOUR\_SECOND | 'HOURS:MINUTES:SECONDS' |
| HOUR\_MINUTE | 'HOURS:MINUTES' |
| DAY\_MICROSECOND | 'DAYS HOURS:MINUTES:SECONDS.MICROSECONDS' |
| DAY\_SECOND | 'DAYS HOURS:MINUTES:SECONDS' |
| DAY\_MINUTE | 'DAYS HOURS:MINUTES' |
| DAY\_HOUR | 'DAYS HOURS' |
| YEAR\_MONTH | 'YEARS-MONTHS' |

