---
title : Outreach Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:42:00
url : https://domo-support.domo.com/s/article/360043432253
linked_kbs :  ['https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360043432253', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003673
views : 2,057
created_date : 2022-10-24 21:14:00
last updated : 2022-10-24 22:42:00
---



Intro
-----


Outreach is a sales communication platform that makes your team's communication workflows faster and reveals the performance insights that make them more effective at selling. To learn more about the Outreach API, visit their page ([https://www.outreach.io/product/platform#api](https://www.outreach.io/product/platform#api "https://www.outreach.io/platform/")).


You connect to your Outreach account in the Data Center. This topic discusses the fields and menus that are specific to the Outreach connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


Prerequisites
-------------


To connect to your Outreach account and create a DataSet, you must have the username and password associated with your Outreach account.


Connecting to Your Outreach Account
-----------------------------------


This section enumerates the options in theÂ **Credentials**Â andÂ **Details**Â panes in the Outreach Connector page.Â The components of the other panes in this page,Â **SchedulingÂ**andÂ **Name & Describe Your DataSet,** are universal across most connector types and are discussed in greater length inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


### Credentials Pane


The DomoÂ OutreachÂ connector uses OAuth to connect, so there is no need to enter credentials within Domo. ClickÂ **Connect**Â (or selectÂ **Add Account**Â ifÂ you haveÂ existing Outreach accounts in Domo) to open the Outreach OAuth screen where you can enter your OutreachÂ username and password. Once you have entered valid OutreachÂ credentials, you can use the same account any time you go to create a new Outreach DataSet. You can manage connector accounts in theÂ **Accounts**Â tab in theÂ Data Center. For more information about this tab, seeÂ [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


**Note:**Â If you are already logged into Outreach when you connect in Domo, you are authenticated automatically when you click **Add account**. If you want to connect to an account that is different from the one you are logged into, you must first log out of Outreach.
### Details Pane


This pane contains a primaryÂ **Reports**Â menu, along with various other menus which may or may not appear depending on the report type you select.




| Menu | Description |
| --- | --- |
| Report | Select the Outreach report you want to run.Â The following reports are available:

|  |  |
| --- | --- |
| Accounts | Retrieves details about accounts used to categorize prospects. |
| Audits | Retrieves details about audit events that happen during the day. Things like login, plugin mapping changes, etc. |
| Call Dispositions | Details about call dispositions used to categorize calls. |
| Call Purposes | Details about call purposes used to categorize calls. |
| Calls | Retrieves details about inbound and outbound calls. |
| Content Category Membership | Retrieves details about content category membership. Use this report to map content to a content category. |
| Content Category Ownership | Retrieves details about content category ownership. use this report to map content to content owners. |
| Content Category | Retrieves details about content categories. |
| Custom Duties | Retrieves details about custom duties, which are freeform user-specified roles or job duties played by a user in their organization. |
| Duty | Retrieves details about duties |
| Email Address | Retrieves details about prospect's email addresses.
 |
| Event | Retrieves details about application events.
 |
| Favorite | Retrieves details about favorites.
 |
| Mail Alias | Retrieves details about mail aliases.
 |
| Mailbox | Retrieves details about mailboxes. |
| Mailings | Retrieves details about emails.
 |
| Messenger Conversation | Retrieves details about messenger conversations.
 |
| Messenger Message | Retrieves details about messenger messages.
 |
| Opportunities | Retrieves details about opportunities. |
| Opportunity Prospect Role | Retrieves details about opportunity prospect roles. |
| Opportunity Stage | Retrieves details about opportunity stages. |
| Personas | Retrieves details about personas used to categorize prospects. |
| Phone Number | Retrieves details about prospect's phone numbers. |
| Profile | Retrieves details about profiles. |
| Prospects | Retrieves details about prospects associated with a logged in user. |
| Recipient | Retrieves details about recipients.
 |
| Role | Retrieves details about roles, which are where an individual falls within the organizational structure.
 |
| Rulesets | Retrieves details about rulesets applied to sequences.
 |
| Sequence States | Retrieves details about sequence states for a prospect
 |
| sequence Steps | Retrieves details about steps in sequences
 |
| Sequence Template | Retrieves details about sequence templates.
 |
| Sequences | Retrieves details about sequences. |
| Snippet | Retrieves details about snippets, a piece of email to be reused in multiple messages. |
| Stages | Retrieves details about stages used to categorize prospects. |
| Task Priority | Retrieves details about priorities used to categorize tasks.
 |
| Tasks | Retrieves details about tasks.
 |
| Team | Retrieves details about teams.
 |
| Template | Retrieves details about email templates.
 |
| Users | Retrieves details about users. |

 |
| Outcome | Select whether you want to retrieve all outcomes, only answered outcomes or only non-answered outcomes. |
| Mailing Type | Select whether to retrieve data for all mailing types or only a specific type (campaign, sequence, or single). |
| Action | Select whether to retrieve data for all task action types or only a specific type (action items, calls, emails, or in-person). |
| State | Select the task state you want to retrieve data for. |
| Type | Select whether to retrieve data for all task types or only a specific type (follow-up, manual, no-reply, open sequence, call sequence, email sequence, task sequence, or touch). |
| Include Email Body? | SelectÂ **True**Â to include the email body in your report data. |
| Date Filter | Select whether to filter dates based on the creation date or the date when updates were last made. |
| DurationÂ  | Select whether you want to pull data for a single date (e.g. January 23) or a date range (e.g. January 23-31).Â Â  |
| Report DateÂ  | Select whether the report data is for a specific date or for a relative number of days back from today. If you chooseÂ **Specific**, the report will always pull data for the selected date whenever it runs. If you choose **Relative**, the report will pull data for the entered number of back days whenever it runs. For example, if you selectedÂ **Relative**Â and entered 7 for the number of days back, each time the report ran it would pull data for the last 7 days.Â  |
| Specific DateÂ  | Select the specific date you want to pull data for.Â  |
| Days Back | Enter the number of past days that should appear in the report. The report will pull data for thisÂ number of pastÂ days whenever it runs. For example, if you entered 7Â here, each time the report ran it would pull data for the last 7 days.Â  |
| Start Date | Specify whether theÂ first date in your date range is a specific or relative date.Â You select the last date in your range inÂ **End Date**.Â  |
| End Date | Specify whether the second date in your date range is a specific or relative date. You select the first date in your range inÂ **Start Date**.Â Â  |
| Specific Start Date | SelectÂ the first date in your date range.Â  |
| Specific End Date | Select the second date in your date range.Â  |
| Days Back to Start From | Enter the number of the farthest day back that should be represented in the report. Combine withÂ **Days Back to End At**Â to create a range of represented days.
For example, if you enteredÂ 10Â forÂ **Days Back to Start From**Â andÂ 5Â forÂ **Days Back to End At**, the report would contain data forÂ 10 days ago up untilÂ 5 days ago. |
| Days Back to End At | Enter the number of the most recent day back that should be represented in the report. Combine withÂ **Days Back to Start From**Â to create a range of represented days.
For example, if you enteredÂ 10Â forÂ **Days Back to Start From**Â andÂ 5Â forÂ **Days Back to End At**, the report would contain data forÂ 10 days ago up untilÂ 5 days ago. |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, seeÂ [AddingÂ a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


### FAQ


Â 


#### What version of the Outreach API does this connector use?


This connector uses version 2 of the Outreach API (<https://api.outreach.io/api/v2>).


#### Which endpoint(s) does each report call in this connector?




| Report Name | Endpoint URL(s) |
| --- | --- |
| Accounts | /accounts |
| Audits | /audits |
| Call Dispositions | /callDispositions |
| Call Purposes | /callPurposes |
| Calls | /calls |
| Content Category Membership | /contentCategoryMemberships |
| Content Category Ownership | /contentCategoryOwnerships |
| Content Category | /contentCategories |
| Custom Duties | /customDuties |
| Duty | /duties |
| Email Address | /emailAddresses |
| Event | /events |
| Favorite | /favorites |
| Mail Alias | /mailAliases |
| Mailbox | /mailboxes |
| Mailings | /mailings |
| Messenger Conversation | /messengerConversations |
| Messenger Message | /messengerMessages |
| Opportunities | /opportunities |
| Opportunity Prospect Role | /opportunityProspectRoles |
| Opportunity Stage | /opportunityStages |
| Personas | /personas |
| Phone Number | /phoneNumbers |
| Profile | /profiles |
| Prospects | /prospects |
| Recipient | /recipients |
| Role | /roles |
| Rulesets | /rulesets |
| Sequence States | /sequenceStates |
| Sequence Steps | /sequenceSteps |
| Sequence Template | /sequenceTemplates |
| Sequences | /sequences |
| Snippet | /snippets |
| Stages | /stages |
| Task Priority | /taskPriorities |
| Tasks | /tasks |
| Team | /teams |
| Template | /templates |
| Users | /users |


#### What kind of credentials do I need to power up this connector?


You need the email address and password of your Outreach account.


#### Why am I getting an error after entering the correct credentials in the OAuth login window?


Outreach has previously had a known issue with their OAuth popup window. This requires you to login into Outreach in a separate tab, then create a Domo Outreach account. For the step-by-step instructions for obtaining a client id, see Outreach  [OAuth Documentation.](https://github.com/getoutreach/outreach-platform-sdk/blob/master/documentation/authorization/oauth.md)


Redirect URL: <https://oauth.domo.com/api/data/v1/oauth/providers/outreach>.


#### How do I know my Outreach account credentials are secure?


Domo's Outreach connector uses OAuth, which authenticates the account without Domo ever having access to your Outreach account credentials.


#### How often can the data be updated?


As often as needed.


#### Are there any API limits that I need to be aware of?


The Outreach API is rate limited on a per-user basis, with a fixed limit of 5,000 requests per one hour period.


#### When I click 'Add Account', why am I getting automatically validated without needing to enter credentials?


If you are already logged into Outreach when you connect to Domo, you are authenticated automatically as you click Add Account. If you want to connect to an account that is different from the one you are logged into, you must first log out of Outreach.