---
title : Available Lollipop Charts
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:42:00
url : https://domo-support.domo.com/s/article/360043428893
linked_kbs :  ['https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360043429153', 'https://domo-support.domo.com/s/article/360043428053', 'https://domo-support.domo.com/s/article/360043428893', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360042923334', 'https://domo-support.domo.com/s/article/360042924614', 'https://domo-support.domo.com/s/article/360043429373', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000004738
views : 4,090
created_date : 2022-10-24 22:28:00
last updated : 2022-10-24 22:42:00
---



Lollipop graphs are essentially modified Bar graphs in which the bars are represented as thin lines so you can fit more in a small area, with small circles to represent mouse-over points. There are eight types of Lollipop graphs in Domo, all of them modified versions of familiar Bar and Line Bar graphs. For more information about these graphs, see [Lollipop Chart](..\lollipop_chart\index.html "Available Bar Graphs").




| Chart Type | Equivalent Bar Graph | Example |
| --- | --- | --- |
| Grouped Lollipop
lollipop-grouped-small.png | [Grouped Bar](..\grouped_bar_chart\index.html "Grouped Bar Graph") | vertical_grouped_lollipop.png |
| Stacked Lollipop
lollipop-stacked-small.png | [Stacked Bar](..\stacked_bar_chart\index.html "Stacked Bar Graph") | vertical_stacked_lollipop.png |
| Grouped Lollipop with Line
lollipop-grouped-with-line-small.png | [Grouped Bar with Line](..\grouped_bar_with_line_chart\index.html "Grouped Bar with Line Graph") | vertical_grouped_lollipop_with_line.png |
| Stacked Lollipop with Line
lollipop-stacked-with-line-small.png | [Stacked Bar with Line](..\stacked_bar_with_line_chart\index.html "Stacked Bar with Line Graph") | vertical_stacked_lollipop_with_line.png |
| Horizontal Grouped Lollipop
lollipop-horizontal-grouped-small.png | [Horizontal Grouped Bar](..\grouped_bar_chart\index.html "Grouped Bar Graph") | horizontal_grouped_lollipop.png |
| Horizontal Stacked Lollipop
lollipop-horizontal-stacked-small.png | [Horizontal Stacked Bar](..\stacked_bar_chart\index.html "Stacked Bar Graph") | horizontal_stacked_lollipop.png |
| Horizontal Grouped Lollipop with Line
lollipop-horizontal-grouped-with-line-small.png | [Horizontal Grouped Bar with Line](..\grouped_bar_with_line_chart\index.html "Grouped Bar with Line Graph") | horizontal_grouped_lollipop_with_line.png |
| Horizontal Stacked Lollipop with Line
lollipop-horizontal-stacked-with-line-small.png | [Horizontal Stacked Bar with Line](..\stacked_bar_with_line_chart\index.html "Stacked Bar with Line Graph") | horizontal_stacked_lollipop_with_line.png |


Â