---
title : MindTouch Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:41:00
url : https://domo-support.domo.com/s/article/360042930274
linked_kbs :  ['https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/article/360042930274', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003429
views : 2,008
created_date : 2022-10-24 21:13:00
last updated : 2022-10-24 22:41:00
---



Intro
-----


MindTouch is a document content management system that helps you organize your documentation so users can easily find it. To learn more about the MindTouch API, visit their page ([https://success.mindtouch.com/Soluti...\_Documentation](https://success.mindtouch.com/Solutions/Knowledge_Management/MindTouch_Tools_and_Features/API_Documentation "https://success.mindtouch.com/Solutions/Knowledge_Management/MindTouch_Tools_and_Features/API_Documentation")).


You connect to your MindTouch account in the Data Center. This topic discusses the fields and menus that are specific to the MindTouch connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).


Prerequisites
-------------


To connect to your MindTouch account and create a DataSet, you must have the following:



* The domain for your MindTouch instance (e.g. [mycompany.mindtouch.com](http://mycompany.mindtouch.com))
* The username and password for your MindTouch account


Connecting to Your MindTouch Account
------------------------------------


This section enumerates the options in the **Credentials** and **Details** panes in the MindTouch Connector page.Â The components of the other panes in this page, **Scheduling**Â and **Name & Describe Your DataSet**, are universal across most connector types and are discussed in greater length inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md "Adding a DataSet Using a Data Connector").


### Credentials Pane


This pane contains fields for entering credentials to connect to your MindTouch account. The following table describes what is needed for each field: Â 




| Field | Description |
| --- | --- |
| Domain | Enter the domain for your MindTouch instance (e.g. [mycompany.mindtouch.com](http://mycompany.mindtouch.com)) |
| Username | Enter your MindTouch username. |
| Password | Enter your MindTouch password. |


Once you have entered valid MindTouch credentials, you can use the same account any time you go to create a new MindTouch DataSet. You can manage connector accounts in the **Accounts** tab in the Data Center. For more information about this tab, see [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


### Details Pane


This pane contains a primaryÂ **Reports**Â menu, along with various other menus which may or may not appear depending on the report type you select.




| Menu | Description |
| --- | --- |
| Report | Select the MindTouch report you want to run.Â The following reports are available:

|  |  |
| --- | --- |
| Archive Files | Retrieves information for all deleted files. |
| Archive Pages | Retrieves information for all deleted pages. |
| Context Maps | Retrieves data about Context Maps. |
| Contexts | Retrieves Contexts data. |
| Events Page Hierarchy | Retrieves a site history summary (last 1000 events per page). |
| Events Page | Retrieves a page history summary (last 1000 events per page). |
| Groups | Retrieves a list of all groups in your MindTouch instance. |
| License | Retrieves information about your MindTouch license. If you are an Admin user in MindTouch, all license information is retrieved; otherwise only the public information is retrieved. |
| Page Rating | Retrieves page rating data for the MindTouch site. |
| Pages | Retrieves a list of pages for the MindTouch site. |
| Search Query Log | Retrieves search query data for a specific date or relative number of days back. |
| Site Activity | Retrieves site activity for a specific date or relative number of days back. |
| Usage | Retrieves data about site usage. |
| Users | Retrieves a list of users in your MindTouch site. |

 |
| Filter | Select whether to retrieve all pages or only those that have been rated. |
| Report Date Type | Select whether to retrieve data for a specific date or relative number of days back. |
| Specific Date | Select the date you want to retrieve data for. |
| Days Back | Enter the number of days back you want to retrieve data for. |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, seeÂ [AddingÂ a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).


Â