---
title : Available Area Charts
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:42:00
url : https://domo-support.domo.com/s/article/360043428873
linked_kbs :  ['https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043428033', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/article/360043429513', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043428873', 'https://domo-support.domo.com/s/article/360043428473', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000004737
views : 4,093
created_date : 2022-10-24 22:28:00
last updated : 2022-10-24 22:42:00
---



An Area graph is a Multi-Line graph in which the area between the topmost line and the category axis is colored in. There are three primary types of Area graphs in Domo:



* Standard Area graphs (referred to simply as "Area" graphs in Domo), in which all series begin from the same axis and are overlaid on top of each other. You can distinguish an individual series by mousing over that series in the legend or in the graph itself. This type of Area graph is useful for quickly discerning the value for individual series, as each series begins from the same baseline. You can learn how to build these graphs in Area Graph.
* Stacked Area graphs, in which series are stacked on top of each other. Because all series do not share the same baseline, this type of Area graph is better for comparing trends than for discerning individual amounts. You can learn how to build these graphs inÂ [Stacked Area Graph](..\stacked_area_chart\index.html "Stacked Area Graph").
* The Stream graph, in which series are centered, similar in appearance to a [Stream Funnel graph](..\stream_funnel_chart\index.html "Stream Funnel Graph") but horizontal instead of vertical. Series in a Stream graph do not share the same baseline and do not overlap. Thus they are better than standard Area and Stacked Area graphs at showing changes between stages. Â


Standard and Stacked Area graphs can be broken down further into various subtypes, including vertical and horizontal, straight lines versus curved and step, etc.


The following tables list the types of Area graphs available in Domo. You can click a thumbnail image to see a larger image.


#### Standard (Overlay) Area Graphs


In a standard Area graph, all series begin from the same axis and are overlaid on top of each other. In their default state these graphs are typically not very useful because data for some series is usually hidden. However, when you mouse over a series in the graph or legend, you can see just the data for that series.Â 


For information about building standard Area graphs, see [Area Overlay Chart](..\area_overlay_chart\index.html "Area Overlay Graph").




| Chart Type | Description | Example |
| --- | --- | --- |
| Vertical Area graph
 | In a vertical Area graph, categories are shown on the x-axis and values on the y-axis, and lines are straight instead of curved. As with other standard Area graphs, all series begin from the baseline, so overlapping of series occurs. However, you can see individual series by mousing over series items in the graph or legend.
The first example at right shows a vertical Area graph in its default state. Seven series are present, but only three are visible in the graph because of overlapping. In the second example, the user is mousing over the **LinkedIn** series, so only that series appears in the graph. | 
 |
| Horizontal Area graph
 | A horizontal Area graph is the same as a vertical Area graph except that the categories are shown on the y-axis and the values on the x-axis.
The first example at right shows a horizontal Area graph in its default state. Seven series are present, but only three are visible in the graph because of overlapping. In the second example, the user is mousing over the **LinkedIn** series, so only that series appears in the graph. | 
 |
| Vertical Curved Area graph
 | In a vertical Curved Area graph, categories are shown on the x-axis and values on the y-axis, and lines curved. As with other standard Area graphs, all series begin from the baseline, so overlapping of series occurs. However, you can see individual series by mousing over series items in the graph or legend.
The first example at right shows a vertical Curved Area graph in its default state. Seven series are present, but only three are visible in the graph because of overlapping. In the second example, the user is mousing over the **LinkedIn** series, so only that series appears in the graph. | 
 |
| Horizontal Curved Area graph
 | A horizontal Curved Area graph is the same as a vertical Curved Area graph except that the categories are shown on the y-axis and the values on the x-axis.
The first example at right shows a horizontal Curved Area graph in its default state. Seven series are present, but only three are visible in the graph because of overlapping. In the second example, the user is mousing over the **LinkedIn** series, so only that series appears in the graph. | 
 |
| Vertical Step Area graph
 | In a vertical Step Area graph, categories are shown on the x-axis and values on the y-axis, and lines are "stepped" throughout the graph. As with other standard Area graphs, all series begin from the baseline, so overlapping of series occurs. However, you can see individual series by mousing over series items in the graph or legend.
The first example at right shows a vertical Step Area graph in its default state. Seven series are present, but only three are visible in the graph because of overlapping. In the second example, the user is mousing over the **LinkedIn** series, so only that series appears in the graph. | 
 |
| Horizontal Step Area graph
 | A horizontal Step Area graph is the same as a vertical Step Area graph except that the categories are shown on the y-axis and the values on the x-axis.
The first example at right shows a horizontal Step Area graph in its default state. Seven series are present, but only three are visible in the graph because of overlapping. In the second example, the user is mousing over the **LinkedIn** series, so only that series appears in the graph. | 
 |


#### Stacked Area Graphs


A Stacked Area graph is a multi-line Line graph in which the space under each line is filled in with a different color, creating colored "segments" that are stacked on top of each other, as in a vertical Stacked Bar graph. The total size of the area for each segment reflects the cumulative value of all data items in that category. These graphs are useful for showing group trends and comparing trends between data series.


For information about building Stacked Area graphs, see [Stacked Area Graph](..\stacked_area_chart\index.html "Stacked Area Graph").




| Chart Type | Description | Example |
| --- | --- | --- |
| Vertical Stacked Area graph
 | In a vertical Stacked Area graph, categories are shown on the x-axis and values on the y-axis, and lines are straight instead of curved or stepped. |  |
| Horizontal Stacked Area graph
 | A horizontal Stacked Area graph is the same as a vertical Stacked Area graph except that the categories are shown on the y-axis and the values on the x-axis. |  |
| Vertical Curved Stacked Area graph
 | A vertical Curved Stacked Area graph is the same as a regular Vertical Stacked Area graph except that the lines are curved instead of straight. |  |
| Horizontal Curved Stacked Area graph
 | A horizontal Curved Stacked Area graph is the same as a regular horizontal Stacked Area graph except that the lines are curved instead of straight. |  |
| Vertical Step Stacked Area graph
 | A vertical Step Stacked Area graph is the same as a regular Vertical Stacked Area graph except that the lines are "stepped." |  |
| Horizontal Step Stacked Area graph
 | A horizontal Step Stacked Area graph is the same as a regular horizontal Stacked Area graph except that the lines are "stepped." |  |
| Vertical 100% Stacked Area graph
 | In a 100% Stacked Area graph, segments are shown as a percentage of 100, similar to a Pie graph. In the standard vertical version, categories are shown on the x-axis and values on the y-axis, and lines are straight instead of curved or stepped. |  |
| Horizontal 100% Stacked Area graph
 | This graph type is the same as a vertical 100% Stacked Area graph except that categories are shown on the y-axis and values on the x-axis. |  |
| Vertical Curved 100% Stacked Area graph
 | This graph type is the same as a standard vertical 100% Stacked Area graph except that the lines are curved instead of straight. |  |
| Horizontal Curved 100% Stacked Area graph
area-horizontal-100-curved-stacked.png | This graph type is the same as a standard horizontal 100% Stacked Area graph except that the lines are curved instead of straight. |  |
| Vertical Step 100% Stacked Area graph
 | This graph type is the same as a standard vertical 100% Stacked Area graph except that the lines are "stepped" instead of straight. |  |
| Horizontal Step 100% Stacked Area graph
 | This graph type is the same as a standard horizontal 100% Stacked Area graph except that the lines are "stepped" instead of straight. |  |


#### Stream Graph


Unlike the other types of Area graphs in Domo, there is only one type of Stream graph. This type of graph is most similar to theÂ [Stream Funnel graph](..\stream_funnel_chart\index.html "Stream Funnel Graph") (classified in DomoÂ with the Pie-type graphs) but is horizontal instead of vertical.




| Chart Type | Description | Example |
| --- | --- | --- |
| Stream graph
 | A Stream graph is a cross between a horizontal Area graph and a Funnel graph.Â Series in a Stream graph are centered. They do not share the same baseline and do not overlap. Thus they are better than standard Area and Stacked Area graphs at showing changes between stages. |  |


Â 


Â 


Â