---
title: CSV Advanced Connector
url: https://domo-support.domo.com/s/article/360043436513
linked_kbs:  ['[https://domo-support.domo.com/s/knowledge-base/](https://domo-support.domo.com/s/knowledge-base/)', '[https://domo-support.domo.com/s/](https://domo-support.domo.com/s/)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZammGAC](https://domo-support.domo.com/s/topic/0TO5w000000ZammGAC)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZanLGAS](https://domo-support.domo.com/s/topic/0TO5w000000ZanLGAS)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZaowGAC](https://domo-support.domo.com/s/topic/0TO5w000000ZaowGAC)', '[https://domo-support.domo.com/s/article/360042926274](https://domo-support.domo.com/s/article/360042926274)', '[https://domo-support.domo.com/s/article/360043630093](https://domo-support.domo.com/s/article/360043630093)', '[https://domo-support.domo.com/s/article/360042926054](https://domo-support.domo.com/s/article/360042926054)', '[https://domo-support.domo.com/s/article/360043436513](https://domo-support.domo.com/s/article/360043436513)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZaowGAC/file-connectors](https://domo-support.domo.com/s/topic/0TO5w000000ZaowGAC/file-connectors)', '[https://domo-support.domo.com/s/article/360043429933](https://domo-support.domo.com/s/article/360043429933)', '[https://domo-support.domo.com/s/article/360043429953](https://domo-support.domo.com/s/article/360043429953)', '[https://domo-support.domo.com/s/article/360042925494](https://domo-support.domo.com/s/article/360042925494)', '[https://domo-support.domo.com/s/article/4408174643607](https://domo-support.domo.com/s/article/4408174643607)', '[https://domo-support.domo.com/s/article/360043429913](https://domo-support.domo.com/s/article/360043429913)', '[https://domo-support.domo.com/s/login/](https://domo-support.domo.com/s/login/)']
article_id: 000003952
views: 2,517
created_date: 2022-10-24 21:17:00
last updated: 2022-10-24 22:40:00
---



Intro
-----


A character-separated values (CSV) file stores tabular data in plain text form. The Domo CSV Advanced connector allows you to access CSV files that you have uploaded to an SFTP server. You can also import files via HTTPS calls.




 


**Note:** Due to security concerns, Domo no longer permits uploading data using FTP. If necessary, please update your server settings to support SFTP instead of FTP. 



You connect to CSV files in the Data Center. This topic discusses the fields and menus that are specific to the CSV Advanced connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed in [Adding a DataSet Using a Data Connector](/s/article/360042926274).




|  |  |
| --- | --- |
| **Primary Use Cases** | Use this connector to access CSV files from an SFTP server. |
| **Primary Metrics** | N/A |
| **Primary Company Roles** | Analysts |
| **Average Implementation Time** | 1 hour |
| **Ease of Use (on a 1-to-10 scale with 1 being easiest)** | 4 |


Best Practices
--------------


If you are using SFTP, make sure your credentials are ready and verified via your SSH key. The accepted formats for the key are either DES or RSA. If you are using HTTPS, you only need to verify that your resource is protected.


Prerequisites
-------------


If you plan to access CSV files by connecting to an SFTP server, you must have a username and password to authenticate to that server. If you plan to access CSV files over HTTPS, credentials are required only if the resource is protected.


You need the username and password associated with your CSV file. You also your SSH key and the passphrase for your ssh key.







**Note:** Domo does not support the SSH keys generated using ssh-keygen. The SSH keys need to be the DES or RSA keys (in PEM format) generated by OpenSSL.



Connecting to CSV Files
-----------------------


This section enumerates the options in the **Credentials**, **Details**, and **Advanced** panes in the CSV Advanced Connector page. The components of the other panes in this page, **Scheduling** and **Name & Describe Your DataSet**, are universal across most connector types and are discussed in greater length in [Adding a DataSet Using a Data Connector](/s/article/360042926274 "Adding a DataSet Using a Data Connector").


### Credentials Pane


In this pane you may need to enter a username and password, depending on what protocol you are using to access CSV data and whether the data is protected. If you plan to access CSV files by connecting to an SFTP server, you must enter the credentials for that server here (username, password, and host name). If you plan to access files over HTTPS, you only need to enter credentials if the resource is protected. You must also whitelist the IP addresses from the following article on the server: [Whitelisting IP Addresses for Connectors](/s/article/360043630093 "Whitelisting IP Addresses").


In either case, once you click **Next**, this CSV account is saved and you can use the same account any time you go to create a new CSV Advanced DataSet. You can manage connector accounts in the **Accounts** tab in the Data Center. For more information about this tab, see [Managing User Accounts for Connectors](/s/article/360042926054 "Managing User Accounts for Connectors").


You may also have the option to import the CSV file from a URL. If this is the case, you need the URL and potentially a username and password, depending on whether the source requires them.


### Details Pane


In this pane you choose a protocol (HTTP request or SFTP file transfer) then fill in the details for that protocol. This pane includes the following fields and menus:




| Menu | Description |
| --- | --- |
| Protocol | Select a protocol for accessing the CSV file.
Use SFTP to access a CSV file located on an SFTP server.
Use HTTP Request to access a CSV file using an HTTP GET request. The request is triggered by the use of a unique URL parameter defined by the service providing the CSV file. |
| URL | Enter the URL for the CSV file.
If using the File Transfer protocol, enter the URL to the folder containing the CSV file. For example: s<ftp://hostname/home/test>. You'll also have to include the port in the URL if the SFTP server is not configured to run on the standard port 22. The 1234 port specific URL would look like s<ftp://hostname:1234/home/test>





**Note:** Due to security concerns, Domo no longer permits uploading data using FTP. If necessary, please update your server settings to support SFTP instead of FTP. 



If using the HTTP Request protocol, enter the full URL for the CSV file. You must provide the URL as well as the fully qualified path, including the filename. For example: <http://www.ferc.gov/docs-filing/eqr/...v/contract.txt>
You can also request a file for a specific date. Name your file using the format file\_[yyyyMMdd]\_suffix.csv.
You can also select the most recent file using the format filenameprefix\_[latest]. |
| File Location Method | Select whether you want to select a specific file from the specified directory or search for a file name. |
| File Name | Enter the name of the file to search for. |
| Directory File | Select a file from the specified directory. You can select a CSV or GZ file to parse or a ZIP file to unzip. |
| File Type | Select the file type for the file you want to access. |
| HTTP Headers | Enter additional headers for your HTTP/HTTPS CSV URL, if necessary. Use the format header Name1 = 'headerValue1' and headerName2 = 'headerValue2'. |
| HTTP Body | Enter additional request body for your HTTPS CSV URL, if necessary. |


### Advanced Pane


In this pane you select the delimiter for your CSV file.




| Menu | Description |
| --- | --- |
| Delimiter Character | Select the delimiter character used to separate columns in your CSV file. |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, see [Adding a DataSet Using a Data Connector](/s/article/360042926274).


Troubleshooting
---------------


* Verify that your credentials are correct.
* If you cannot connect using SFTP, check your firewall settings.


FAQ
---


##### How frequently will my data update?


Data will update every hour.


##### Are there any API limits that I need to be aware of?


No.


##### Can I use the same CSV Advanced account for multiple datasets?


Yes.


##### What do I do if I cannot connect using SFTP?


If you cannot connect using SFTP, check your firewall settings.

