---
title: Inline Editing Implementation Guide
url: https://domo-support.domo.com/s/article/1500000406641
linked_kbs:  ['[https://domo-support.domo.com/s/knowledge-base/](https://domo-support.domo.com/s/knowledge-base/)', '[https://domo-support.domo.com/s/](https://domo-support.domo.com/s/)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZampGAC](https://domo-support.domo.com/s/topic/0TO5w000000ZampGAC)', '[https://domo-support.domo.com/s/topic/0TO5w000000Zan9GAC](https://domo-support.domo.com/s/topic/0TO5w000000Zan9GAC)', '[https://domo-support.domo.com/s/article/360042933754](https://domo-support.domo.com/s/article/360042933754)', '[https://domo-support.domo.com/s/article/1500000406641](https://domo-support.domo.com/s/article/1500000406641)', '[https://domo-support.domo.com/s/topic/0TO5w000000Zan9GAC/available-apps](https://domo-support.domo.com/s/topic/0TO5w000000Zan9GAC/available-apps)', '[https://domo-support.domo.com/s/article/360043429933](https://domo-support.domo.com/s/article/360043429933)', '[https://domo-support.domo.com/s/article/360043429953](https://domo-support.domo.com/s/article/360043429953)', '[https://domo-support.domo.com/s/article/360042925494](https://domo-support.domo.com/s/article/360042925494)', '[https://domo-support.domo.com/s/article/360043429913](https://domo-support.domo.com/s/article/360043429913)', '[https://domo-support.domo.com/s/article/4408174643607](https://domo-support.domo.com/s/article/4408174643607)', '[https://domo-support.domo.com/s/login/](https://domo-support.domo.com/s/login/)']
article_id: 000004131
views: 2,308
created_date: 2022-10-24 21:24:00
last updated: 2022-10-24 22:41:00
---



Intro
-----


This guide helps you implement the Inline Editing app with your own data. For more information on the Inline Editing app, please visit the [Inline Editing User Guide](https://domo-support.domo.com/s/article/360042933754?language=en_US).  
  
Inline Editing is a premium app you can use to individually or collectively modify the content of any DataSet from a card within Domo.  
  
This guide details how to implement the Inline Editing app in the following topics:


* [Preparing your data](#prepare_data)
* [Converting to an upsert DataSet](#upsert)
* [Deploying the app](#deploy_app)


Preparing Your Data
-------------------


The Inline Editing app is built to handle two types of data models: standard and upsert DataSets. For this version of the app, connector-based DataSets that are updated through outside sources are not recommended, as any changes you save are overwritten by data coming through the connector. 


Standard DataSets have some inherent limitations in terms of how they can be updated, and because of this, if your app is using a standard DataSet you are limited to DataSets that have 100,000 or fewer rows and 500 or fewer columns.


Upsert DataSets can be any size, but they take a little extra effort to set up. Follow the instructions below to convert a DataSet to an upsert DataSet.


### Converting to an Upsert DataSet


(Optional) To convert a DataSet to an upsert DataSet, follow the steps below. 


1. In Domo, navigate to your DataSet.
2. Go to the **Settings** tab, then select the **Update Mode** setting to expand it.
3. Select the **Update method** and choose **Append** from the list.
4. Select **Save** to keep your changes.
5. Now create your upsert keys.  
 Upsert keys are a group of columns in your data that when put together create a unique key for each row— you must set these keys manually.
 The next steps describe how to set your keys.
6. Download the Java CLI tool using the following link: <https://app-domo-com-prod.s3.amazonaws.com/labs/java-sdk/latest/domoUtil.jar>
7. Navigate to and run the JAR file from either your terminal or command line tool.
  




 

**Note:** To run the JAR file in the Mac Terminal, make sure you have java installed and then navigate to the correct directory and use the following command: `'java -jar domoUtil.jar'`
8. When the program is running in your command line, you'll first need to connect to your Domo instance and use the command:
 `connect -s <domain> -t <access_token>`


<domain> is the name of your Domo instance (*mycompany*.[domo.com](http://domo.com)), and <access\_token> is a generated access token from your Domo instance. Access tokens can be generated by admins in your Domo instance by navigating to **Admin** > **Security** > **Access Tokens** and selecting **Generate Access Token**.
9. After you have connected to your instance, use the following command: 


`define-upsert -i <dataset_id> -c <columns>`


<dataset\_id> is the dataset id of the DataSet that you want to set as an upsert DataSet and <columns> is a comma-separated list of columns names that you want to use as upsert keys ("*Column 1"*, "*Column 2"*, and so on). Remember to use double quotes around any columns that have spaces in the column name.
10. To check to see if this process worked, use the following command:


`get-schema -i <dataset_id>`


and check to see if 'upsertKey' is set to true for the columns that you passed through in the last command.
11. Close the CLI tool. Your DataSet is now an upsert DataSet.


Deploying the App
-----------------


If you have access to the app asset, deploy the app from your **Asset Library** and connect your DataSet to it.  
If you don't have access to the app asset, your app admin can connect the app to your DataSet.


App admins must be added to a Domo Group. To learn how to set this up, see the [Inline Editing User Guide](http://domo-support.domo.com/s/article/360042933754?language=en_US). If the group does not exist, the app still functions, but users cannot make any changes to it.


After your data is connected and app admins have been configured, the app is ready to use. See the [Inline Editing User Guide](https://domo-support.domo.com/s/article/360042933754?language=en_US) to learn more.


 