---
title : SugarCRM Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:40:00
url : https://domo-support.domo.com/s/article/360043434333
linked_kbs :  ['https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429913', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043434333']
article_id : 000003487
views : 2,008
created_date : 2022-10-24 21:13:00
last updated : 2022-10-24 22:40:00
---



Intro
-----


SugarCRM produces the web application Sugar, a customer relationship management system that is available in both open-source and commercial open-source applications. You can use Domo's SugarCRMÂ connector to retrieve data about employees, notifications, records by module, and more. To learn more about the SugarCRM API, visit their website. ( [http://support.sugarcrm.com/Document...ces/index.html](http://support.sugarcrm.com/Documentation/Sugar_Developer/Sugar_Developer_Guide_7.8/Integration/Web_Services/index.html "http://support.sugarcrm.com/Documentation/Sugar_Developer/Sugar_Developer_Guide_7.8/Integration/Web_Services/index.html") ).


The SugarCRM connector is a "Cloud App" connector, meaning it retrieves data stored in the cloud. In the Data Center, you can access the connector page for this and other Cloud App connectors by clicking **Cloud App** in the toolbar at the top of the window.


You connect to your SugarCRM account in theÂ Data Center. This topic discusses the fields and menus that are specific to the SugarCRM connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").




|  |  |
| --- | --- |
| **Primary Use Cases** | 
* Lead management
* Pipeline management
* Sales management
* Customer relationship management
 |
| **Primary Metrics** | 
* Leads
* MQL
* SAO
* Closed Deals
* Won Deals
* Average Deal Size
* Open Opportunities
 |
| **Primary Company Roles** | Marketing, sales |
| **Average Implementation Time** | 10-15 hours |
| **Ease of Use (on a 1-to-10 scale with 1 being easiest)** | 5 |


Prerequisites
-------------


To connect to your company SugarCRM instance and create a DataSet, you must have the following:



* The host URL for your company's SugarCRM instance
* Your SugarCRM username and password
* Your SugarCRM client ID (which you can find in the SugarCRM Admin page under **OAuth Keys**; sugar is the default client ID for API access)Â


Connecting to Your SugarCRM Account
-----------------------------------


This section enumerates the options in theÂ **Credentials**Â andÂ **Details**Â panes in the SugarCRM Connector page.Â The components of the other panes in this page,Â **Scheduling**Â andÂ **Name & Describe Your DataSet**, are universal across most connector types and are discussed in greater length inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


Credentials Pane
----------------


This pane contains fields for entering credentials to connect to your SugarCRM account. The following table describes what is needed for each field:




| Field/Menu | Description |
| --- | --- |
| Username | Enter your SugarCRM username. |
| Password | Enter your SugarCRM password. |
| Host | Enter the host URL for your company's SugarCRM instance. For example: <https://domo.sugarondemand.com> |
| Client ID | Enter your SugarCRM client ID (sugar is the default client ID for API access). |


Once you have entered validÂ SugarCRM credentials, you can use the same account any time you go to create a newÂ SugarCRM DataSet. You can manage connector accounts in theÂ AccountsÂ tab in theÂ Data Center. For more information about this tab, seeÂ [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


Details Pane
------------


This pane contains a primary **ReportÂ**menu, along with various other menus that may or may not appear depending on your selected report.




| Menu | Description |
| --- | --- |
| Report | Select a SugarCRM report. The following reports are available:

|  |  |
| --- | --- |
| Dashboards | Returns the authenticated user's dashboards. |
| Employees | Returns a list of employees. |
| Notifications | Returns a list of notifications. |
| Records by Module | Returns a list of records for the selected module. |
| Users | Returns a list of users.Â  |

Â  |
| Select the Module | Select the module with data you want to extract. If your module is not listed, enter the name of the desired module in theÂ **Module Name**Â field. |
| Module Name (Optional) | If your desired module is not listed in the module list, enter the name here. This name is case-sensitive.Â  |
| Select the Fields | Select the fields to retrieve for each record. |
| Additional Field Names to Retrieve | Enter a comma-separated list of names of additional fields you want to retrieve. |
| Deleted Records | SelectÂ **Yes**Â to import deleted records in your report; otherwise selectÂ **No**. |
| Select the Date Filter | Select the date field you want to filter data on. |
| DurationÂ  | Select whether you want to pull data for a specific date or a date range.Â  |
| Report DateÂ  | Select whether the report data is for a specific date or for a relative number of days back from today.Â  |
| Select Specific DateÂ  | Select the date for the report.Â  |
| Days Back | Enter the number of past days that should appear in the report.Â Â  |
| Start Date | Specify whether theÂ first date in your date range is a specific or relative date.Â You select the last date in your range inÂ **End Date**.Â  |
| End Date | Specify whether the second date in your date range is a specific or relative date. You select the first date in your range inÂ **Start Date**.Â Â  |
| Select Specific Start Date | SelectÂ the first date in your date range.Â  |
| Select Specific End Date | Select the second date in your date range.Â  |
| Days Back to Start From | Enter the number of the farthest day back that should be represented in the report. Combine withÂ **Days Back to End At**Â to create a range of represented days.
For example, if you enteredÂ 10Â forÂ **Days Back to Start From**Â andÂ 5Â forÂ **Days Back to End At**, the report would contain data forÂ 10 days ago up untilÂ 5 days ago. |
| Days Back to End At | Enter the number of the most recent day back that should be represented in the report. Combine withÂ **Days Back to Start From**Â to create a range of represented days.
For example, if you enteredÂ 10Â forÂ **Days Back to Start From**Â andÂ 5Â forÂ **Days Back to End At**, the report would contain data forÂ 10 days ago up untilÂ 5 days ago. |


Other Panes
-----------


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, seeÂ [Â a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.html "Adding a DataSet Using a Data Connector").


Â