---
title : Changing the Font Size in Your Chart
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-11-03 20:01:00
url : https://domo-support.domo.com/s/article/360042925214
linked_kbs :  ['https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429913', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360042924034', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042925214']
article_id : 000005042
views : 4,205
created_date : 2022-11-03 19:34:00
last updated : 2022-11-03 20:01:00
---



In the [Analyzer](..\analyzer_layout\index.qmd "Card Builder Layout") of a chart, you can increase or decrease the scale label font size for many of the chart types, including the following:



* Vertical bar
* Horizontal bar
* Vertical grouped bar
* Vertical stacked bar
* Horizontal stacked bar
* Line
* Multi-line
* Curved line
* Symbol line
* Curved symbol line
* Grouped bar with line/symbol
* Stacked bar with line/symbol
* Grouped and stacked bar with line
* Running total bar
* Running total grouped bar
* Running total stacked bar
* Running total line


For more information about available chart types, see [Chart Types](..\..\category\chart_types\index.qmd "Available Chart Types").


You change the font size in the **Chart Properties**. Changing the font size affects scale label text only. Other text such as legends and hover text is not affected.


The following table describes each available font size and contains example images. 




| Font Size | Description | Example |
| --- | --- | --- |
| Smaller | The smallest scale label font size. |   |
| Default | The default scale label font size in Domo. This size falls between "Smaller" and "Larger." |   |
| Larger | The second-largest scale label font size. |   |
| Largest | The largest scale label font size. |   |


**To change the font size in a chart,**


1. Open the Analyzer for the chart you want to edit.
2. In **Chart Properties**, click **General**.
3. Select a font size in the **Font Size** menu.