---
title : Available Gauges
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:42:00
url : https://domo-support.domo.com/s/article/360042924334
linked_kbs :  ['https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042924774', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042924414', 'https://domo-support.domo.com/s/article/4546361976087', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/article/360042924934', 'https://domo-support.domo.com/s/article/360043429293', 'https://domo-support.domo.com/s/article/360043429493', 'https://domo-support.domo.com/s/article/4546335931031', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360042924334', 'https://domo-support.domo.com/s/article/360042924554', 'https://domo-support.domo.com/s/article/360043429913', 'https://domo-support.domo.com/s/article/360042924714', 'https://domo-support.domo.com/s/article/360042924534', 'https://domo-support.domo.com/s/article/360042924434', 'https://domo-support.domo.com/s/article/4546378883863']
article_id : 000004734
views : 4,272
created_date : 2022-10-24 22:27:00
last updated : 2022-10-24 22:42:00
---



Gauges classify data values as belonging to a predetermined range. An example would be a bulb that turns green or red, depending on the air quality.


The following table lists the types of gauges available in Domo:


Â 




| Gauge Type | Description | Example |
| --- | --- | --- |
| Single ValueÂ gauge
 | A Single Value gauge displays the first value in your DataSet as a numeral. No other graphics or images are used. This chart type is useful when you want to see a single value quickly without having to interpret bars, lines, etc.
For more information, see [Single Value Gauge](..\single_value_gauge\index.html "Single Value Gauge"). | 
Â  |
| Filled gauge
 | Filled gauges are circular gauges that "fill" to indicate the current value of the gauge, like a thermometer.
For more information, see [Filled Gauge](..\filled_gauge\index.html "Filled Gauge"). |  |
| Progress Bar gauge

Â  | A Progress Bar gauge is similar to a Filled gauge but is bar-shaped rather than circular and shows its value as a percentage.
For more information, see [Progress Bar Gauge](..\progress_bar_gauge\index.html "Progress Bar Gauge"). |  |
| Radial gauge
 | Radial gauges use an indicator that pivots around the gauge scale to indicate the current data value associated with the gauge. Common Radial gauges include dials and speedometers.
For more information, see [Radial Gauge](..\radial_gauge\index.html "Radial Gauge"). |  |
| Face gauge
 | In a Face gauge, any of three different versions of a face (smiling, happy, or neither) is shown, depending on where the current value falls. This can be used to instantly classify a value as poor, fair, or good.
For more information, see [Face Gauge](..\face_gauge\index.html "Face Gauge"). |  |
| Comparative gauge
 | A Comparative gauge is a simple gauge consisting of a single value that shows the degree of change between a previous value and a current value. The degree of change may be shown as a percentage or as the actual difference between values. Alternatively, you may choose to show only the current value.
For more information, seeÂ [Comparative Gauge](..\comparative_gauge\index.html "Comparative Gauge"). |  |
| Comparative Fill gauge (Basic)
 | A basic Comparative Fill Gauge is similar to a Filled Gauge but includes aÂ parameter for a previous value.Â The gaugeÂ fills in only between this previous value and the current value so viewers can see the degree of change since the gauge was last updated. In addition,Â the percentage and direction of changeÂ appears in the center of the chart. This gauge type also includes a parameter for a target value, but this is optional.
ThisÂ gauge type is the same as an advanced Comparative Fill Gauge but is simpler, requiring only four columns (with an optional fifth), whereas theÂ advancedÂ version requires eight.
For more information aboutÂ Comparative Fill Gauges, seeÂ [Comparative Fill Gauge](..\comparative_fill_gauge\index.html "Comparative Fill Gauge"). |  |
| Comparative Fill gauge (Advanced)
 | An advanced Comparative Fill Gauge has the same features asÂ the basic version but also allows you toÂ create a lower and upper range andÂ specify a median value.Â These elements are displayedÂ on a second circle in the gauge for a cleaner look.Â 
For more information about Comparative Fill Gauges, seeÂ [Comparative Fill Gauge](..\comparative_fill_gauge\index.html "Comparative Fill Gauge").Â  |  |
| Radial Progress gauge
Small_Radial_Progress_Gauge.png | Filled gauges are circular gauges that "fill" to indicate the current value of the gauge, like a thermometer. For more information, see [Radial Progress Gauge](..\radial_progress_gauge\index.md). | Radial_Progress.png |
| Shape gauge
Screen_Shot_2022-06-14_at_10.50.37_AM.png | A shape gauge uses any of 45 different images to indicate a current value. By using different images to indicate different ranges, you can convey to users whether the current value is positive, neutral, or negative. For more information, see [Shape Gauge.](..\shape_gauge\index.md) | Screen_Shot_2022-06-14_at_10.48.38_AM.png |
| Multi Radial Progress gauge
Small_Multi_Radial_Progress_Gauge.png | Filled gauges are circular gauges that "fill" to indicate the current value of the gauge, like a thermometer. The Multi Radial Gauge allows for displaying for more than one metric. For more information, see [Multi Radial Progress Gauge](..\multi_radial_progress_gauge\index.md). | Multi_Radial_Progress.png |
| Multi-Value gauge
Screen_Shot_2022-06-14_at_10.50.31_AM.png | Â A multi-value gauge displays the current value of your as DataSetÂ as a numeral, along with theÂ degree of change for the gauge data, whether positive or negative.Â This chart type is useful when you want to see a change in value quickly, without having to interpret bars, lines, etc. For more information, see [Multi-Value Gauge.](..\multivalue_gauge\index.md) | Screen_Shot_2022-06-14_at_10.46.03_AM.png |
| Waffle gauge
Small_Waffle_Gauge.png | Waffle charts provide a new, simple and intuitive way to visualize data as it includes many customizable settings to tell a more informative story. For more information, see [Waffle Gauge](..\waffle_gauge\index.md). | Waffle.png |


Â