---
title: Domo University Programs
url: https://domo-support.domo.com/s/article/360043440453
linked_kbs:  ['[https://domo-support.domo.com/s/knowledge-base/](https://domo-support.domo.com/s/knowledge-base/)', '[https://domo-support.domo.com/s/](https://domo-support.domo.com/s/)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZamyGAC](https://domo-support.domo.com/s/topic/0TO5w000000ZamyGAC)', '[https://domo-support.domo.com/s/topic/0TO5w000000Zao1GAC](https://domo-support.domo.com/s/topic/0TO5w000000Zao1GAC)', '[https://domo-support.domo.com/s/article/360043440453](https://domo-support.domo.com/s/article/360043440453)', '[https://domo-support.domo.com/s/topic/0TO5w000000Zao1GAC/paid-training](https://domo-support.domo.com/s/topic/0TO5w000000Zao1GAC/paid-training)', '[https://domo-support.domo.com/s/article/360043429933](https://domo-support.domo.com/s/article/360043429933)', '[https://domo-support.domo.com/s/article/360043429953](https://domo-support.domo.com/s/article/360043429953)', '[https://domo-support.domo.com/s/article/360042925494](https://domo-support.domo.com/s/article/360042925494)', '[https://domo-support.domo.com/s/article/360043429913](https://domo-support.domo.com/s/article/360043429913)', '[https://domo-support.domo.com/s/article/4408174643607](https://domo-support.domo.com/s/article/4408174643607)', '[https://domo-support.domo.com/s/login/](https://domo-support.domo.com/s/login/)']
article_id: 000004549
views: 2,278
created_date: 2022-10-24 22:14:00
last updated: 2022-10-24 22:40:00
---



**Video - Registering for a Public Learning Course in Domo University**



 


**Video - Using a Certification in Domo University**



 


Click on any of the below links to view PDFs for Domo University's training programs:




| PDF | Description |
| --- | --- |
| **[What is Domo University?](https://domosoftware.sharepoint.com/:b:/s/CS-Edu-PublicFiles/Edt8EnZCeB5NqsCbsN_ZC9IBHUkr6hZNmzEQNQoa6pfqyQ?e=jsbNm5 "Domo+University+in+a+Page.pdf")** | Get information on Domo University modalities, full-day classes, delivery methods, and pricing. |
| **[Virtual Instructor-Led Training](https://domosoftware.sharepoint.com/:b:/s/CS-Edu-PublicFiles/EWsqVAA8CKFJrsrREjKcl3ABN8cQ-jkYfSAgTlvNSV7E-Q?e=9xbDHA "Domo University VILT.pdf")** | Learn how Domo's Virtual Instructor-Led Training can give you the instruction you need without the hassle of travel.  |
| **[Onsite Training](https://domosoftware.sharepoint.com/:b:/s/CS-Edu-PublicFiles/EUztrCpMDWVNq-WciAPuf50BCHDZ-WhPRWgpUhzyaD_zuw?e=I0E56S "Domo University Onsite Training.pdf")** | Find out how to bring a Domo University trainer to your company to help accelerate onboarding and adoption. |
| **[Public Training](https://domosoftware.sharepoint.com/:b:/s/CS-Edu-PublicFiles/Eddc3ToZoatFuXP9RJzDCIABWkseuWpjbZ-0j8gLGknWRg?e=qRgYG0 "Domo University Public Training.pdf")** | Participate in a hands-on environment building solutions in Domo under the guidance of an expert Domo University trainer. |
| **[Train the Trainer Program](https://domosoftware.sharepoint.com/:b:/s/CS-Edu-PublicFiles/EdcIiPZgLpBIt_QAFuADGmMByTV1bA_tlwzyjqi2zZIAIg?e=mVjecX "Domo University Train the Trainer.pdf")** | Learn how to train your own teams to get the most from your Domo investment. |


 

