---
title: Requesting Access to an App
url: https://domo-support.domo.com/s/article/360042933274
linked_kbs:  ['[https://domo-support.domo.com/s/knowledge-base/](https://domo-support.domo.com/s/knowledge-base/)', '[https://domo-support.domo.com/s/](https://domo-support.domo.com/s/)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZampGAC](https://domo-support.domo.com/s/topic/0TO5w000000ZampGAC)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZaoMGAS](https://domo-support.domo.com/s/topic/0TO5w000000ZaoMGAS)', '[https://domo-support.domo.com/s/article/360042933274](https://domo-support.domo.com/s/article/360042933274)', '[https://domo-support.domo.com/s/topic/0TO5w000000ZaoMGAS/using-the-appstore](https://domo-support.domo.com/s/topic/0TO5w000000ZaoMGAS/using-the-appstore)', '[https://domo-support.domo.com/s/article/360043429933](https://domo-support.domo.com/s/article/360043429933)', '[https://domo-support.domo.com/s/article/360043429953](https://domo-support.domo.com/s/article/360043429953)', '[https://domo-support.domo.com/s/article/360042925494](https://domo-support.domo.com/s/article/360042925494)', '[https://domo-support.domo.com/s/article/360043429913](https://domo-support.domo.com/s/article/360043429913)', '[https://domo-support.domo.com/s/article/4408174643607](https://domo-support.domo.com/s/article/4408174643607)', '[https://domo-support.domo.com/s/login/](https://domo-support.domo.com/s/login/)']
article_id: 000005019
views: 1.138
created_date: 2022-11-02 20:16:00
last updated: 2022-11-02 20:37:00
---



By default, when a user installs an app, only that user has access to the app Dashboard and the Cards in it (along with "Admin"-level users and those with custom security roles that include the "Manage Appstore" grant). If you want access, you can request access to the app Dashboard from the Appstore. If you have access, you can share access to the Dashboard the same way you share access to any Dashboard. 



For more information, see [Controlling Access to Cards and Pages](https://domohelp.domo.com/Administer/Controlling_Access_in_Domo/01Controlling_Access_to_Cards_and_Pages "Controlling Access to Cards and Pages").


**To request access to a Dashboard app page,**


1. Click **Appstore**in the toolbar at the top of the screen.
2. Identify the app you want to add.  
  
You can use the various filter and sorting options to locate the desired app. For more information, see [Filtering Apps and Connectors in the Appstore](https://domohelp.domo.com/The_Appstore/Using_the_Appstore/Filtering_Apps_and_Connectors_in_the_Appstore "Filtering Apps and Connectors in the Appstore"). You can also view a list of installed apps by clicking **Installed**.
3. Click the app to open its details view.
4. In the details view, click **Request Access**.   
A dialog appears with a boilerplate message you can send or customize.
5. (Optional) Customize the message.
6. Click **Send Request**.  
Your request is sent to the app owner via Buzz.


