---
title : Dial800 Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:39:00
url : https://domo-support.domo.com/s/article/360043435153
linked_kbs :  ['https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/article/360043435153', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003402
views : 2,002
created_date : 2022-10-24 21:12:00
last updated : 2022-10-24 22:39:00
---



Intro
-----


Dial800 is a call performance marketing and communication tool. To learn more about the Dial800 API, visit their page ([https://www.dial800.com/solutions/call-tracking/](https://www.dial800.com/solutions/call-tracking/ "https://www.dial800.com/solutions/call-tracking/")).


You connect to your Dial800 account in the Data Center. This topic discusses the fields and menus that are specific to the Dial800 connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed in [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).


Prerequisites
-------------


To connect to your Dial800 account and create a DataSet, you must have a Dial800 username and password.


Connecting to Your Dial800 Account
----------------------------------


This section enumerates the options in the **Credentials** and **Details** panes in the Dial800 Connector page. The components of the other panes in this page, **Scheduling** and **Name & Describe Your DataSet**, are universal across most connector types and are discussed in greater length in [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md "Adding a DataSet Using a Data Connector").


### Credentials Pane


This pane contains fields for entering credentials to connect to your Dial800 account. The following table describes what is needed for each field:  




| Field | Description |
| --- | --- |
| Username | Enter your Dial800 username. |
| Password | Enter your Dial800 password. |


Once you have entered valid Dial800 credentials, you can use the same account any time you go to create a new Dial800 DataSet. You can manage connector accounts in the **Accounts** tab in the Data Center. For more information about this tab, see [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


### Details Pane


This pane contains a primary **Reports** menu, along with various other menus which may or may not appear depending on the report type you select.




| Menu | Description |
| --- | --- |
| Report | Select the Dial800 report you want to run. The following reports are available:

|  |  |
| --- | --- |
| Analytics | Returns Dial800 analytics information. |
| Callers | Returns a list of callers. |
| Calls | Returns a list of calls. |
| Client Searches | Returns a list of client searches. |
| Client Target | Returns a list of client targets. |
| Countries | Returns a list of countries. |
| DNIs | Returns a list of DNIS. |
| DNISes | Returns a list of DNISes. |
| Domain | Returns a list of domains. |
| Legacy DNIs | Returns a list of legacy DNIs. |
| Messages | Returns a list of messages. |
| Owner | Returns a list of owners. |
| Profiles | Returns a list of profiles. |
| Reports | Returns a list of reports. |
| Routing Profiles | Returns a list of routing profiles. |
| Tags | Returns a list of tags. |
| Targets | Returns a list of targets. |

 |
| Client ID | Select the ID of the client you want to retrieve information for. |
| Search ID | Select the search ID you want to retrieve information for. |
| Tag Type | Select the tag type you want to retrieve information for. |
| DNIS | Enter the DNIS you want to retrieve information for. |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, see [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).