---
title : October 2015 Release 1
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:41:00
url : https://domo-support.domo.com/s/article/360048116854
linked_kbs :  ['https://domo-support.domo.com/s/article/360043438993', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360048116854', 'https://domo-support.domo.com/s/article/360042934454', 'https://domo-support.domo.com/s/article/360042926134', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042922874', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000004460
views : 2,015
created_date : 2022-10-24 22:11:00
last updated : 2022-10-24 22:41:00
---



**Note:** Depending on the product version you are using, the documentation may include information about features that may not be available or may have changed.
New features and enhancements
-----------------------------


Features and enhancements in this release include the following:


### Searching for Publication group configurations


Now you can search for a publication group configuration using the Search pane. You can also create a publication group by clicking New Publication Group or delete a publication group by clicking Delete Publication Group.


For more information, see [Using Publication Groups](..\setting_up_publication_groups\index.html "Using Publication Groups").


 


### Exporting DataSets


You can now export DataSets in the Data Center as Excel or CSV files.


For more information, see [Exporting DataSets](..\exporting_datasets\index.html "Exporting DataSets").


On-demand features and enhancements
-----------------------------------


**Note:** This feature is available *on demand.*  
 


To request that this feature be enabled,



* contact Technical Support
* reach out to your Domo Customer Success Manager or Technical Consultant.


Depending on the feature, you may be required to complete training before you can use the feature.
 


Features and enhancements in this release include the following:


### Managing User Licenses


Now Domo administrators can view how many users there are in Domo, how many user licenses have been purchased, and whether the number of licenses in use exceeds the allotted number of licenses. If over the license count, Domo administrators can order licenses from Domo.


If you have an "Admin" security role, you can review your user license usage and order licenses from Domo. When you confirm a license purchase order, Domo sends an email to a Domo sales representative who sends you a purchase order invoice.


You access the Licensing page by clicking **> Admin > Licenses**.


For more information, see [Adding User Licenses in Domo](..\adding_user_licenses_in_domo\index.html "Admin Settings Layout").


Getting Help
------------


You can view the latest release notes information in the Help Center, which you can access from Domo by clicking **Help Center**.


If you have questions about Domo,



* search for a topic in the Help Center
* train in Domo University at [http://www.domo.com/university](http://www.domo.com/university "http://www.domo.com/university")
* get answers in the Domo Community at [dojo.domo.com](https://domohelp.domo.com/dojo.domo.com "dojo.domo.com")
* contact Technical Support
* reach out to your Domo Customer Success Manager or Technical Consultant


If you have feedback, please send it from within Domo (**> Feedback**). Or send an email to [product.feedback@domo.com](mailto:product.feedback@domo.com "product.feedback@domo.com").


For more information about getting help, see [Getting Help](..\getting_help\index.html "Getting Help").