---
title : Harvest Connector
categories: ['https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC']
date: 2022-10-24 22:39:00
url : https://domo-support.domo.com/s/article/360042930434
linked_kbs :  ['https://domo-support.domo.com/s/article/360042926274', 'https://domo-support.domo.com/s/knowledge-base', 'https://domo-support.domo.com/s/article/360042925494', 'https://domo-support.domo.com/s/article/360043429953', 'https://domo-support.domo.com/s/article/360042930434', 'https://domo-support.domo.com/s/article/360042926054', 'https://domo-support.domo.com/s/article/360043429933', 'https://domo-support.domo.com/s/article/360043429693', 'https://domo-support.domo.com/s/topic/0TO5w000000ZamwGAC', 'https://domo-support.domo.com/s/article/360043429913']
article_id : 000003419
views : 2,018
created_date : 2022-10-24 21:12:00
last updated : 2022-10-24 22:39:00
---



Intro
-----


Harvest offers time tracking, invoicing, expense tracking, and time-based reporting. To learn more about the Harvest API, visit their page ([http://help.getharvest.com/api/](http://help.getharvest.com/api/ "http://help.getharvest.com/api/")).


You connect to your Harvest account in the Data Center. This topic discusses the fields and menus that are specific to the Harvest connector user interface. General information for adding DataSets, setting update schedules, and editing DataSet information is discussed inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).


Prerequisites
-------------


To connect to your Harvest account and create a DataSet, you must have your Harvest username and password OR a Google account. You must also know the name of your Harvest instance, as this is required for all reports. This is your company name as it appears in your Harvest URL. For example, if your URL was [domo.harvestapp.com](http://domo.harvestapp.com), the instance would be domo.


Connecting to Your Harvest Account
----------------------------------


This section enumerates the options in theÂ **Credentials**Â andÂ **Details**Â panes in the Harvest Connector page.Â The components of the other panes in this page,Â **SchedulingÂ**andÂ **Name & Describe Your DataSet,** are universal across most connector types and are discussed in greater length inÂ [Adding a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).


### Credentials Pane


The Domo Harvest connector uses OAuth to connect, so there is no need to enter credentials within Domo. ClickÂ **Connect**Â (or selectÂ **Add Account**Â ifÂ you haveÂ existing Harvest accounts in Domo) to open the Harvest OAuth screen where you can enter your Harvest username and password. (You can also enter Google credentials to authenticate.) Once you have entered valid credentials, you can use the same account any time you go to create a new Harvest DataSet. You can manage connector accounts in theÂ **Accounts**Â tab in theÂ Data Center. For more information about this tab, seeÂ [Managing User Accounts for Connectors](..\managing_user_accounts_for_connectors\index.html "Managing User Accounts for Connectors").


**Note:**Â If you are already logged into Harvest when you connect in Domo, you are authenticated automatically when you click **Add account**. If you want to connect to an account that is different from the one you are logged into, you must first log out of Harvest.
### Details Pane


This pane contains a primaryÂ **Reports**Â menu, along with various other menus which may or may not appear depending on the report type you select.




| Menu | Description |
| --- | --- |
| Report | Select the Harvest report you want to run.Â The following reports are available:

|  |  |
| --- | --- |
| All Projects Time Entries | Retrieve time entries for all projects in a specified time period. |
| All Projects Logged Expenses | List all logged expenses for all projects in a specified time period. |
| All Users Logged Expenses | List all expenses logged by users. |
| All Users Time Entries | List all users' time entries. |
| Assignments | List all task assignments for all projects in a specified time period. |
| Clients | List all clients. |
| Contacts | List all contacts. |
| Daily | List all time entries. |
| Expense Categories | List all expense categories. |
| Invoices | List all invoices. |
| Invoice Messages | List invoice messages. |
| Invoice Payments | List invoice payments. |
| Invoice Item Categories | List invoice item categories. |
| People | List all users. |
| Projects | List all projects. |
| Project Expenses | List all projects' logged expenses. |
| Tasks | List all tasks. |
| User Expenses | List all user expenses. |

 |
| Instance | Enter your Harvest instance name. This is your company name as it appears in your Harvest URL. For example, if your URL was [domo.harvestapp.com](http://domo.harvestapp.com), the instance would be domo. |
| DurationÂ  | Select whether you want to pull data for a specific date or a date range.Â  |
| Report DateÂ  | Select whether the report data is for a specific date or for a relative number of days back from today.Â  |
| Report Updated Since Date | Select whether the report data is for a specific date or for a relative number of days back from today. |
| Specific DateÂ  | Select the date for the report.Â  |
| Days Back | Enter the number of past days that should appear in the report.Â Â  |
| Start Date | Specify whether theÂ first date in your date range is a specific or relative date.Â You select the last date in your range inÂ **End Date**.Â  |
| End Date | Specify whether the second date in your date range is a specific or relative date. You select the first date in your range inÂ **Start Date**.Â Â  |
| Specific Start Date | SelectÂ the first date in your date range.Â  |
| Specific End Date | Select the second date in your date range.Â  |
| Days Back to Start From | Enter the number of the farthest day back that should be represented in the report. Combine withÂ **Days Back to End At**Â to create a range of represented days.
For example, if you enteredÂ 10Â forÂ **Days Back to Start From**Â andÂ 5Â forÂ **Days Back to End At**, the report would contain data forÂ 10 days ago up untilÂ 5 days ago. |
| Days Back to End At | Enter the number of the most recent day back that should be represented in the report. Combine withÂ **Days Back to Start From**Â to create a range of represented days.
For example, if you enteredÂ 10Â forÂ **Days Back to Start From**Â andÂ 5Â forÂ **Days Back to End At**, the report would contain data forÂ 10 days ago up untilÂ 5 days ago. |
| Invoice Status | Select the invoice status you want to filter your report by. If you select **None**, no status is applied. |
| Project ID | Enter the ID(s) of the project(s) you want to pull data for. Separate multiple IDs using commas. |
| User ID | Enter the ID(s) of the user(s) you want to pull data for. Separate multiple IDs using commas. |


### Other Panes


For information about the remaining sections of the connector interface, including how to configure scheduling, retry, and update options, seeÂ [AddingÂ a DataSet Using a Data Connector](..\adding_a_dataset_using_a_connector\index.md).